### ISSUE TITLE
Draft Caenorhabditis elegans

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#1020]
## Pending Issues

---

## Design

This draft design reflects additions to corresponding sections in [schema 5.2.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md). Reviewers are expected to be familiar with the CELLxGENE schema.

**Editorial Notes** that are inlined in the design below will not be surfaced in the schema. 

---

### Required Ontologies

| Ontology | OBO Prefix | Releases | OLS |
|:--|:--|:--|:--|
| [C. elegans Gross Anatomy Ontology] | WBbt |  [Releases](https://github.com/obophenotype/c-elegans-gross-anatomy-ontology/releases) | [OLS](https://www.ebi.ac.uk/ols4/ontologies/wbbt)
| [C. elegans Development Ontology] | WBls |  [Releases](https://github.com/obophenotype/c-elegans-development-ontology/releases) | [OLS](https://www.ebi.ac.uk/ols4/ontologies/wbls)
|||||

[C. elegans Gross Anatomy Ontology]: https://obofoundry.org/ontology/wbbt.html
[C. elegans Development Ontology]: https://obofoundry.org/ontology/wbls.html

#### Editorial Notes

These ontologies are under active development. CELLxGENE pins ontology releases in each version of the schema. A specific release of the ontologies above must be selected in the future.

---

### Required Gene Annotations

| Organism | Source | Required version | Download |
|:--|:--|:--|:--|
| <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6239"</code></a><br>for <i>Caenorhabditis elegans</i>  | [ENSEMBL (Caenorhabditis elegans)] | WBcel235 (GCA_000002985.3) | [Caenorhabditis_elegans.WBcel235.113.gtf] |

[ENSEMBL (Caenorhabditis elegans)]: https://useast.ensembl.org/Caenorhabditis_elegans/Info/Index
[Caenorhabditis_elegans.WBcel235.113.gtf]: https://ftp.ensembl.org/pub/release-113/gtf/caenorhabditis_elegans/Caenorhabditis_elegans.WBcel235.113.gtf.gz

#### Editorial Notes

---

### cell_type_ontology_term_id

No schema changes are required. 

#### Editorial Notes

UBERON and CL [bridges](https://obophenotype.github.io/uberon/bridges/#the-bridges) are available. 

---

### development_stage_ontology_term_id

<table><tbody>
  <tr>
    <th>Key</th>
    <td>development_stage_ontology_term_id</td>
  </tr>
  <tr>
    <th>Annotator</th>
    <td>Curator MUST annotate.</td>
  </tr>
  <tr>
    <th>Value</th>
    <td>
      categorical with <code>str</code> categories. If unavailable, this MUST be <code>"unknown"</code>.<br><br>
      If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6239"</code></a> for <i>Caenorhabditis elegans</i>, this MUST be the most accurate descendant of <a href="https://www.ebi.ac.uk/ols4/ontologies/wbls/classes?obo_id=WBls%3A0000075"<code>WBls:0000075</code></a> for <i>worm life stage</i> ...
    </td>
  </tr>
</tbody></table>
<br>

#### Editorial Notes

This may be outdated, but [potential recommendations](https://github.com/obophenotype/developmental-stage-ontologies/blob/master/external/bgee/report.md#caenorhabditis-elegans) for STRONGLY RECOMMENDED terms:

```
UBERON:0000104 life cycle
    WBls:0000669 unfertilized egg Ce (C. elegans)
    UBERON:0000068 embryo stage
        UBERON:0000106 zygote stage
        UBERON:0000107 cleavage stage
            UBERON:0007232 2 cell stage
            UBERON:0007233 4 cell stage
            UBERON:0007236 8 cell stage
        UBERON:0000108 blastula stage
            WBls:0000072 12-cell embryo Ce (C. elegans)
            WBls:0000084 14-cell embryo Ce (C. elegans)
            WBls:0000085 24-cell embryo Ce (C. elegans)
        UBERON:0000109 gastrula stage
            WBls:0000009 28-cell embryo Ce (C. elegans)
            WBls:0000086 44-cell embryo Ce (C. elegans)
            WBls:0000011 51-cell embryo Ce (C. elegans)
            WBls:0000087 68-cell embryo Ce (C. elegans)
            WBls:0000088 86-cell embryo Ce (C. elegans)
            WBls:0000012 88-cell embryo Ce (C. elegans)
            WBls:0000090 96-cell embryo Ce (C. elegans)
            WBls:0000089 190-cells embryo Ce (C. elegans)
            WBls:0000014 late cleavage stage embryo Ce (C. elegans)
                WBls:0000013 enclosing embryo Ce (C. elegans)
        UBERON:0000110 neurula stage
        UBERON:0000111 organogenesis stage
            UBERON:0004707 pharyngula stage
        UBERON:0007220 late embryonic stage
            WBls:0000015 elongating embryo Ce (C. elegans)
                WBls:0000016 bean embryo Ce (C. elegans)
                WBls:0000017 comma embryo Ce (C. elegans)
                WBls:0000018 1.5-fold embryo Ce (C. elegans)
                WBls:0000019 2-fold embryo Ce (C. elegans)
                WBls:0000020 3-fold embryo Ce (C. elegans)
            WBls:0000021 fully-elongated embryo Ce (C. elegans)
    UBERON:0000092 post-embryonic stage
        UBERON:0000069 larval stage
            UBERON:0004729 nematode larval stage
                WBls:0000024 L1 larva Ce (C. elegans)
                    WBls:0000801 newly hatched L1 larval stage Ce (C. elegans)
                        WBls:0000802 L1 arrest Ce (C. elegans)
                WBls:0000026 L1-L2 molt Ce (C. elegans)
                    WBls:0000025 L1-L2 lethargus Ce (C. elegans)
                    WBls:0000042 L1-L2 ecdysis Ce (C. elegans)
                WBls:0000043 L1-L2d molt Ce (C. elegans)
                    WBls:0000044 L1-L2d lethargus Ce (C. elegans)
                    WBls:0000045 L1-L2d ecdysis Ce (C. elegans)
                WBls:0000027 L2 larva Ce (C. elegans)
                WBls:0000046 L2d larva Ce (C. elegans)
                    WBls:0000053 L2d-L3 molt Ce (C. elegans)
                        WBls:0000054 L2d-L3 lethargus Ce (C. elegans)
                        WBls:0000055 L2d-L3 ecdysis Ce (C. elegans)
                WBls:0000031 L2d-dauer molt Ce (C. elegans)
                    WBls:0000030 L2d-dauer lethargus Ce (C. elegans)
                    WBls:0000048 L2d-dauer ecdysis Ce (C. elegans)
                WBls:0000029 L2-L3 molt Ce (C. elegans)
                    WBls:0000028 L2-L3 lethargus Ce (C. elegans)
                    WBls:0000047 L2-L3 ecdysis Ce (C. elegans)
                WBls:0000035 L3 larva Ce (C. elegans)
                WBls:0000032 dauer larva Ce (C. elegans)
                WBls:0000052 post dauer L3 stage Ce (C. elegans)
                    WBls:0000034 postdauer-L4 molt Ce (C. elegans)
                        WBls:0000033 postdauer-L4 lethargus Ce (C. elegans)
                        WBls:0000051 postdauer-L4 ecdysis Ce (C. elegans)
                WBls:0000037 L3-L4 molt Ce (C. elegans)
                    WBls:0000036 L3-L4 lethargus Ce (C. elegans)
                    WBls:0000049 L3-L4 ecdysis Ce (C. elegans)
                WBls:0000038 L4 larva Ce (C. elegans)
                    WBls:0000683 L4.0 larva Ce (C. elegans)
                    WBls:0000684 L4.1 larva Ce (C. elegans)
                    WBls:0000685 L4.2 larva Ce (C. elegans)
                    WBls:0000686 L4.3 larva Ce (C. elegans)
                    WBls:0000687 L4.4 larva Ce (C. elegans)
                    WBls:0000688 L4.5 larva Ce (C. elegans)
                    WBls:0000689 L4.6 larva Ce (C. elegans)
                    WBls:0000690 L4.7 larva Ce (C. elegans)
                    WBls:0000691 L4.8 larva Ce (C. elegans)
                    WBls:0000692 L4.9 larva Ce (C. elegans)
                WBls:0000040 L4-adult molt Ce (C. elegans)
                    WBls:0000039 L4-adult lethargus Ce (C. elegans)
                    WBls:0000050 L4-adult ecdysis Ce (C. elegans)
                WBls:0000828 post dauer L4 stage Ce (C. elegans)
                WBls:0000664 microfilaria (C. elegans)
                    WBls:0000110 sheathed microfilaria (C. elegans)
                    WBls:0000666 unsheathed microfilaria (C. elegans)
                        WBls:0000667 nodular microfilaria (C. elegans)
                        WBls:0000668 skin microfilaria (C. elegans)
                WBls:0000679 nematode infective stage larva (C. elegans)
        UBERON:0000066 fully formed stage
            UBERON:0000112 sexually immature stage
            UBERON:0000113 post-juvenile
                WBls:0000060 reproductive stage adult hermaphrodite Ce (C. elegans)
                WBls:0000061 oocyte-laying stage adult hermaphrodite Ce (C. elegans)
                WBls:0000062 post-reproductive stage adult hermaphrodite Ce (C. elegans)
            WBls:0000063 newly molted young adult hermaphrodite Ce (C. elegans)
            WBls:0000064 1-day post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000065 2-days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000066 3-days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000069 4-7 days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000067 4-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000068 5-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000670 6-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000671 7-days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000070 7-10 days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000672 8-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000673 9-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000674 10-days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000074 11-15 days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000797 11-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000798 12-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000799 13-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000800 14-days post-L4 adult hermaphrodite Ce (C. elegans)
                WBls:0000675 15-days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000111 16-18 days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000676 20-days post-L4 adult hermaphrodite Ce (C. elegans)
            WBls:0000829 post dauer adult stage Ce (C. elegans)
```

---

### disease_ontology_term_id

No schema changes are required.

#### Editorial Notes

---

### ontology_cell_type_ontology_term_id

If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6239"</code></a> for <i>Caenorhabditis elegans</i> this MUST be the most accurate descendant of <a href="https://www.ebi.ac.uk/ols4/ontologies/wbbt/classes?obo_id=WBbt%3A0004017"><code>WBbt:0004017</code></a> for <i>Cell</i> or <code>"unknown"</code> ...

#### Editorial Notes

Also see [Add CL bridge between species-specific and taxon-neutral ontology terms](https://github.com/chanzuckerberg/single-cell-curation/issues/1002)

---

### organism_ontolology_term_id

<code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6239"</code></a> for <i>Caenorhabditis elegans</i> 

---

### organism_tissue_ontology_term_id

If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6239"</code></a> for <i>Caenorhabditis elegans</i> this MUST be the most accurate descendant of <a href="https://www.ebi.ac.uk/ols4/ontologies/wbbt/classes?obo_id=WBBT%3A0005766"><code>WBbt:0005766</code></a> for <i>Anatomy</i> ...

#### Editorial Notes

Also see [Add UBERON bridge between species-specific and taxon-neutral ontology terms](https://github.com/chanzuckerberg/single-cell-curation/issues/1003)

---

### sex_ontology_term_id

If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6239"</code></a> for <i>Caenorhabditis elegans</i> this MUST be <a href="https://www.ebi.ac.uk/ols4/ontologies/pato/classes?obo_id=PATO%3A0000384"><code>PATO:0000384</code></a> for <i>male</i>   or <a href="https://www.ebi.ac.uk/ols4/ontologies/pato/classes?obo_id=PATO%3A0001340"><code>PATO:0001340</code></a> for <i>hermaphrodite</i>.

#### Editorial Notes

[Introduction to sex determination](http://www.wormbook.org/chapters/www_introsexdetermination/introsexdetermination.html):

> C. elegans has two sexes, hermaphrodite and male.

---

### tissue_ontology_term_id

No schema changes are required.

#### Editorial Notes

UBERON and CL [bridges](https://obophenotype.github.io/uberon/bridges/#the-bridges) are available. 

---

### feature_reference

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_reference</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. This MUST be the reference organism for a feature:
          <br><br>
          <table>
          <thead>
          <tr>
          <th>Reference Organism</th>
          <th>MUST Use</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><i>Caenorhabditis elegans</i></td>
              <td><a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A6239"><code>"NCBITaxon:6293"</code></a></td>
            </tr>
          </tbody></table>
        </td>
    </tr>
</tbody></table>
<br>

---

## Reference

[WormBase](https://wormbase.org/)

[BGEE](https://www.bgee.org/species/6239)

**Comment by SESDNA** [comment]
Summary of some issues/questions for C. elegans, would be great to get feedback from the CxG team on how we handle/improve it:
i) General ontology mapping (CL and UBERON): translating “cell.type” annotations to organism-specific WBBT terms works effectively for C. elegans-specific types. However, mapping these annotations to general ontologies (CL and UBERON) frequently results in “unknown” entries, as not all C. elegans cell types have direct equivalents in these broader ontologies. Is this level of unknowns acceptable for you?

ii) Separation of cell and tissue annotations: the schema requires distinct fields for cell and tissue annotations using WBBT terms. Since the “cell.type” column in our dataset combines both cell and tissue types, separating them out leads to some undefined entries. For instance, “intestine” is recognized as WBBT:0005772 for tissue but appears as “unknown” for cell types due to its exclusion from the WBBT Cell tree. Would you prefer that we continue separating them this way to follow the schema strictly?

iii) Anatomy tree requirement vs. functional categories: the specific schema for C. elegans specifies that only terms from the “Anatomy” tree should be used for tissue annotations in WBBT. However, many relevant tissues are classified under “Functional System - Organ System” or “Functional System - Tissue” instead. To avoid significant data loss, we are including these functional categories, adhering strictly to the Anatomy tree would lead to more unknowns. Would it be acceptable to continue including functional categories, or should we follow the Anatomy tree restriction more closely despite the potential loss of information?

iv) Generalized terms for missing matches: in cases where no exact matches are available, some terms are generalized to maintain annotation consistency. For example, “Pharyngeal_neuron” is annotated as “neuron" in general CL terms and “Intestinal_and_rectal_muscle” will be “intestinal muscle” in WBBT terms. This approach minimizes unknowns but involves some generalization and compromises. Is this level of flexibility acceptable for you, or would you prefer only exact matches, even if it increases the number of unknown entries?

v) High-Level mapping for tissue_ontology_term_id: detailed mapping in tissue_ontology_term_id can be challenging, so we are using high-level terms like UBERON:0000922 for “embryo”. This aligns with previous examples for other datasets.
