### ISSUE TITLE
Require CSR encoding in X (Matrix Layers)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#1022]
## `X` (Matrix Layers)

The data stored in the `X` data matrix is the data that is viewable in CELLxGENE Explorer. For `X`, `raw.X`, and in any layer, if a matrix has 50% or more values that are zeros, it MUST be encoded as a [`scipy.sparse.csr_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) with zero values encoded as <a href="https://docs.scipy.org/doc/scipy/tutorial/sparse.html#sparse-arrays-implicit-zeros-and-duplicates">implicit zeros</a>.

CELLxGENE's matrix layer requirements are tailored to optimize data reuse. Because each assay has different characteristics, the requirements differ by assay type. In general, CELLxGENE requires submission of "raw" data suitable for computational reuse when a standard raw matrix format exists for an assay. It is STRONGLY RECOMMENDED to also include a "normalized" matrix with processed values ready for data analysis and suitable for visualization in CELLxGENE Explorer. The schema imposes the following requirements:

*   All matrix layers MUST have the same shape, and have the same cell labels and gene labels.
*  ...

---

## Context

Per conversation on the September 25 DP Call, @nayib-jose-gloria proposed:

> CSC matrices–only found 2 in the corpus, and they are memory inefficient compared to CSR/COO. How do we feel about converting existing cases and codifying in the schema that we won’t take CSC? Or putting a size limit on CSC submissions?
“Backed” mode is prohibitively slow for validating CSC, requiring us to read into memory; we allocate processing resources relative to the worst case scenario, and we are quite close to making backed reads/writes happen in constant memory for CSR/COO matrices.

Also see continuing conversation in  [**cell-sci-platform**](https://czi-sci.slack.com/archives/C06AVGFV222/p1727283001596439).

**Comment by jahilton** [comment]
I would think to also extend this to .raw.X, when present.

**Comment by joyceyan** [comment]
@jahilton @brianraymor My understanding is that for existing datasets with CSC, they should be converted (or in the process of converting) to CSR. For any new datasets the validator sees with CSC, the expectation is that the validator should raise a failure message rather than converting to CSR.

It also seems reasonable to me that this requirement should extend to `.raw.X`

**Comment by brianraymor** [comment]
Slight refinements but otherwise, agree:

_My understanding is that for existing datasets with CSC, they ~~should~~ must be converted **by curators** ..._ And @jahilton is addressing that per earlier comments.

_the expectation is that the validator ~~should~~ must raise a failure message rather than converting to CSR._

I will be updating the 5.3 draft _soonish_.

**Comment by nayib-jose-gloria** [comment]
@brianraymor I think for layers with low sparsity we'll still want to support dense matrices as well; we just want to limit the options for sparse matrices to encode. That said, I can follow-up and see if our initial review of the corpus covered how many dense X/raw.X matrices actually exist.

**Comment by brianraymor** [comment]
@nayib-jose-gloria - would you review again? I've incorporated Jason's suggestion for `raw.X` and your feedback.

**Comment by nayib-jose-gloria** [comment]
LGTM! Thanks! @brianraymor
