### ISSUE TITLE
Amend cell_type in Olah et al (2020) Single-cell Human Microglia

### ISSUE THREAD

**Issue by cjsifuen** [chanzuckerberg/single-cell-curation#105]
The `Olah et al (2020) Single-cell Human Microglia` dataset from the `Live Human Microglia Single-cell RNA-seq` collection contains a label that needs to be changed.

Specific edit (if just editing the dataset)
- change `native cell (CL:0000003)` to `neural cell (CL:0002319)` in `cell_type`

**Comment by jahilton** [comment]
migrated & notified @cjsifuen via Slack of the update
