### ISSUE TITLE
cellxgene-schema must add feature_reference

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#109]
The curator MUST NOT annotate `feature_reference`.

### feature_reference

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_reference</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. This MUST indicate the reference organism of genes and MUST be <code>NCBITaxon:9606</code> for <i>Homo sapiens</i>, <code>NCBITaxon:10090</code> for <i>Mus musculus</i>, <code>NCBITaxon:2697049</code> for  <i>SARS-CoV-2</i>, or <code>NCBITaxon:32630</code> for <i>synthetic construct</i> (spike-in). 
        </td>
    </tr>
</tbody></table>
<br>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
