### ISSUE TITLE
cellxgene-schema must update validation for X (Matrix Layers) 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#1099]
# Changelog

## X (Matrix Layers)

- Updated Visium Spatial Gene Expression table row to **Descendants** of Visium Spatial Gene Expression
- Added matrix requirements for Visium CytAssist Spatial Gene Expression, 11mm.

# Design

| Assay | "raw" required? | "raw" location | "normalized" required? | "normalized" location |
|-|-|-|-|-|
| Descendant of Visium Spatial Gene Expression | REQUIRED. Values MUST be de-duplicated molecule counts. All non-zero values MUST be positive integers stored as `numpy.float32`.<br><br>If <code>uns['spatial']['is_single']</code> is <code>False</code> then each cell MUST contain at least one non-zero value.<br><br>If <code>uns['spatial']['is_single']</code> is <code>True</code> then the unfiltered feature-barcode matrix (<code>raw_feature_bc_matrix</code>) MUST be used. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/space-ranger-feature-barcode-matrices">Space Ranger Feature-Barcode Matrices</a>.<br><br>if <code>assay_ontology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0022860"><code>"EFO:0022860"</code></a> for <i>Visium CytAssist Spatial Gene Expression, 11mm</i>, this matrix MUST contain 14336 rows; otherwise, this matrix MUST contain 4992 rows.<br><br>If the <code>obs['in_tissue']</code> value is <code>1</code>, then the cell MUST contain at least one non-zero value. If any <code>obs['in_tissue']</code> values are <code>0</code>, then at least one cell corresponding to a <code>obs['in_tissue']</code> with a value of <code>0</code> MUST contain a non-zero value.| `AnnData.raw.X` unless no "normalized" is provided, then `AnnData.X` | STRONGLY RECOMMENDED | `AnnData.X` |
|||||

**Comment by ejmolinelli** [comment]
@brianraymor 

For this requirement:

> If uns['spatial']['is_single'] is True then the unfiltered feature-barcode matrix (raw_feature_bc_matrix) MUST be used. See [Space Ranger Feature-Barcode Matrices](https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/space-ranger-feature-barcode-matrices).

Is this simply a check in the matrix dimensions? How else would we know that the matrix is or is not `raw_feature_bc_matrix`?

**Comment by nayib-jose-gloria** [comment]
> @brianraymor
> 
> When might a cell in a matrix have MORE than one value?
> 
> > If uns['spatial']['is_single'] is False then each cell MUST contain at least one non-zero value.

The "Cell" in this context refers to a biological cell; each row in our matrix represents a cell from our obs dataframe (and each col is a gene). Therefore, we must check that each row in our matrix has at least one non-zero value (that is, ensure each cell has at least one gene with a gene expression value > 0)

**Comment by nayib-jose-gloria** [comment]
> Is this simply a check in the matrix dimensions? How else would we know that the matrix is or is not raw_feature_bc_matrix?

correct, all our validator can do is enforce the right matrix dimensions. the rest is instructions for a curator/submitter to do manually
