### ISSUE TITLE
Cross-dataset queries (like "where's my gene") will need to filter out duplicated datasets that result from meta-analysis to provide accurate results.

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#11]
Story: As a user, I want to evaluate where a gene is expressed across tissues by examining the expression of that gene across datasets hosted in cellxgene. 

Problem: As we publish meta-analyses, datasets will begin to be represented multiple times in our database, and the above query will place higher weight on datasets that appear more often (are more popular) unless the original dataset can be distinguished from derivative publications. 

Candidate Solution: 
- Create a schema flag that marks datasets "primary" when the authors generated the data themselves, and flag data as secondary when data are derivative uses of primary datasets. 
- Strongly encourage authors submitting meta-analyses to also submit the primary collections. 

@pablo-gar can you please note the Kang/Aronow use case in this issue?

**Comment by brianraymor** [comment]
Added `is_primary_data` to schema 2.0.0.
