### ISSUE TITLE
Refresh pinned ontologies before releasing cellxgene-schema into the wild

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#112]
The following pinned ontologies MUST be refreshed:
 
| Ontology | OBO Prefix | Required version | JSON<br>available |
|:--|:--|:--|:-:|
| [Cell Ontology] | CL | [cl.owl] : [2021-08-10]| X |
| [Experimental Factor Ontology] | EFO | [efo.owl] : [2021-08-16 EFO 3.33.0] | X |
| [Human Developmental Stages] |  HsapDv | [hsapdv.owl] : 2020-03-10 | - |
| [Mondo Disease Ontology] | MONDO |[mondo.owl] : [2021-08-11] | X |
| [Mouse Developmental Stages]| MmusDv |  [mmusdv.owl] : 2020-03-10 | - |
| [Phenotype And Trait Ontology] | PATO | [pato.owl] : [2021-08-06] | X |
| [Uberon multi-species anatomy ontology] |  UBERON | [uberon.owl] : [2021-07-27] |X|

Unchanged:

| Ontology | OBO Prefix | Required version | JSON<br>available |
|:--|:--|:--|:-:|
| [Human Ancestry Ontology] | HANCESTRO |[hancestro.owl] : [2021-01-04 (2.5)] | - |
| [NCBI organismal classification] |  NCBITaxon | [ncbitaxon.owl] : [2021-06-10] | X |
| | | |

[Cell Ontology]: http://obofoundry.org/ontology/cl.html
[2021-08-10]: https://github.com/obophenotype/cell-ontology/releases/tag/v2021-08-10
[cl.owl]: https://github.com/obophenotype/cell-ontology/blob/v2021-08-10/cl.owl

[Experimental Factor Ontology]: http://www.ebi.ac.uk/efo
[2021-08-16 EFO 3.33.0]: https://github.com/EBISPOT/efo/releases/tag/v3.33.0
[efo.owl]: https://github.com/EBISPOT/efo/releases/download/v3.33.0/efo.owl

[Human Ancestry Ontology]: http://www.obofoundry.org/ontology/hancestro.html
[2021-01-04 (2.5)]: https://github.com/EBISPOT/ancestro/releases/tag/2.5
[hancestro.owl]: https://github.com/EBISPOT/ancestro/blob/2.5/hancestro.owl

[Human Developmental Stages]: http://obofoundry.org/ontology/hsapdv.html
[hsapdv.owl]: http://purl.obolibrary.org/obo/hsapdv.owl

[Mondo Disease Ontology]: http://obofoundry.org/ontology/mondo.html
[2021-08-11]: https://github.com/monarch-initiative/mondo/releases/tag/v2021-08-11
[mondo.owl]: https://github.com/monarch-initiative/mondo/releases/download/v2021-08-11/mondo.owl

[Mouse Developmental Stages]: http://obofoundry.org/ontology/mmusdv.html
[mmusdv.owl]: http://purl.obolibrary.org/obo/mmusdv.owl

[NCBI organismal classification]: http://obofoundry.org/ontology/ncbitaxon.html
[2021-06-10]: https://github.com/obophenotype/ncbitaxon/releases/tag/v2021-06-10
[ncbitaxon.owl]: https://github.com/obophenotype/ncbitaxon/releases/download/v2021-06-10/ncbitaxon.owl.gz

[Phenotype And Trait Ontology]: http://www.obofoundry.org/ontology/pato.html
[2021-08-06]: https://github.com/pato-ontology/pato/releases/tag/v2021-08-06
[pato.owl]: https://github.com/pato-ontology/pato/blob/v2021-08-06/pato.owl

[Uberon multi-species anatomy ontology]: http://www.obofoundry.org/ontology/uberon.html
[2021-07-27]: https://github.com/obophenotype/uberon/releases/tag/v2021-07-27
[uberon.owl]: https://github.com/obophenotype/uberon/blob/v2021-07-27/uberon.owl

**Comment by pablo-gar** [comment]
Updating ontologies will be pretty [easy](https://github.com/chanzuckerberg/single-cell-curation/tree/cellxgene_schema_cli_v_1_0_0-ontology_and_gene_checkers/cellxgene_schema_cli/scripts), we should do this as one of the last steps before releasing the validator

**Comment by pablo-gar** [comment]
NCBITaxon should be update to only include a subset of the entire tree of life. Currently, loading NCBITaxon in the validator is the longest step.

Some suggestions are:

- eukaryotes only + sars-cov2 + spike ins
- metazoa only + sars-cov2 + spike ins
- 'Homo sapiens' + 'Mus musculus' + 'Macaca' + 'Callithrix jacchus' + sars-cov2 + spike-ins

**Comment by brianraymor** [comment]
To be clear, by  _NCBITaxon should be update to only include a subset_, you mean that the schema should be updated to change the requirements to a subset?

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
