### ISSUE TITLE
Amend DOI in Urethral luminal epithelia are castration-insensitive cells of the proximal prostate 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#113]
The `DOI` in [Urethral luminal epithelia are castration-insensitive cells of the proximal prostate](https://cellxgene.cziscience.com/collections/fbc5881f-1ee3-4ffe-8095-35e15e1a08fc) duplicates the `Data Source`. 

The DOI value should be https://doi.org/10.1002/pros.24020

Based on some future work to automatically add publication metadata to collections  based on its DOI, these links should reference preprints or journal publications.

**Comment by pablo-gar** [comment]
Addressed here https://github.com/chanzuckerberg/single-cell-curation/issues/144
