### ISSUE TITLE
Update requirements for obs['sex_ontology_term_id']

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#1140]
# Context

See [**sci-data-eng**](https://czi-sci.slack.com/archives/C07AV4NU9D2/p1732644692581919). 

# Design

### schema v5.3.0
* obs (Cell metadata)
  * Updated requirements for `sex_ontology_term_id` to limit values to <I>female</i>, <i>hermaphrodite</i>, or <i>male</i>

---

### sex_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>sex_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"unknown"</code> if unavailable; otherwise, this MUST be one of:<br><br>
        <ul>
        <li><a href="https://www.ebi.ac.uk/ols4/ontologies/pato/classes?obo_id=PATO%3A0000383">PATO:0000383</a> for  <i>female</i></li>
        <li><a href="https://www.ebi.ac.uk/ols4/ontologies/pato/classes?obo_id=PATO%3A0000384">PATO:0000384</a> for  <i>male</i></li>
        <li><a href="https://www.ebi.ac.uk/ols4/ontologies/pato/classes?obo_id=PATO%3A0001340">PATO:0001340</a> for  <i>hermaphrodite</i></li>
        </ul>
        </td>
    </tr>
</tbody></table>
<br>

**Comment by brianraymor** [comment]
@nayib-jose-gloria @jahilton - can you review the design above?

**Comment by jahilton** [comment]
lgtm

**Comment by nayib-jose-gloria** [comment]
LGTM!
