### ISSUE TITLE
Explain to users how to interpret datasets hosted on cellxgene

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#127]
#### Story: 

_A Single Cell Biologist who is visualizing data in the cellxgene explorer wants to understand how to interpret the data values so that they can make correct inferences about the data_

#### Problem: 

For RNA-seq data, there are conventions that define how raw and normalized expression data should be interpreted. Raw RNA-seq data with UMIs can be interpreted to be the number of molecules of a gene detected in a cell. Normalized counts are the same data, but transformed so each cell has approximately the same total molecule abundance. In both cases, large counts mean high expression of a gene. This information is broadly known to the Single Cell Biology community, but will not be known by non-experts. When we want to expose data to the broader community, as user will need to understand how to interpret the data. 

Methyl-C-seq [(dataset link)](https://cellxgene.cziscience.com/e/7eb757a2-e93f-4273-9cde-bcc7d7d0ac4f.cxg/) may be problematic even for our most savvy users. It should be interpreted inversely to the dominant RNA-seq expression type - _low_ counts imply high expression of a gene. This is not communicated in any way by the application. 

In the below screenshot, Arpp21 is _highly expressed_ in glutamatergic neurons. You **must** understand how the assay functions to understand why this is the case. 

![image.png](https://images.zenhubusercontent.com/5b2bd089a26e500c78d1a809/bd8d4245-fd2a-4d6e-afca-923f13d8088f)

There are at least three considerations:

1. Should we provide more guidance in the schema about how data should be submitted? If yes, how should we approach this? Should we enable users to submit new assays in the form they want to for a period, and then revise them, or do up-front research on data formats, only accepting them when we're convinced there is convergence?)
2. How should we convey what we know to be true about data and its interpretation to users in the UI?
3. How should we ensure that each data type we accept is supported by our algorithms (such as differential expression). While it appears to function, it is not a given that differential expression would function properly on these data distributions.

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell #292](https://github.com/chanzuckerberg/single-cell/issues/292) via [**ZenHub**](https://www.zenhub.com/)
