### ISSUE TITLE
Release curation tool with 2.0.0 schema support

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-curation#135]
. Review pending [PRs](https://github.com/chanzuckerberg/single-cell-curation/pulls), decide on inclusion into release, and merge as needed.
-1. `make fmt lint` (Consider running these automatically as part of pydist)
0. Verify unit tests pass: Either check github actions or run `make unit-test`  (Consider running these automatically as part of pydist)
~1. Upgrade `setup.py` version to `1.0.0` and commit~ (TODO: anywhere else? use a cmd to update in all places?)
2. Test local install: `make --install` and run `--validate` on example file
3. Release to test.pypi.org: `make test-release`
4. Verify test.pypi.org package installs and runs (Consider adding an `install-test-release` Make target for convenience).
5. Announce on #single-cell-data-wrangling (Stanford curators only), inviting curators to verify the test.pypi.org package installs and runs
6. Release to pypi.org: `make release`.
7. Verify install. (Consider adding an `install-release` Make target for convenience).
8. Announce on #single-cell-data-representation (full curator community)
9. Git tag `v1.0.0` on `main` branch

Consider:
* Freezing pip pkg requirements to latest versions.

**Comment by brianraymor** [comment]
RE `5`  and `8`- only Stanford is on #single-cell-data-wrangling. There's a separate channel in CZI Science Community slack named #single-cell-data-representation that includes the full community. There's also a biweekly call on Tuesdays with the curators where we discuss proposals and share early designs for feedback.

**Comment by atolopko-czi** [comment]
Ah, good to know! Sound like we can limit the test.pypi.org test to Stanford then (keep 5 as is) and announce globally in 8.

**Comment by atolopko-czi** [comment]
Samples files we can use to test curation tool usage (before and/or after releasing to pypi): 
* https://submissions-lattice.s3.us-west-1.amazonaws.com/cxg_migration/final/9c8808ce-1138-4dbe-818c-171cff10e650_cfa3c355-ee77-4fc8-9a00-78e61d23024c.h5ad
* https://submissions-lattice.s3.us-west-1.amazonaws.com/cxg_migration/final/60358420-6055-411d-ba4f-e8ac80682a2e_2d66790a-6621-4a49-8f0d-4002db5cc98d.h5ad
*https://submissions-lattice.s3.us-west-1.amazonaws.com/cxg_migration/final/60358420-6055-411d-ba4f-e8ac80682a2e_08e94873-c2a6-4f7d-ab72-aeaff3e3f929.h5ad
* https://submissions-lattice.s3.us-west-1.amazonaws.com/cxg_migration/final/b9fc3d70-5a72-4479-a046-c2cc1ab19efc_ae5341b8-60fb-4fac-86db-86e49ee66287.h5ad
* https://submissions-lattice.s3.us-west-1.amazonaws.com/cxg_migration/final/9c8808ce-1138-4dbe-818c-171cff10e650_26ae14da-9e5f-4d18-abae-18a5a328feef.h5ad
* https://submissions-lattice.s3.us-west-1.amazonaws.com/cxg_migration/final/9132fae8-bdfe-480f-9e45-45bc77f320b3_257adc73-8152-414b-a2c7-73861b8e0c0a.h5ad

**Comment by atolopko-czi** [comment]
@pablo-gar successfully released to test.pypi.org and performed install from there, and successfully validated a curator's hda5 file.

Note that on test.pypi.org we had to upload as v1.0.1, not v1.0.0, since the latter apparently had been used in the past and we ran into file naming conflict errors.  For prod pypi, we'll attempt to use 1.0.0, but will increment similarly if needed.

**Comment by maniarathi** [comment]
@atolopko-czi For cellxgene Desktop, we added `rc` to signify release candidates so that we wouldn't accidentally burn version numbers. Do you think it's worth instituting that policy for this package as well or do you think it would be overkill? Reference to the release process here: https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/release_process.md#releasing-a-major-or-minor-version-of-cellxgene

**Comment by atolopko-czi** [comment]
Yeah, `rc` suffixes should be part of this test release process.  Will that build that in, as I work on documenting (and adding some minor Makefile automation) for this repo's release process. Will use the `cellxgene` release process for "inspiration" along the way. :)  

This time around `1.0.0` seems to have simply been used by a prior release effort, and presumably deleted/yanked.  We're hoping that *prod* pypi.org still allows us to use `1.0.0`. (There doesn't seem to be a way to check on previously uploaded, but deleted filenames on pypi!?)

**Comment by atolopko-czi** [comment]
I was hoping to rely upon the cellxgene desktop release process and went so far as to copy much of the Makefile targets for the release process, which include the release candidate flow to test.pypi.org. Alas, that process seems fairly broken: bumpversion doesn't work as expected, there are some minor Makefile bugs, etc. So it seems like it needs some love.  I started down the path of fixing bumpversion, got close but ended up stuck, and began experimenting with `tbump` and `incremental`. So still a work in progress, but going to table this for a bit to get on with Desktop 1.0 squad work.

**Comment by atolopko-czi** [comment]
@pablo-gar Can we close this issue now? Looks like we're fully released with 1.0.0 to pypi.org.   Perhaps we should just tag the git repo with `v1.0.0` on the commit that was used to build the release?

**Comment by pablo-gar** [comment]
Seems like that release version is not the most up to date version. @atolopko-czi I can release the latest as version 2.0.0 -- per the discussion we had -- update the log change and then merge to main with the 2.0.0 tag. I think that would be enough to close this issue.

**Comment by atolopko-czi** [comment]
> Seems like that release version is not the most up-to-date version. @atolopko-czi I can release the latest as version 2.0.0 -- per the discussion we had -- update the change log and then merge to main with the 2.0.0 tag. I think that would be enough to close this issue.

Sounds good! And maybe we can "yank" (hide) the 1.0.0 release using pypi UI.

**Comment by pablo-gar** [comment]
All done!
We can close this now.
