### ISSUE TITLE
update publication DOI and contact of published Collections

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#144]
A couple of weeks ago, we ran through each Collection to see if the specified DOI resolved to the most updated publication version. Below are the additions/edits needed
<google-sheets-html-origin><style type="text/css"></style>

collection_id | collection_name | doi
-- | -- | --
180bff9c-c8a5-4539-b13b-ddbc00d643e6 | Molecular characterization of selectively vulnerable neurons in Alzheimer's Disease | 10.1038/s41593-020-00764-7
fbc5881f-1ee3-4ffe-8095-35e15e1a08fc | Urethral luminal epithelia are castration-insensitive cells of the proximal prostate | 10.1002/pros.24020
e5f58829-1a66-40b5-a624-9046778e74f5 | Tabula Sapiens | 10.1101/2021.07.19.452956
00109df5-7810-4542-8db5-2288c46e0424 | Massively multiplex chemical transcriptomics at single-cell resolution | 10.1126/science.aax6234
5d445965-6f1a-4b68-ba3a-b8f765155d3a | A molecular cell atlas of the human lung from single cell RNA sequencing | 10.1038/s41586-020-2922-4
9b02383a-9358-4f0f-9795-a891ec523bcc | Single cell transcriptional and chromatin accessibility profiling redefine cellular heterogeneity in the adult human kidney | 10.1038/s41467-021-22368-w
9c8808ce-1138-4dbe-818c-171cff10e650 | A single-cell transcriptional roadmap of the mouse and human lymph node lymphatic vasculature | 10.3389/fcvm.2020.00052
d0e9c47b-4ce7-4f84-b182-eddcfa0b2658 | Single-cell gene expression profiling of SARS-CoV-2 infected human cell lines | 10.1016/j.isci.2021.102151
2a79d190-a41e-4408-88c8-ac5c4d03c0fc | Single-cell longitudinal analysis of SARS-CoV-2 infection in human bronchial epithelial cells | 10.1101/2020.05.06.081695
38833785-fac5-48fd-944a-0f62a4c23ed1 | Construction of a human cell landscape at single-cell level | 10.1038/s41586-020-2157-4
558385a4-b7b7-4eca-af0c-9e54d010e8dc | Single-Cell RNAseq analysis of diffuse neoplastic infiltrating cells at the migrating front of human glioblastoma | 10.1016/j.celrep.2017.10.030
a238e9fa-2bdf-41df-8522-69046f99baff | Single-Cell Analysis of Human Pancreas Reveals Transcriptional Signatures of Aging and Somatic Mutation Patterns | 10.1016/j.cell.2017.09.004
a72afd53-ab92-4511-88da-252fb0e26b9a | Single-cell atlas of peripheral immune response to SARS-CoV-2 infection | 10.1038/s41591-020-0944-y
cdfb9ead-cb58-4a53-879d-5e4ed5329e73 | Direct Exposure to SARS-CoV-2 and Cigarette Smoke Increases Infection Severity and Alters the Stem Cell-Derived Airway Repair Response | 10.1016/j.stem.2020.11.010

We also looked at Collections with no specified Contact, and looked in the uns for what was noted there. A couple have multiple, so we may need to ask the curator for each Collection which is most appropriate (or just pick one based on publication contact author?)
<google-sheets-html-origin><style type="text/css"></style>

collection_id | collection_name | contact
-- | -- | --
00109df5-7810-4542-8db5-2288c46e0424 | Massively multiplex chemical transcriptomics at single-cell resolution | {"name": "Sanjay Srivatsan", "institution": "University of Washington", "email": "sanjays@uw.edu"}
5d445965-6f1a-4b68-ba3a-b8f765155d3a | A molecular cell atlas of the human lung from single cell RNA sequencing | {"name": "Angela Pisco", "institution": "Chan Zuckerberg Biohub", "email": "angela.pisco@czbiohub.org"}
d0e9c47b-4ce7-4f84-b182-eddcfa0b2658 | Single-cell gene expression profiling of SARS-CoV-2 infected human cell lines | {"name": "Wyler Emanuel", "institution": "Berlin Institute for Medical Systems Biology", "email": "emanuel.wyler@mdc-berlin.de"}
2a79d190-a41e-4408-88c8-ac5c4d03c0fc | Single-cell longitudinal analysis of SARS-CoV-2 infection in human bronchial epithelial cells | {"name": "Neal G. Ravindra", "institution": "Yale University", "email": "neal.ravindra@yale.edu"}
38833785-fac5-48fd-944a-0f62a4c23ed1 | Construction of a human cell landscape at single-cell level | [{"name": "Huiyu Sun", "institution": "Zhejiang University School of Medicine", "email": "sunhuiyu@zju.edu.cn"}, {"name": "Guoji Guo", "institution": "Zhejiang University School of Medicine", "email": "ggj@zju.edu.cn"}]
a72afd53-ab92-4511-88da-252fb0e26b9a | Single-cell atlas of peripheral immune response to SARS-CoV-2 infection | [{"name": "Aaron Wilk", "institution": "Stanford University", "email": "awilk@stanford.edu"}, {"name": "Angela J. Rogers", "institution": "Stanford University", "email": "ajrogers@stanford.edu"}, {"name": "Catherine A. Blish", "institution": "Stanford University", "email": "cblish@stanford.edu"}]

**Comment by pablo-gar** [comment]
All of these collections have been updated.

For reference I had a spreadsheet to keep track of the changes:
https://docs.google.com/spreadsheets/d/1tGEmkRLKCqwKO6z7ZcWFAGXMgOxSey_81eZ50AeasQ4/edit#gid=1148298792
