### ISSUE TITLE
When users receive errors about ENSEMBL genes that don't exist in our chosen reference, provide guidance to help them resolve the problem.

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#146]
There are at least three ENSEMBL genome references _in play_. We've chosen to standardize on one. As a result, we anticipate that there will be small numbers of invalid gene IDs in any dataset that was aligned to references other than the one we picked. In those cases, it would be good to provide the user with some guidance about how to reconcile their gene reference with our requirements. Some ideas that could be explored include: 

1. Pointing them to the file that we store, which records valid names, and providing a link to documentation that instructs them on how to remove the genes
2. The validator could identify the list of gene names that are invalid and print them so that the user could copy them and directly use them to filter out genes. 

cc @jahilton

**Comment by brianraymor** [comment]
@ambrosejcarr - I wonder if the [ID History Converter](https://uswest.ensembl.org/Help/View?db=core;id=560) would be helpful?

**Comment by ambrosejcarr** [comment]
Closing based on validator capabilities.
