### ISSUE TITLE
Amend DOI in Ye dataset

### ISSUE THREAD

**Issue by MaximilianLombardo** [chanzuckerberg/single-cell-curation#147]
The following [collection](https://cellxgene.cziscience.com/collections/7d7cabfd-1d1f-40af-96b7-26a0825a306d), needs to be amended.

The amendments that need to be made are:

- DOI
- Title (based on new DOI link)
- Abstract (base on new DOI link)

## New DOI

[https://doi.org/10.1126/scitranslmed.abh2624](https://doi.org/10.1126/scitranslmed.abh2624)

## New Title (collection name and dataset title)
Type I interferon autoantibodies are associated with systemic immune alterations in patients with COVID-19

## New abstract text

Neutralizing autoantibodies against type I interferons (IFNs) have been found in some patients with critical coronavirus disease 2019 (COVID-19), the disease caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). However, the prevalence of these antibodies, their longitudinal dynamics across the disease severity scale, and their functional effects on circulating leukocytes remain unknown. Here, in 284 patients with COVID-19, we found type I IFN-specific autoantibodies in peripheral blood samples from 19% of patients with critical disease and 6% of patients with severe disease. We found no type I IFN autoantibodies in individuals with moderate disease. Longitudinal profiling of over 600,000 peripheral blood mononuclear cells using multiplexed single-cell epitope and transcriptome sequencing from 54 patients with COVID-19 and 26 non-COVID-19 controls revealed a lack of type I IFN-stimulated gene (ISG-I) responses in myeloid cells from patients with critical disease. This was especially evident in dendritic cell populations isolated from patients with critical disease producing type I IFN-specific autoantibodies. Moreover, we found elevated expression of the inhibitory receptor leukocyte-associated immunoglobulin-like receptor 1 (LAIR1) on the surface of monocytes isolated from patients with critical disease early in the disease course. LAIR1 expression is inversely correlated with ISG-I expression response in patients with COVID-19 but is not expressed in healthy controls. The deficient ISG-I response observed in patients with critical COVID-19 with and without type I IFN-specific autoantibodies supports a unifying model for disease pathogenesis involving ISG-I suppression through convergent mechanisms.

**Comment by jahilton** [comment]
Collection metadata have been updated & published
Added these to our migration guide...
uns['publication_doi'] updated to `https://doi.org/10.1126/scitranslmed.abh2624`
uns['title'] updated to `Type I interferon autoantibodies are associated with systemic immune alterations in patients with COVID-19`

**Comment by jahilton** [comment]
Dataset has been migrated & published
