### ISSUE TITLE
Define the requirements for AnnData uns when converting to RDS

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#149]
See the [conversation](https://czi-sci.slack.com/archives/C024HCSH9PT/p1632951471257100?thread_ts=1632861659.254700&cid=C024HCSH9PT) in wrangling. During ingestion of the cellxgene Data Portal, `uns` metadata is currently ignored by `sceasy`, so it is missing in the RDS download.

Before crafting a solution, there needs to be clarity on the requirements for `uns` when schema 2.0.0 AnnData datasets are converted to RDS.

Other [conversions](https://rdrr.io/github/mojaveazure/seurat-disk/man/H5ADToH5Seurat.html) document behavior such as:

> All groups and datasets from /uns will be copied to misc in the h5Seurat file except for the following:
> Any group or dataset named the same as a dimensional reduction (eg. /uns/pca)
> /uns/neighbors

**Comment by ambrosejcarr** [comment]
`@misc` appears to be the leading candidate. The [third converter I am aware of does not have an opinion about uns](https://theislab.github.io/scanpy-in-R/#converting-from-r-to-python-1). 

I recommend asking the Seurat group's opinion of the correct solution during review of #148

**Comment by pablo-gar** [comment]
The Seurat group confirmed that the the slot `misc` should be used to transfer the dataset metadata from `uns`.

**Comment by brianraymor** [comment]
@pablo-gar - would you update the seurat encoding to reflect the decision to use `misc` and close this issue? @metakuni is starting on [Seurat conversion is missing the uns metadata](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1581). 

**Dataset Metadata**
At the moment a Seurat object downloaded from cellxgene does not contain the dataset metadata stored in the AnnData slot uns.

**Comment by metakuni** [comment]
@brianraymor / @ambrosejcarr / @pablo-gar : Ok to close this story? I've implemented the uns metadata migration in the Seurat conversion. :smile:

**Comment by brianraymor** [comment]
@pablo-gar should merge #179 which will close this issue.
