### ISSUE TITLE
Use assay-specific naming for expression matrices in Seurat object

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#150]
As a consequence of using `sceasy` during automatic conversion from AnnData to Seurat in the cellxgene portal, all expression matrices are transferred to `seurat_object@assays$RNA`. 

Non-RNA assays should be labeled based on the name of the assay, e.g. ATAC-seq data should be assigned to `seurat_object@assays$ATAC`.

Potential solutions:

- Update `sceasy` to be assay-aware and perform proper naming of the expression matrices in the Seurat object.
- After automatic conversion with `sceasy` further process the converted object to change the name of the expression matrix if needed.

**Comment by brianraymor** [comment]
Moving to single-cell-data-portal. The sceasy conversion is part of the ingestion pipeline.

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell-data-portal #2776](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2776) via [**ZenHub**](https://www.zenhub.com/)
