### ISSUE TITLE
Pre-analysis data schema & validation

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#151]
### Pre-analysis data schema & validation

Over the last week, the HCA DCP and Gut Cell Atlas about whether it would be possible to use the schema for earlier, pre-publication data sharing and standardization within their networks. The use case is the same for both groups: 

> _As a consortium, we want to encourage our teams to format their data matrices in a standard way, but groups often lack analysis results at the stage that they want to share data, so cannot generate data that adheres to the cellxgene schema._

We want to encourage the ecosystem to adopt a standard schema. If the single cell matrix schema does not fulfill this use case, toolchains and consortia that need to handle data pre-publication will not have access to single cell matrix schema validation tooling, and will not be able to use this schema to standardize their data until it is ready for publication. 

I came up with a potential approach that would work (and which includes an analysis of changes required to cellxgene products) to illustrate, and am interested in feedback.

### Potential solution

1. The schema is partitioned into 
  a. Base module
  b. Visualization module
2. Validation is expanded to validate: 
  a. Base module 
  b. Base + Visualization module
3. Portal updated to utilize validation option 2.b (no changes to data entering portal)

##### Changes to schema 

`X` (matrix data)
* "strongly recommended" processed results eliminated from Base module. Processed results are REQUIRED in visualization module. 

`obs` (cell metadata)
* CL terms move to visualization module

`obsm`
* required embeddings move to visualization module

`uns`
* X_normalization moves to visualization module

#### Problems:

1. AnnData's decision to use `.X` as the required and default data slot make it very challenging to consistently represent raw data only (raw in `.X`) and raw + processed data (raw in `.X.raw` and processed in `.X`). Any user adding processed data to this schema needs to remake their AnnData object. 
2. Theoretically, we currently accept RNA-seq data that includes only raw data, and we let that be visualized in the explorer. This is an almost universally bad experience. To address these cases, In the future, cellxgene _could_ accept and enable download but NOT visualization of data that validates only the _Base Module_. Or, we could reject these cases.

**Comment by brianraymor** [comment]
@BAevermann - I'll let you close this issue if it will not be used further.

**Comment by brianraymor** [comment]
Closing @BAevermann - reopen if needed.
