### ISSUE TITLE
validation error in MMUSDV element

### ISSUE THREAD

**Issue by davidsebfischer** [chanzuckerberg/single-cell-curation#158]
I am using a .obo representation of MMUSDV and am getting an error when trying to supply the field `2-week-old stage` which is `MmusDv:0000141`:

`
"ERROR: 'MmusDv:0000141' in 'development_stage_ontology_term_id' is not a valid ontology term id of 'MmusDv'. When 'organism_ontology_term_id' is 'NCBITaxon:10090' (Mus musculus), 'development_stage_ontology_term_id' MUST be a term id of 'MmusDv' or unknown."]
`

This node is registered in the newest version of that ontology (master branch, but not released):
https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/master/src/mmusdv/mmusdv.obo
But not in the newest release (0.1, from 5 years ago):
https://raw.githubusercontent.com/obophenotype/developmental-stage-ontologies/0.1/src/mmusdv/mmusdv.obo

In the documentation of schema version 2.0.3, it says that you want the newer MMUSDV release (https://github.com/chanzuckerberg/single-cell-curation/blob/v2.0.3/schema/2.0.0/schema.md) and also distinguish exactly these tags 0.1 and the newer version from earlier this year. 
So I am wondering if the validate CLI accidentally accesses the older version or if there is a diversion between the obo on github and the owl that you use?

**Comment by brianraymor** [comment]
Unlike the other pinned ontologies in the schema, HsapDv and MmuDv do not have recent releases tagged in their repo. See [tags](https://github.com/obophenotype/developmental-stage-ontologies/tags) for example.

The schema pins the `data-version: releases/2020-03-10` which is the "current" release on:

- http://www.obofoundry.org/ontology/mmusdv.html
- http://aber-owl.net/ontology/MMUSDV/#/
- https://www.ebi.ac.uk/ols/ontologies/mmusdv
