### ISSUE TITLE
Document Lattice guidance for curators

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#159]
We need to provide guidance for curators that are able to create Collections, submit h5ad datasets, publish, etc.
How to report error on upload or conversion, how to contact Lattice for a pre-Publish QA, etc.

**Comment by brianraymor** [comment]
@jahilton - will you have time to address in Q3?

**Comment by jahilton** [comment]
No, I think Q4 is more realistic for this

**Comment by jahilton** [comment]
@brianraymor thoughts on where to keep these guidelines?
We have [this directory](https://github.com/Lattice-Data/lattice-tools/tree/main/cellxgene_resources) in our repo that we haven't publicized but will be shaping up for curator resources.
Or somewhere in single-cell-curation?

**Comment by brianraymor** [comment]
I think it would be best to keep the guidelines in single-cell-curation with the schema and CLI.
