### ISSUE TITLE
document guidance for contributors that do not have submit keys

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#160]
We need to provide guidance for researchers that would like to submit data to cellxgene but cannot directly submit and therefore, need to work with a curator to submit datasets
Who to contact, what to expect, what types of data are accepted, etc.

The single-cell-curation readme may be the appropriate place for this documentation

**Comment by brianraymor** [comment]
This should be addressed as part of the _doc site_ project which includes a FAQ

**How can I contribute a dataset to the cellxgene data portal?**
_We are continuing to expand our data corpus and would love to chat further. Reach out to our curation team at ..._

Raised on their [slack](https://czi-sci.slack.com/archives/C037WS42XV3/p1654274960404139).

**Comment by jahilton** [comment]
This is handled via https://github.com/chanzuckerberg/single-cell-data-portal/pull/2735
