### ISSUE TITLE
Remove feature_id from schema

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#166]
The schema indicates that var.index & raw.var.index should be named `feature_id` (https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#feature_id)
But this is not validated and not an actual requirement so should be removed from the schema.

**Comment by brianraymor** [comment]
> But this is not validated 

**Naughty.**

---

How 'bout:

~~`var.index` MUST contain unique identifiers for features. `raw.var.index` MUST be identical to `var.index`~~

Curators MUST annotate the following columns in the `var` and `raw.var` dataframes:

...

### index

<table><tbody>
    <tr>
      <th>Key</th>
      <td><code>index</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. <code>var.index</code> MUST contain unique identifiers for features. <code>raw.var.index</code> MUST be identical to <code>var.index</code>.<br><br> If the <code>feature_biotype</code> is <code>"gene"</code> then this MUST be an ENSEMBL term. If the <code>feature_biotype</code> is <code>"spike-in"</code> then this MUST be an ERCC Spike-In identifier. </td>
    </tr>
</tbody></table>
<br>
