### ISSUE TITLE
Example of Configuration.yaml in Corpora Schema guide is outdated

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#17]
@brianraymor commented on [Wed Jan 20 2021](https://github.com/chanzuckerberg/single-cell/issues/112)

This was reported by @jahilton. 

The [schema](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/schema/corpora_schema.md) version is 1.1.0, but the sample [configuration.yaml](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/schema_guide.md#configuration-yaml) in the Corpora Schema Guide has not been updated to reflect the changes, including some [deprecations of fields]( https://github.com/chanzuckerberg/single-cell/issues/75). 

---

@mckinsel commented on [Tue Feb 16 2021](https://github.com/chanzuckerberg/single-cell/issues/112#issuecomment-780133401)

We're moving this to the single-cell-curation repo (which will be public shortly), and the guide has been updated.

---

@brianraymor commented on [Tue Feb 16 2021](https://github.com/chanzuckerberg/single-cell/issues/112#issuecomment-780139563)

You can use `Transfer issue` to accomplish that task.

<img width="184" alt="Screen Shot 2021-02-16 at 1 48 59 PM" src="https://user-images.githubusercontent.com/3644743/108125774-cdaf0180-705d-11eb-8943-a9a879d127b0.png">

**Comment by pablo-gar** [comment]
This was amended during the transfer to single-cell-curation

**Comment by brianraymor** [comment]
Missed it by _that much_, the example is introduced as "required fo the 1.0.0 schema":

> The configuration yaml file describes how to apply the schema. This is an example of a "skeleton" yaml that has all the fields required for the **1.0.0** schema but is not yet filled in with any logic:

**Comment by pablo-gar** [comment]
Thanks! Fixed [here](https://github.com/chanzuckerberg/single-cell-curation/commit/3f5038a0f02e3067d911b9e8469baa0e82aeb156)
