### ISSUE TITLE
The schema policy for PII and deprecated fields must be clarified and enforced.

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#181]
Per the [thread](https://czi-sci.slack.com/archives/C024HCSH9PT/p1638490598132100) in **wrangling**. 

Deprecated schema 1.0.0 (see [Refinements to schema](https://github.com/chanzuckerberg/single-cell/issues/75)) and 1.1.0 fields SHOULD NOT be present in datasets curated to 2.0.0. This is especially true for **PII such as contributors email addresses**.

> {'X_normalization': 'log1p', 'contributors': '[{"name": "Menglan Xiang", "email": "mxiang1@stanford.edu", "institution": "Stanford University"}]', 'default_embedding': 'X_tUMAP', 'layer_descriptions': {'X': 'log1p', 'raw.X': 'raw'}, 'preprint_doi': 'https://doi.org/10.1101/2019.12.31.892166', 'publication_doi': 'https://doi.org/10.1101/2019.12.31.892166', 'schema_version': '2.0.0', 'title': 'A Single-Cell Transcriptional Roadmap of the Mouse and Human Lymph Node Lymphatic Vasculature - mouse'}

Including DOI(s) in the dataset duplicates collection metadata and does not allow the portal to update stale pre-print DOI(s) with the published version which is planned for 2022. 

To that end:

1. The current data corpus must be _tidied_ by Stanford to eliminate deprecated fields.
1. The specification must inform curators that a future version of the `cellxgene-schema` CLI will fail such cases during validation.
2. The PII requirement in the specification must be clarified per @jahilton's suggestion:

> No PII. Curators agree to this requirement as part of the data submission policy. However, it is not strictly enforced in our validation tooling because it is difficult for software to predict what is and is not PII. It is up to the submitter to ensure that no metadata can be personally identifiable: no names, dates of birth, specific locations, etc. This includes names, emails, and other PII of any researcher or curator involved in the data generation and submission. See this list for guidance.

**Comment by jahilton** [comment]
I think if I were learning cellxgene schema for the first time, I'd want more explanation...

- **Reserved Names**. The names of the metadata keys specified by the schema are reserved and MUST be unique. For example, duplicate "feature_biotype" keys in AnnData var are not allowed. Reserved Names from previous schema versions that have since been deprecated MUST NOT be present in datasets:

**Comment by brianraymor** [comment]
Addressed in #263

**Comment by brianraymor** [comment]
I'm still pondering the PII editorial because it feels a bit redundant. Keeping the issue open for the moment.

**Comment by jahilton** [comment]
Should probably define PII, right?
**No Personal Identifiable Information (PII).** ...

I think it's good otherwise
