### ISSUE TITLE
Expand Schema to represent composed datasets

### ISSUE THREAD

**Issue by BAevermann** [chanzuckerberg/single-cell-curation#186]
This ticket serves to start the requirement gathering process for representing composed datasets in cellxgene schema. Currently composed datasets are inferred from the "is_primary" metadata; however, as Atlasing becomes a key driver of our dissemination strategy, we will need to be more explicit on how composed datasets are assembled. One possible use case being the provenance of the cells included in the Atlas, i.e., in what dataset is this cell "primary" and what data processing has transpired from that "primary" state.

**Comment by brianraymor** [comment]
No action conversation. Not actionable. Closing.
