### ISSUE TITLE
In gene reference files, some gene names are ENSEMBL ids that are not the same as the actual gene id

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#188]
Reference: [single-cell-data-representation](https://cziscience.slack.com/archives/C01L65J7PLP/p1642006704002800).

The gene reference file `cellxgene_schema_cli/cellxgene_schema/ontology_files/genes_homo_sapiens.csv.gz` contains genes whose gene name is an ENSEBML id and it is not the same as the actual gene id.

For example:
`ENSG00000276312	ENSG10010139884.1`

There are 620 of such genes.

Further investigation indicates that this discrepancy already exists in the ENCODE reference GTF file used to create `genes_homo_sapiens.csv.gz`

**Potential solutions**
1. Do nothing, maintaining consistency with ENCODE.
2. Change the gene name to the original ENSEMBL id.

**Comment by jahilton** [comment]
Pulled directly from ENSEMBL - http://ftp.ensembl.org/pub/release-105/gtf/homo_sapiens/
`$  grep "ENSG00000276312" Homo_sapiens.GRCh38.105.*`

None of the results show any gene name for this gene.
`Homo_sapiens.GRCh38.105.chr_patch_hapl_scaff.gtf:KI270733.1	ensembl	gene	167218	167307	.	+	.	gene_id "ENSG00000276312"; gene_version "1"; gene_source "ensembl"; gene_biotype "misc_RNA";
Homo_sapiens.GRCh38.105.chr_patch_hapl_scaff.gtf:KI270733.1	ensembl	transcript	167218	167307	.	+	.	gene_id "ENSG00000276312"; gene_version "1"; transcript_id "ENST00000615130"; transcript_version "1"; gene_source "ensembl"; gene_biotype "misc_RNA"; transcript_source "ensembl"; transcript_biotype "misc_RNA"; tag "basic"; transcript_support_level "NA";
Homo_sapiens.GRCh38.105.chr_patch_hapl_scaff.gtf:KI270733.1	ensembl	exon	167218	167307	.	+	.	gene_id "ENSG00000276312"; gene_version "1"; transcript_id "ENST00000615130"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "misc_RNA"; transcript_source "ensembl"; transcript_biotype "misc_RNA"; exon_id "ENSE00003727949"; exon_version "1"; tag "basic"; transcript_support_level "NA";
Homo_sapiens.GRCh38.105.gtf:KI270733.1	ensembl	gene	167218	167307	.	+	.	gene_id "ENSG00000276312"; gene_version "1"; gene_source "ensembl"; gene_biotype "misc_RNA";
Homo_sapiens.GRCh38.105.gtf:KI270733.1	ensembl	transcript	167218	167307	.	+	.	gene_id "ENSG00000276312"; gene_version "1"; transcript_id "ENST00000615130"; transcript_version "1"; gene_source "ensembl"; gene_biotype "misc_RNA"; transcript_source "ensembl"; transcript_biotype "misc_RNA"; tag "basic"; transcript_support_level "NA";
Homo_sapiens.GRCh38.105.gtf:KI270733.1	ensembl	exon	167218	167307	.	+	.	gene_id "ENSG00000276312"; gene_version "1"; transcript_id "ENST00000615130"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "misc_RNA"; transcript_source "ensembl"; transcript_biotype "misc_RNA"; exon_id "ENSE00003727949"; exon_version "1"; tag "basic"; transcript_support_level "NA";`

Makes me wonder if it's something that GENCODE introduces

**Comment by jahilton** [comment]
Sorry for pushing #allthebuttons

Grabbed the GTFs from ENSEMBL (http://ftp.ensembl.org/pub/release-105/gtf/homo_sapiens/) and those do not have a gene_name listed for ENSG00000276312

Grabbed the ALL GTF from GENCODE (https://www.gencodegenes.org/human/) and it looks "typical" with the same ID used for gene_name
`KI270733.1	ENSEMBL	gene	167218	167307	.	+	.	gene_id "ENSG00000276312.1"; gene_type "misc_RNA"; gene_name "ENSG00000276312"; level 3;`

**Comment by jahilton** [comment]
Based on the results above from v39, it seems like this may have been a bug in v38. I would think to look at all mismatch ID/symbol cases from v38 and see if they are matched as expected in v39 (noting that some may have been given actual symbols). If so, that could confirm the bug & give us more confidence going forward with option 2.

**Comment by brianraymor** [comment]
> I would think to look at all mismatch ID/symbol cases from v38 ...

@jahilton - where you planning to perform this exercise or was it a recommendation for someone else to pursue?

**Comment by jahilton** [comment]
I wrote it thinking @pablo-gar had a certain go-getter-ness about him, so I have not acted on it.
However, my 10-going-on-17-year-old daughter would say "You do it, it was your idea". So I will take the action item to compare what we're seeing in the v38 file with other versions.

**Comment by jahilton** [comment]
Pulled the PRI annotation version from [GENCODE](https://www.gencodegenes.org/human/releases.html) for v37, v38, and v39.
First looked at each to see how many genes had a gene_name that began with ENSG and did not match the gene_id. 620 for v38, 0 for v37, 0 for v39
Then I looked at the 620 IDs from v38 to see what their gene_name is in v37 & v39. They all have correctly matching ENSG IDs in v39. Interestingly, none have an ENSG gene_name in v37 ([full report](https://docs.google.com/spreadsheets/d/1UAzZhPIIaemwiYao84nW2jsOw-7IwMtxvYjfLkNEnyE/edit?usp=sharing)).

To me, this signals that it is acceptable for us to amend the v38 gene symbols: if the symbol starts with ENSG and it does not match the Ensembl ID, then the symbol used should be the Ensembl ID

**Comment by brianraymor** [comment]
@jahilton - do you have a sense for when we should update to v39?

**Comment by jahilton** [comment]
>do you have a sense for when we should update to v39?

Researchers are not necessarily hungry for best, most updated, annotations (hg19 is still a thing). So I don't anticipate any need to jump with each new version (as it requires filtering all the existing datasets). If we start seeing data come in from v39 or above, then we should bump to the most recent version as staying on v38 would mean filtering out 'good' genes from those datasets.
I think we should be keeping an eye on CellRanger. If their default GRCh38 version is updated (currently 32), then I think that would be good cause for us matching them, as that would most definitely result in a lot of data on that version.
