### ISSUE TITLE
explicitly note that specific ages above 89 are PII

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#192]
In the [General Requirements ](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#general-requirements)of the schema, there is a **No PII** bullet point, which then links to [this doc](https://docs.google.com/document/d/1sboOmbafvMh3VYjK1-3MAUt0I13UUJfkQseq8ANLPl8/edit) for guidance, which specifies `all ages over 89 or elements indicative of such age` is included as a direct personal identifier.
This is guided by [HIPAA Privacy Rule](https://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html) which specifies `The following identifiers of the individual or of relatives, employers, or household members of the individual must be removed to achieve the “safe harbor” method of de-identification...all ages over 89 and all elements of dates (including year) indicative of such age, except that such ages and elements may be aggregated into a single category of age 90 or older`

Easily the most common (only) PII that we've seen attempted to be submitted to cellxgene, I think we could specifically call it out in the **No PII** bullet point.

I will also create a validator ticket as this is something we could check for development_stage_ontology_term_id

**Comment by brianraymor** [comment]
Closing. Will discuss offline with @jahilton.
