### ISSUE TITLE
Improve cellxgene’s value proposition for data generators and consumers by capturing RNA+ATAC experiments.

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#195]
### Goal
Improve cellxgene's value proposition for researchers generating and publishing experiments that take both RNA-seq and ATAC-seq measurements from the same cells by enabling users to access both RNA and ATAC data modalities for the same set of cells in the cellxgene explorer, when they are available.

### Context
cellxgene currently serves data from RNA-seq experiments, measuring per-gene expression, and ATAC-seq experiments, measuring open chromatin regions along the genome. As ATAC-seq data are not confined to gene bodies, cellxgene serves only gene activity matrices, where the features have been translated from genomic coordinates to genes, resulting in gene features akin to RNA-seq data. We are anticipating an increasing amount of data from assays that provide both RNA-seq and ATAC-seq readouts from the same cell/nucleus. Users want to be able to explore both RNA-seq and ATAC-seq data, and leverage the dual measurements, using cellxgene.

If trends follow other assays, then we can expect a majority of data from these joint profiling experiments to come from 10x products, which in this case would be the [multiome kit](https://www.10xgenomics.com/products/single-cell-multiome-atac-plus-gene-expression). Other protocols that achieve similar measurements include [SNARE-seq](https://doi.org/10.1038/s41587-019-0290-0) and [SHARE-seq](https://doi.org/10.1016/j.cell.2020.09.056).

**Comment by jahilton** [comment]
[landscape doc](https://docs.google.com/document/d/1Ucxusje8KmSdtDhMCFIZ1bHBoRLw-k1XrZI_kdSqCco/edit?usp=sharing)

**Comment by brianraymor** [comment]
[Document](https://docs.google.com/document/d/1mnem9U5UZ2CRpuSGQ0JtOVDn05w-4oRs5POwlDFp4bQ/edit#heading=h.nc5agzmeh6t0) reviewed with curators.

**Comment by jahilton** [comment]
Update:
We currently have 2 Collections that contain data from "10x multiome", an assay which measure both expression (RNA) & chromatin accessibility (ATAC).

- https://cellxgene.cziscience.com/collections/348da6dc-5bf6-435d-adc5-37747b9ae38a
- https://cellxgene.cziscience.com/collections/1ca90a2d-2943-483d-b678-b809bf464c30

We have data incoming from Seed Network researchers that will be mCT-seq, which measure expression & methylation - so will present a similar challenge.
Summarizing the issue at hand: There is currently no way for a user to know if the data represents the expression or the accessibility measurements (both of those Collection currently only have expression data)
I imagine this will be a blocker for including these datasets in the Census.

**Comment by brianraymor** [comment]
Closing again until this experiment is prioritized by Data Generation.
