### ISSUE TITLE
Add mandatory "batch" field

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#2]
Ambrose says _Normalization and integration methods perform better when conditioned on the "batch" that data were produced in, as different batches tend to vary due to technical (nuisance) factors._

**Note**: Capturing #single-cell-data-wrangling thread [with minor edits] before it _evanesces_.

@ambrosejcarr

_`batch` is **categorical**. Most often I find they are integer valued. Unless batches have been dropped, they are usually sequential integers._

_For normalization (and integration), `batch` is as important as donor or disease, and should therefore be mandatory.
`batch` can sometimes take a scalar value when you run all the data on a single lane of a sequencer -- so, sometimes it’s not a useful thing to record (`batch` is just all “0") Of course, this isn’t unique to `batch` -- you can also have datasets generated from a single donor._

@mckinsel 

_so the thing is, i don’t think anybody has submitted data that has a clear concept of `batch` ... like it’s in there in some sense, and if we wanted to we could make batch a mandatory field. but if we leave it an optional field, then what exactly are we saying? “you can have a meta[data] field called `batch` and it can take on whatever values you want” that’s already true. everything not prohibited is permitted_

@bkmartinjr 

_a) is there a practical way to normalize and/or integrate datasets if we do not know which metadata is associated with `batch` (ie, can be used to condition models)?  If we do not have `batch`, is there an alternative where we can do without, or automatically detect it, to achieve the same result? I have been operating on the assumption that the answer is "no", and that we must add some support for this if we want to hit our longer-term goal of enabling integration.  Is this misinformed?_

_b) I imagine that the concept of `batch` will often be ambiguous in scope, at least when used for model building (eg, [scarches](https://github.com/theislab/scarches) label transfer). It really boils down to "which metadata do I condition the model on", which will often be more than traditional "lab batch" identity.  It might even be multiple metadata fields - I have seen several examples where the conditioning required multiple "batch ids".  Can we actually mandate a single field, with a single meaning or do we need something more flexible._

_I am wondering if an alternative is a DataSet-wide field that encodes which per-cell metadata are (together) the batch / condition variable?  Ie. if `adata.obs["patient"]` and `adata.obs["seqBatch"]` exist, then `adata.uns["conditions"] = ["patient", "seqBatch"]`_

@ambrosejcarr

_Agree with "**I imagine that the concept of `batch` will often be ambiguous in scope**," from (b). What we're lacking is a `batch-other` field to capture ideas like seqBatch that aren't in our schema. I anticipate that conditioning on multiple metadata will be critical in the future._

@bkmartinjr 

_So, why not simply let people encode which fields are the "conditions", ie, should be used in combination as a `batch`? Mandate that, but don't mandate the actual encoding of the individual fields._

@ambrosejcarr

_That may be the right path. Making sure I'm understanding -- some of the fields referenced as "conditions" may be non-standard fields, right?_

@bkmartinjr 

_actually, I was proposing adding a "meta field", which names the fields that are suggested conditions. ie, `adata.uns["condition_fields"] = ["batch", "patient", "some_other_column"]`and you could make that condition_fields dataset attribute mandatory._

@ambrosejcarr

_I think the existence of some_other_column in the reference answers the question I had -- I wasn't articulating it well. I wanted to know if you saw any requirement that fields referenced in the "meta-field" (batch, patient, some_other_field) in your example, needed to be defined in our schema -- I think the answer is no, based on your responses._

@bkmartinjr 

_correct, I didn't see any reason to mandate which columns are batch, only that the indirect pointer to the batch/condition columns exist. Likewise, I didn't see a reason to mandate the type of the batch/condition columns - while they are often enumerated types, I don't think they will always be so (and the algos don't really care)._

@ambrosejcarr 

_**(and the algos don't really care).** Say more about this? My understanding is that so long as the algo can convert the column into an enumerated type, the algo is happy. Does that match your understanding?_

@bkmartinjr 

_I think a lot of the algos don't even care how big the enumeration is, ie, it can effectively be continuous and it will work OK.  TL;DR - you can feed it almost anything.   Probably worth confirming this if we end up doubling down on this schema._

**Comment by ambrosejcarr** [comment]
sfaira are discussing here this concept: theislab/sfaira#141

**Comment by ambrosejcarr** [comment]
We discussed this topic on the 21-3-2 curation call and there was support for the thesis that different scientists will require flexibility in defining what "batch" means to them. There was at least one anecdote about removing information from a "batch" schema label (e.g. "technical_batch" --> "batch") to make room for differing interpretations. 

This supports Bruce's proposal of implementing a "batch key".

**Comment by brianraymor** [comment]
Added as optional `batch_condition` in schema 2.0.0.
