### ISSUE TITLE
cellxgene-schema MUST add feature_name and feature_reference to the raw.var dataframe

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#203]
When a dataset is uploaded, cellxgene Data Portal MUST automatically add the matching human-readable name for the corresponding feature identifier and the inferred NCBITaxon term for the reference organism  to the `var` and `raw.var` dataframes. Curators MUST NOT annotate the following columns:

### feature_name

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_name</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. If the <code>feature_biotype</code> is <code>"gene"</code> then this MUST be the human-readable ENSEMBL gene name assigned to the feature identifier in <code>var.index</code>. If the <code>feature_biotype</code> is <code>"spike-in"</code> then this MUST be the ERCC Spike-In identifier appended with <code>" (spike-in control)"</code>.
        </td>
    </tr>
</tbody></table>
<br>

### feature_reference

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_reference</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. This MUST be the reference organism for a feature:
          <br><br>
          <table>
          <thead>
          <tr>
          <th>Reference Organism</th>
          <th>MUST Use</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><i>Homo sapiens</i></td>
              <td><code>"NCBITaxon:9606"
              </code></td>
            </tr>
            <tr>
              <td><i>Mus musculus</i></td>
              <td><code>"NCBITaxon:10090"</code></td>
            </tr>
            <tr>
              <td><i>SARS-CoV-2</i></td>
              <td><code>"NCBITaxon:2697049"</code></td>
            </tr>
            <tr>
              <td><i>ERCC Spike-Ins</i></td>
              <td><code>"NCBITaxon:32630"</code></td>
            </tr>
          </tbody></table>
        </td>
    </tr>
</tbody></table>
<br>

**Comment by brianraymor** [comment]
@pablo-gar wrote:

Hmmm as I'm looking at the code, the definition was added to the schema yaml:

https://github.com/chanzuckerberg/single-cell-curation/blob/b91f784e4c80d2e92dc36107ba247e1f435992d2/cellxgene_schema_cli/cellxgene_schema/schema_definitions/2_0_0.yaml#L84-L90

But there was a change that had to be done to `write_labels.py` and wasn't included:

https://github.com/chanzuckerberg/single-cell-curation/blob/b91f784e4c80d2e92dc36107ba247e1f435992d2/cellxgene_schema_cli/cellxgene_schema/write_labels.py#L302

needs to be:

``` python3
for component in ["obs", "var", "raw.var"]:
```

or more generalizable:

```python3
for component in self.schema_def["components"]
```

And I think that should fix it

**Comment by seve** [comment]
`for component in self.schema_def["components"]` won't work due to the keys consisting of: `dict_keys(['obsm', 'uns', 'var', 'raw.var', 'obs'])`

**Comment by pablo-gar** [comment]
yes, but it will ignore those because of this:

https://github.com/chanzuckerberg/single-cell-curation/blob/b91f784e4c80d2e92dc36107ba247e1f435992d2/cellxgene_schema_cli/cellxgene_schema/write_labels.py#L309

**Comment by seve** [comment]
`Columns` doesn't exist on those components, I could just throw in a `if "columns" in self.schema_def["components"][component]`
