### ISSUE TITLE
post-ontology bump updates

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#205]
The 2 methylation (snmC-seq) datasets here: ae1420fe-6630-46ed-8b3d-cc6056a66467
update to: EFO:0030027 (snmC-Seq2)

The 3 datasets here: 00109df5-7810-4542-8db5-2288c46e0424
update to: EFO:0030026 (sci-Plex)

All of the datasets here: 8e880741-bf9a-4c8e-9227-934204631d2a & "Spatial transcriptomic maps of whole mouse embryos reveal principles of neural tube patterning"
update to: EFO:0030062 (Slide-seqV2)

The '10x technology' cells in this dataset: "UCSD WashU HuBMAP KPMP"
update to: EFO:0030059 (10x multiome)

**Comment by jahilton** [comment]
2 cell populations in the dataset here: 6f6d381a-7701-4781-935c-db10d30de293
From Lisa Sikkema...
1: Our annotation: EC aerocyte capillary. Your ontology version: capillary endothelial cell. Newest ontology version: alveolar capillary type 2 endothelial cell
2: Our annotation: EC general capillary. Your ontology version: capillary endothelial cell. Newest ontology version: alveolar capillary type 1 endothelial cell

**Comment by jychien** [comment]
For HTAN Broad breast cancer collection: a96133de-e951-4e2d-ace6-59db8b3bfb1d
- CODEX datasets: update to EFO:0700002 PhenoCycler
- ExSeq: update to https://github.com/EBISPOT/efo/issues/1666 (just submitted)
- Slide-seq: update to EFO:0030062 (Slide-seqV2)

**Comment by jychien** [comment]
For Slide-seq collection: 02b01703-bf1b-48de-b99a-23bef8cccc81, the assay_ontology_term_id needs to be updated to  EFO:0030062 (Slide-seqV2). The one thing to consider is that these are Slide-TCR-seq datasets. There is no EFO term for this assay, but we have yet to determine how to handle TCR/BCR data and if there is some minimum metadata required in order for the assay to be TCR/BCR. Also, have yet to determine if Slice-TCR-seq is different enough from Slide-seqV2 to be considered it's own assay.

**Comment by jahilton** [comment]
Collection `93eebe82-d8c3-41bc-a906-63b5b5f24a9d`

Dataset `c05fb583-eb2f-4e3a-8e74-f9bd6414e418`, assay should be `EFO:0700003` [BD Rhapsody Whole Transcriptome Analysis]

The other 3 Datasets `d3566d6a-a455-4a15-980f-45eb29114cab`, `b3a5a10f-b1cb-4e8e-abce-bf345448625b`, `cd4c96bb-ad66-4e83-ba9e-a7df8790eb12`, assay should be `EFO:0700004` [BD Rhapsody Targeted mRNA]

**Comment by jychien** [comment]
Collection `a48f5033-3438-4550-8574-cdff3263fdfd` 

All 3 datasets will need assay updated to `EFO:0700010` 'TruDrop' (https://github.com/EBISPOT/efo/issues/1759). I don't think this will make schema 3.0.0 pinned ontologies, though.

**Comment by jahilton** [comment]
Collection `1ca90a2d-2943-483d-b678-b809bf464c30`
All datasets have `HANCESTRO:0306` [admixed ancestry] that will need to be updated to `multiethnic`

**Comment by jahilton** [comment]
- [ ] 2 methylation (snmC-seq) datasets here: `ae1420fe-6630-46ed-8b3d-cc6056a66467`
- [ ] 3 datasets here: `00109df5-7810-4542-8db5-2288c46e0424`
- [ ] All of the datasets here: `8e880741-bf9a-4c8e-9227-934204631d2a`
- [ ] All of the datasets here: `Spatial transcriptomic maps of whole mouse embryos reveal principles of neural tube patterning`
- [ ] The '10x technology' cells in this dataset: `UCSD WashU HuBMAP KPMP`
- [ ] CL:0000115 [endothelial cell] cells in the dataset here: `32f2fd23-ec74-486f-9544-e5b2f41725f5`
- [ ] 2 cell populations in the dataset here: `6f6d381a-7701-4781-935c-db10d30de293`
- [ ] `HTAN/HTAPP Broad - Spatio-molecular dissection of the breast cancer metastatic microenvironment`
- [ ] `Spatially mapping T cell receptors and transcriptomes`
- [ ] Collection `93eebe82-d8c3-41bc-a906-63b5b5f24a9d` Dataset `c05fb583-eb2f-4e3a-8e74-f9bd6414e418`
- [ ] Collection `93eebe82-d8c3-41bc-a906-63b5b5f24a9d` 3 Datasets `d3566d6a-a455-4a15-980f-45eb29114cab`, `b3a5a10f-b1cb-4e8e-abce-bf345448625b`, `cd4c96bb-ad66-4e83-ba9e-a7df8790eb12`
- [ ] `A Proximal-to-Distal Survey of Healthy Adult Human Small Intestine and Colon Epithelium by Single-Cell Transcriptomics`
- [ ] Collection `a48f5033-3438-4550-8574-cdff3263fdfd` All 3 datasets
- [ ] Collection `1ca90a2d-2943-483d-b678-b809bf464c30`

**Comment by jahilton** [comment]
All that can be updated are updated
The remaining 2 have been carried over to #373
