### ISSUE TITLE
Disambiguation of "assay" term in the Experimental Factor Ontology (EFO)

### ISSUE THREAD

**Issue by BAevermann** [chanzuckerberg/single-cell-curation#212]
Just wanted to open a ticket that acknowledges that the Values that we are using for Key = assay in our schema come from the class "single cell library construction" in EFO that is a sibling of class "assay". 

Whereas terms such as 
"Visium Spatial Gene Expression"
"Slide-seq"
"methylation profiling by high throughput sequencing"
"RNA-seq of coding RNA from single cells"
...

Anyways, the point is that any Ontology aware search will not be able to roll up to these parents as they are in different branches. 

Also. The humor in the fact that  "Visium Spatial Gene Expression" is under both "Assay" and "single cell library construction" hasnt escaped me. 

Perhaps we should lobby EFO to fully harmonize the branches?

**Comment by brianraymor** [comment]
@jahilton @BAevermann - this is not actionable for the schema. Per the comment _Perhaps we should lobby EFO to fully harmonize the branches?_, it would be more appropriate for Stanford to share a design proposal with EFO?

**Comment by BAevermann** [comment]
Are we thinking about instituting an ontology aware search for "Assay"? If no, then this would probably be too much effort for the benefit.

**Comment by jahilton** [comment]
I'm in support of an ontology-aware filter for Assay to make those more accessible. At least high-level categories "RNA assay", "spatial transcriptomics", "protein assay", "DNA assay", maybe even a "10x" vs "Smart-seq" level. Unfortunately, EFO isn't currently annotated enough to allow "full length", "3'", "5'", "plate-based", etc. but we could help them get there
Not sure how that impacts this concern though. Based on how EFO organizes these, I would expect all of the terms we use to be under "assay" AND "single cell library construction" - together taken to mean something like "an RNA assay done on a single-cell sample".
Is the issue the terms "assay" & "library preparation"? Like, it would be more logical/consistent if they called it "single cell _assay_"?

**Comment by brianraymor** [comment]
An ontology aware search for assay is currently not on our roadmap and will not be unless there's a demand from data consumers.

**Comment by BAevermann** [comment]
We can close this ticket for now then and revisit if that feature is
requested.

b.

**Comment by brianraymor** [comment]
For this issue to be actionable, I would expect a detailed recommendation to propose to EFO for assay modeling.
