### ISSUE TITLE
cellxgene-schema must enforce the AnnData encoding version required by the schema

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#215]
### AnnData Encoding

See the related conversation in [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1648255752093579).

`cellxgene-schema` CLI must enforce the encoding requirements in the schema:

_The canonical data format for the cellxgene Data Portal is HDF5-backed [AnnData](https://anndata.readthedocs.io/en/latest) as written by version 0.8 of the anndata library. Part of the rationale for selecting this format is to allow cellxgene to access both the data and metadata within a single file. The schema requirements and definitions for the AnnData X, obs, var, raw.var, obsm, and uns attributes are described below._

**Comment by brianraymor** [comment]
@jahilton - for visibility since he reported the issue that resulted in the requirement to validate encoding.

@ebezzi raised an issue in the connected [PR](https://github.com/chanzuckerberg/single-cell-curation/pull/317#issue-1333334668):
> I don't think we should enforce that the AnnData version is less than 0.8 as it should be backward compatible. It would be great to enforce AnnData <= 0.8 though (since future versions of AnnData will likely fail with unpredictable errors), but unfortunately, it doesn't look like AnnData adds the version to the file metadata, so that's not possible. This could be a good addition to AnnData, if we're ok with submitting an issue. Thoughts @brianraymor @maniarathi?

There is a note in a [comment](https://github.com/scverse/anndata/issues/698#issuecomment-1028201630) that claims:

> The file format version is something that's new this version!

I have not tracked this down yet.

Is there also a possibility, that there are different encoding versions used for data types for the [on disk format](https://github.com/scverse/anndata/blob/74b63d41a9494d1d5bb78915cab9fb23169a287f/docs/fileformat-prose.rst) that could provide a heuristic? 

@pablo-gar @ambrosejcarr - any thoughts?

**Comment by brianraymor** [comment]
RE _the [on disk format](https://github.com/scverse/anndata/blob/74b63d41a9494d1d5bb78915cab9fb23169a287f/docs/fileformat-prose.rst) that could provide a heuristic?_ 

```
import h5py
f = h5py.File("anndata8.h5ad", "r")
dict(f["obs"].attrs)
```

returns an encoding version of:

```
 'encoding-type': 'dataframe',
 'encoding-version': '0.2.0'}
```

compared to inspecting an anndata 7 dataset that returns:

```
'encoding-type': 'dataframe',
 'encoding-version': '0.1.0'}
```

**Comment by brianraymor** [comment]
@ebezzi @metakuni - This is not ready for production. Happy to split encoding into a separate issue.

**Comment by pablo-gar** [comment]
Yes this is very hacky, what if the encoding changes but not the anndata version? or vice versa? It could lead to issues.

We should wait to see if the developers have better ways to access the version on an object.

They made it seen as if there's a way but I can't find documentation, I try playing around with the attributes of an anndata object v0.8 and couldn't find anything.

**Comment by ebezzi** [comment]
@brianraymor unfortunately that won't work, based on my investigation `'encoding-version': '0.1.0'`shows up for AnnData 0.8 files, while nothing shows up for AnnData 0.7 files. I would strongly recommend against defining an internal standard based on heuristic considerations that aren't properly documented in the AnnData repo.

That said, I agree we should create a separate issue and think about future solutions, possibly by reaching out to their developers. Another alternative would be to require the AnnData version to be part of `uns` through a new field, although it would totally be up to the curator to set up the right value in it.

**Comment by brianraymor** [comment]
> Another alternative would be to require the AnnData version to be part of uns through a new field, although it would totally be up to the curator to set up the right value in it.

Curators already set the schema version for the dataset which would be a "promise" that the encoding is correct, so an additional field would not be helpful.

**Comment by ebezzi** [comment]
For now, we're adding a warning in case the encoding schema is different from `0.1.0`.

**Comment by jychien** [comment]
Looks good to me!
