### ISSUE TITLE
"Human developing neocortex by area" collection -- switch cells to ` is_primary_data=True`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#217]
This collection has only one dataset. Originally it intended to have two datasets, the current one and a larger one that never made it. The current one was intended to be a subset of the larger one.

As a consequence all cells are labelled as `is_primary_data=False`  and thus the data is not making it to scExpression. I recommend we change all cells to `is_primary_data=True` until more data is received — these 0.5 mi cells are extremely valuable for scExpression.

Human developing neocortex by area
https://cellxgene.cziscience.com/collections/c8565c6a-01a1-435b-a549-f11b452a83a8

**Comment by jahilton** [comment]
Made the update - will pass the private link to @pablo-gar for review

**Comment by jahilton** [comment]
@pablo-gar gave the 👍 
✅  Published
