### ISSUE TITLE
represent lack of information similarly across schema

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#218]
Currently, we are inconsistent because we capture unknown information a few different ways across the obs schema...

1. string `unknown`
- development_stage
- sex
- self_reported_ethnicity

2. non-specific term from the required ontology
- assay - not allowed in practice (but technically could be as broad as `assay by molecule` or `single cell library construction`)
- organism - not allowed in practice (but technically could be as broad as `unclassified Metazoa`)
- tissue - not allowed in practice (but technically could be as broad as `anatomical structure`)
- cell_type - non-specific term from CL `native cell` or `animal cell` or `eukaryotic cell`

3. term from a different ontology than known information
- disease - `PATO:0000461 [normal]`
---
Issues caused

- The variability can make understanding the schema more difficult
- When extending the schema, we have no single principle to align new fields with
- The mix of free text strings & ontology term IDs in the *_ontology_term_id fields can make coding inconvenient (the level of inconvenience will increase as the schema expands)
- The non-specific terms are confusing to users & contributors
- Using non-specific terms results in inconsistent annotations across the corpus (un-annotated cells could be native or animal or eukaryotic cells) - overlaps with #380 

~To be consistent, we could choose to use a non-specific term from the appropriate ontology but these labels are likely to lead to general confusion for data consumers...~ Bad idea as noted in the Issues

One option would be to conform to the disease approach of "borrowing" a term from another resource so that every value in *_ontology_term_id field is an ID in the format <resource>:<identifier>

- `NCIT:C17998 [unknown]`
- `NCIT:C48660 [not applicable]` (suspension_type & self_reported_ethnicity currently use string `na`)
- There is also `NCIT:C14165 [normal]` if that's preferable to align on NCIT

National Cancer Institute Thesaurus [downloads](https://evs.nci.nih.gov/ftp1/NCI_Thesaurus/) and [README](https://evs.nci.nih.gov/ftp1/NCI_Thesaurus/ReadMe.txt).

**Comment by brianraymor** [comment]
Are there concrete cases where this has caused specific problems? I noticed _some use non-ontology ID strings so **could** trip up computational folks_.

**Comment by bkmartinjr** [comment]
I have run into issues writing code for [Ontology UI](https://github.com/chanzuckerberg/ontology-ui), in particular trying to classify cells by their labels and relationships.  I ended up writing special filters to ignore the ad hoc terms.  It would have been cleaner if I could have just used standard OBO or RDF tools without these modifications.

IMHO, this isn't a huge deal, but does speak to data hygiene and setting precedents for future extensions

**Comment by brianraymor** [comment]
Per triage, @brianraymor to review further because who doesn't like "data hygiene", but my perception is that this adds little value for _data consumers_ and requires  _unwinding_ to re-handle cases like "unknown" vs NCIT:C17998 [unknown].

**Comment by brianraymor** [comment]
@ebezzi @nayib-jose-gloria - I'd be interested in your impressions as you become more familiar with the code base. Would any changes make it easier to validate?

**Comment by brianraymor** [comment]
@nayib-jose-gloria privately responded:

> I think using 'unknown' or 'na' across the board is the most clear on our end for an engineer reading+contributing the code, but I don't think it would introduce any technical challenge to do either of the other two proposed solutions

**Comment by brianraymor** [comment]
Closing in favor of addressing the specific case #380
