### ISSUE TITLE
HGNC Database version is unknown  

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#22]
The HGNC database version is unknown. Its version should be tracked and documented somewhere.

[https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/hgnc_complete_set.txt.gz](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/hgnc_complete_set.txt.gz)

**Comment by brianraymor** [comment]
If/when we refresh the HGNC download, it should be tied to schema version updates to ensure that we have consistent validation behavior for a schema version. Are there actual HGNC versions or simply [monthly refreshes](https://www.genenames.org/download/statistics-and-files/) ?

And we could probably reverse engineer the current date/version by comparing with older versions in the [HGNC archive](ftp://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/).

**Comment by pablo-gar** [comment]
Correct, it's only monthly refreshes. I checked the archive, the earliest one is from 2020-06-01 and none of them matches with the one we have. I'm assuming Marcus got it earlier than that.

**Comment by brianraymor** [comment]
Also see https://github.com/chanzuckerberg/corpora-data-portal/issues/320

**Comment by pablo-gar** [comment]
Also note that our approach to standardize gene symbols occurs when using `cellxgene-schema apply` [here](https://github.com/chanzuckerberg/single-cell-curation/blob/f2b872edec347acb37959ba006a8387c80550385/cellxgene_schema_cli/cellxgene_schema/gene_symbol.py#L12-L24).

Thus curated datasets that did not go through our apply command are likely to have inconsistent gene names. e.g. external contributors.

**Comment by brianraymor** [comment]
Outdated due to the change to ENSEMBL and pinned references.
