### ISSUE TITLE
Update "Animal Cells" in collection 29f92179-ca10-4309-a32b-d383d80347c1

### ISSUE THREAD

**Issue by BAevermann** [chanzuckerberg/single-cell-curation#228]
In many of the datasets within collection:29f92179-ca10-4309-a32b-d383d80347c1 there are cells labeled as "Animal Cell". These should be curated to a more granular resolution or perhaps these are really "Unknown"? 

Collection Title: Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19

Dataset Titles known to be affected:
66 years old female - Fresh PBMCs (7 days post-intubation)
74 years old female - Fresh PBMCs (8 days post-intubation)
74 years old female - Fresh PBMCs (7 days post-intubation)
74 years old female - Fresh PBMCs (3 days post-intubation)
66 years old female - Fresh PBMCs (2 days post-intubation)
82 years old female - Fresh PBMCs (1 day post-intubation)
74 years old female - Fresh PBMCs (4 days post-intubation)
66 years old female - Fresh PBMCs (3 days post-intubation)
66 years old female - Fresh PBMCs (4 days post-intubation)

Thanks,

Brian A.

**Comment by jahilton** [comment]
Currently, "unknown" is not allowed for cell_type. "[This MUST be a CL term.](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#cell_type_ontology_term_id)" (the inconsistency of "unknown" across fields is addressed in #218)
We typically default to [CL:0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000003) [native cell]. I agree that some rule is needed to ensure that unknown/unannotated cells are handled consistently.

**Comment by brianraymor** [comment]
@jahilton - the original case ("animal cell") will be invalid in schema 4. Do you want to include in your 3.1 changes?

**Comment by jahilton** [comment]
@brianraymor if you're OK with it, we'll just wait until schema 4 and migrate all 'animal cell' (maybe 'somatic cell' & others too?) to 'native cell' with that migration

**Comment by jahilton** [comment]
This has been revised (and the now 'native cell' will soon go to 'unknown' in 5.0.0)
