### ISSUE TITLE
How to encode datasets where raw and normalized count matrices have different shapes. 

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#23]
@MaximilianLombardo and @pablo-gar identify that we often receive datasets where the "normalized" count data contain a subset of the gene features of the "raw" count data. This occurs because toolchains tend to filter genes to generate better clusters and low dimensional embeddings. This filtering typically removes low variance genes, and genes that are thought to explain more technical variation (ribosomal) or confounding stress information (mitochondrial) than interesting biological information. 

While filtering is helpful for downstream steps in the initial analysis, it produces a data reuse problem when other scientists want to explore the expression of a specific gene or set of genes. Many times their genes of interest are not present in the filtered, normalized matrix. It also causes a visualization problem for cellxgene. Since normalized counts are the data that we visualize, and users may only visualize features that are present in the matrix.

I would prefer that data submitters use distance metrics that are aware of feature variance, so they don't need to filter variable genes. We'd also prefer that they regress out confounding signatures instead of filtering "troublesome genes" like mitochondrial and ribosomal genes. However, this is not common practice and the schema's primary goal is to best represent scientific data. 

Proposed solution: @MaximilianLombardo suggests the following solution: 
1. Our schema should require that raw and normalized data have the same set of features.
2. To meet this requirement, when we receive submissions, any feature present in `raw` but not in `normalized` should be added to `normalized` and its values filled with `np.nan`
3. An amendment is written to the schema explaining why including all features in the normalized dataset increases the breadth of users who will be able to reuse the data, and maximizes the value of submitted data, and explaining how step (2) above is applied to data that do not meet this requirement. 

Corollary: This decision will affect the format of our downloaded files, which can't support matrices of different shapes. 

Unresolved question: How do we visualize these np.nan columns in the explorer? cc @signechambers1 @colinmegill 

cc @jahilton we're considering this approach instead of the one I suggested to you. The difference here is instead of subsetting to the features of the normalized matrix, we expand to the features of the raw matrix.

**Comment by signechambers1** [comment]
@ambrosejcarr @pablo-gar @colinmegill and I discussed, we don't think there should be any issues with np.nan values on the front end. If a user loads a gene that only has these values, they will see a large bar on the left hand side of the histogram and coloring by these genes will turn the main image grey.

If you can point us to a dataset with the np.nan values we can load it up and confirm.

**Comment by brianraymor** [comment]
@ambrosejcarr - I believe that your [final model](https://github.com/chanzuckerberg/single-cell-curation/issues/23#issuecomment-764966734) were addressed in schema 2.0.0. Please close this issue if you're in agreement.

**Comment by brianraymor** [comment]
Closing due to no response.
