### ISSUE TITLE
Add description of custom fields

### ISSUE THREAD

**Issue by Hrovatin** [chanzuckerberg/single-cell-curation#230]
It would be really nice if authors would be obligated to provide descriptions of all custom fields that could be then displayed in cxg during hover-over (as is now done for full name of e.g. obs columns). This could be stored in uns in format 
```
{
obs : { 
  col1 : description, 
  ...
  },
var : {
  col1 : description,
  ...
  }, 
obsm : { 
  embedding1 : description,
  ...
  }
}
```

**Comment by brianraymor** [comment]
@Hrovatin - Thank you very much for your proposal. During our issue triage today, there was agreement that while this would be a nice feature for data consumers, the additional **MUST** requirement would be onerous for data submitters and curators. Please keep sharing ideas!
