### ISSUE TITLE
Update the schema encoding to anndata 0.8

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#232]
### Context

The canonical data format for the cellxgene Data Portal is HDF5-backed [AnnData](https://anndata.readthedocs.io/en/latest) as written by **version 0.7** of the anndata library. Recently, curators have seen more cases where datasets are provided in anndata 0.8 which require conversion to 0.7. 

See [wrangling](https://czi-sci.slack.com/archives/C024HCSH9PT/p1650932174832059) and the [sc-integration-workshop](https://cziscience.slack.com/archives/C039LKBF97Y/p1650931700616599?thread_ts=1650930307.686739&cid=C039LKBF97Y).

Changes to the pinned anndata version have **BROAD** impact across the portal infrastructure which need to be assessed. 

---

See [0.8 release notes](https://anndata.readthedocs.io/en/latest/release-notes/index.html#th-march-2022) **especially** _The on disk format of AnnData objects has been updated with this release. Previous releases of anndata will not be able to read all files written by this version._

**Comment by jahilton** [comment]
During the May tissue integration workshop, at least 3 or 4 of the integration groups provided AnnData objects in 0.8 for submission (out of 8 groups)

Last week, we had a contributor provide an AnnData object in 0.8 for submission.

**Comment by brianraymor** [comment]
@cakirb - I'd also be curious about why you've adopted anndata 0.8 for curation to help motivate whether we should be updating the schema encoding. What additional value does 0.8 provide for you over 0.7?

**Comment by jahilton** [comment]
Thanks for catching that @cakirb! We originally created these scripts for very specific purposes and I didn't catch the var issue when making it more generalized. We have been using these on the initial h5ad prior to curation, and then curating in 0.7 as usual (so feature_is_filtered wasn't added yet).
I can't think of any compelling reason to use one workflow over the other.

**Comment by brianraymor** [comment]
@ebezzi - are there changes required in sceasy if we adopted 0.8?
