### ISSUE TITLE
cellxgene-schema needs an option to remove or overwrite the labels that are applied to datasets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#233]
The data portal runs the following command in the ingestion pipeline:

`cellxgene-schema validate --add-labels output.h5ad input.h5ad`

This validates the dataset AND adds the human-readable labels for the ontology and gene IDs as defined in the schema. If the validation is successful, a new AnnData file (output.h5ad) is written to disk with the labels appended.

If the resulting dataset is re-processed during a schema migration, then validation will fail. There MUST be an option for `cellxgene-schema` to either remove or overwrite the labels that were previously applied.

**Comment by jahilton** [comment]
>There MUST be an option for cellxgene-schema to either remove or overwrite the labels that were previously applied.

This seems risky as you might overwrite information that the contributor/curator would prefer to retain (cell_type is a common example where you want to move the information to a different column). As such, during a standard (non-migration) submission, you would expect the user to submit the `input.h5ad` that does not have labels added.

What's the proposed migration workflow? Download existing dataset, make revisions, run `validate` with strip-labels option so the portal fields are removed, file is validated and written?

**Comment by jahilton** [comment]
That makes sense.
