### ISSUE TITLE
add publication DOI to follicular lymphoma study

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#237]
Michael Green sent this new publication to add to his Collection: https://pubmed.ncbi.nlm.nih.gov/35687817/
Should be added to this Collection: https://cellxgene.cziscience.com/collections/968834a0-1895-40df-8720-666029b3bbac)

I have started a revision.

Just waiting for CrossRef to register the DOI. Can be checked via https://api.crossref.org/works/10.1158/2643-3230.BCD-21-0075
(the DOI isn't even active yet: www.doi.org/10.1158/2643-3230.BCD-21-0075)

Looks like the Journal Issues come out on the 1st of every other month, so the next one is anticipated on July 1. https://aacrjournals.org/bloodcancerdiscov/issue

**Comment by brianraymor** [comment]
@jahilton - it's registered now.

**Comment by jahilton** [comment]
Excellent.
Added & Published
