### ISSUE TITLE
Update pinned ontologies

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#238]
**Note: The required ontologies will be updated at the last possible minute for Q3.**

### Required Ontologies

The following ontology dependencies are *pinned* for this version of the schema.

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Cell Ontology] | CL | [cl.owl] : [2021-08-10]|
| [Experimental Factor Ontology] | EFO | [efo.owl] : [2021-08-16 EFO 3.33.0]
| [Human Ancestry Ontology] | HANCESTRO |[hancestro.owl] : [2021-01-04 (2.5)] |
| [Human Developmental Stages] |  HsapDv | [hsapdv.owl] : 2020-03-10 |
| [Mondo Disease Ontology] | MONDO |[mondo.owl] : [2021-08-11] |
| [Mouse Developmental Stages]| MmusDv |  [mmusdv.owl] : 2020-03-10 |
| [NCBI organismal classification] |  NCBITaxon | [ncbitaxon.owl] : [2021-06-10] |
| [Phenotype And Trait Ontology] | PATO | [pato.owl] : [2021-08-06] |  |
| [Uberon multi-species anatomy ontology] |  UBERON | [uberon.owl] : [2021-07-27] |
| | | |

[Cell Ontology]: http://obofoundry.org/ontology/cl.html
[2021-08-10]: https://github.com/obophenotype/cell-ontology/releases/tag/v2021-08-10
[cl.owl]: https://github.com/obophenotype/cell-ontology/blob/v2021-08-10/cl.owl

[Experimental Factor Ontology]: http://www.ebi.ac.uk/efo
[2021-08-16 EFO 3.33.0]: https://github.com/EBISPOT/efo/releases/tag/v3.33.0
[efo.owl]: https://github.com/EBISPOT/efo/releases/download/v3.33.0/efo.owl

[Human Ancestry Ontology]: http://www.obofoundry.org/ontology/hancestro.html
[2021-01-04 (2.5)]: https://github.com/EBISPOT/ancestro/releases/tag/2.5
[hancestro.owl]: https://github.com/EBISPOT/ancestro/blob/2.5/hancestro.owl

[Human Developmental Stages]: http://obofoundry.org/ontology/hsapdv.html
[hsapdv.owl]: http://purl.obolibrary.org/obo/hsapdv.owl

[Mondo Disease Ontology]: http://obofoundry.org/ontology/mondo.html
[2021-08-11]: https://github.com/monarch-initiative/mondo/releases/tag/v2021-08-11
[mondo.owl]: https://github.com/monarch-initiative/mondo/releases/download/v2021-08-11/mondo.owl

[Mouse Developmental Stages]: http://obofoundry.org/ontology/mmusdv.html
[mmusdv.owl]: http://purl.obolibrary.org/obo/mmusdv.owl

[NCBI organismal classification]: http://obofoundry.org/ontology/ncbitaxon.html
[2021-06-10]: https://github.com/obophenotype/ncbitaxon/releases/tag/v2021-06-10
[ncbitaxon.owl]: https://github.com/obophenotype/ncbitaxon/releases/download/v2021-06-10/ncbitaxon.owl.gz

[Phenotype And Trait Ontology]: http://www.obofoundry.org/ontology/pato.html
[2021-08-06]: https://github.com/pato-ontology/pato/releases/tag/v2021-08-06
[pato.owl]: https://github.com/pato-ontology/pato/blob/v2021-08-06/pato.owl

[Uberon multi-species anatomy ontology]: http://www.obofoundry.org/ontology/uberon.html
[2021-07-27]: https://github.com/obophenotype/uberon/releases/tag/v2021-07-27
[uberon.owl]: https://github.com/obophenotype/uberon/blob/v2021-07-27/uberon.owl

**Comment by pablo-gar** [comment]
Is there a plan to check if all data currently hosted will be supported after updating the ontologies?

**Comment by brianraymor** [comment]
There is a plan or process, but this issue is specific to the schema changes. See **Migrate Corpus** in [Submit Find Manage](https://docs.google.com/document/d/16xPhBQb1nOaAAMEfpr9sq4nz18DM0GuAIgUFQN6Zr20/edit#heading=h.f30n46dmey5c).
