### ISSUE TITLE
Validator should check for the existence of raw layer

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#24]
In the schema v1.1.0 we [require to have a "raw" matrix ](https://github.com/chanzuckerberg/single-cell-curation/blob/main/docs/corpora_schema.md#matrix-layers) and suggest to store it AnnData.raw.X. 

The [validator](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/validate.py) does not currently check for this requirement. 

We should:
- Include a check in the validator for the existence of a raw layer.
- [Suggestion] check for int as the type in that layer.
- [Suggestion] to make integration processes easily streamable and to make checks easier, we should require to have the raw layer in AnnData.raw, as opposed to just have this as a suggestion. And added plus to this is that AnnData has some extra checks/restrictions on AnnData.raw

**Comment by brianraymor** [comment]
This issue needs to be updated to reflect the assay specific requirements in the schema.

**Comment by pablo-gar** [comment]
I'd like to know if we are going update the schema version in the current iteration of changes. See my comment [here](https://github.com/chanzuckerberg/single-cell-curation/pull/46#issuecomment-825089894).

If we do change the schema version number then the validator should adapt the corresponding changes to each version.

**Comment by brianraymor** [comment]
Will create a new issue based on the schema 2.0.0 changes to raw requirements.
