### ISSUE TITLE
clarify "final" matrix in schema

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#241]
### Context

See [**single-cell-data-representation**](https://cziscience.slack.com/archives/C01L65J7PLP/p1655389183023089).

The schema references a "final" matrix several times when [discussing layers](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#x-matrix-layers) and in the [feature_is_filtered spec](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md#feature_is_filtered), yet "final" is an ambiguous term.

---

### Proposal

Option 1: define "final" matrix. Something like "The matrix containing scaled, normalized data that are more appropriate for intra-dataset comparisons (e.g. differential expression) than raw counts."
Option 2: use the term "normalized" matrix instead.

**Comment by brianraymor** [comment]
I prefer:

> Option 2: use the term "normalized" matrix instead.

but wonder if that's a trick where @jahilton then asks "What do you mean when you say normalized?"

@ambrosejcarr - any preference and/or does the new documentation touch on this in any way that the schema should leverage?

**Comment by ambrosejcarr** [comment]
I think that in either case we should define what we mean by the term because as @brianraymor points out, _both_ are ambiguous. The scientist in me itches to dive down the rabbit hole and identify the best term, but I think there will be flaws with anything we pick. 

If we're going to reference normalization in the definition of final, then I have a slight preference for just using the term normalized up front.

**Comment by pablo-gar** [comment]
I agree with @ambrosejcarr. Normalize is ambiguous but I believe most scientist would understand the context and think "Not raw", further clarifying what we mean by normalized would help for those left with some questions. 

So I'd propose:

Option 3 "Normalized": "Matrix with processed values ready for data analysis" 

Intentionally vague and going away from rigid normalization steps

**Comment by jahilton** [comment]
>If we're going to reference normalization in the definition of final, then I have a slight preference for just using the term normalized up front.

Agreed

>Option 3 "Normalized": "Matrix with processed values ready for data analysis"
Intentionally vague and going away from rigid normalization steps

I like this approach & text.

**Comment by brianraymor** [comment]
I'd propose a small edit to the first appearance of "final". Change

> In general, cellxgene requires submission of "raw" data suitable for computational reuse when a standard raw matrix format exists for an assay and strongly recommends that a "final" matrix suitable for visualization in cellxgene Explorer be included.

to:

> cellxgene requires submission of "raw" data suitable for computational reuse when a standard raw matrix format exists for an assay.  Also including a "normalized" matrix with processed values ready for data analysis and suitable for visualization in cellxgene Explorer is STRONGLY RECOMMENDED.


and then a global substitution of "final" with "normalized".

**Comment by brianraymor** [comment]
Small editorial refinement:

It is STRONGLY RECOMMENDED to also include a "normalized" matrix with processed values ready for data analysis and suitable for visualization in cellxgene Explorer.
