### ISSUE TITLE
Add self_reported_ethnicity to obs

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#243]
See the proposal in [Deprecate ethnicity and ethnicity_ontology_term_id](https://github.com/chanzuckerberg/single-cell-curation/issues/199#issuecomment-1149268863) for details. 

Also see [Mind the gap: how multiracial individuals get left behind when we talk about race, ethnicity, and ancestry in genomic research](https://arxiv.org/pdf/2205.00027.pdf).

**Comment by brianraymor** [comment]
@jahilton - per our earlier discussion, there are no requirements related to delimiters to be enforced by the validator. Any comments? 

### self_reported_ethnicity

<table><tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If <code>organism_ontolology_term_id</code> is <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>, this MUST be either free-text or <code>"unknown"</code> if unavailable. <br><br>Otherwise, for all other organisms this MUST be <code>"na"</code>.
        </td>
    </tr>
</tbody></table>

**Comment by brianraymor** [comment]
@jahilton - this is addressed in #258. Please reopen this issue if further refinements are required.

**Comment by jahilton** [comment]
>there are no requirements related to delimiters to be enforced by the validator.

Correct. I think we can give some guidance
`If listing multiple ethnic categories in the same string, we STRONGLY RECOMMEND separating the values with a comma`
(need to decide what that suggested delimiter is though - i'll browse to see if there are any categories that might include commas)

Personally, I find that using quotations _and_ the code formatting for exact values (`"unknown"`, `"NCBITaxon:9606"`) to be redundant and the quotes should be removed. Read literally, someone may interpret it as the quotes should be included in the value.

**Comment by brianraymor** [comment]
Re-opening for [pending editorial changes](https://github.com/chanzuckerberg/single-cell-curation/issues/243#issuecomment-1170719026).

**Comment by brianraymor** [comment]
Per July 12 call with Norbert, @jahilton, and @hthomas-czi - we agreed to rename and reuse the current ethnicity field with its HANCESTRO value. Closing.
