### ISSUE TITLE
Investigate biosample id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#244]
This conversation started in [Add donor id field](https://github.com/chanzuckerberg/single-cell-curation/issues/164#issuecomment-955078694) when @jahilton noted:

> I think these could be determined to be separate concepts. A left eye and a right eye from Ambrose would be 1 donor_id but 2 biosample_ids.

@jahilton also provided the following use cases:

for a "sample" identifier, several use cases to consider when deciding what entity we want to capture here, and how to communicate that in the schema...

**1. The 1-to-1-to-1 case**
Each donor in the study provides a single specimen and each specimen is processed individually.
Very common.
No question about what entity is captured as they will all be assigned the same.

**2. The pooling/multiplexing case**
Several specimens are pooled and the pool is processed together. Various methods can be used to demultiplex the data downstream (identify a cell back to its specimen)
The guidance above from data integrators was that they want the _specimen_, not the _pool_. We also know that, in these cases, the pool is commonly noted anyway (`Processing_Cohort` [here](https://cellxgene.cziscience.com/e/218acb0f-9f2f-4f76-b90b-15a4b7c7f629.cxg/), `pool` [here](https://cellxgene.cziscience.com/e/01ad3cd7-3929-4654-84c0-6db05bd5fd59.cxg/), `pool_number` [here](https://cellxgene.cziscience.com/e/3faad104-2ab8-4434-816d-474d8d2641db.cxg/) ), and we can suggest that the pool information can be submitted separately.

**3. The longitudinal study case**
Each donor in the study may provide multiple specimens over months/years.
[This Seed Network project](https://chanzuckerberg.com/science/programs-resources/single-cell-biology/seednetworks/human-immune-variation-across-genetic-backgrounds-gender-and-time/) and [this Pediatric Network project](https://chanzuckerberg.com/science/programs-resources/single-cell-biology/pediatric-networks/a-cell-atlas-of-trained-immunity-in-bacillus-calmette-guerin-vaccinated-african-infants/) are such examples.
The entity to be captured would be the individual specimen taken at a given time point.

**4. The split tissue case**
A donor provides a single specimen and that specimen is split and each sub-specimen is processed individually. This may be for replication or for different modalities (one sub-specimen is used for expression and one for chromatic accessibility).
In [this dataset](https://cellxgene.cziscience.com/e/c6413315-7158-46c5-a5fd-7228385694f1.cxg/), coloring by `tissue` and then observing the `donor_uuid` values, you can see 3 donors have cells of 3 sub-tissues of the fallopian tube. The entity not depicted here is the fallopian tube (specimen) that each sub-specimen came from. Could be more significant distinction if a donor provides 2 specimens of the same type (eg a right & left eye) and then those are split.
In [the 2 datasets here](https://cellxgene.cziscience.com/collections/9b02383a-9358-4f0f-9795-a891ec523bcc), the `sample_uuid` values are the same because the identifiers are representing the pre-split specimen.
Unclear which entity should be captured in the proposed sample_id.

Combinations of the above cases may occur (eg longitudinal samples may be multiplexed, specimens may be pooled then split for processing)

**Comment by LuckyMD** [comment]
The split tissue case is very common also for lung, where different samples can be from different locations in the lung. The combination of donor_id and an encoding of anatomical location would be useful for sample_id. An example is [this dataset](https://www.biorxiv.org/content/10.1101/2021.11.26.470108v1) with 25 samples from 5 donors and from 5 different locations in the lung.

**Comment by brianraymor** [comment]
Closing. Infeasible to address in a standard manner.
