### ISSUE TITLE
cellxgene-schema must deprecate X_normalization

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#250]
See [Deprecate X_normalization](https://github.com/chanzuckerberg/single-cell-curation/issues/199) for background.

**Note**:  Pending requirements related to the [The schema policy for PII and deprecated fields must be clarified and enforced](https://github.com/chanzuckerberg/single-cell-curation/issues/181).

**Comment by ebezzi** [comment]
Note: we'll just remove `X_normalization` from the code as part of this ticket. Enforcing the non-existence of this field will be done as part of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/264

**Comment by jychien** [comment]
Associated github ticket (above links to ethnicity ticket): https://github.com/chanzuckerberg/single-cell-curation/issues/250
Overall expected outcome is that the validator will fail if 'X_normalization' is present in uns. The requirements for presence of raw or normalized matrices remain unchanged from schema 2.0.0, and are as listed in the 'X (layers)' table in schema 3.0.0 documentation.

| Test Case                                                                                | Expected Result         | Obtained Result                                                                                                                                                                                                                                                                                   | Test File                         | Needs attention |
| ---------------------------------------------------------------------------------------- | ----------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------- | --------------- |
| X\_normalization' is present in uns for scRNA-seq dataset with normalized & raw matrices | Fail validation<br><br> | Passed validation                                                                                                                                                                                                                                                                                 | adata\_norm\_raw.h5ad             | X               |
| X\_normalization' is absent in uns for scRNA-seq dataset with normalized & raw matrices  | Pass validation<br><br> | Passed validation                                                                                                                                                                                                                                                                                 | adata\_norm\_raw\_noX.h5ad        |                 |
| X\_normalization' is present in uns for Slide-seq dataset with only raw matrix           | Fail validation<br><br> | Failed validation, but the file failed for the incorrect reason.<br>Current logging: ERROR: Only raw data was found, i.e. there is no 'raw.X'.                                                                                                                                                    | adata\_only\_raw.h5ad             | X               |
| X\_normalization' is absent in uns for Slide-seq dataset with only raw matrix            | Pass validation<br>     | Failed validation<br>Current logging: ERROR: Only raw data was found, i.e. there is no 'raw.X'.<br>Previous logging: WARNING: Only raw data was found, i.e. there is no 'raw.X' and 'uns\['X\_normalization'\]' is 'none'. It is STRONGLY RECOMMENDED that 'final' (normalized) data is provided. | adata\_only\_raw\_noX.h5ad        | X               |
| X\_normalization' is present in uns for ATAC dataset with only normalized matrix         | Fail validation         | Passed validation                                                                                                                                                                                                                                                                                 | adata\_atac\_norm\_only.h5ad      | X               |
| X\_normalization' is absent in uns for ATAC dataset with only normalized matrix          | Pass validation         | Passed validation                                                                                                                                                                                                                                                                                 | adata\_atac\_norm\_only\_noX.h5ad |
 |

h5ad files can be found in: https://drive.google.com/drive/folders/1hNK5E2f9BBFky16nga486Mh0mHhTkgCR?usp=sharing

**Comment by ebezzi** [comment]
@jychien as stated in my previous comment, enforcing the absence of `X_normalization` will be done as part of another ticket, so I believe that will cover cases 1, 3, and 5. 3 is interesting as it shows that checking for deprecated fields should be done at an early stage of the validation, to make errors more precise. I will make sure the ticket is ready before you re-validate.

I'm gonna look at case 4 and submit another PR. Thanks!

**Comment by jychien** [comment]
Thanks for the clarification, @ebezzi. Here are the test cases that the validator warns and errors on. It looks to good to me! For any additional edge cases that may arise, curators need to be on the look out and troubleshoot.
| Test Case                   | Expected Result       <img width=200/>  | Obtained Result                                                                                                                                                  | Test File <img width=220/>| Needs attention |
| ----------------------------------------------------------------- | ----------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------- | --------------- |
| scRNA-seq dataset with normalized & raw matrices                  | Pass validation<br><br> | Passed validation                                                                                                                                                | adata\_norm\_raw\_updated.h5ad        |                 |
| Slide-seq dataset with only raw matrix                            | Pass validation<br>     | Passed validation<br>Logging: WARNING: Only raw data was found, i.e. there is no 'raw.X'. It is STRONGLY RECOMMENDED that 'final' (normalized) data is provided. | adata\_only\_raw\_noX\_updated.h5ad   |                 |
| scRNA-seq dataset with only normalized                            | Fail validation         | Failed validation<br>Logging: ERROR: Raw data is missing: there is only a normalized matrix in X and no raw.X                                                    | adata\_only\_norm\_updated.h5ad       |                 |
| scRNA-seq dataset with raw in .X and a normalized matrix in raw.X | Fail validation         | Failed validation<br>Logging: ERROR: Raw data may be missing: data in 'raw.X' contains non-integer values.                                                       | adata\_matrix\_flipped\_updated.h5ad  |                 |
| ATAC dataset with only normalized matrix                          | Pass validation         | Passed validation                                                                                                                                                | adata\_atac\_norm\_only\_updated.h5ad |
