### ISSUE TITLE
cellxgene-schema must rename ethnicity and ethnicity_ontology_term_id and add "multiethnic"

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#251]
Also see [cellxgene-schema must perform basic 2.0.0 -> 3.0.0 migration](https://github.com/chanzuckerberg/single-cell-curation/issues/262) for updating existing datasets.

This is a simple rename in the code base:

1. `ethnicity` -> `self_reported_ethnicity`
1. `ethnicity_ontology_term_id` -> `self_reported_ethnicity_ontology_term_id` 

with additional validation and labeling requirements for a new value that is allowed - `"multiethnic"`:

### self_reported_ethnicity_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If <code>organism_ontolology_term_id</code> is <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>, this MUST be either a HANCESTRO term, <code>"multiethnic"</code> if more than one ethnicity is reported, or <code>"unknown"</code> if unavailable. <br><br>Otherwise, for all other organisms this MUST be <code>"na"</code>.
        </td>
    </tr>
</tbody></table>
<br>

---

### self_reported_ethnicity

<table><tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"na"</code>, <code>"multiethnic"</code>, or <code>"unknown"</code> if set in <code>self_reported_ethnicity_ontology_term_id</code>; otherwise, this MUST be the human-readable name assigned to the value of <code>self_reported_ethnicity_ontology_term_id</code>.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by brianraymor** [comment]
Pending question of whether to add "unreported" as a value - _differentiate real “unknowns” vs non-reported ethnicity or ancestry. Currently unknown means unreported for ~90% of the cases._

**Comment by jychien** [comment]
Here's the test cases I ran for this field, and it looks good to me:
| Test Case  <img width=300/> | Expected Result<img width=200/> | Obtained Result                                                                                                                                                                                                                                                                                                                                                                                       | Test File                   <img width=200/>       | Needs attention <img width=200/>|
| ----------------------------------------- | --------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------- | --------------- |
| have "multiple" as ethnicity for human    | Fail validation | Failed validation<br>Logging: ERROR: 'multiple' in 'self\_reported\_ethnicity\_ontology\_term\_id' is not a valid ontology term id of 'HANCESTRO'. When 'organism\_ontology\_term\_id' is 'NCBITaxon:9606' (Homo sapiens), self\_reported\_ethnicity\_ontology\_term\_id MUST be either: a term id of 'HANCESTRO', 'multiethnic' if more than one ethnicity is reported, or 'unknown' if unavailable. | adata\_ethnicity\_multi.h5ad       |                 |
| have "multiethnic" as ethnicity for human | Pass validation | Pass validation                                                                                                                                                                                                                                                                                                                                                                                       | adata\_ethnicity\_multiethnic.h5ad |                 |
| have "multiethnic" as ethnicity for mouse | Fail validation | Failed validation<br>Logging: ERROR: 'multiethnic' in 'self\_reported\_ethnicity\_ontology\_term\_id' is not a valid value of 'self\_reported\_ethnicity\_ontology\_term\_id'. When 'organism\_ontology\_term\_id' is NOT 'NCBITaxon:9606' (Homo sapiens), self\_reported\_ethnicity\_ontology\_term\_id MUST be 'na'.                                                                                | adata\_ethnicity\_mouse.h5ad       |
