### ISSUE TITLE
cellxgene-schema must not allow clarifying text for assay_ontology_term_id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#253]
The schema has removed guidance in `assay_ontology_term_id` that allowed clarifying text enclosed in parentheses if there was not an exact match for an assay:

`assay_ontology_term_id`

 If there is not an exact match for the assay, clarifying text MAY be enclosed in parentheses and appended to the most accurate term. For example, the sci-plex assay could be curated as <code>"EFO:0010183 (sci-plex)"</code>

If present, then validation MUST fail and display a warning.

---

The following must be removed from the cellxgene-schema label application step:

`assay`

Any clarifying text enclosed in parentheses and appended to <code>assay_ontology_term_id</code> MUST be appended to <code>assay</code>.<br><br> For example, if the sci-plex assay was curated as <code>"EFO:0010183 (sci-plex)"</code>, then the value would be <code>"single-cell library construction (sci-plex)"</code>.

**Comment by jychien** [comment]
Tested the following cases. It looks good, but logging could be slightly improved to be more precise:
| Test Case                 | Expected Result<img width=200/> | Obtained Result                                                                                                                                                                                                                                                                  | Test File  <img width=200/> | Needs attention<img width=100/> |
| --------------------------------------------------------------------------------- | --------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------ | --------------- |
| assay\_ontology\_term\_id appended with ' (Slide-seqV2)'                          | Fail validation | Failed validation<br>Logging: ERROR: 'EFO:0009899 (Slide-seqV2)' in 'assay\_ontology\_term\_id' is not a valid ontology term id of 'EFO'.<br>ERROR: 'EFO:0009899 (Slide-seqV2)' in 'assay\_ontology\_term\_id' is not a child term id of '\[\['EFO:0002772', 'EFO:0010183'\]\]'. | adata\_assay\_text.h5ad  |                 |
| valid efo assay\_ontology\_term\_id but not a child of EFO:0002772 or EFO:0010183 | Fail validation | Failed validation<br>Logging: ERROR: 'EFO:0006571' in 'assay\_ontology\_term\_id' is not a child term id of '\[\['EFO:0002772', 'EFO:0010183'\]\]'.                                                                                                                              | adata\_assay\_child.h5ad |                 |

For the first test case, it correctly logs that it is not a valid ontology term id of 'EFO'. However, there is no need to have the additional check if it is a child of  '[['EFO:0002772', 'EFO:0010183']]'.

**Comment by jychien** [comment]
Test file is located: https://drive.google.com/drive/u/0/folders/1hNK5E2f9BBFky16nga486Mh0mHhTkgCR

**Comment by nayib-jose-gloria** [comment]
updated logging to be more concise and precise

**Comment by jychien** [comment]
Thanks for making the logging more concise. This looks good to me!
| Test Case                                                | Expected Result | Obtained Result   <img width=250/>                                                                               | Test File               | Needs attention |
| -------------------------------------------------------- | --------------- | ----------------------------------------------------------------------------------------------------------------------------------------- | ----------------------- | --------------- |
| assay\_ontology\_term\_id appended with ' (Slide-seqV2)' | Fail validation | Failed validation<br>Logging: ERROR: 'EFO:0009899 (Slide-seqV2)' in 'assay\_ontology\_term\_id' is not a valid ontology term id of 'EFO'. | adata\_assay\_text.h5ad |
