### ISSUE TITLE
cellxgene-schema must annotate feature_biotype

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#257]
**Note: Clarifying a [dependency](https://github.com/chanzuckerberg/single-cell-curation/issues/236#issuecomment-1170511153)**.

Previously, `feature_biotype` was [set by Curators](https://github.com/chanzuckerberg/single-cell-curation/issues/236). It now needs to be annotated by the Data Portal.

When a dataset is uploaded, cellxgene Data Portal MUST automatically add the matching human-readable name for the corresponding feature biotype, identifier, and the NCBITaxon term for the reference organism to the `var` and `raw.var` dataframes. Curators MUST NOT annotate the following columns:

### feature_biotype

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_biotype</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>This MUST be <code>"gene"</code> or <code>"spike-in"</code>.  
        </td>
    </tr>
</tbody></table>
<br>

**Comment by jychien** [comment]
I've tested genes and spike-ins for datasets with only raw matrix and datasets with both raw and normalized matrix. Everything looks good!
| Test Case                                            | Expected Result                                             | Obtained Result                                                              | Test File                        | Needs attention |
| ---------------------------------------------------- | ----------------------------------------------------------- | ---------------------------------------------------------------------------- | -------------------------------- | --------------- |
| scRNA-seq with both var and raw.var gene features    | Pass validation, and add feature\_biotype with --add-labels | Passed validation and added feature\_biotype='gene' for var and raw.var      | adata\_biotype\_genes\_both.h5ad |                 |
| scRNA-seq with both var and raw.var spike-ins        | Pass validation, and add feature\_biotype with --add-labels | Passed validation and added feature\_biotype='spike-ins' for var and raw.var | adata\_biotype\_ercc\_both.h5ad  |                 |
| scRNA-seq with only var and no raw.var gene features | Pass validation, and add feature\_biotype with --add-labels | Passed validation and added feature\_biotype='gene' for var                  | adata\_biotype\_genes.h5ad       |                 |
| scRNA-seq with only var and no raw.var spike-ins     | Pass validation, and add feature\_biotype with --add-labels | Passed validation and added feature\_biotype='spike-ins' for var and raw.var | adata\_biotype\_ercc.h5ad        |                 |
