### ISSUE TITLE
Empty values in `cell_type` should pass validation

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#26]
According to our schema definition

>  The tissue field must be appended with " (cell culture)" or " (organoid)" if appropriate. Also, if the source of cells is cell culture or organiod, the **cell_type field can be left empty.**

But the validator throws an error if empty strings are found for certain fields, including cell_type:
https://github.com/chanzuckerberg/single-cell-curation/blob/f2b872edec347acb37959ba006a8387c80550385/cellxgene_schema_cli/cellxgene_schema/validate.py#L89-L93

The error looks like this:
`Column cell_type in dataframe obs contains empty values.`

We should either update the schema definition to not allow empty strings in `cell_type` or add an exception in the validator that allows empty strings in `cell_type`

**Comment by brianraymor** [comment]
@pablo-gar - this has been clarified in the schema update to be a MUST

> When no appropriate ontology value is available, then the most precise accurate term MUST be used. For example if the cell_type field describes a relay interneuron, but the most specific available term in the CL ontology is CL:0000099 ("Interneuron"), then the interneuron term can be used to fulfill this requirement, and ensures that users searching for "neuron" are able to find these data. 

Recommend that we close this issue.

**Comment by pablo-gar** [comment]
Since this specific to cell culture, maybe we should add a suggestion for the following high CL level term. Users not familiar with the CL ontology may not know about it (I didn't a few months ago).

[Cell in vitro, CL:0001034
](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001034&viewMode=PreferredRoots&siblings=false)

**Comment by pablo-gar** [comment]
> Since this specific to cell culture, maybe we should add a suggestion for the following high CL level term. Users not familiar with the CL ontology may not know about it (I didn't a few months ago).
> 
> [Cell in vitro, CL:0001034 ](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001034&viewMode=PreferredRoots&siblings=false)

It was already added to the text
