### ISSUE TITLE
cellxgene-schema must perform basic 2.0.0 -> 3.0.0 migration

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#262]
To make it easier for Lattice and/or the Data Portal to migrate datasets from 2.0.0 to 3.0.0:

The `cellxgene-schema` CLI should have an option to update the datasets prior to re-validation:

- Rename `ethnicity_term_ontology_id` to `self_reported_ethnicity_term_ontology_id`
- Rename `ethnicity` to `self_reported_ethnicity`
- Delete all deprecated fields in the table below:

<table>
<thead>
  <tr>
    <th>Reserved Name</th>
    <th>AnnData</th>
    <th>Deprecated in</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>X_normalization</td>
    <td>uns</td>
    <td>3.0.0</td>
  </tr>
  <tr>
    <td>default_field</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
  <tr>
    <td>layer_descriptions</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
  <tr>
    <td>tags</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
   <tr>
    <td>version</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
  <tr>
    <td>contributors</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>preprint_doi</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>project_description</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>project_links</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>project_name</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>publication_doi</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>

- Set `suspension_type` based on the corresponding `assay_ontology_term_id` if possible - some assays support multiple choices.
- Update `schema_version` to "3.0.0"

**Comment by jahilton** [comment]
I think 3. Delete X_normalization should be updated to
3. Delete any deprecated field (#264 )

**Comment by brianraymor** [comment]
@jahilton - so you're comfortable if migration deletes a `publication-doi` in `uns` for example? Just saying that it's a sharp tool ...

**Comment by jahilton** [comment]
Yes, I'm actually counting on it.

**Comment by brianraymor** [comment]
I update the top-level summary comment to include that requirement.

**Comment by nayib-jose-gloria** [comment]
documenting one more feature to include, from Jason:

> Would it be possible to include an ontology update function, as well?
For the cases where we know there is a direct replacement for a deprecated term
As of now, there are 3 cases in 2-to-3 migration
obs.disease - MONDO:0008345 --> MONDO:0800029
obs.cell_type - CL:0002609 --> CL:0010012
obs.cell_type - CL:0011107 --> CL:0000636

**Comment by jychien** [comment]
For suspension_type column, it would be great to have the following behavior and logging to help track what was done by the "convert" command:
- If suspension_type column is already in obs, leave it in the object and report what the categories currently are for this column
- If suspension_type is not present in obs, add suspension_type for assays that have only one possible value and report the value that was added
- Else, if NaN was added for suspension_type, report this as well

**Comment by jychien** [comment]
Logging looks good! Thank you! Closing ticket.
| Test Case                                                  | Expected Result                                      | Obtained Result                                                                                                                                                                                                                                                                                                                               | Test File                         |
| ---------------------------------------------------------- | ---------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------- |
| no suspension\_type column for 10x 3' v2 and v3            | Logging and add suspension\_type nan                 | column 'suspension\_type' not found in obs. Adding column and auto-assigning value where possible.<br>Dataset contains row(s) with assay\_ontology\_term\_id EFO:0009899. Automatically assigned suspension\_type nan<br>Dataset contains row(s) with assay\_ontology\_term\_id EFO:0009922. Automatically assigned suspension\_type nan      | heart\_v3\_nosus.h5ad             |
| suspension\_type 'cell' and 'nucleus' for 10x 3' v2 and v3 | Logging                                              | suspension\_type already exists in obs, with categories Index(\['cell', 'nucleus'\], dtype='object')                                                                                                                                                                                                                                          | heart\_cell\_nucleus\_v3.h5ad     |
| no suspension\_type column for spatial                     | Logging and add suspension\_type na                  | column 'suspension\_type' not found in obs. Adding column and auto-assigning value where possible.<br>Dataset contains row(s) with assay\_ontology\_term\_id EFO:0010961. Automatically assigned suspension\_type na                                                                                                                          | heart\_spatial\_v3.h5ad           |
| no suspension\_type column for DroNc-seq                   | Logging and add suspension\_type "nucleus"           | column 'suspension\_type' not found in obs. Adding column and auto-assigning value where possible.<br>Dataset contains row(s) with assay\_ontology\_term\_id EFO:0008720. Automatically assigned suspension\_type nucleus                                                                                                                     | heart\_droncseq\_v3.h5ad          |
| no suspension\_type column for DroNc-seq and Drop-seq      | Logging and add suspension\_type "nucleus" or "cell" | column 'suspension\_type' not found in obs. Adding column and auto-assigning value where possible.<br>Dataset contains row(s) with assay\_ontology\_term\_id EFO:0008720. Automatically assigned suspension\_type nucleus<br>Dataset contains row(s) with assay\_ontology\_term\_id EFO:0008722. Automatically assigned suspension\_type cell | heart\_droncseq\_dropseq\_v3.h5ad |
