### ISSUE TITLE
cellxgene-schema must detect and fail reserved names that are deprecated

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#264]
Reserved Names from previous schema versions that have since been deprecated MUST NOT be present in datasets:

<table>
<thead>
  <tr>
    <th>Reserved Name</th>
    <th>AnnData</th>
    <th>Deprecated in</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>ethnicity</td>
    <td>obs</td>
    <td>3.0.0</td>
  </tr>
  <tr>
    <td>ethnicity_ontology_term_id</td>
    <td>obs</td>
    <td>3.0.0</td>
  </tr>
  <tr>
    <td>X_normalization</td>
    <td>uns</td>
    <td>3.0.0</td>
  </tr>
  <tr>
    <td>default_field</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
  <tr>
    <td>layer_descriptions</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
  <tr>
    <td>tags</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
   <tr>
    <td>version</td>
    <td>uns</td>
    <td>2.0.0</td>
  </tr>
  <tr>
    <td>contributors</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>preprint_doi</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>project_description</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>project_links</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>project_name</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td>publication_doi</td>
    <td>uns</td>
    <td>1.1.0</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>

**Comment by jychien** [comment]
Added the reserved names to obs and uns to check for logging. All looks good:
| Test Case                                    | Expected Result | Obtained Result                                                                                                           | Test File                             | Needs attention |
| -------------------------------------------- | --------------- | ------------------------------------------------------------------------------------------------------------------------- | ------------------------------------- | --------------- |
| ethnicity present in obs                     | Fail validation | Failed validation<br>Logging: ERROR: The field 'ethnicity' is present in 'obs', but it is deprecated.                     | adata\_reserved\_ethnicity.h5ad       |                 |
| ethnicity\_ontology\_term\_id present in obs | Fail validation | Failed validation<br>Logging: ERROR: The field 'ethnicity\_ontology\_term\_id' is present in 'obs', but it is deprecated. | adata\_reserved\_ethnicity\_term.h5ad |                 |
| X\_normalization present in uns              | Fail validation | Failed validation<br>Logging: ERROR: The field 'X\_normalization' is present in 'uns', but it is deprecated.              | adata\_reserved\_Xnorm.h5ad           |                 |
| default\_field present in uns                | Fail validation | Failed validation<br>Logging: ERROR: The field 'default\_field' is present in 'uns', but it is deprecated.                | adata\_reserved.h5ad                  |                 |
| layer\_descriptions present in uns           | Fail validation | Failed validation<br>Logging: ERROR: The field 'layer\_descriptions' is present in 'uns', but it is deprecated.           | adata\_reserved\_layer.h5ad           |                 |
| tags present in uns                          | Fail validation | Failed validation<br>Logging: ERROR: The field 'layer\_descriptions' is present in 'uns', but it is deprecated.           | adata\_reserved.h5ad                  |                 |
| version present in uns                       | Fail validation | Failed validation<br>Logging: ERROR: The field 'version' is present in 'uns', but it is deprecated.                       | adata\_reserved.h5ad                  |                 |
| contributors present in uns                  | Fail validation | Failed validation<br>Logging: ERROR: The field 'contributors' is present in 'uns', but it is deprecated.                  | adata\_reserved.h5ad                  |                 |
| preprint\_doi present in uns                 | Fail validation | Failed validation<br>Logging: ERROR: The field 'preprint\_doi' is present in 'uns', but it is deprecated.                 | adata\_reserved.h5ad                  |                 |
| project\_description present in uns          | Fail validation | Failed validation<br>Logging: ERROR: The field 'project\_description' is present in 'uns', but it is deprecated.          | adata\_reserved.h5ad                  |                 |
| project\_links present in uns                | Fail validation | Failed validation<br>Logging: ERROR: The field 'project\_links' is present in 'uns', but it is deprecated.                | adata\_reserved.h5ad                  |                 |
| project\_name present in uns                 | Fail validation | Failed validation<br>Logging: ERROR: The field 'project\_name' is present in 'uns', but it is deprecated.                 | adata\_reserved.h5ad                  |                 |
| publication\_doi present in uns              | Fail validation | Failed validation<br>Logging: ERROR: The field 'publication\_doi' is present in 'uns', but it is deprecated.              | adata\_reserved.h5ad                  |                 |
