### ISSUE TITLE
Add feature sets in uns

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#266]
### Context

See the [Gene Sets Publishing](https://docs.google.com/document/d/1aFqj_0I3oQsdwguwq9nO8O9307IXCpZNVBm1xzwKDtM/edit) one-pager.

### Design

```
AnnData.uns.feature_sets[{
        "name": "feature set name",
        "description": "feature set description",
        "features": ["ENSG0001230", …]
```

1. All keys are required for each feature set.
1. `"name"` must be unique in `"feature sets"`. 
1. `"features"` must be unique ENSEMBL identifiers. These identifiers must be present in the dataset.

 *Presentation* to be defined later such as use of `"description"` in the portal.

---

**Open questions for the Schema**

1. Is there value in linking gene sets to sets of cells in submitted studies?
1. Should we enable users to link feature sets to feature names? For example: 
`"evidence_for"`: `"CL:00000232"`
1. Are feature sets ordered for presentation in the portal?

**Comment by brianraymor** [comment]
Capturing a review comment from @pablo-gar:

>As I look at it I find it less intuitive as compared to an alternate solution. For example a more disk costly solution would be to add bool columns to "adata.var" with standard names like "gene_set_{name}". Obviously this sacrifices the description of the gene set. 
>
>But again I'm not opposed to the embedding solution presented here.

**Comment by LuckyMD** [comment]
One could combine both the feature set description and the bool column in `adata.var` using the same approach as in `adata.uns['batch_condition']` by keeping a description of any feature set and linked column in uns.

**Comment by BAevermann** [comment]
I prefer the solution Malte is proposing as I believe the designations will
be more available for reuse by the community within adata.var versus in a
dictionary in adata.uns.

**Comment by jahilton** [comment]
I agree that annotating these as var metadata feels more appropriate & more accessible to users.
Then something like uns.feature_set_descriptions for descriptions makes sense. Could be a list of {name: n, description: d}s or could just be a dict of n,d pairs

**Comment by brianraymor** [comment]
Per November 27 triage, not a priority.
