### ISSUE TITLE
Validator should check that one item of dict AnnData.uns["layer_descriptions"] is "raw"

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#27]
According to schema v1.1.0 all layers must be described in `AnnData.uns["layer_descriptions"]` which is a dictionary mapping from `{layer_name: layer_description, ...}`

One of `layer_description` must be "raw" (not "Raw", "Raw counts", etc). Otherwise there [will be an error](https://github.com/chanzuckerberg/corpora-data-portal/blob/ffca067b9e4aea237fa2bd7c7a9cbc5813ebd449/backend/corpora/dataset_processing/process.py#L257-L258) when processing the data in the corpora data portal.

The validator should check for this.

**Comment by brianraymor** [comment]
Outdated.
