### ISSUE TITLE
cellxgene-schema must detect and fail reserved names that start with "__"

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#271]
**Reserved Names**. The names of metadata keys MUST NOT start with `"__"`.

**Comment by jychien** [comment]
Looks good to me! :) 
| Test Case                                     | Expected Result | Obtained Result                                                                                                                                                                                                                   | Test File                    | Needs attention |
| --------------------------------------------- | --------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------- | --------------- |
| scRA-seq witth 1 obs column start with '\_\_' | Fail validation | Failed validation<br>Logging: ERROR: The field '\_\_n\_genes' in 'obs' is invalid. Fields that start with '\_\_' are reserved.                                                                                                             | adata\_obs\_underscore.h5ad  |                 |
| scRA-seq witth 2 obs column start with '\_\_' | Fail validation | Failed validation<br>Logging: ERROR: The field '\_\_n\_counts' in 'obs' is invalid. Fields that start with '\_\_' are reserved.<br>ERROR: The field '\_\_n\_genes' in 'obs' is invalid. Fields that start with '\_\_' are reserved. | adata\_obs\_underscores.h5ad |
