### ISSUE TITLE
cellxgene-schema must validate suspension_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#273]
See [schema reference](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#suspension_type).

1. `cellxgene-schema `MUST warn and fail if the corresponding assay is present in the table, but the value of the `suspension_type` does not match the required value(s) in the table.
2. `cellxgene-schema` MUST warn if the corresponding assay is not present in the table. 

---

Curators MUST annotate the following column in the `obs` dataframe:

### suspension_type

<table><tbody>
    <tr>
      <th>Key</th>
      <td>suspension_type</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"cell"</code>, <code>"nucleus"</code>, or <code>"na"</code>.<br>
        <br>This MUST be the correct type for the corresponding assay:
          <br><br>
          <table>
          <thead>
          <tr>
          <th>For Assay</th>
          <th>MUST Use</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><i>10x transcription profiling</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0030080"><code>EFO:0030080</code></a>] and its children</td>
              <td><code>"cell"</code> or <code>"nucleus"</code></td>
           </tr> 
            <tr>
              <td><i>ATAC-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0007045"><code>EFO:0007045</code></a>] and its children</td>
              <td><code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>CEL-seq2</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0010010"><code>EFO:0010010</code></a>]</td>
              <td><code>"cell"</code> or <code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>CITE-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0009294"><code>EFO:0009294</code></a>] and its children</td>
              <td><code>"cell"</code></td>
           </tr>
            <tr>
              <td><i>DroNc-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0008720"><code>EFO:0008720</code></a>]</td>
              <td><code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>Drop-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0008722"><code>EFO:0008722</code></a>]</td>
              <td><code>"cell"</code></td>
           </tr>
            <tr>
              <td><i>microwell-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0030002"><code>EFO:0030002</code></a>]</td>
              <td><code>"cell"</code></td>
           </tr>    
            <tr>
              <td><i>Patch-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0008853"><code>EFO:0008853</code></a>]</td>
              <td><code>"cell"</code></td>
           </tr>
            <tr>
              <td><i>sci-Plex</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0030026"><code>EFO:0030026</code></a>]</td>
              <td><code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>sci-RNA-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0010550"><code>EFO:0010550</code></a>]</td>
              <td><code>"cell"</code> or <code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>Seq-Well</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0008919"><code>EFO:0008919</code></a>]</td>
              <td><code>"cell"</code></td>
           </tr>
            <tr>
              <td><i>Smart-like</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0010184"><code>EFO:0010184</code></a>] and its children</td>
              <td><code>"cell"</code> or <code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>smFISH</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0009918"><code>EFO:0009918</code></a>] and its children</td>
              <td><code>"na"</code></td>
           </tr>   
            <tr>
              <td><i>snmC-seq</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0008939"><code>EFO:0008939</code></a>]</td>
              <td><code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>snmC-seq2</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0030027"><code>EFO:0030027</code></a>]</td>
              <td><code>"nucleus"</code></td>
           </tr>
            <tr>
              <td><i>spatial proteomics</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0700000"><code>EFO:0700000</code></a>] and its children</td>
              <td><code>"na"</code></td>
           </tr>
            <tr>
              <td><i>spatial transcriptomics by high-throughput sequencing</i> [<a href="http://www.ebi.ac.uk/efo/EFO_0030005"><code>EFO:0030005</code></a>] and its children</td>
              <td><code>"na"</code></td>
           </tr>    
          </tbody></table>
          <br>If the assay does not appear in this table, the most appropriate value MUST be selected and <a href="mailto:cellxgene@chanzuckerberg.com">the curation team informed</a> during submission so that the assay can be added to the table.<br>
        </td>
    </tr>
</tbody></table>
<br>

**Comment by jychien** [comment]
Validator looks good! :) Going to. close the ticket.
| Test Case                                                                             | Expected Result                  | Obtained Result                                                                                                                                                                                                                                                                                                                                                                                              | Test File                  | Needs attention |
| ------------------------------------------------------------------------------------- | -------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------- | --------------- |
| "cell", "nucleus", "na" for EFO:0030080 and EFO:0009922 (10x transcription profiling) | Fail validation for na           | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['na'\]'. Values must be one of \['cell', 'nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0030080 or its children                                                                                                                                                                            | adata\_suspension\_1.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0007045 and EFO:0030007                               | Fail validation for cell & na    | Failed validation<br>Logging:ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'na'\]'. Values must be one of \['nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0007045 or its children                                                                                                                                                                             | adata\_suspension\_2.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0010010 and EFO:0010550                               | Fail validation for na           | Failed validation<br>Logging:ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['na'\]'. Values must be one of \['cell', 'nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0010010<br>ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['na'\]'. Values must be one of \['cell', 'nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0010550      | adata\_suspension\_3.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0009294 and EFO:0030008                               | Fail validation for nucleus & na | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['nucleus', 'na'\]'. Values must be one of \['cell'\] when 'assay\_ontology\_term\_id' is EFO:0009294 or its children<br>                                                                                                                                                                        | adata\_suspension\_4.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0008720 and EFO:0030026                               | Fail validation for cell & na    | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'na'\]'. Values must be one of \['nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0008720<br>ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'na'\]'. Values must be one of \['nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0030026     | adata\_suspension\_5.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0008722 and EFO:0030002                               | Fail validation for nucleus & na | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['nucleus', 'na'\]'. Values must be one of \['cell'\] when 'assay\_ontology\_term\_id' is EFO:0008722<br>ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['nucleus', 'na'\]'. Values must be one of \['cell'\] when 'assay\_ontology\_term\_id' is EFO:0030002     | adata\_suspension\_6.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0008853 and EFO:0008919                               | Fail validation for nucleus & na | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['nucleus', 'na'\]'. Values must be one of \['cell'\] when 'assay\_ontology\_term\_id' is EFO:0008853<br>ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['nucleus', 'na'\]'. Values must be one of \['cell'\] when 'assay\_ontology\_term\_id' is EFO:0008919<br> | adata\_suspension\_7.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0010184 and EFO:0008931                               | Fail validation na               | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['na'\]'. Values must be one of \['cell', 'nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0010184 or its children                                                                                                                                                                            | adata\_suspension\_8.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0009918 and EFO:0008992                               | Fail validation cell & nucleus   | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'nucleus'\]'. Values must be one of \['na'\] when 'assay\_ontology\_term\_id' is EFO:0009918 or its children                                                                                                                                                                            | adata\_suspension\_9.h5ad  |                 |
| "cell", "nucleus", "na" for EFO:0008939 and EFO:0030027                               | Fail validation for cell & na    | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'na'\]'. Values must be one of \['nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0008939<br>ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'na'\]'. Values must be one of \['nucleus'\] when 'assay\_ontology\_term\_id' is EFO:0030027     | adata\_suspension\_10.h5ad |                 |
| "cell", "nucleus", "na" for EFO:0700000 and EFO:0700001                               | Fail validation cell & nucleus   | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'nucleus'\]'. Values must be one of \['na'\] when 'assay\_ontology\_term\_id' is EFO:0700000 or its children                                                                                                                                                                            | adata\_suspension\_11.h5ad |                 |
| "cell", "nucleus", "na" for EFO:0030005 and EFO:0030062                               | Fail validation cell & nucleus   | Failed validation<br>Logging: ERROR: Column 'suspension\_type' in dataframe 'obs' contains invalid values '\['cell', 'nucleus'\]'. Values must be one of \['na'\] when 'assay\_ontology\_term\_id' is EFO:0030005 or its children                                                                                                                                                                            | adata\_suspension\_12.h5ad |
