### ISSUE TITLE
cellxgene-schema must detect obs categories with zero observations

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#277]
See [**wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1657756439540589) for background. 

The proposal is to:

1. Detect and warn during validation
2. Detect and correct during `--add-labels`

**Comment by jychien** [comment]
The warning is correct, but running --add-labels does not remove the unused categories.
| Test Case                                              | Expected Result                                         | Obtained Result                                                                                                                                                                                                                                                                                      | Test File                       | Needs attention |
| ------------------------------------------------------ | ------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------- | --------------- |
| obs with single column with multiple zero observations | Pass validation with warning, corrected in --add-labels | Pass validation<br>Logging: WARNING: Column 'author\_cell\_type' in dataframe 'obs' contains a category 'T cells' with zero observations. These categories will be removed when \`--add-labels\` flag is present.<br>However, after running --add-labels, the category with zero obs is still there. | adata\_obs\_zero.h5ad           | X               |
| obs with multiple columns with zero observations       | Pass validation with warning, corrected in --add-labels | Pass validation<br>Logging: WARNING: Column 'author\_cell\_type' in dataframe 'obs' contains a category 'T cells' with zero observations. These categories will be removed when \`--add-labels\` flag is present.<br>However, after running --add-labels, the category with zero obs is still there. | adata\_obs\_zero\_multiple.h5ad | X               |

**Comment by jychien** [comment]
Test files are located: https://drive.google.com/drive/folders/1hNK5E2f9BBFky16nga486Mh0mHhTkgCR?usp=sharing

**Comment by jychien** [comment]
I ran the cli with --add-labels flag, and the generated h5ad have the categories with zero obs removed. Looks good!
