### ISSUE TITLE
cellxgene-schema must warn about quality issues in development_stage_ontology_term_id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#284]
Reported by @jahilton 

•	16 collections currently contain some unknown
•	6 of those are all unknown

To improve data quality, `cellxgene-schema` must warn when:
1.  The value of `development_stage_ontology_term_id` is "unknown" for the entire dataset.
2. The value of `development_stage_ontology_term_id` is HsapDv:0000087 for "human adult stage". This is specific to Homo Sapiens.

**Comment by brianraymor** [comment]
@jahilton - is there a case similar to "human adult stage" for MmusDv?

**Comment by jahilton** [comment]
Yes, we could warn for `MmusDv:0000110` (mature stage)

**Comment by brianraymor** [comment]
Per November 27 triage, @jahilton agreed to close as low value.
