### ISSUE TITLE
cellxgene-schema must warn about quality issues in assay_ontology_term_id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#286]
To improve data quality, `cellxgene-schema` must warn when:
1.  The value of `assay_ontology_term_id` is EFO:0008913 for "single-cell RNA sequencing".

**Comment by brianraymor** [comment]
@jahilton - should there be a similar warning for "single nucleus RNA sequencing"?

**Comment by jahilton** [comment]
Yes, that makes sense

**Comment by brianraymor** [comment]
Per November 27 triage, @jahilton agreed to close as low value.
