### ISSUE TITLE
Remove footnotes from Molecular, spatial and projection diversity of neurons in primary motor cortex revealed by in situ single-cell transcriptomics

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#29]
The Description for [Molecular, spatial and projection diversity of neurons in primary motor cortex revealed by in situ single-cell transcriptomics](https://cellxgene.cziscience.com/collections/9132fae8-bdfe-480f-9e45-45bc77f320b3) includes footnote numbers.

See **bolded** cases below:

> A mammalian brain is comprised of numerous cell types organized in an intricate manner to form functional neural circuits. Single-cell RNA sequencing provides a powerful approach to identify cell types based on their gene expression profiles and has revealed many distinct cell populations in the brain**1-3**. Single-cell epigenomic profiling**4,5** further provides information on gene-regulatory signatures of different cell types. Understanding how different cell types contribute to brain function, however, requires knowledge of their spatial organization and connectivity, which is not preserved in sequencing-based methods that involve cell dissociation**3,6**. Here, we used an in situ single-cell transcriptome-imaging method, multiplexed error-robust fluorescence in situ hybridization (MERFISH)**7** ...

**Comment by jahilton** [comment]
This has been updated.
