### ISSUE TITLE
Please remove "www." from DOI(s)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#309]
There are two legacy cases where https://www.doi.org is being used as the origin instead of https://doi.org:

['Urethral luminal epithelia are castration-insensitive cells of the proximal prostate'](https://cellxgene.cziscience.com/collections/fbc5881f-1ee3-4ffe-8095-35e15e1a08fc)
['Massively multiplex chemical transcriptomics at single-cell resolution'](https://cellxgene.cziscience.com/collections/00109df5-7810-4542-8db5-2288c46e0424)

1. These are not the official DOIs which do not include "www".
1. "www" is a blast from the past - 90's? 
1. These makes filtering more complex for API consumers of the DOI.

Could these be updated? The portal UX blocks this from happening further with the DOI changes. I need to review this in the API.

**Comment by jahilton** [comment]
Revised & published. I no longer see 'www' in the DOI. @brianraymor can you confirm & close?

**Comment by brianraymor** [comment]
LGTM. Thanks Jason.
