### ISSUE TITLE
cellxgene-schema must enforce the schema version required by the schema

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#324]
### schema_version

<table><tbody>
    <tr>
      <th>Key</th>
      <td>schema_version</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          This MUST be <code>"3.0.0"</code>.
        </td>
    </tr>
</tbody></table>

**Comment by jychien** [comment]
Looks good! Thanks!
| Test Case                     | Expected Result | Obtained Result                                                                                                                                          | Test File             | Needs attention |
| ----------------------------- | --------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------- | --------------- |
| uns.schema\_version = '2.0.0' | Fail validation | Failed validation<br>Logging: ERROR: Schema version '2.0.0' is not supported. Current supported versions: '\['3.0.0'\]'. Validation cannot be performed. | adata\_schema\_2.h5ad |                 |
| uns.schema\_version = '3.0    | Fail validation | Failed validation<br>Logging: ERROR: Schema version '3.0' is not supported. Current supported versions: '\['3.0.0'\]'. Validation cannot be performed.   | adata\_schema\_3.h5ad |
