### ISSUE TITLE
self_reported_ethnicity must allow multiple HANCESTRO terms

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#334]
# Design

**Notes**: 

I recommend that this issue be addressed last when updating `cellxgene-schema` CLI. Its design may be simplified prior to Schema 4 delivery **IF** HANCESTRO is updated to address pending requests:

1. The ontology is modeled to make it possible to identify HANCESTRO terms that are appropriate for the self reported use case. The ontologist is planning to ensure that _each term is tagged accordingly so we could infer 2 new parent classes to automatically give us a full list of geographic descriptors and of ethnicity descriptors._ Currently, CELLxGENE must assess the entire ontology and _cherry pick_ terms to block which increases the complexity of curation and validation. 
1. [Preferred term label for HANCESTRO:0015](https://github.com/EBISPOT/ancestro/issues/36) was addressed. 

Also see [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1689288801992369?thread_ts=1686097986.283929&cid=C024HCSH9PT).

---

## `obs` (Cell Metadata)

`obs` is a [`pandas.DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

Curators MUST annotate the following columns in the `obs` dataframe:

### self_reported_ethnicity_ontology_term_id

<table>
  <tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>
        categorical with <code>str</code> categories. If
        <code>organism_ontolology_term_id</code> is
        <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>,
        the value MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO
        terms is ascending lexical order or <code>"unknown"</code> if unavailable.<br><br>For example, if the terms are <code>"HANCESTRO:00014</code> and <code>HANCESTRO:0005"</code> then the value of <code>self_reported_ethnicity_ontology_term_id</code> MUST be <code>"HANCESTRO:0005,HANCESTRO:0014"</code>.<br><br>The following terms MUST NOT be used:<br /><br />
        <ul>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0002?lang=en"
              ><code>"HANCESTRO:0002"</code></a
            >
            for <i>regions</i> and its children
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0003?lang=en"
              ><code>"HANCESTRO:0003"</code></a
            >
            for <i>country</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0004?lang=en"
              ><code>"HANCESTRO:0004"</code></a
            >
            for <i>ancestry category</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0018?lang=en"
              ><code>"HANCESTRO:0018"</code></a
            >
            for <i>uncategorised population</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0290?lang=en"
              ><code>"HANCESTRO:0290"</code></a
            >
            for <i>genetically isolated population</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0304?lang=en"
              ><code>"HANCESTRO:0304"</code></a
            >
            for <i>ancestry status</i> and its children
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0323?lang=en"
              ><code>"HANCESTRO:0323"</code></a
            >
            for <i>Finnish founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0324?lang=en"
              ><code>"HANCESTRO:0324"</code></a
            >
            for <i>Dutch founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0551?lang=en"
              ><code>"HANCESTRO:0551"</code></a
            >
            for <i>genetically homogenous Irish</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0554?lang=en"
              ><code>"HANCESTRO:0554"</code></a
            >
            for <i>Silk Road founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0555?lang=en"
              ><code>"HANCESTRO:0555"</code></a
            >
            for <i>Arab Israeli founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0557?lang=en"
              ><code>"HANCESTRO:0557"</code></a
            >
            for <i>Costa Rican founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0558?lang=en"
              ><code>"HANCESTRO:0558"</code></a
            >
            for <i>French Canadian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0559?lang=en"
              ><code>"HANCESTRO:0559"</code></a
            >
            for <i>Italian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0560?lang=en"
              ><code>"HANCESTRO:0560"</code></a
            >
            for <i>Northern Finnish founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0561?lang=en"
              ><code>"HANCESTRO:0561"</code></a
            >
            for <i>Romanian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0564?lang=en"
              ><code>"HANCESTRO:0564"</code></a
            >
            for <i>Vis founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0565?lang=en"
              ><code>"HANCESTRO:0565"</code></a
            >
            for <i>Split founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0566?lang=en"
              ><code>"HANCESTRO:0566"</code></a
            >
            for <i>undefined ancestry population</i>
          </li>
          <li>
            The imported GEO term
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGEO_000000374?lang=en"
              ><code>"GEO:000000374"</code></a
            >
            for <i>continent</i> and its children:
            <ul>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0029?lang=en"
                  ><code>"HANCESTRO:0029"</code></a
                >
                for <i>Africa</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0030?lang=en"
                  ><code>"HANCESTRO:0030"</code></a
                >
                for <i>Asia</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0031?lang=en"
                  ><code>"HANCESTRO:0031"</code></a
                >
                for <i>Europe</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0032?lang=en"
                  ><code>"HANCESTRO:0032"</code></a
                >
                for <i>Oceania</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0033?lang=en"
                  ><code>"HANCESTRO:0033"</code></a
                >
                for <i>Latin America and the Caribbean</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0034?lang=en"
                  ><code>"HANCESTRO:0034"</code></a
                >
                for <i>Northern America</i>
              </li>
            </ul>
          </li>
        </ul>
        <br />Otherwise, for all other organisms the
        <code>str</code> value MUST be <code>"na"</code>.
      </td>
    </tr>
  </tbody>
</table>
<br />

---

When a dataset is uploaded, the CELLxGENE Discover MUST automatically add the matching human-readable name for the corresponding ontology term to the `obs` dataframe. Curators MUST NOT annotate the following columns.

### self_reported_ethnicity

<table><tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"na"</code> or <code>"unknown"</code> if set in <code>self_reported_ethnicity_ontology_term_id</code>; otherwise, this MUST be one or more comma-separated (with no leading or trailing spaces) human-readable names for the terms in <code>self_reported_ethnicity_ontology_term_id</code> in the same order.<br><br> For example, if the value of <code>self_reported_ethnicity_ontology_term_id</code> is <code>"HANCESTRO:0005,HANCESTRO:0014"</code> then the value of <code>self_reported_ethnicity</code> is <code>"European,Hispanic or Latin American"</code>.
        </td>
    </tr>
</tbody></table>
<br>

---

schema v4.0.0

* obs (Cell metadata)
  * Updated `self_reported_ethnicity_ontology_term_id`
  * Updated `self_reported_ethnicity`

# Context

_To support accurate metadata for multiethnic donors (donors who have selected more than one ethnicity),`self_reported_ethnicity` must allow multiple HANCESTRO terms._

**Comment by jahilton** [comment]
2 Collections use `multiethnic` currently so those will be replaced by a list of multiple HANCESTRO terms

- https://cellxgene.cziscience.com/collections/7d7cabfd-1d1f-40af-96b7-26a0825a306d (15 donors)
- https://cellxgene.cziscience.com/collections/1ca90a2d-2943-483d-b678-b809bf464c30 (3 donors)

In Lattice DB, yet to get to CxG, there are 26 donors in another study that would have multiple terms

**Comment by jahilton** [comment]
For multiple terms, are we OK with comma+space separated, like the current examples? And/or comma only?

---
Are we prepared for a comma within a single label? [HANCESTRO:0015](https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0015?lang=en) is `Greater Middle Eastern (Middle Eastern, North African or Persian)`. Is there another delimiter we could use to avoid any parsing confusion/errors?

---
>The order of multiple terms is not significant

While I agree that curators & submitters ideally won't need to worry about it, but seems like they should be ordered for users so the Census users won't see `HANCESTRO:0005, HANCESTRO:0008` & `HANCESTRO:0008, HANCESTRO:0005` and cxg viewers won't see `European, Asian` & `Asian, European`, etc.


---
Couple typos in the URLs:

- `"HANCESTRO:0002"` - current link is for HANCESTRO_000**1**
- `"HANCESTRO:0324"` - current link is for HANCESTRO_032**3**

**Comment by brianraymor** [comment]
> Couple typos in the URLs:

Thanks for catching. Corrected.

**Comment by brianraymor** [comment]
> For multiple terms, are we OK with comma+space separated, like the current examples? And/or comma only?
> 

I was tempted to write some ABNF earlier. 

> Are we prepared for a comma within a single label? [HANCESTRO:0015](https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0015?lang=en) is Greater Middle Eastern (Middle Eastern, North African or Persian). Is there another delimiter we could use to avoid any parsing confusion/errors?

I meant to check the presence of commas in labels. Doh. This is primarily an issue because we're unable to use arrays for the list of self reported ethnicities. Possible options:

1. Since there's only case where a HANCESTRO label includes a comma, we could request that it be replaced by an "or"? And ask that no further comma(s) be specified?
2. We replace the comma with a separator that's unlikely to appear in an HANCESTRO label such as "|".

@pablo-gar @bkmartinjr @atarashansky - do you have preferences?

**Comment by brianraymor** [comment]
> >The order of multiple terms is not significant
> 
> While I agree that curators & submitters ideally won't need to worry about it, but seems like they should be ordered for users so the Census users won't see `HANCESTRO:0005, HANCESTRO:0008` & `HANCESTRO:0008, HANCESTRO:0005` and cxg viewers won't see `European, Asian` & `Asian, European`, etc.

I had an earlier draft that normalized the labels by ascending lexcographical order would then require a rewrite of their term id(s) to match. Based on my earlier draft, your example above:

`HANCESTRO:0005, HANCESTRO:0008` would be normalized to `HANCESTRO:0008, HANCESTRO:0005` to match the ordered labels `Asian, European`.

Another option is to normalize by ascending term id(s) but then the labels are more random:

`HANCESTRO:0008, HANCESTRO:0005` becomes `HANCESTRO:0005, HANCESTRO:0008`

CC: @pablo-gar @bkmartinjr @atarashansky

**Comment by jahilton** [comment]
RE:ordering - both options result in consistent display of the same values so I don't have a strong preference. Maybe slight preference for lexicographical order of labels (users are more likely to see the A-->Z pattern & therefore less likely to think the order means something significant?)

**Comment by bkmartinjr** [comment]
Re: array syntax:
* prefer a single-character delimiter (not the space+comma combination used in the first example).
* also prefer a delimiter which is illegal in an ontology term, so we do not have to worry about escaping it. That makes the typical query (via string regex) feasible.  OTOMH, I don't know what is legal/illegal in RDF terms (and I hope OBO follows the same?), but I'd look to that grammar to find a character that we can safely use.  Perhaps a simple space is the best choice?
* I don't think the Census cares strongly about ordering unless there are semantics associated with the ordering (there are weak arguments for a (any) canonical ordering as that would help compression).  I agree that visualization tools _do_ care, but I think they care in different ways, and can apply their own logic (i.e., it does not need to be codified in the schema).  In Jason's "cxg" (I think he means Explorer) example, it is trivial for the Explorer backend to sort these at CXG creation time.

**Comment by brianraymor** [comment]
> Perhaps a simple space is the best choice?

I may be missing your point, but there are many cases where the HANCESTRO labels include spaces like "South East Asian" or consider Jason's outlier :

"Greater Middle Eastern (Middle Eastern, North African or Persian **separator** European"

> prefer a delimiter which is illegal in an ontology term

I could see if OWL(s) have different constraints beyond [XML](https://www.w3.org/TR/xml/#charsets). 

What about using multiple characters such as `"<br>"`.  There are some crazier ideas out there like scanning the source text and finding a unique character.

**Comment by brianraymor** [comment]
I've asked Dani if the one label could be updated to not use a comma. Fingers crossed.

Could we double-quote terms within single-quoted strings?

label = '"Greater Middle Eastern (Middle Eastern, North African, or Persian)", "European"'
list = (re.findall('"([^"]*)"', label)) 

which produces a helpful list:

['Greater Middle Eastern (Middle Eastern, North African, or Persian)', 'European']

**Comment by bkmartinjr** [comment]
> I may be missing your point, but there are many cases where the HANCESTRO labels include spaces like "South East Asian" or consider Jason's outlier :

You were not - I was myopically focused on the term id syntax, and forgot about the labels.  Sigh. We may simply have to escape labels, although that will make any regex-based search interesting

**Comment by pablo-gar** [comment]
Everything looks good to me. Great job on going over the HANCESTRO ontology and excluding terms.

Only two points: 

- I propose we use `;` as a separator.
- We should include the curated spreadsheet at the very least in this ticket and ideally in the schema. For that spreadsheet I suggest naming the tab as "HANCESTRO_version..." to know exactly what version it is.

**Comment by brianraymor** [comment]
> We should include the curated spreadsheet at the very least in this ticket and ideally in the schema. For that spreadsheet I suggest naming the tab as "HANCESTRO_version..." to know exactly what version it is.

Can you say more about the rationale? The schema pins a HANCESTRO version. The requirements for `self_reported_ethnicity_term_id` ensure that only terms appropriate for self reporting can be selected by curators. (There are 290 appropriate terms after the filtering) I'm happy to link the spreadsheet to the issue if it's helpful for others to _check the math_. 

For the future, we've asked Dani to consider adding a property that would allow HANCESTRO consumers to easily filter terms that are appropriate for self reporting rather than requiring the manual review and cherry picking of terms.

**Comment by brianraymor** [comment]
After reviewing with Dani, I opened [Preferred term label for HANCESTRO:0015](https://github.com/EBISPOT/ancestro/issues/36).

**Comment by brianraymor** [comment]
And since I'm _knee deep_ in clarifying requirements for #216 -  any reordering of terms/labels could impact `_colors` if a submitter was coloring by this field.

**Comment by pablo-gar** [comment]
> Can you say more about the rationale? The schema pins a HANCESTRO version. The requirements for self_reported_ethnicity_term_id ensure that only terms appropriate for self reporting can be selected by curators. (There are 290 appropriate terms after the filtering) I'm happy to link the spreadsheet to the issue if it's helpful for others to check the math.
> 
> For the future, we've asked Dani to consider adding a property that would allow HANCESTRO consumers to easily filter terms that are appropriate for self reporting rather than requiring the manual review and cherry picking of terms.

Mainly a historical record of the decisions that were made, it can come in handy for when explaining the decisions and or in the future when we have to revise HANCESTRO.
