### ISSUE TITLE
cellxgene-schema must validate Drop-seq refinement in suspension_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#343]
Please see the details in [Drop-seq must use either "cell" or "nucleus" in suspension_type](https://github.com/chanzuckerberg/single-cell-curation/issues/342).

**Comment by nayib-jose-gloria** [comment]
release candidate for cellxgene-schema version with updated validation and conversion accounting for this change: https://drive.google.com/file/d/1PIC7UkqvRsIgeEHffxr87i5iqDvwDbCr/view?usp=sharing

**Comment by jychien** [comment]
Just got the updated cellxgene-schema-3.0.0rc14.tar.gz from you, and it looks good! :) Thanks!
