### ISSUE TITLE
Update dataset metadata in Time-resolved Systems Immunology Reveals a Late Juncture Linked to Fatal COVID-19 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#35]
The datasets in [Time-resolved Systems Immunology Reveals a Late Juncture Linked to Fatal COVID-19](https://cellxgene.cziscience.com/collections/ed9185e3-5b82-40c7-9824-b2141590c7f0) should be corrected to:

- [ ] Use 'blood' rather than 'Blood' as the` tissue label`
- [ ] Use 'normal' and rather than 'Normal' as the `disease label` as indicated by PATO:0000461

**Comment by jahilton** [comment]
During migration, we will remove the fields containing labels, and allow the Portal to assign the correct label.
Is this ticket still necessary?

**Comment by jahilton** [comment]
resolved via migration to 2.0.0
