### ISSUE TITLE
Integrate all required ontology processing into ontology preparation

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#357]
### Context

The `cellxgene-schema` CLI [downloads and processes](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/scripts/ontology_processing.py) pinned ontologies to address the schema requirements. 

There is separate (distributed in the code base) ontology processing occurring for _filter by metadata_, _filter with ontology awareness_, _gene expresssion_, and _cell census_. 

We should investigate integrating all required ontology processing into the ontology preparation step for the `cellxgene-schema `CLI  to eliminate duplication of code and ensure that all features are based on the pinned versions of the ontologies.

See [Proposal: Standardization of ontology-derived process and assets of CELLxGENE Discover](https://docs.google.com/document/d/10rFC55RCOyt8zDO1iBXEap5sVUBRwrBgivSnxqz9spk/edit#heading=h.9jrt25c1j4et).

---

@atolopko-czi also writes:

_I've attempted to capture the currently ad hoc, manual [Schema Upgrade Process](https://docs.google.com/document/d/1R3a43eLVtWLOxgSu2HCMdD8QK5hddHjtY7uZJrC4VuE/edit). This can serve as requirements for what processes and configuration updates need to be automated and simplified in order to address this story._

**Comment by atolopko-czi** [comment]
I've attempted to capture the currently ad hoc, manual [Schema Upgrade Process](https://docs.google.com/document/d/1R3a43eLVtWLOxgSu2HCMdD8QK5hddHjtY7uZJrC4VuE/edit). This can serve as requirements for what processes and configuration updates need to be automated and simplified in order to address this story.

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell #446](https://github.com/chanzuckerberg/single-cell/issues/446) via [**Zenhub**](https://www.zenhub.com/)
