### ISSUE TITLE
Change ownership in portal of collection: "Single-Cell RNAseq analysis of diffuse neoplastic infiltrating cells at the migrating front of human glioblastoma"

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#37]
Due to technical issues at UCSC, this collection was uploaded to the [portal](https://cellxgene.cziscience.com/) by me but it was contributed by Rachel Schwartz (raschwar@ucsc.edu)

[https://cellxgene.cziscience.com/collections/558385a4-b7b7-4eca-af0c-9e54d010e8dc](https://cellxgene.cziscience.com/collections/558385a4-b7b7-4eca-af0c-9e54d010e8dc
)

When the feature of ownership change is available in the portal, Rachel must be turned into the owner of this collection.

**Comment by brianraymor** [comment]
@maniarathi - how did we change the owner for the collections that Marcus curated?

**Comment by maniarathi** [comment]
We never ended up changing permissions so there are still a number of collections under Marcus's id. It's a pretty easy database switch to do though once we are ready to update those older collections.

**Comment by brianraymor** [comment]
@maniarathi - can you confirm or deny?

**Comment by seve** [comment]
Can confirm that Rachel is the owner of the collection in our DB.
