### ISSUE TITLE
Recommended terms if donor_id is unknown

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#371]
See [**data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1666655738788709).

@jahilton has documented one case for "pooled" :

> The only cases where we have no donor_id is when samples were pooled - common in mouse studies. For those, we marked as pooled, so that may be potential for a note in the schema

**Comment by pablo-gar** [comment]
Please add an unknown option in the schema in anticipation for when that occurs

**Comment by brianraymor** [comment]
@pablo-gar - my plan is to wait for migration to complete and see if there are additional **STRONGLY RECOMMENDED** terms for other cases that @jahilton discovers. I've left the 3.0.0 schema in a draft stage to address any emerging issues during migration.

**Comment by cakirb** [comment]
Hi, I agree that "unknown" option would be needed. In addition to this, I have come across and wrangled some [human datasets](https://cellxgene.cziscience.com/collections/793fdaec-5067-428a-a9db-ecefe135c945) with pooled samples & the samples that were demultiplexed by [souporcell](https://github.com/wheaton5/souporcell) (discussed with @jahilton recently). I have annotated all of them as "pooled", but I think that would be beneficial to indicate the donors coming from demultiplexing.

**Comment by pablo-gar** [comment]
Yes please include "unknown" preemptively as it will very likely be needed and it is anticipated in the cell census schema

**Comment by jahilton** [comment]
In migration, we only had 1 Collection that required `unknown` in its Datasets, but it is private & we'll get resolution prior to Publishing. I view `unknown` here similar to development_stage - they must have _some_ idea about this so `unknown` would be fairly alarming and avoided at all costs.

Suggested text to add...
It is STRONGLY RECOMMENDED that `pooled` be used for observations from a sample of multiple individuals that were not confidently assigned to a single individual through demultiplexing.
It is STRONGLY RECOMMENDED that `unknown` be used for observations in a dataset when it is not known which observations came from the same individual, and only for those cases.
