### ISSUE TITLE
Should organoids and cell cultures be updated or removed ? 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#372]
Capturing the related comment thread in the cell census schema review:

@bkmartinjr :

This section [Data to be Incorporated Into the Census] must specify how to handle organoids and cell cultures, which have a CELLxGENE-specific term syntax ('<term> (organoid)').

In the first census schema we excluded these, as there were open questions (I can't recall the exact issue - maybe hybrids?) ...

Options I see:
* Retain them, but warn people that they don't have legal ontology term IDs
* Remove them
* or ?

---

@ambrosejcarr :

We removed them in the first schema because cultured cells do not recapitulate healthy human physiology very well (they are closer to cancer)

Organoids are in a gray area, but we didn't think they added enough value to warrant the extra requirements.

---
@bkmartinjr :

I also worry about the ability to query based on their label, as they have this ad hoc syntax we invented.

A third idea for encoding them (which breaks from schema 3.0.0 slightly, which may make this a bad idea). Add a new obs column that contains the "stripped" ontology ID, so that you can query based on either "term_id", or on "term_id (organoid)"

---

@pablo-gar :

It is of my opinion that we should include them because while they are not representative of the "normal" human body, they are still part of our data portal as a whole. If they shouldn't be part of the Census they why are they in our portal?

However they are also of low priority, so figuring out a solution for them to be included is less important than releasing an MVP of the cell census. Thus I'll remove them for now but will leave this thread unresolved for reference.

---

@ambrosejcarr :

Pablo landed in the same place as I did. Exclude for now, but requires more future thought to resolve.

Either:
* Fix representation
* Remove from portal/corpus

**Comment by jahilton** [comment]
#240 might provide a solution (move the appended organoid/cell culture into a separate field)

**Comment by BAevermann** [comment]
I for one am still in favor of separating into a new field. Perhaps "Sample Type" is too vague, but I like the examples given in the attached file in #240.

**Comment by jahilton** [comment]
Reviewing what "cell culture" Collections/Datasets we have

4 Collections have only cell culture data

- https://cellxgene.cziscience.com/collections/d0e9c47b-4ce7-4f84-b182-eddcfa0b2658 (cell lines)
- https://cellxgene.cziscience.com/collections/cdfb9ead-cb58-4a53-879d-5e4ed5329e73
- https://cellxgene.cziscience.com/collections/00109df5-7810-4542-8db5-2288c46e0424 (cell line)
- https://cellxgene.cziscience.com/collections/2a79d190-a41e-4408-88c8-ac5c4d03c0fc

1 Collection has 1 of 2 Datasets as cell culture

- https://cellxgene.cziscience.com/collections/db468083-041c-41ca-8f6f-bf991a070adf

1 Collection has 1 Dataset - 1660 out of 599926 cells are cell culture

- https://cellxgene.cziscience.com/collections/38833785-fac5-48fd-944a-0f62a4c23ed1

**Comment by BAevermann** [comment]
From discussions with @jonahcool, @norbid, and @ambrosejcarr, our recommendation is to continue supporting both Cell Cultures and Organoids; however., the acquisition of this data is low priority.  As such, I believe we should prioritize a more standardized representation in schema 4.

**Comment by brianraymor** [comment]
Per discussion with @BAevermann @jahilton @norbid , there is consensus to retain both organoids and cell cultures in the corpus and to simplify their representation via #240 and not rely on labeling to differentiate. CC: @pablo-gar

**Comment by pablo-gar** [comment]
We will need to do a coordinated effort to update the Census builder, as organoids and cell types must not be included per the census schema.

https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_schema.md#sample-types
