### ISSUE TITLE
post-ontology bump updates (3.0.0+1)

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#373]
Collection `a48f5033-3438-4550-8574-cdff3263fdfd` - All 3 datasets all **assay: EFO:0700010**

Collection `A Proximal-to-Distal Survey of Healthy Adult Human Small Intestine and Colon Epithelium by Single-Cell Transcriptomics` - update CL:0000677 'gut absorptive cell' to **cell_type: CL:4030026** (@rachadele please review/confirm & update the title to the Collection ID once published)

Collection `edb893ee-4066-4128-9aec-5eb2b03f8287` - Both datasets update EFO:0010183 'single cell library construction' to **assay: EFO:0700011**

**Comment by jlzamanian** [comment]
Collection: d2684035-a36e-458e-96af-8e37930bfdf6
Dataset: Integrated tendon dataset (only dataset)

Update the tissue ontology of all 4 samples to new term UBERON:8480009

[tendon of semitendinosus](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_8480009&lang=en&viewMode=PreferredRoots&siblings=false) 

The update will go through Lattice.

**Comment by EMRutherford** [comment]
Collection:  https://cellxgene.cziscience.com/collections/1d1c7275-476a-49e2-9022-ad1b1c793594
Dataset:  Amacrine cells of the human fovea and peripheral retina

Replace CL:0000561 (amacrine cell) with CL:4030027 (GABAergic amacrine cell).

**Comment by EMRutherford** [comment]
Collection:  Integration of eQTL and a Single-Cell Atlas in the Human Eye Identifies Causal Genes for Age-Related Macular Degeneration
Dataset:  Amacrine cells of human eye

For the following group IDs in the processed matrix files:
1.0 - Replace CL:0000561 (amacrine cell) with CL:0004219 (A2 amacrine cell)
5.0 - Replace CL:0000561 (amacrine cell) with CL:4030028 (glycinergic amacrine cell)
11.0 - Replace CL:0000561 (amacrine cell) with CL:0004232 (starburst amacrine cell)

**Comment by EMRutherford** [comment]
Collection: Integration of eQTL and a Single-Cell Atlas in the Human Eye Identifies Causal Genes for Age-Related Macular Degeneration

Dataset:  Retinal ganglion cells of human eye

For the following group IDs in the processed matrix files:
1.0 and 4.0 - Replace CL:0000740 (retinal ganglion cell) with CL:4023033 (OFF retinal ganglion cell)
2.0 and 5.0 - Replace CL:0000740 (retinal ganglion cell) with CL:4023032 (ON retinal ganglion cell)

Dataset:  Cone cells of human eye

For the following group IDs in the processed matrix files:
2.0 - Replace CL:0000573 (retinal cone cell) with CL:0003050 (S cone cell)

**Comment by jahilton** [comment]
Collection: `Single-cell RNA sequencing unifies developmental programs of Esophageal and Gastric Intestinal Metaplasia` - all datasets - update MONDO:0004298 (stomach disorder) to new_term_tbd (gastric intestinal metaplasia) (should be in the Feb MONDO release)

**Comment by jahilton** [comment]
Collection: `A molecular cell atlas of COVID-19 initiation in human lung` - all datasets

- CL:0002144 (capillary endothelial cell) --> CL:4028001 (pulmonary capillary endothelial cell)
- CL:0000669 (pericyte) --> CL:0009089 (lung pericyte)

**Comment by jahilton** [comment]
Collection: `Transcriptional responses of the human dorsal striatum in opioid use disorder implicates cell type-specifc programs`

- D2-Matrix & D2-Striosome need to be updated to CL:4023029
- D1-Matrix & D1-Striosome need to be updated to CL:4023026

**Comment by jahilton** [comment]
Collection: `A single-cell transcriptomic atlas spanning the adult rhesus macaque brain`.

- Update `CL:0002319` to `CL:4023072` - 3 datasets: all cells, 1.5M subset, vascular cells

**Comment by rachadele** [comment]
Collection: `A proximal-to-distal survey of healthy adult human small intestine and colon epithelium by single-cell transcriptomics`

- update  `CL:0002254`  to `CL:4030026`

**Comment by liaanym** [comment]
Collection `A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation`

- update UBERON:0000956 (cerebral cortex) to UBERON:0000956 (gustatory cortex)

**Comment by jahilton** [comment]
Collection `ced320a1-29f3-47c1-a735-513c7084d508`, self_reported_ethnicity

- update Indian to Singaporean Indian [HANCESTRO:0598]
- update Malaysian to Singaporean Malay [HANCESTRO:0597]

(Lattice will subsequently remove the Ethnicity_Selfreported column)

**Comment by jahilton** [comment]
- [661a402a-2a5a-4c71-9b05-b346c57bc451](https://cellxgene.cziscience.com/collections/661a402a-2a5a-4c71-9b05-b346c57bc451) donor_id:GSM4643738 - update to 5 day [MmusDv:0000115]
- [48d354f5-a5ca-4f35-a3bb-fa3687502252](https://cellxgene.cziscience.com/collections/48d354f5-a5ca-4f35-a3bb-fa3687502252) var_time:P7 - update to 7 day [MmusDv:0000117]
- [d86517f0-fa7e-4266-b82e-a521350d6d36](https://cellxgene.cziscience.com/collections/d86517f0-fa7e-4266-b82e-a521350d6d36) Dataset:RomanovDev10x - update to 23 day [MmusDv:0000144]

**Comment by jlzamanian** [comment]
Collection: 9d63fcf1-5ca0-4006-8d8f-872f3327dbe9 
[Brain matters: Unveiling the Distinct Contributions of Region, Age, and Sex to Glia diversity and CNS Function
](https://cellxgene.cziscience.com/collections/9d63fcf1-5ca0-4006-8d8f-872f3327dbe9)

datasets: 
white matter - all cells c05e6940-729c-47bd-a2a6-6ce3730c4919
white matter - oligodendroglia 12194ced-8086-458e-84a8-e2ab935d8db1

Update the cell_type_ontology_term_id for author cell types 
COP_A
COP_B
COP_C

to CL:4023059 [differentiation-committed oligodendrocyte precursor](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_4023059)

**Comment by jahilton** [comment]
- [ ] Collection a48f5033-3438-4550-8574-cdff3263fdfd - All 3 datasets all assay: EFO:0700010
- [ ] Collection A Proximal-to-Distal Survey of Healthy Adult Human Small Intestine and Colon Epithelium by Single-Cell Transcriptomics - update CL:0000677 'gut absorptive cell' to cell_type: CL:4030026
- [ ] Collection edb893ee-4066-4128-9aec-5eb2b03f8287 - Both datasets update EFO:0010183 'single cell library construction' to assay: EFO:0700011
- [ ] Collection Human breast cell atlas - replace CL:0011026 (progenitor cell) w/ CL:0009116 (progenitor cell of mammary luminal epithelium)
- [ ] Collection: Single nucleus and spatial transcriptomic profiling of human healthy hamstring tendon - Update the tissue ontology of all 4 samples to new term UBERON:8480009 (tendon of semitendinosus)
- [ ] Collection: Cell Atlas of The Human Fovea and Peripheral Retina. Dataset: Amacrine cells of the human fovea and peripheral retina. Replace CL:0000561 (amacrine cell) with CL:4030027 (GABAergic amacrine cell). Replace CL:1001509 (glycinergic neuron) with CL:4030028 (glycinergic amacrine cell).
- [ ] Collection: Integration of eQTL and a Single-Cell Atlas in the Human Eye Identifies Causal Genes for Age-Related Macular Degeneration. Dataset: Amacrine cells of human eye. For the following group IDs in the processed matrix files:. Replace CL:0000561 (amacrine cell) with CL:0004219 (A2 amacrine cell), CL:4030028 (glycinergic amacrine cell), CL:0004232 (starburst amacrine cell)
- [ ] Collection: Integration of eQTL and a Single-Cell Atlas in the Human Eye Identifies Causal Genes for Age-Related Macular Degeneration. Dataset: Retinal ganglion cells of human eye. For the following group IDs in the processed matrix files: Replace CL:0000740 (retinal ganglion cell) with CL:4023033 (OFF retinal ganglion cell), CL:4023032 (ON retinal ganglion cell)
- [ ] Collection: Integration of eQTL and a Single-Cell Atlas in the Human Eye Identifies Causal Genes for Age-Related Macular Degeneration. Dataset: Cone cells of human eye. 2.0 - Replace CL:0000573 (retinal cone cell) with CL:0003050 (S cone cell)
- [ ] Collection: Single-cell RNA sequencing unifies developmental programs of Esophageal and Gastric Intestinal Metaplasia - all datasets - update MONDO:0004298 (stomach disorder) to new_term_tbd (gastric intestinal metaplasia)
- [ ] Collection: A molecular cell atlas of COVID-19 initiation in human lung - all datasets. CL:0002144 (capillary endothelial cell) --> CL:4028001 (pulmonary capillary endothelial cell). CL:0000669 (pericyte) --> CL:0009089 (lung pericyte)
- [ ] Collection: Transcriptional responses of the human dorsal striatum in opioid use disorder implicates cell type-specifc programs. D2-Matrix & D2-Striosome need to be updated to CL:4023029. D1-Matrix & D1-Striosome need to be updated to CL:4023026
- [ ] Collection: A single-cell transcriptomic atlas spanning the adult rhesus macaque brain. Update CL:0002319 to CL:4023072 - 3 datasets: all cells, 1.5M subset, vascular cells
- [ ] Collection A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation. update UBERON:0000956 (cerebral cortex) to UBERON:8440075 (gustatory cortex) & 1 dataset in collection, Smart-Seq. update EFO:0010184 (Smart-like) to SMART-seq4
- [ ] Collection: 9d63fcf1-5ca0-4006-8d8f-872f3327dbe9 , datasets: white matter - all cells c05e6940-729c-47bd-a2a6-6ce3730c4919, white matter - oligodendroglia 12194ced-8086-458e-84a8-e2ab935d8db1. Update the cell_type_ontology_term_id for author cell types: COP_A, COP_B, COP_C to CL:4023059

From ontologies not in this update...

- ced320a1-29f3-47c1-a735-513c7084d508, self_reported_ethnicity. update Indian to Singaporean Indian [HANCESTRO:0598]. update Malaysian to Singaporean Malay [HANCESTRO:0597]
- [661a402a-2a5a-4c71-9b05-b346c57bc451](https://cellxgene.cziscience.com/collections/661a402a-2a5a-4c71-9b05-b346c57bc451) donor_id:GSM4643738 - update to 5 day [MmusDv:0000115]
- [48d354f5-a5ca-4f35-a3bb-fa3687502252](https://cellxgene.cziscience.com/collections/48d354f5-a5ca-4f35-a3bb-fa3687502252) var_time:P7 - update to 7 day [MmusDv:0000117]
- [d86517f0-fa7e-4266-b82e-a521350d6d36](https://cellxgene.cziscience.com/collections/d86517f0-fa7e-4266-b82e-a521350d6d36) Dataset:RomanovDev10x - update to 23 day [MmusDv:0000144]

**Comment by jahilton** [comment]
Verified that all non HANCESTRO/Dv updates were completed during migration. The rest were carried over to #605
