### ISSUE TITLE
The h5ad schema should indicate what versions of the validator "validate" the current schema

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#376]
Main issue: the linking between the schema version and validator version is not explicitly defined anywhere. 

I understand that we made major versions of the validator match major versions of the schema. For tracking, visibility and reproducibility, I propose the schema doc should indicate what versions of the validator work with the given schema and what is the latest version that should be used by curators and ingestion system. 

This is the only point of disconnect that I've found between the ontology versions defined in the schema and the intermediate files used by the validator (https://github.com/chanzuckerberg/single-cell-curation/tree/main/cellxgene_schema_cli/cellxgene_schema/ontology_files)

These intermediates files are packaged in the [python pypi installable](https://pypi.org/project/cellxgene-schema/#history) and github releases, thus providing reproducibility at the validator level. However when a user (internal/external) wishes to use the intermediate files for a given schema version it is now impossible to know what version of the validator to use to grab those files, without the a priori knowledge of version matching between the validator and the schema.

**Comment by brianraymor** [comment]
I have no desire to update the schema if a bug is patched in the CLI. I'd reverse the polarity. The CLI could document which version of the schema it implements. 

In general, I think you need to make a better case for the requirement. It seems theoretical.

**Comment by brianraymor** [comment]
Closing. If needed, then the CLI should document which version of the schema it implements.
