### ISSUE TITLE
Add feature_length to schema

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#377]
# Design (@brianraymor)

### feature_length

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_length</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>uint</code> number of base-pairs (bps). If the <code>feature_biotype</code> is <code>"gene"</code>, then the value is calculated by creating non-overlapping concatenated exons across all isoforms of the gene, and then adding up their length in base-pairs. This approach was inspired by the "length of merged exons of isoforms of a gene" from <a href="https://doi.org/10.1093/bioinformatics/btac561">GTFtools: a software package for analyzing various features of gene models.</a>
<br><br> If <code>feature_biotype</code> is NOT <code>"gene"</code> then the value MUST be set to 0.
</td>
    </tr>
</tbody></table>
<br>

---

## Appendix A. Changelog

schema v4.0.0

* var and raw.var (Gene Metadata)
  * Added `feature_length`
 
---

# Context

`feature_length` as in gene length in base pairs has been requested by users and it is necessary information for normalizing data from full-length RNA sequencing (e.g. smartseq).

It is ideal to encode this information at time of ingestion as this makes it immediately available to users and it propagates to all other functionalities of CELLxGENE Discover (importantly the Cell Census). Additionally this provides a standard platform for any analyses that require this information.

This information is already calculated from the pinned Gene References and is readily available here  `single-cell-curation/cellxgene_schema_cli/cellxgene_schema/ontology_files/` on the files `genes_[organism].csv.gz`

This information can and should be added by the validator.

---

We need to explicitly detail how we calculated this value from the gene reference files. Currently there are few approaches used by the community.

The one used by us:

> For each gene, its length is calculated by creating non-overlapping concatenated exons across all isoforms of a gene, and then adding up their length in base-pairs. Our implementation is inspired by GTF tools http://www.genemine.org/gtftools.php

This calculation is done [here](https://github.com/chanzuckerberg/single-cell-curation/blob/100f935eac932e1f5f5dadac0627204da3790f6f/cellxgene_schema_cli/scripts/gene_processing.py#L77)

---

**Comment by pablo-gar** [comment]
Food for thought

As we evolve on accepting other feature spaces, for example proteins, we need to think how this field will evolve. I'm thinking `0` when `"feature_biotype"` is not `"gene"`

**Comment by jahilton** [comment]
Worth exploring how the length of a given gene has changed across GENCODE versions to understand if this would be confusing/misleading to users (eg GeneA was x nt long when I aligned to hg19, but CxG shows GeneA is y nt long because they're using v43)
