### ISSUE TITLE
Document how `feature_length` is calculated

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#378]
Related to #377 

Upon addition of `feature_length` to the schema, we need to explicitly detail how we calculated this value from the gene reference files. Currently there are few approaches used by the community.

The one used by us:

> For each gene, its length is calculated by creating non-overlapping concatenated exons across all isoforms of a gene, and then adding up their length in base-pairs. Our implementation is inspired by GTF tools http://www.genemine.org/gtftools.php

This calculation is done [here](https://github.com/chanzuckerberg/single-cell-curation/blob/100f935eac932e1f5f5dadac0627204da3790f6f/cellxgene_schema_cli/scripts/gene_processing.py#L77)

@brianraymor I'm guessing that best place to document this is in the schema once it gets added? Or should this be documented somewhere else?

**Comment by brianraymor** [comment]
I added the information to #377. Closing as duplicate.
