### ISSUE TITLE
Update dataset metadata in A single-cell transcriptional roadmap of the mouse and human lymph node lymphatic vasculature

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#38]
The **Homo sapiens** dataset in [A single-cell transcriptional roadmap of the mouse and human lymph node lymphatic vasculature](https://cellxgene.cziscience.com/collections/9c8808ce-1138-4dbe-818c-171cff10e650) should be corrected to:

- [ ] Use 'human adult stage' rather than 'adult' for the `development_stage label` as indicated by HsapDv:0000087
- [ ] Use 'HsapDv:0000087' rather than 'EFO:0001272' for the `development_stage_ontology_term_id` per the schema  _HsapDv term if human, child of EFO:0000399 otherwise_

Note that 'adult' is correct for the Mus musculus dataset.

**Comment by jahilton** [comment]
updated via migration to 2.0.0
