### ISSUE TITLE
The schema must be authoritative and specific on "unknown" cell types

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#380]
# Proposal (@brianraymor)

## Integration Metadata

...

  To meet cellxgene schema requirements, the most accurate available CL term MUST be used until the new term is available. For example if `cell_type_ontology_term_id` describes a relay interneuron, but the most accurate available term in the CL ontology is [CL:0000099](https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000099) for *interneuron*, then the interneuron term can be used to fulfill this requirement and ensures that users searching for "neuron" are able to find these data. If the cell type is unknown or a single cell type is not appropriate (e.g. the observation is from a mixed population or represents a doublet), then the most accurate term is [CL:0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000003) for *native cell*. Users will still be able to access more specific cell type annotations that have been submitted with the dataset (but aren't required by the schema).

### cell_type_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>cell_type_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be a CL term.<br><br>If no appropriate high-level term can be found or the cell type is unknown, then it is STRONGLY RECOMMENDED to use <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000003"><code>"CL:0000003"</code></a> for <i>native cell</i>. The following terms MUST NOT be used:
        <ul><li>
          <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000255"><code>"CL:0000255"</code></a> for <i>eukaryotic cell</i>
        </li>
        <li>
          <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000257"><code>"CL:0000257"</code></a> for <i>Eumycetozoan cell</i>
        </li>
        <li>
            <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000548"><code>"CL:0000548"</code></a> for <i>animal cell</i>
         </li></ul>
    </tr>
</tbody></table>
<br>

--

## Appendix A. Changelog

schema v4.0.0

* obs (Cell metadata)
  * Updated `cell_type_ontology_term_id`

--

# Context

Currently the schema states:

> To meet cellxgene schema requirements, the most accurate available CL term MUST be used until the new term is available. For example if cell_type_ontology_term_id describes a relay interneuron, but the most accurate available term in the CL ontology is [CL:0000099](https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000099) for interneuron, then the interneuron term can be used to fulfill this requirement and ensures that users searching for "neuron" are able to find these data. If no appropriate high-level term can be found or the cell type is unknown, then the most accurate term is [CL:0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000003) for native cell. Users will still be able to access more specific cell type annotations that have been submitted with the dataset (but aren't required by the schema).

This allows for discretion to use terms other than "Native cell" when the cell type is not known, as curators may interpret that the most accurate term for an unknown cell is "Animal cell" or "Eukaryotic cell". These cells are effectively unknown for all intents a purposes. Having different values to indicate "unknown" has rippling effects on all other features of CELLxGENE Discover and non-standardized exceptions have to be made to account for this issue.

I recommend we state that "cells of unknown identity MUST be  use the term is [CL:0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000003) for native cell"

---

See also [Hide native cell, eukaryotic, and animal cell for each tissue from Gene Expression](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4348). 

---

**Comment by brianraymor** [comment]
In retrospect, none of these statements above are really **MUST** because they are not enforced by the validator only Lattice review. They're **STRONGLY RECOMMENDED**.  

Should the schema **MUST NOT** eukaryotic cell and animal cell as choices to nudge curators in the direction that you're recommending, @pablo-gar ?

Also see @jahilton 's comments [elsewhere](https://github.com/chanzuckerberg/single-cell-curation/issues/228#issuecomment-1137304940).

**Comment by pablo-gar** [comment]
> Should the schema MUST NOT eukaryotic cell and animal cell as choices to nudge curators in the direction that you're recommending, @pablo-gar ?

Yes that'd be great, and to minimize the chances of other terms being used for unknown cells (apart from native cell) we may want to do a quick curation of CL and add more terms to this forbidden list .

**Comment by signechambers1** [comment]
@brianraymor this popped up again on the data viz team, we think it is slightly confusing in gene expression to have native cell, animal cell, and eukaryotic cell all within one tissue (more context in slack here if you are curious). This isn't urgent on our end, but curious what the priority is on the curation side?

cc @pablo-gar @atarashansky

**Comment by brianraymor** [comment]
It's included in Q1 Discovery for schema and migration improvements to ensure that we have consensus on the desired solution. The subsequent implementation (cellxgene-cli enforcement) would not be available until H2 when we publish schema `4.0` (per the label on the issue).

**Comment by signechambers1** [comment]
Thank you Brian!

**Comment by brianraymor** [comment]
@pablo-gar to provide recommendations for other high-level cell types that MUST be blocked.

**Comment by pablo-gar** [comment]
@brianraymor please include the following as a MUST NOT use:

CL:0000257 "Eumycetozoan cell"

**Comment by jahilton** [comment]
If ~no appropriate high-level term can be found or~ the cell type is unknown or a single cell type is not appropriate (e.g. the observation is from a mixed population or represents a doublet).

If they _can't find_ appropriate terms, we'd prefer that they address that with CL, so I think the 2 other examples are more indicative of when we see "native cell" used.

**Comment by brianraymor** [comment]
Addressed in #569
