### ISSUE TITLE
cellxgene-schema _is_raw must validate all raw values

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#382]
### Context

Reported by @bkmartinjr. See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1668815096553109).

The original [`_is_raw`](https://github.com/chanzuckerberg/single-cell-curation/blob/e7c8a3ade641bfb597de782aea7ed096e3082135/cellxgene_schema_cli/cellxgene_schema/validate.py#L1045) implementation validated only 5000 values as a default heuristic:

[:param int max_values_to_check: total values to check, default set to 5000 due to performance concerns.](https://github.com/chanzuckerberg/single-cell-curation/blob/e7c8a3ade641bfb597de782aea7ed096e3082135/cellxgene_schema_cli/cellxgene_schema/validate.py#L1056)

This default must be removed. All values must be valid.

**Comment by nayib-jose-gloria** [comment]
As part of the output of this change, please also provide a few performance benchmarks to determine the performance hit of this change (and thus, if any changes need to be made to the batch migration job timeouts to accommodate, for instance)

**Comment by jychien** [comment]
We’ve recently had 4 very large datasets in a private collection, and their size was comparable to the large [SEA-AD](https://cellxgene.cziscience.com/collections/1ca90a2d-2943-483d-b678-b809bf464c30) datasets (~45Gb per h5ad file). Wanted to give you a heads up that they’re there and was also curious about how long the validation in the portal will take after this ticket fix goes in.

**Comment by Bento007** [comment]
@nayib-jose-gloria do we still want this to be configurable somewhere or completely removed?

**Comment by jahilton** [comment]
This one passes our QA ([our notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/382_all_raw_values.ipynb))
