### ISSUE TITLE
Add cell type mappings

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#384]
### Context

See [**single-cell-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1667600105942149).

All high-level mappings (1-1 or tree) of cell types MUST be defined in the dataset schema. When a dataset is uploaded, cellxgene Data Portal MUST automatically add the relevant mapping. The results will be consumed by all cellxgene _experiences_ for consistency.

---

Known cell type mappings implemented in CELLxGENE Discover:

1. Discover UX Cell Type Filter [maps a cell type ](https://github.com/chanzuckerberg/single-cell-data-portal/blob/2505cefa0408cb7b0efd5df75649fbd477fc8fa4/scripts/compute_tissue_and_cell_type_mappings.ipynb)to its _Cell Class_ and _Cell Subclass_. 

---

There are open questions in  [Proposal: Standardization of ontology-derived process and assets of CELLxGENE Discover](https://docs.google.com/document/d/10rFC55RCOyt8zDO1iBXEap5sVUBRwrBgivSnxqz9spk/edit#heading=h.9jrt25c1j4et) about whether such information is required to be embedded in datasets rather than be returned by an API.

**Comment by pablo-gar** [comment]
Also see: 

https://github.com/chanzuckerberg/cell-census/issues/17

**Comment by brianraymor** [comment]
@pablo-gar @signechambers1 - is there any modeling of cell type mappings in data-vis ?

**Comment by signechambers1** [comment]
@brianraymor i'm not aware of any cell type mapping on the data viz side but @pablo-gar can you confirm?

**Comment by brianraymor** [comment]
CC: @atarashansky

**Comment by brianraymor** [comment]
Per the June 13 _tissue mappings - there can be only one_ call with @BAevermann @jahilton @signechambers1 @pablo-gar  there was consensus that this was not broadly required for schema 4. Pending.

**Comment by brianraymor** [comment]
Per cell census schema triage, closing schema mappings in favor of returning mappings in an ontology service. 

See [Integrate all required ontology processing into ontology preparation](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/446)

**Comment by brianraymor** [comment]
Re-opening per conversation on [#cell-science-census](https://czi-sci.slack.com/archives/C048BN7K6U8/p1699389752564209).

**Comment by brianraymor** [comment]
Not required for the dataset schema.
