### ISSUE TITLE
Update pinned GENCODE references

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#386]
# Design

| Source | Required version | Download |
|:--|:--|:--|
| [GENCODE (Human)] | Human reference GRCh38.p14 (GENCODE v44/Ensembl 110) | [gencode.v44.primary_assembly.annotation.gtf] |
| [GENCODE (Mouse)] | Mouse reference GRCm39 (GENCODE vM33/Ensembl 110) | [gencode.vM33.primary_assembly.annotation.gtf] |
||||

[GENCODE (Human)]: https://www.gencodegenes.org/human/
[gencode.v44.primary_assembly.annotation.gtf]: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.primary_assembly.annotation.gtf.gz

[GENCODE (Mouse)]: https://www.gencodegenes.org/mouse/
[gencode.vM33.primary_assembly.annotation.gtf]: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M33/gencode.vM33.primary_assembly.annotation.gtf.gz

---

### Lattice commentary

@jahilton wrote:

**Goal:** Identify the factors that will inform the timing of a gene annotation version bump in the CELLxGENE schema and the procedures to do so.

**Context/Problem**: Currently, the CELLxGENE schema only accepts feature identifiers that are present in GENCODE v38 (human, release 5/2021) or vM27 (mouse, released 5/2021), in addition to SARS-CoV-2 genes and spike-ins. See [Reference](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#required-gene-annotations).

In order to submit data processed using reference versions more recent than v38/vM27 to CELLxGENE, it would require removing data from features which are present in the most recent annotation but weren’t in 5/2021. This means losing data on what are thought to be valid genomic features based on the current best knowledge of the genome.

To our knowledge, no data submitted to CELLxGENE to-date have used reference versions more recent than v38/vM27, but when it happens, it would be preferable to have the reference versions bumped or be able to do so quickly, rather than lose meaningful data.

A gene annotation version bump would require each Dataset in the corpus to have features removed from it - those that were in v38/vM27 annotations but no longer present in the versions that the schema updates to. Currently, this sort of migration entails the download, update, resubmission, and re-Publish of each Dataset.

**Additional Information**: CellRanger is a commonly-used alignment tool for data submitted to CELLxGENE, and it provides pre-built references that are often used. Since 7/2020, the default pre-built references provided are v32/vM23. See [Reference](https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build).

As of November 4, 2022, the most recent GENCODE versions are [v42 (human)](https://www.gencodegenes.org/human/releases.html) and vM31 (mouse), each released [10/2022](https://www.gencodegenes.org/mouse/releases.html).

Per Angela Pisco, Tabula Sapiens has moved to GENCODE v41 & is planning a spring 2023 data release.

---

### Alternatives for Automation

[What is the best way to programmatically convert Ensembl ids from one release to other?](https://bioinformatics.stackexchange.com/questions/15573/what-is-the-best-way-to-programmatically-convert-ensembl-ids-from-one-release-to)

**Note**: This is not the preferred method for Lattice. See [Jason's comment below](https://github.com/chanzuckerberg/single-cell-curation/issues/386#issuecomment-1332727355).

**Comment by jahilton** [comment]
Is there a reason we wouldn't treat this like ontologies and get the most recent at the time of the schema bump? (Human currently at v42, mouse at M31)

>[What is the best way to programmatically convert Ensembl ids from one release to other?](https://bioinformatics.stackexchange.com/questions/15573/what-is-the-best-way-to-programmatically-convert-ensembl-ids-from-one-release-to)

Our curation practices have not been to "convert Ensembl ids" so I feel this would deviate from practices up til now. Instead, we just filter out features that aren't represented by an Ensembl id that is present in the pinned annotation.

**Comment by brianraymor** [comment]
> Is there a reason we wouldn't treat this like ontologies and get the most recent at the time of the schema bump? (Human currently at v42, mouse at M31)

@aopisco - is there a reason that you're not using GENCODE 42 which is the current reference?

**Comment by jahilton** [comment]
In case it's helpful, our standard procedure for filtering out deprecated genes - adapted from our [notebook w/ sample curation code](https://github.com/Lattice-Data/lattice-tools/blob/main/cellxgene_resources/curation_sample_code.ipynb)...
```
ref_files = [
    'genes_ercc.csv',
    'genes_homo_sapiens.csv',
    'genes_mus_musculus.csv',
    'genes_sars_cov_2.csv'
]

if not os.path.exists('genes_approved.csv'):
    ids = pd.DataFrame()
    for f in ref_files:
        df = pd.read_csv(f, names=['feature_id','symb','num','length'],dtype='str',index_col=False)
        ids = ids.append(df)
        os.remove(f)
    ids.to_csv('genes_approved.csv', index=False)

approved = pd.read_csv('genes_approved.csv',dtype='str')
```
```
var_to_keep = adata.var.index.tolist()
var_in_approved = adata.var.index[adata.var.index.isin(approved['feature_id'])].tolist()
var_to_keep = [e for e in var_to_keep if e in var_in_approved]
adata = adata[:, var_to_keep]
```
