### ISSUE TITLE
revise is_primary_data

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#391]
We are currently reviewing data overlap across the data corpus. As a result, we anticipate revising is_primary_data for some Datasets. We'll update this ticket once the specifics are known.

**Comment by jahilton** [comment]
Review is complete
Patches are complete with 1 exception

**Comment by jahilton** [comment]
additionally, [a summary write-up](https://docs.google.com/document/d/1TxcO1IeQqeGjp4W9HtH1zmVKkxtf1pTL_ysexpUg2Xk/edit#heading=h.52yp3vnp1fiw) of the results from this review

**Comment by brianraymor** [comment]
Great minds. I asked @jahilton earlier in the week. Still pending. If it continues beyond this week, Jason will update the progress.

**Comment by jahilton** [comment]
The only outstanding issue was to identify the overlap amongst these 3 Collections
[367d95c0-0eb0-4dae-8276-9407239421ee](https://cellxgene.cziscience.com/collections/367d95c0-0eb0-4dae-8276-9407239421ee) - Bakken et al
[283d65eb-dd53-496d-adb7-7570c7caa443](https://cellxgene.cziscience.com/collections/283d65eb-dd53-496d-adb7-7570c7caa443) - Siletti et al
[1ca90a2d-2943-483d-b678-b809bf464c30](https://cellxgene.cziscience.com/collections/1ca90a2d-2943-483d-b678-b809bf464c30) - SEA-AD

Kyle has helped wrangle this information.
✅ Bakken et al cells are all in Siletti et al, so Bakken et al Collection was revised so the human cells are now primary:False - 20,490 cells revised True-->False
✅ We have a list of cell IDs that overlap between Siletti et al & SEA-AD, revised the ones in SEA-AD to False during the associated revisions that accompanied the Whole Taxonomy dataset submission - 77,104 cells revised True-->False
