### ISSUE TITLE
Cannot validate large h5ad files because the entire X matrix is read into memory

### ISSUE THREAD

**Issue by danielsf** [chanzuckerberg/single-cell-curation#399]
## Motivation
This may just be a question (though, depending on the answer, it might be a feature request).

I'm a scientist at the Allen Institute for Brain Science. We have a single cell rnaseq dataset comprised of 4 million cells and 30 thousand genes. Stored as a sparse matrix in an h5ad file, this produces a 215 GB file. We would like to experiment with aligning our files with the cellxgene curation schema. However, running the validation tool is impossible. This line of code

https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/validate.py#L111-L113

means that the first thing the validation tool tries to do is read the full 215 GB X matrix into memory. I don't know the history of this choice. Is there no work around that will enable the h5ad to be read in with `backed='r'`?

**Comment by bkmartinjr** [comment]
Hi @danielsf - this sounds fantastic! I have also been experimenting with very large datasets. The `backed` feature solves some issues, but is not a panacea if the X data is needed (the validator currently requires part of X, to perform a spot validation). Could you share a bit more info to help us identify possible paths forward?

1. What is a reasonable memory budget in your computing environment? In other words, what is the available RAM on the machine you are running the validator?
2. Is your goal submission of the dataset to our CELLxGENE portal, or just to explore other uses of the validator?  If other, would you be open to sharing your goal?

Thanks!

**Comment by danielsf** [comment]
Hi @bkmartinjr 

1) It would be nice if I could run this on a machine with 64 GB of memory. I could come by a 128 GB machine if I needed to, though.

2) We're still very much in the exploratory phase. At this point, we have this dataset, we want *some* tool to validate it, and we thought maybe we could leverage pre-existing tools. Whether or not the data ultimately gets submitted to CELLxGENE is still an open question (though the answer is not "no"). Sorry to be so vague.

Is there anyway to use anndata's chunking mechanism to do that spot check? That might limit the memory requirements.

**Comment by bkmartinjr** [comment]
There are definitely some possible avenues to reducing memory footprint (possibly at the cost of time). I will do a bit of investigation and see what turns up.  I don't think chunking will help per se (if you look at how it is implemented, it just uses the standard indexer on X).

One more question: what is the format / type of your X matrix?  CSR or something else?

**Comment by bkmartinjr** [comment]
@danielsf - I have a PR & branch #400 which is an attempt to resolve this issue. It has not yet been reviewed, and I don't know if or when we will release it.  I have tested it on much larger datasets than yours, on a 64GiB machine, and it worked for me. If you are comfortable testing from a source build, this should unblock you. We would also greatly appreciate hearing back if this resolved your issue. If you need any assistance with installing from source, drop me an email or Slack DM in the CZI Science slack workspace.

**Comment by brianraymor** [comment]
> Whether or not the data ultimately gets submitted to CELLxGENE is still an open question (though the answer is not "no"). Sorry to be so vague.

@danielsf - I'd note that @jahilton and I have also been collaborating with Kyle Travaglini related to [Large dataset handling discovery](https://github.com/chanzuckerberg/single-cell-data-portal/issues/3607). Currently, _CELLxGENE Discover_ has the following limitations based on dataset characteristics:

* Datasets larger than 30GB cannot be uploaded. 
* Datasets with more than 2 million cells cannot be explored in the _CELLxGENE DIscover_ visualization.

**Comment by brianraymor** [comment]
@danielsf - any thoughts on @bkmartinjr's:

> If you are comfortable testing from a source build, this should unblock you. We would also greatly appreciate hearing back if this resolved your issue. If you need any assistance with installing from source, drop me an email or Slack DM in the CZI Science slack workspace.

**Comment by danielsf** [comment]
I'm sorry this fell off my radar.

I have verified that I can now run our massive h5ad files through the validator. They fail validation, but that's my problem. Thank you.

**Comment by brianraymor** [comment]
We appreciate the update @danielsf ...
