### ISSUE TITLE
Mine the single cell portal for datasets

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#4]
The [Broad Single Cell Portal](https://singlecell.broadinstitute.org/single_cell) has at least 4 colon datasets in it that were not in our list. Likely there are many more. 

* Decide on a search strategy
* Mine the Single Cell Portal for datasets.

**Comment by brianraymor** [comment]
@ambrosejcarr - can this be moved to the data roadmap and closed?

**Comment by ambrosejcarr** [comment]
Yes. I think we have sufficient coverage of past datasets through our curation partners and prospective datasets via monitoring of biorxiv. Closing.
