### ISSUE TITLE
Assess impact of updating HsapDv and MmusDv

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#401]
# Design

**In Progress**

See [Review impact of HsapDv and MMusDV updates to development stage filter](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6539)

# Historical Context

We must assess the impact of the three years of ontologyevolution for the schema (and subsequent re-curation) and CELLxGENE _experiences_ such as the `Development Stages` filters in the Discover UX.

**September 7 2023**: _There is now a release tag shared across all development stage ontologies. See https://github.com/obophenotype/developmental-stage-ontologies/releases/tag/v2023-08-18_. 

**July 15 2023**: _Moving to Schema 5 due to a lack of progress in tagged HsapDv and MmusDv releases_. 

HsapDv and MmusDv are being updated, but there have been no official releases since 2020. 

CELLxGENE dataset schema requires:

| Ontology | OBO Prefix | Release | Download |
|:--|:--|:--|:--|
| [Human Developmental Stages] |  HsapDv | 2020-03-10 | [hsapdv.owl] |
| [Mouse Developmental Stages]| MmusDv | 2020-03-10 | [mmusdv.owl] |
| | | | |

[Human Developmental Stages]: http://obofoundry.org/ontology/hsapdv.html
[hsapdv.owl]: http://purl.obolibrary.org/obo/hsapdv.owl

[Mouse Developmental Stages]: http://obofoundry.org/ontology/mmusdv.html
[mmusdv.owl]: http://purl.obolibrary.org/obo/mmusdv.owl

`2020-03-10` is the same version available on [EBI OLS](https://www.ebi.ac.uk/ols/ontologies/hsapdv).

@jahilton noted a recent [response](https://github.com/obophenotype/developmental-stage-ontologies/issues/83#issuecomment-1438271254) to a Lattice inquiry indicating that a valid term in the 2020 release is now obsolete.

There are ongoing updates in https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/hsapdv but it does not seem to follow the regular release cadence of other ontologies. 

---

**Comment by jahilton** [comment]
Reached out to Frédéric Bastian & got a quick response...

- Confirmed that the latest versions live here: 
  - https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/hsapdv/
  - https://github.com/obophenotype/developmental-stage-ontologies/tree/master/src/mmusdv/
- Was surprised that purl does not link to the latest version & is going to contact OBO Foundry
- Noted that a formal release is complicated due to the repo hosting ~20 ontologies (dev stages of various organisms). They are currently exploring splitting each ontology into its own repo.

**Comment by jahilton** [comment]
Looking at just the HsapDv updates - did a [comparison here](https://docs.google.com/spreadsheets/d/1bELrjC18WH7wVyxlfKPvWjvUKKqy7y4iFav9ddNooAg/edit#gid=0)
Some deprecated terms have terms available with slightly larger ranges, making them easy migrations, but other deprecated terms would need to be reinvestigated or they'd be migrated to a much larger range.

**Comment by brianraymor** [comment]
Related [note](https://czi-sci.slack.com/archives/C06AVGFV222/p1705516985673359?thread_ts=1705514733.452099&cid=C06AVGFV222) on UX filtering hierarchy from @jahilton:

While I’m looking at it, I’ll even toss out a proposal for filters after the bump…
(taking in to account the deprecated terms and several current terms with 0s in our data for very granular terms)

* prenatal stage [HsapDv:0000045]
  * embryonic stage [HsapDv:0000002]
  * fetal stage [HsapDv:0000037]
* postnatal stage [HsapDv:0010000]
  * pediatric stage (0-15y) [HsapDv:0000264]
    * newborn stage (0-28d) [HsapDv:0000262]
    * infant stage (28d-1y) [HsapDv:0000261]
    * child stage (1-5y) [HsapDv:0000265]
    * juvenile stage (5-15y) [HsapDv:0000271]
* adult stage (15y+) [HsapDv:0000258]
  * young adult stage (15-40y) [HsapDv:0000266]
  * middle aged stage (40-60y) [HsapDv:0000267]
  * late adult stage (60y+) [HsapDv:0000227]
--------------
* prenatal [MmusDv:0000042]
  * embryonic [MmusDv:0000002]
  * fetal [MmusDv:0000031]
* postnatal stage [MmusDv:0000092]
  * immature (0-6w) [MmusDv:0000043]
  * mature (6w+) [MmusDv:0000110]
    * prime adult (6w-18m) [MmusDv:0000136]
    * young adult (6w-10m) [MmusDv:0000153]
    * middle aged (10-18m) [MmusDv:0000135]
  * late adult (18m+) [MmusDv:0000134]

**Comment by jahilton** [comment]
We have started organizing the data in the corpus that are using now-deprecated terms
On [the lattice/dev-ont-migration branch](https://github.com/chanzuckerberg/single-cell-curation/tree/lattice/dev-ont-migration/cellxgene_schema_cli/cellxgene_schema) there are 2 files:

- _automigrate_terms.json_ - a deprecated-to-new term mapping for the terms that we feel can be automigrated (the new term range includes the full deprecated term range and the range expands minimally as to not justify full re-curation)
- _donor_updates.json_ - per Collection per donor_id mapping of new terms. We will continue to add to this as we dig through existing corpus and as new submissions come in

When the time comes, migrate.py should be able to read in the metadata from these
Will update here once we have addressed existing metadata

**Comment by jahilton** [comment]
We have assessed all existing metadata in CELLxGENE - private & public and annotated the donors with deprecated dev_stage terms to updated dev_stage terms. We'll soon be pushing those mappings to the files in the branch noted above.
We have also added a step in the curation QA to check for newly submitted donors that will need similar mapping.

**Comment by brianraymor** [comment]
Incorporated into #884 for a _cleaner copy_.
