### ISSUE TITLE
Add genome assembly version to cell metadata

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#402]
It was recently brought up to my attention that including the **genome assembly used during mapping** (e.g. GRCh38.XXX) as cell metadata would be valuable. 

We need to consider if this is a common need from the community that we would want to fulfill. I believe it is a relatively easy lift from the curation perspective and it may provide valuable batch information to users.

Please proceed as follows:

1. Assess the impact that the addition of this field brings to the community. cc @BAevermann @jahilton 
2. Provide an estimate on the reach of such addition. cc @BAevermann 
3. Decide on including it in the schema v4.0, or a future version, or just put on hold for the time being.  

cc @brianraymor

**Comment by BAevermann** [comment]
Can you provide more information on #2 specifically what how "reach" in this context is measured? Thanks!

**Comment by jahilton** [comment]
I'm interested in specifically why it would be valuable and what the "XXX" represents in "GRCh38.XXX"

**Comment by pablo-gar** [comment]
> Can you provide more information on https://github.com/chanzuckerberg/single-cell-curation/issues/2 specifically what how "reach" in this context is measured?

@BAevermann, I was hoping for an informed guess on the percentage of users that would _benefit_ from this information. For example, I'd say that supension_type likely benefit 90% of users.

> I'm interested in specifically why it would be valuable and what the "XXX" represents in "GRCh38.XXX"
@jahilton The _minor_ version number

GRCh38.p14 (current)
GRCh38.p13
GRCh38.p12
...

**Comment by brianraymor** [comment]
>  I was hoping for an informed guess on the percentage of users that would benefit from this information

I'm not too keen on SWAG approaches because then it's easy to make a theoretical case for any new field. That has not worked well in the past based on recent deprecations. I'd prefer to have some concrete users and use cases (like Malte and integration workshops for suspension_type). 

We need to understand what "valuable" means and how the field will be used.

**Comment by jahilton** [comment]
If reference information is being explored, I would suggest expanding the scope beyond the proposed assembly version. The information in order of general resolution:

- Assembly (hg19, GRCh38, mm10)
- Assembly version (GRCh38.p13)
- Annotation version (Ensembl/GENCODE/RefSeq version)
  - This is more likely to be readily available than the patch version and a curator or submitter is probably using the annotation version to look up which patch version is used in that annotation reference. And it is more specific than the patch version (GRCh38.p13 was used for more than 10 different GENCODE versions)
  - n/a for non-expression assays

Any of them will hit issues when there's a custom reference used

**Comment by brianraymor** [comment]
Per today's triage, closing until there is further information about the user value for such an addition.
