### ISSUE TITLE
Add schema_reference

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#411]
# Design

## `uns` (Dataset Metadata)

...

When a dataset is uploaded, CELLxGENE Discover MUST automatically set the URL to the schema reference for the `schema_version`. 

Curators MUST NOT annotate the following column.

### schema_reference

<table><tbody>
    <tr>
      <th>Key</th>
      <td>schema_reference</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          This MUST be the permanent URL to the schema reference for the <code>schema_version</code>.
        </td>
    </tr>
</tbody></table>
<br>

---

## Appendix A. Changelog

schema v4.0.0

* uns (Dataset metadata)
  * Added `schema_reference`

---

# Context

See [**single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1678900108341319).

Once a dataset has been downloaded from CELLxGENE Discover, how _to be clear [about] where the file originated - try to answer “what is this schema_version:3.0.0 I see in this file - I’m at the HCA Portal and don’t see any notion of this schema version?”_

@jahilton writes:

Additional use cases...

- I have downloaded the .h5ad and would like to know where to find raw counts
- I have downloaded the .rds and would like to know where to find raw counts
- I am viewing the cxg and would like to know if the raw counts will be in a downloaded file of this dataset
- I have downloaded the .h5ad and would like to know how the `assay` values were standardized
- I have downloaded the .rds and would like to know how the `assay` values were standardized
- I am viewing the cxg and would like to know how the `assay` values were standardized

---

**Comment by jahilton** [comment]
Additional use cases...

- I have downloaded the .h5ad and would like to know where to find raw counts
- I have downloaded the .rds and would like to know where to find raw counts
- I am viewing the cxg and would like to know if the raw counts will be in a downloaded file of this dataset
- I have downloaded the .h5ad and would like to know how the `assay` values were standardized
- I have downloaded the .rds and would like to know how the `assay` values were standardized
- I am viewing the cxg and would like to know how the `assay` values were standardized

**Comment by brianraymor** [comment]
Addressed in #566
