### ISSUE TITLE
cellxgene-schema must validate that raw matrix does not have more genes than raw var.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#418]
## Motivation

See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1680714440373239).

Catching datasets that will not succeed in the Discover submission pipeline before submission. This saves compute resources and speeds the job of curators to validate and submit new data.

It's possible to submit a dataset that will fail seurat conversion because the raw matrix has more genes than raw var. Here is [an example datasets in s3](https://s3.console.aws.amazon.com/s3/object/kuni-tmp?region=us-west-2&prefix=fail_bc_raw_matrix_has_more+genes_than_raw_var.h5ad).

Here is a screenshot of what is in var. 
![screenshot_2023-04-05_at_11.00.49_am.png](https://images.zenhubusercontent.com/5a4d3418a016c5b034bbeac9/38e46943-1cbd-4733-8bb6-aedc938a1dff)
The adata.raw.var is not matching up with adata.raw.X

## Definition of Done

The example datasets should fail validation.

## Tasks

- [ ] Add a check to validation, that `adata.raw.var` matches the same dimension as `adata.raw.X`
- [ ] Add a test for this error condition.

**Comment by nayib-jose-gloria** [comment]
@jahilton / @corismall ready for QA! Same instructions to pull HEAD of main as other tickets

**Comment by jahilton** [comment]
This is still passing validation
See the bottom setup & test in [this notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/418_raw_matrix_vs_var.ipynb) for the example which has 22356 features in raw.X and only 22000 features in raw.var

**Comment by danieljhegeman** [comment]
@jahilton ok thanks for flagging. I'll investigate.

**Comment by danieljhegeman** [comment]
@jahilton can you share (a link to) the specific datafile you're using?

**Comment by danieljhegeman** [comment]
@jahilton ah, to be clear, the datafile _should_ still pass validation (right @nayib-jose-gloria ?). It simply should give the _warning_ that it will fail Seurat conversion if it is submitted.

**Comment by danieljhegeman** [comment]
Ok. So in those cases we want to fail validation altogether, but in other cases such as where the file is simply too large for Seurat conversion, we want to continue only warn the user.

Thanks for pointing me to the detail @brianraymor

**Comment by nayib-jose-gloria** [comment]
@jahilton did you re-run the `pip install git+https://github.com/chanzuckerberg/single-cell-curation/@main#subdirectory=cellxgene_schema_cli` command right before running this script? Only asking because I would've expected to see the warning at least if we were pointing at head of main--if you did and are not seeing the warning, we'll need to dig to find where another change is needed

**Comment by jahilton** [comment]
@nayib-jose-gloria correct. I ran the pip install, did not see even a warning, and is_valid=True

**Comment by jahilton** [comment]
The notebook used to test is linked above, and that reads in `valid.h5ad` which is found on the same branch as the notebook ([here](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/valid.h5ad)).

**Comment by danieljhegeman** [comment]
> The notebook used to test is linked above, and that reads in `valid.h5ad` which is found on the same branch as the notebook ([here](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/valid.h5ad)).

@jahilton which _invalid_ Dataset did you use?

**Comment by jahilton** [comment]
@danieljhegeman you'll see the notebook also includes some reporting to assess whether our manipulation was successful

> Shape of raw: (2000, 22356)
Number of features in var: 22000

...means the raw matrix has 22356 features but the var dataframe has 22000 features

**Comment by danieljhegeman** [comment]
> @danieljhegeman you'll see the notebook also includes some reporting to assess whether our manipulation was successful
> 
> > Shape of raw: (2000, 22356)
> > Number of features in var: 22000
> 
> ...means the raw matrix has 22356 features but the var dataframe has 22000 features

Ok... hm. I tried to reproduce and did not get those outputs. I may go back and try again, but regardless, we got the error we expected with Jenny's original dataset that was mismatched on these dimensions.

**Comment by jahilton** [comment]
It now fails when expected.

Current error message...
>ERROR: This dataset has a mismatch between 1) the number of variables in the raw matrix and 2) the number of raw var key-indexed variables. These counts must be identical.

I suggest updating to...
>ERROR: This dataset has a mismatch between 1) the number of features in the raw.X and 2) the number of features in raw.var. These counts must be identical.

specifying raw.X & raw.var instead of "raw matrix" removes opportunity to confuse this for "raw counts" which may not be in the raw.X slot
specifying features instead of "variables" again removes ambiguity

**Comment by jahilton** [comment]
LGTM!
