### ISSUE TITLE
Call validation from code - not CL

### ISSUE THREAD

**Issue by dosumis** [chanzuckerberg/single-cell-curation#426]
We would like to incorporate testing of schema compliance into python libraries that we are developing (initial use-case: ontology enrichment library).  We would love to be able to use your code to test this, but, AFAIK, there is no python package that we could import in order to achieve this. Such a python package could support adoption of and compliance with your schema in the wider developing ecosystem of single cell transcriptomics tools and platforms.

**Comment by brianraymor** [comment]
The schema validator - `cellxgene-schema` - is released on [pypi](https://pypi.org/project/cellxgene-schema/). Does this address your use cases or are there more specific requirements that can be shared ?

**Comment by pablo-gar** [comment]
Also see the Usage section in the the repo readme:

https://github.com/chanzuckerberg/single-cell-curation#usage

**Comment by dosumis** [comment]
I would like to call from code rather than run as a command line application.  Is this possible with the PyPi package?  If so, is there some doc or a NB showing how to do this?
