### ISSUE TITLE
Validator should check that embeddings in `AnnData.obsm` are numpy arrays 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#43]
Cell embeddings are stored in `AnnData.obsm` which is a dictionary, for each key it stores a two or higher-dimensional `ndarray` (numpy array) of length `AnnData.n_obs`.

If something other than a numpy array is stored in the `AnnData.obsm` (use case has been pandas data frame), the conversion to loom and Seurat will fail when processing an upload in the portal, moreover the conversion error message in the logs is vague. 

While this is an AnnData requirement (see [here](https://anndata.readthedocs.io/en/latest/anndata.AnnData.obsm.html)),  it is not checked nor enforced. 

**Solution**
- `cellxgene-schema apply` tries to transform elements of `AnnData.obsm` to numpy arrays if they aren't already numpy arrays.
- `cellxgene-schema validate` raises an error and appropriate message if elements of `AnnData.obsm` are not numpy arrays.

**Comment by brianraymor** [comment]
This requirement should also be documented.

**Comment by MaximilianLombardo** [comment]
requirement documented here: https://github.com/chanzuckerberg/single-cell-curation/blob/tutorial-review/docs/curation-review-tut.md#required-data-and-anndata-structure

In "Table: Required data and `AnnData` object structure"

**Comment by MaximilianLombardo** [comment]
Out of curiosity, why would we not perform the conversion (i.e. `pands_df.to_numpy()`) to a required datatype upon upload?

**Comment by brianraymor** [comment]
RE this [comment](https://github.com/chanzuckerberg/single-cell-curation/issues/43#issuecomment-814539453), I believe this should be documented in the Anndata encoding document, @ambrosejcarr.
