### ISSUE TITLE
Pre-migration bump updates

### ISSUE THREAD

**Issue by jychien** [chanzuckerberg/single-cell-curation#431]
SOD2 was [ENSG00000112096](https://jul2022.archive.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000112096;r=6:159669069-159762529) in v38 and is [ENSG00000291237](https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000291237;r=6:159669069-159762529) in v43. The gene location and transcripts were unchanged between the two releases. Ensembl's response to why there was an update in identifier:

> Thank you for your patience while we were looking into your query. The original stable ID was unintentionally updated during the manual annotation of the gene, which seems to have been caused by a bug in our annotation tool. This change went unnoticed until it had made it into the database in release 108 and it was too late to be reverted. Once it had been released in Ensembl 108, we decided to keep the stable ID as it could have cause more confusion if it was changed back to the original stable ID. We are very sorry about this and I hope that it does not cause too much of an inconvenience in your pipelines. If you have any other questions please do not hesitate to get back in touch.

In order to manually maintain persistency of SOD2, `ENSG00000112096` needs to be updated to `ENSG00000291237` in the data corpus BEFORE the application of Lattice algorithm for gene migration. I've asked Ensembl if additional genes have been affected.

_[Dan's comment on immediately-above section]_ The update should be performed _as part_ of the migration, and _not before_. If it is done before then we will have instantiated a (previous) version which has the wrong mapping.

**Comment by metakuni** [comment]
jychien writes:
>  [10:32](https://czi-sci.slack.com/archives/C06AVGFV222/p1706121134139089)
FYI, since [431](https://github.com/chanzuckerberg/single-cell-curation/issues/431) is redundant with [572](https://github.com/chanzuckerberg/single-cell-curation/issues/572), I am going to close 431.
