### ISSUE TITLE
The instructions for get_dataset_version.ipynb#Download-Dataset-Assets are a sadness

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#433]
The instructions for the **Download Dataset Assets** cell state:

```
# Uncomment code below to locally download all dataset version assets

# download_assets([dataset_version], log_version_id=True)
```

When the line is uncommented, it then fails because `download_assets` is commented out in the **Import Dependencies** cell. 

```
from src.dataset import (
    # download_assets,
    get_dataset,
)
```

I recommended uncommenting both. Was there a rationale to not demonstrate downloads by default?

**Comment by danieljhegeman** [comment]
Removing comments so that the assets download when the notebook is run... but also reverting sample id to a fake uuid, in keeping with all other notebooks.
