### ISSUE TITLE
Investigate why this dataset requires so much memory and time to process

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#435]
## Motivation
One of the parameters we use to gate keep datasets from the cellxgene data corpus is the size of the file on disk. At the time of writing this, the max size supported was 50GB. It was assumed that all validated datasets smaller than 50GB will pass through the datasets submission pipeline without issue. The Neuron dataset bellow which is smaller than the size limit is an exception to that rule. It fails during cxg generation because out of memory. Processing the datasets also takes longer than most and exceeded the 10 hour processing timeout. 

## Goal
Investigate the Neuron dataset and determine what characteristic cause it to required so much memory and time to process. Determine if there is a way to detect datasets with those characteristics that way they can be handled accordingly. Handling might include blocking the submission, or recommending modifications to the dataset.
 
### [Whole Taxonomy](https://s3.console.aws.amazon.com/s3/object/kuni-tmp?region=us-west-2&prefix=whole_taxonomy.h5ad) 
This dataset is larger and has no problem processing in the datasets submission pipeline.
- Size on disk (~47 GB)
- X
  - 1378211 x 36517 (50,328,131,087)
  - stored as sparse csr
  - 7,618,135,711 non-zero elements (84.9% sparse)
- raw.X
  - 1378211 x 36517 (50,328,131,087)
  - stored as sparse csr
  - 7,618,135,711 non-zero elements (84.9% sparse)

### [Neurons](https://s3.console.aws.amazon.com/s3/object/kuni-tmp?region=us-west-2&prefix=harmony_A_revised_revised_.h5ad)
This dataset is smaller but required significantly more memory than the whole taxonomy dataset.
- size on disk (~31 GB)
- X
  - 2480956 x 59357 (147,262,105,292)
  - stored as sparse csr
  - 14,131,422,385 non-zero elements (90.4% sparse)
- S3 

## Definition of Done

- Determine why the dataset requires so much memory and time to process.
- Determine if improvement to the validator could detect datasets like this

**Comment by metakuni** [comment]
@Bento007, assigning to you since you have the most context. Perhaps you could spend some time on this during your next on-call next week?

**Comment by metakuni** [comment]
To be continued on @Bento007 's next on-call shift in July...

**Comment by brianraymor** [comment]
@metakuni - can this be closed or do you expect to invest more time in discovery?

**Comment by metakuni** [comment]
Closing this issue. We'll open a new one when necessary or when we get guidance on dataset size growth targets so that we can focus our efforts.
