### ISSUE TITLE
Add splicing information

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#479]
@pablo-gar commented on [Fri Mar 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291)

Original contributor Zach DeBruine @zdebruine 

## Description

To have splicing information/status in the Cell Census. Specifically, for a given gene (or transcript?) to be able to separate spliced counts vs unspliced counts

## Context

Splicing information is useful for modeling biological behavior and in particular [trajectory analysis](http://bioconductor.org/books/3.14/OSCA.advanced/trajectory-analysis.html), e.g. pseudotime 

## Relevance

It currently blocks certain analysis as the aforementioned trajectory analysis.

See also comment below by @zdebruine 

## Ideal behavior 

See comment below by @zdebruine 

---

@pablo-gar commented on [Fri Mar 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1483610767)

Zach, can you please add any other information as comment for the Context, Relevance, an Ideal behavior sections?

---

@zdebruine commented on [Fri Mar 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1483656974)

Certainly! It would be great to include unspliced transcript expression alongside spliced transcript expression, as it can provide valuable information in single-cell sequencing assays. 

**Context and Relevance:**  Here are some reasons why unspliced transcript expression is important (and I'm not an expert per se on this):

- Unspliced transcript expression can be used to map cellular differentiation trajectories in real-time, rather than relying on pseudotime (as seen in scVelo/velocyto).
- Including unspliced transcript expression in dimension reduction analysis can provide better sensitivity and more powerful results, as it effectively doubles the amount of information available. I would be happy to provide an example of this in a post if desired.
- Excluding unspliced transcript expression means throwing away up to ~40% of the mapped sequencing reads (based on data I have analyzed from developing mouse embryos), which contains useful information.
- The ratio of unspliced to spliced transcript expression is a measure of cellular transcriptional activity, and can be used to distinguish between active and quiescent cells.
- The inclusion of unspliced transcript expression can support research that may be underpowered due to small sample sizes, as there are currently no large datasets available (to my knowledge) that provide both spliced and unspliced transcript count matrices.

**Ideal Behavior:**  Simply add rows to the matrix for unspliced features.  You may add feature metadata so that it is easy to filter just spliced, if desired, or simply append "_unspliced" to the feature name, however you like.

---

@pablo-gar commented on [Fri Mar 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1483678450)

Thanks @zdebruine this is great! 

---

@brianraymor commented on [Wed May 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1561721019)

@pablo-gar to review with @BAevermann and Lattice. 

---

@BAevermann commented on [Wed May 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1561731707)

I am confused, are we proposing: 
1. Adding support for differentially spliced transcripts
2. Adding support for Unspliced transcripts only, i.e., whole gene (including all introns)
Thanks!

---

@zdebruine commented on [Wed May 24 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1561751308)

@BAevermann The second item.  There is already some support for the first point, and further support would be challenging given the experimental/unstandardized software in this domain and limited sequencing depth in most assays.  But with advances in long-read deep sequencing, it may be worth revisiting differentially spliced transcripts again in time.

---

@BAevermann commented on [Fri May 26 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1564896809)

Thanks for the clarification @zdebruine!
This may be a daft question, but how does the resulting expression matrices look different between "unspliced" counts to the current "gene" counts (CELLxGENE schema requires Ensemble gene IDs). I am just curious how we can determine if the gene concept used contains all introns/exons or omits portions. 

Thanks!

b.

---

@zdebruine commented on [Fri May 26 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1565223285)

@BAevermann I am not sure.  This may be more of a question for the authors of velocyto or scVelo who have more experience with various builds.  I have only used processed data from other authors and found it to significantly improve the power of dimension reduction, hence the request.

---

@BAevermann commented on [Mon May 29 2023](https://github.com/chanzuckerberg/cellxgene-census/issues/291#issuecomment-1567740583)

Thanks @zdebruine! I will look into velocyto and scVelo to get a better understanding about how they invoke annotation in their data workflow...

**Comment by jychien** [comment]
10x CellRanger now defaults to including intronic reads: https://support.10xgenomics.com/docs/intron-mode-rec. So, I am assuming most of the newly aligned data does include unspliced transcripts. Most of the single nuclei data that goes through Lattice include intronic reads, and we capture this with a boolean field `intronic_reads_counted`, defined as: “True if reads mapped to intronic regions were used for gene quantifications.”
We do have one dataset where contributors ran VeloCyto for their gene quantification, but they merged the unspliced and spliced counts together as their raw counts. If contributors were interested, though, they could provide the either counts as additional layers in adata.layers.

**Comment by zdebruine** [comment]
@jychien You are correct, but I am not sure why 10x does not provide intronic and exonic reads separately.  After all, they provide different information.

I gather that the ability to support this within CZI resources would require contributors to provide these counts matrices separately.  As you say, _perhaps contributors could at least be encouraged to provide the spliced and unspliced counts separately in adata.layers?_

**Comment by BAevermann** [comment]
Hey @zdebruine! 
Sorry about the delay. The summer is always chaotic with work and personal travel.  
You are correct that this data contributors would need to provide these layers. Do you have an example matrix or could you point me to a publication that used splicing in this way? 
Thanks!
Brian A

**Comment by jahilton** [comment]
Got a similar request from Luca Pinello to support this [Data Insights Project](https://chanzuckerberg.com/science/programs-resources/single-cell-biology/data-insights/a-probabilistic-framework-for-rna-velocity-statistical-tests-using-pyro/)

A next-best option may be to make it easier for CxG users to identify raw sequence reads that correspond to CxG obs, so that they can realign.

**Comment by zdebruine** [comment]
It would be very exciting to have easier access to raw sequence reads.  Just linking this to `soma_joinid` would already be very helpful, and somehow integrating into the CellCensus API would make it very easy to gather data for these large transformer models.

**Comment by brianraymor** [comment]
Per November 27 triage, there was consensus to close this issue. @jahilton may open another more general issue related to his suggestion:

> A next-best option may be to make it easier for CxG users to identify raw sequence reads that correspond to CxG obs, so that they can realign.
