### ISSUE TITLE
Potential schema entry: Post-mortem interval

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#48]
The time that elapses between sample extraction and processing (post-mortem interval) was a highly mentioned sample quality metadata. Anecdotally, it often correlates with poor sample quality and scientists may use it as a filter when selecting data to reuse. 

When sufficient data are accumulated, it would be valuable to *test* the extent to which post-mortem interval is predictable from commonly computed QC metrics, stress, and cell death pathway expression. If this metadata is predictable then we can continue to disregard it.

**Comment by brianraymor** [comment]
@ambrosejcarr - closing since there's been no further action in the last year. Please re-open if you disagree. I'd prefer to create issues as the need arises.
