### ISSUE TITLE
Separate schema and encoding

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell-curation#50]
Description: cellxgene maintains one schema, one ingestion format (AnnData) and _three_ download formats. The team decided to create three classes of documents to support its data model. 

1. The Schema, which should be unopinionated about implementation
2. The encodings, which should describe AnnData (ingestion and download) and Seurat v3 (download)
3. A curation tutorial, which describes how to generate an AnnData file that adheres to our schema, validate it, and upload it. 

The work will be broken down into two tasks: 

1. Separating the schema and AnnData encoding into two documents (currently there is AnnData logic in the schema)
2. Writing a separate document that describes the Seurat encoding.

This issue tracks task 1, separation of schema and encoding.

**Comment by brianraymor** [comment]
Adopted AnnData as the canonical format and merged encoding and schema in v2.0.0.
