### ISSUE TITLE
Potential annotation error: Tabula Sapiens hepatocytes annotated as heart cells

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-curation#509]
Looks like Tabula Sapiens is defining 1.1k heart cells as hepatocytes. See this in Gene Expression [here](https://cellxgene.cziscience.com/gene-expression?datasets=53d208b0-2cfd-4366-9866-c3c6114081bc&tissues=heart&genes=CPA3%2CFER%2CIL18R1%2CKIT%2CNTM%2CSLC24A3&ver=2). Thank you to Jonah for finding!

**Comment by niknak33** [comment]
In addition to this, another user pointed some errors they found:

I poked around at it and plugged in “Tabula Sapiens,” then tissue “heart” and genes “PAM and TNNT1.” Two issues.  First – hepatocytes show up under the heart and those cells are exclusively found in the liver.  Secondly, TNNT1 is exclusively and strongly expressed by cardiac muscle cells, but here it shows up strongest in hepatocytes. In the actual TS data, TNNT1 is correctly localized in cardiac muscle cells and slow skeletal muscle cells, while absent in hepatocytes.  So something is amiss.
![image.png](https://images.zenhubusercontent.com/6306898cc3fd3cfeeb1b7727/8d22b00e-1338-4299-a337-f4e4f474fd47)

**Comment by jahilton** [comment]
Do we know what they're referring to as "the actual TS data"?

**Comment by jahilton** [comment]
In response to the newer comment, TS team provided a more thorough answer
>there are on the order of 1-500 cells that were manually annotated as hepatocytes from the heart tissue. From there, automatic cell annotations were run on the un-annotated cells and some of them were therefore labelled as hepatocytes as well. However, I believe many of those cells upon closer inspection are not hepatocyte-like. We've edited these out in the update (not released yet), but basically only the cells with hepatocyte expression (Alb, for example) are likely to be actual contaminating cells (or some weird biological phenomenon that we can't explain/rule out).

Again, no action to take as the next data release will resolve it

**Comment by niknak33** [comment]
I am not sure, what they mean by actual TS data - I can ask them and get back to you.

**Comment by niknak33** [comment]
> In response to the newer comment, TS team provided a more thorough answer
> 
> > there are on the order of 1-500 cells that were manually annotated as hepatocytes from the heart tissue. From there, automatic cell annotations were run on the un-annotated cells and some of them were therefore labelled as hepatocytes as well. However, I believe many of those cells upon closer inspection are not hepatocyte-like. We've edited these out in the update (not released yet), but basically only the cells with hepatocyte expression (Alb, for example) are likely to be actual contaminating cells (or some weird biological phenomenon that we can't explain/rule out).
> 
> Again, no action to take as the next data release will resolve it

When is the next data release is scheduled for?

**Comment by jahilton** [comment]
>When is the next data release is scheduled for?

TBD

**Comment by brianraymor** [comment]
@jahilton - is there any update to share?

**Comment by jahilton** [comment]
no updates

**Comment by jahilton** [comment]
The contributors have approved the relabeling of these cells to 'native cell'
(they preferred this over cardiocyte because they do not look like heart cells. "Most likely these cells are not actual cells")

**Comment by jahilton** [comment]
Resolved

Updated cells that were cell_type:hepatocyte & tissue_in_publication:Heart to CL:0000003 - impacting 2 Datasets, Epithelial (`97a17473-e2b1-4f31-a544-44a60773e2dd`) & All cells (`53d208b0-2cfd-4366-9866-c3c6114081bc`)
& any cells that were cell_type:hepatocyte in the Heart Dataset (`e6a11140-2545-46bc-929e-da243eed2cae`) to CL:0000003
Also updated the tissue in the Heart Dataset (all were cardiac atrium but anatomical_information noted some as ventricle)
