### ISSUE TITLE
cellxgene-schema must validate tissue_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#514]
# Design

This also changes the validation and label application for `tissue_ontology_term_id` and `tissue`.

See [tissue_type](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#tissue_type).

### tissue_type

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue_type</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"tissue"</code>, <code>"organoid"</code>, or <code>"cell culture"</code>.
    </tr>
</tbody></table>
<br>

### tissue_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
   <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If <code>tissue_type</code> is <code>"tissue"</code> or <code>"organoid"</code>, this MUST be the most accurate child of <a href="https://www.ebi.ac.uk/ols4/ontologies/uberon/classes?obo_id=UBERON%3A0001062"><code>UBERON:0001062</code></a> for <i>anatomical entity</i>.<br><br> If <code>tissue_type</code> is <code>"cell culture"</code> this MUST follow the requirements for <code>cell_type_ontology_term_id<code>.</td>
     </tr>
</tbody></table>
<br>

### tissue

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be the human-readable name assigned to the value of <code>tissue_ontology_term_id</code>.
        </td>
    </tr>
</tbody></table>

**Comment by nayib-jose-gloria** [comment]
@jahilton / @corismall ready for testing!

implementation note: uses same logic as [this](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/517) issue to enforce CL term validation on tissue_ontology_term_id when 'tissue_type' is 'cell culture', so if there are any problems validating that ticket I'd expect to see them here as well.

**Comment by jahilton** [comment]
This passes when expected and fails when expected. [QA notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/514_tissue_type.ipynb)

When tissue_type is `organoid` or `tissue` and tissue_ontology_term_id is too broad (ex: `UBERON:0001062`), there seem to be excessive brackets around UBERON:0001062 in the error message (expect single quotes only like the first and 3rd instance within the mesage)...
>ERROR: 'UBERON:0001062' in 'tissue_ontology_term_id' is not a child term id of '[['UBERON:0001062']]'. When 'tissue_type' is 'tissue' or 'organoid', 'tissue_ontology_term_id' MUST be a child term id of 'UBERON:0001062' (anatomical entity).

**Comment by nayib-jose-gloria** [comment]
@jahilton fixed that error message if you want to double check it

**Comment by jahilton** [comment]
LGTM
