### ISSUE TITLE
cellxgene-schema must validate self_reported_ethnicity

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#515]
**Notes**: 

I recommend that this issue be addressed last when updating `cellxgene-schema` CLI. Its design may be simplified prior to Schema 4 delivery **IF** HANCESTRO is updated to address pending request:

1. The ontology is modeled to make it possible to identify HANCESTRO terms that are appropriate for the self reported use case. The ontologist is planning to ensure that _each term is tagged accordingly so we could infer 2 new parent classes to automatically give us a full list of geographic descriptors and of ethnicity descriptors._ Currently, CELLxGENE must assess the entire ontology and _cherry pick_ terms to block which increases the complexity of curation and validation. 

This design is based on HANCESTRO 2.8, but this issue was addressed in HANCESTRO 3.0:

1. [Preferred term label for HANCESTRO:0015](https://github.com/EBISPOT/ancestro/issues/36)

Also see [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1689288801992369?thread_ts=1686097986.283929&cid=C024HCSH9PT).

# Design

See [schema4](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#self_reported_ethnicity_ontology_term_id)

### self_reported_ethnicity_ontology_term_id

<table>
  <tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>
        categorical with <code>str</code> categories. If
        <code>organism_ontolology_term_id</code> is
        <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>,
        the value MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO
        terms in ascending lexical order or <code>"unknown"</code> if unavailable.<br><br>For example, if the terms are <code>"HANCESTRO:0014</code> and <code>HANCESTRO:0005"</code> then the value of <code>self_reported_ethnicity_ontology_term_id</code> MUST be <code>"HANCESTRO:0005,HANCESTRO:0014"</code>.<br><br>The following terms MUST NOT be used:<br /><br />
        <ul>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0002?lang=en"
              ><code>"HANCESTRO:0002"</code></a
            >
            for <i>regions</i> and its children
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0003?lang=en"
              ><code>"HANCESTRO:0003"</code></a
            >
            for <i>country</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0004?lang=en"
              ><code>"HANCESTRO:0004"</code></a
            >
            for <i>ancestry category</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0018?lang=en"
              ><code>"HANCESTRO:0018"</code></a
            >
            for <i>uncategorised population</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0290?lang=en"
              ><code>"HANCESTRO:0290"</code></a
            >
            for <i>genetically isolated population</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0304?lang=en"
              ><code>"HANCESTRO:0304"</code></a
            >
            for <i>ancestry status</i> and its children
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0323?lang=en"
              ><code>"HANCESTRO:0323"</code></a
            >
            for <i>Finnish founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0324?lang=en"
              ><code>"HANCESTRO:0324"</code></a
            >
            for <i>Dutch founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0551?lang=en"
              ><code>"HANCESTRO:0551"</code></a
            >
            for <i>genetically homogenous Irish</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0554?lang=en"
              ><code>"HANCESTRO:0554"</code></a
            >
            for <i>Silk Road founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0555?lang=en"
              ><code>"HANCESTRO:0555"</code></a
            >
            for <i>Arab Israeli founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0557?lang=en"
              ><code>"HANCESTRO:0557"</code></a
            >
            for <i>Costa Rican founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0558?lang=en"
              ><code>"HANCESTRO:0558"</code></a
            >
            for <i>French Canadian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0559?lang=en"
              ><code>"HANCESTRO:0559"</code></a
            >
            for <i>Italian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0560?lang=en"
              ><code>"HANCESTRO:0560"</code></a
            >
            for <i>Northern Finnish founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0561?lang=en"
              ><code>"HANCESTRO:0561"</code></a
            >
            for <i>Romanian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0564?lang=en"
              ><code>"HANCESTRO:0564"</code></a
            >
            for <i>Vis founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0565?lang=en"
              ><code>"HANCESTRO:0565"</code></a
            >
            for <i>Split founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0566?lang=en"
              ><code>"HANCESTRO:0566"</code></a
            >
            for <i>undefined ancestry population</i>
          </li>
          <li>
            The imported GEO term
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGEO_000000374?lang=en"
              ><code>"GEO:000000374"</code></a
            >
            for <i>continent</i> and its children:
            <ul>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0029?lang=en"
                  ><code>"HANCESTRO:0029"</code></a
                >
                for <i>Africa</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0030?lang=en"
                  ><code>"HANCESTRO:0030"</code></a
                >
                for <i>Asia</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0031?lang=en"
                  ><code>"HANCESTRO:0031"</code></a
                >
                for <i>Europe</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0032?lang=en"
                  ><code>"HANCESTRO:0032"</code></a
                >
                for <i>Oceania</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0033?lang=en"
                  ><code>"HANCESTRO:0033"</code></a
                >
                for <i>Latin America and the Caribbean</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0034?lang=en"
                  ><code>"HANCESTRO:0034"</code></a
                >
                for <i>Northern America</i>
              </li>
            </ul>
          </li>
        </ul>
        <br />Otherwise, for all other organisms the
        <code>str</code> value MUST be <code>"na"</code>.
      </td>
    </tr>
  </tbody>
</table>
<br />

---

### self_reported_ethnicity

<table><tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"na"</code> or <code>"unknown"</code> if set in <code>self_reported_ethnicity_ontology_term_id</code>; otherwise, this MUST be one or more comma-separated (with no leading or trailing spaces) human-readable names for the terms in <code>self_reported_ethnicity_ontology_term_id</code> in the same order.<br><br> For example, if the value of <code>self_reported_ethnicity_ontology_term_id</code> is <code>"HANCESTRO:0005,HANCESTRO:0014"</code> then the value of <code>self_reported_ethnicity</code> is <code>"European,Hispanic or Latin American"</code>.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by nayib-jose-gloria** [comment]
@jahilton ready for QA! FYI I noticed the [qa notebook ](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/515_self_reported_ethnicity.ipynb) is testing for 'na' as a valid term using NCBITaxon:9606 as the organism_ontology_term_id. The schema expects 'na' to only be valid for non-human organism term IDs, lmk if this is a mistake in the notebook or not the expected behavior

**Comment by jahilton** [comment]
Thanks @nayib-jose-gloria  (we tend to find things like that when actually running them). Pushed the run notebook (with some edits/additions) to our branch.
Everything behaves as expected.
But I think the error message for array values could be more direct (3rd test from the bottom), if possible. Something like `self_reported_ethnicity_ontology_term_id contains array values but MUST contain only string values` or whatever matches other similar 'type' errors elsewhere in the validator. Current error report...

> ERROR: '['HANCESTRO:0005' in 'self_reported_ethnicity_ontology_term_id' is not a valid ontology term id of 'HANCESTRO'. When 'organism_ontology_term_id' is 'NCBITaxon:9606' (Homo sapiens), self_reported_ethnicity_ontology_term_id MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO terms in ascending lexical order, or 'unknown' if unavailable. Cannot match any forbidden HANCESTRO terms listed in schema definition.
ERROR: 'HANCESTRO:0014']' in 'self_reported_ethnicity_ontology_term_id' is not a valid ontology term id of 'HANCESTRO'. When 'organism_ontology_term_id' is 'NCBITaxon:9606' (Homo sapiens), self_reported_ethnicity_ontology_term_id MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO terms in ascending lexical order, or 'unknown' if unavailable. Cannot match any forbidden HANCESTRO terms listed in schema definition.
ERROR: '['HANCESTRO:0005,HANCESTRO:0014']' in 'self_reported_ethnicity_ontology_term_id' is not in ascending lexical order. When 'organism_ontology_term_id' is 'NCBITaxon:9606' (Homo sapiens), self_reported_ethnicity_ontology_term_id MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO terms in ascending lexical order, or 'unknown' if unavailable. Cannot match any forbidden HANCESTRO terms listed in schema definition.

**Comment by nayib-jose-gloria** [comment]
@jahilton the QA notebook seems to be casting the array back to a string, which is what's leading to the weird error message. We can check for '[' or ']' to give a more bespoke error message, but it is technically a string, just one that looks like an array

**Comment by jahilton** [comment]
Thanks for catching that.
I'm unable to save an AnnData with the intended case for that cell.
So this is Good-to-Got
