### ISSUE TITLE
cellxgene-schema must annotate feature_length

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#516]
# Design

@pablo-gar writes:

This information is already calculated from the pinned Gene References and is readily available here `single-cell-curation/cellxgene_schema_cli/cellxgene_schema/ontology_files/` on the files `genes_[organism].csv.gz`

See [feature_length](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#feature_length). 

### feature_length

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_length</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
        <code>uint</code> number of base-pairs (bps). If the <code>feature_biotype</code> is <code>"gene"</code>, then the value is calculated by creating non-overlapping concatenated exons across all isoforms of the gene, and then adding up their length in base-pairs. This approach is modeled on the "length of merged exons of isoforms of a gene" from <a href="https://doi.org/10.1093/bioinformatics/btac561">GTFtools: a software package for analyzing various features of gene models.</a><br><br> If <code>feature_biotype</code> is NOT <code>"gene"</code> then the value MUST be set to 0.
      </td>
    </tr>
</tbody></table>

**Comment by nayib-jose-gloria** [comment]
@jahilton / @corismall ready for testing!

**Comment by jahilton** [comment]
good to go
[QA Notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/516_annotate_feature_length.ipynb)
