### ISSUE TITLE
cellxgene-schema must detect and fail new reserved names

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#519]
### *** This ticket is awaiting a rewrite from @brianraymor ***

**Reserved Names**. The names of metadata keys MUST NOT start with `__`. The names of the metadata keys specified by the schema are reserved and MUST be unique. For example, duplicate <code>feature_biotype</code> keys in AnnData <code>var</code> are not allowed. 

These new fields must be reserved.

* citation
* feature_length
* schema_reference
* ~~tissue_type~~

Copying @nayib-jose-gloria 's comment below for visibility:

> Note to engineers: feature_length, tissue_type, and schema_reference will be detected and validated as part of their individual tickets because of how our validation module is structured. This ticket should only add 'citation' to reserved names under 'uns', since it must be annotated outside of the add-labels function during DP upload.

**Comment by jahilton** [comment]
tissue_type is listed as a reserved field, but it is submittable (and required #514 ) so I don't think it should be included as a reserved name

**Comment by nayib-jose-gloria** [comment]
Note to engineers: feature_length, tissue_type, and schema_reference will be detected and validated as part of their individual tickets because of how our validation module is structured. This ticket should only add 'citation' to reserved names under 'uns', since it must be annotated outside of the add-labels function during DP upload.

**Comment by danieljhegeman** [comment]
@brianraymor can you say more about when such "duplicate keys" would occur?

> For example, duplicate "feature_biotype" keys in AnnData var are not allowed.

**Comment by danieljhegeman** [comment]
The `__` prefix issue is [already handled by the existing code](https://github.com/chanzuckerberg/single-cell-curation/blob/81737b218ed5dcabfc37d4d50f0a674e8d8c783c/cellxgene_schema_cli/cellxgene_schema/validate.py#L1007-L1022)

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria @brianraymor what is the data type of a citation? String? Is it specifically a doi? Wondering only for the sake of creating a test uns object that makes sense.

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman See https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/462

**Comment by brianraymor** [comment]
Always look in the schema - https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#citation

**Comment by danieljhegeman** [comment]
It is not in alphabetical order 💔 (the other issue being my editor does not permit ctrl+f when viewing markdown files in rendered mode 😞 )

**Comment by brianraymor** [comment]
Actually, it is in alphabetical order within the scope of _Curators MUST NOT annotate the following keys and values in uns._

And I recommend visual studio code for markdown.

**Comment by nayib-jose-gloria** [comment]
@jahilton This portion is ready for QA:

```
These new fields must be reserved.

citation
feature_length
schema_reference
```

**Comment by jahilton** [comment]
Good 2 go
[QA ntbk](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/519_reserved_names.ipynb)
