### ISSUE TITLE
Add observation_joinid

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#522]
# Design

**Notes**: Blocked on a data type that can be supported in R. See [**#single-cell-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1690396401300579). 

## `obs` (Cell Metadata)

`obs` is a [`pandas.DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

When a dataset is uploaded, CELLxGENE Discover MUST annotate a unique observation identifier for each cell. Curators MUST NOT annotate the following column.

### observation_joinid

<table><tbody>
    <tr>
      <th>Key</th>
      <td>observation_joinid</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>
    </tr>
</tbody></table>
<br>

---

## Appendix A. Changelog

schema v4.0.0

* obs (Cell metadata)
  * Added `observation_joinid`

---

# Context

See [Cell Census unique cell identifiers](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-census/25).

*A census cell can be mapped to a cell in its source h5ad.*

----

**Comment by pablo-gar** [comment]
`"source_cell_row"` is a suggestion, better names may exist @BAevermann @jahilton @bkmartinjr

**Comment by jahilton** [comment]
The Requirements did not originate from the triage call.
I suggest we use the index as the row identifiers rather than add a new field.

**Comment by pablo-gar** [comment]
I believe @bkmartinjr had some hesitations with using the index, as in currently it is too flexible to encode anything (e.g. int, float, strings) this can be problematic for the census since we cannot have multi-type columns. 

We could enforce data-type consistency of the anndata index or replace it with a new index, in the first scenario that means there may be some extra load on the curators to make sure it passes the validation.

**Comment by bkmartinjr** [comment]
AnnData historically requires a string index, which would bloat the Census memory use, etc. In addition, AnnData is reportedly moving away from string-only, which would be very hard for us to encode (as Pablo mentions).  So ideally we would have something more compact and supporting polymorphic index keys.

There is one possibility -- we could simply use a well defined hash of the index value (whatever that value is in the source H5AD), and store the hash digest as an int64 source_data_key.  Assuming we pick a well-defined hash function and converstion method from "index_value" to hash, then:

Pro:
* very easy to encode, with good space characteristics
* very fast to encode from any value (need to establish the method, but likely something as simple as  `hash(str(index_value))`
* fast lookup in both SOMA and AnnData (i.e., you can use it as an obs index if you want to do so)
* can be created dynamically/on-demand if we don't want to store it inside the H5AD

Con:
* not an array offset value - _slightly_ more overhead to than an `iloc`-style offset.  Mostly affects use cases doing bulk operations.
* not reversible - you can't reverse the hash to get the index key.  Not sure if this is a problem in reality.

If you do want to explore this further, I have thoughts on possible hashes and implementation.

**Comment by brianraymor** [comment]
> If you do want to explore this further, I have thoughts on possible hashes and implementation.

Please tell us more.

**Comment by jahilton** [comment]
>bloat the Census memory use
>AnnData is reportedly moving away from string-only, which would be very hard for us to encode

Thank you. Both are reasonable justification for not using the existing index (which would have provided likely, but not guaranteed, consistency across versions)

For naming the field, I would suggest including `census` in the name to avoid confusion for a user looking at the downloaded file without the context of the Census.
I have a slight preference for `obs`/`observation` over `cell`.
`census_observation_id`?

**Comment by pablo-gar** [comment]
Having the word `census` in there will then be confusing for census users. A few other suggestions:

1. `h5ad_observation_row`
2. `h5ad_observation_id`
3. `source_observation_row`
4. `source_observation_id`
5. `census_h5ad_join_id`

I like 5

**Comment by bkmartinjr** [comment]
> Please tell us more.

OTOMH:
* Pick a fast non-cryptographic hash with availability in Python & R packages.  xxhash would be a good choice (very fast, available in Python and R packages).  There are others (slower, but somewhat more commonly available).
* Store the hash as either an int64 digest (best) or a string digest (less best, but OK)
* Well-defined conversion of AnnData obs.index values to hash input.  This is easy - just need to write it down.  (e.g., for strings, take the UTF-8 raw bytes and hash it;  for ints, hash the raw little-endian bytes;  etc)

**Comment by brianraymor** [comment]
From **June 27** call with @jahilton, @bkmartinjr, @pablo-gar, @brianraymor 

1. `observation_joinid` proposed as the name in `obs`. 
1. @bkmartinjr to prototype hash. 
1. @pablo-gar to draft schema proposal. This field is calculated/added by the portal during ingestion and should NOT be presented in Explorer.

**Comment by bkmartinjr** [comment]
Proto which adds `observation_joinid` to an H5AD and writes out a new H5AD containing the modification.


```
import os.path
import sys

import anndata
import numpy as np
import xxhash


"""
Annotate an H5AD with `observation_joinid`

Uses xxhash (https://xxhash.com/), via https://pypi.python.org/pypi/xxhash/.

NOTE: xxhash is licensed BSD-2
"""


def main():
    h5ad_filename = sys.argv[1]
    ad = anndata.read_h5ad(h5ad_filename)

    ad.obs["observation_joinid"] = (
        ad.obs.index.to_series()
        .map(lambda idx: xxhash.xxh3_64_intdigest(idx, seed=0))
        .astype(np.uint64)
    )

    fpath, fext = os.path.splitext(h5ad_filename)
    save_to_filename = f"{fpath}_with_joinid.h5ad"
    ad.write(save_to_filename)


if __name__ == "__main__":
    sys.exit(main())
```

**Comment by pablo-gar** [comment]
### observation_joinid

<table><tbody>
    <tr>
      <th>Key</th>
      <td>observation_joinid</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>int64</code>.This `MUST` be the int64-encoded output of the {HASH FUNCTION} applied to the index of <code>var</code>. It represents a unique observation identifier for the given versioned dataset.</td>
    </tr>
</tbody></table>
<br>

**Comment by bkmartinjr** [comment]
@pablo-gar - two questions to help refine this:
* any issues using a 64-bit int for the R user base?
* any reason to prefer int64 vs. uint64?   We can cast to either, as it doesn't change the number of bits in the hash.  I did the proto above using uint, but it is easily fixed.

**Comment by brianraymor** [comment]
@pablo-gar - I'm confused by [these references](https://github.com/chanzuckerberg/single-cell-curation/issues/522#issuecomment-1610356230).

> Draft schema addition for` var` and `raw.var`
> ... applied to the index of var

**Comment by pablo-gar** [comment]
> @pablo-gar - I'm confused by https://github.com/chanzuckerberg/single-cell-curation/issues/522#issuecomment-1610356230.
> 
>
> > Draft schema addition for var and raw.var
>  >... applied to the index of var

Mistake, it must be `obs`

**Comment by pablo-gar** [comment]
> @pablo-gar - two questions to help refine this:
>
> > any issues using a 64-bit int for the R user base?

AFAIK R doesn't have issue with 64-bit encoded values (R tiledbsoma uses them all the time). The issue comes when allocating vectors (lists) with number of elements greater than the max 32-bit number

> any reason to prefer int64 vs. uint64? We can cast to either, as it doesn't change the number of bits in the hash. I did the proto above using uint, but it is easily fixed.

No strong preference and I was not thinking about them, `uint64` seems cleaner to me I'd say keep it that way.

**Comment by brianraymor** [comment]
@pablo-gar @jahilton - I don't see a rationale for exposing this field in the [Seurat encoding](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/seurat_encoding.md#cell-metadata). (And if we did, it would be a `numeric`?)

**Comment by jahilton** [comment]
>I don't see a rationale for exposing this field in the Seurat encoding

Isn't the rationale the same for including it in the AnnData objects?
_I'm a ~python~ R user of the Census and want to link my selected observations to the observations in CELLxGENE Datasets that have more metadata._

**Comment by brianraymor** [comment]
Playing in R Studio using an actual hash generated by Bruce's prototype:

```
> observation_joinid = 15233143882409214278

> observation_joinid 
[1] 1.523314e+19
> class(observation_joinid)
[1] "numeric"
```

How will a uint64 be modeled in R without the bit64 package? Strings?

**Comment by pablo-gar** [comment]
We need to make compatibility with R  a requirement. `tiledbsoma` which is required by Census has a [dependency on `bi64`](https://github.com/single-cell-data/TileDB-SOMA/blob/e464b0f11b420c7a0993d383efa25f8168d2ecda/apis/r/DESCRIPTION#L42). 

I see two options:
- We encode this as a `unit32` OR
- We ensure `bi64` is used during the Seurat conversion.

**Comment by brianraymor** [comment]
> We encode this as a unit32 OR

R does not support **unsigned** 32 bit integers?

> We ensure bit64 is used during the Seurat conversion.

I do not believe that `bit64` supports **unsigned** 64 bit integers per:

> Package 'bit64' provides serializable S3 atomic 64bit **(signed)** integers

Reading [Arrow R Package](https://arrow.apache.org/docs/r/articles/data_types.html):


> Some of these differences are purely cosmetic: **integers in R are in fact 32 bit signed integers**, so the underlying data types in Arrow and R are direct analogs of one another. In other cases the differences are purely about the implementation: Arrow and R have different ways to store a vector of strings, but at a high level of abstraction the R character type and the Arrow string type can be viewed as direct analogs. In some cases, however, there are no clear analogs: while Arrow has an analog of POSIXct (the timestamp type) it does not have an analog of POSIX; conversely, w**hile R can represent 32 bit signed integers, it does not have an equivalent of a 64 bit unsigned integer.**

**Comment by pablo-gar** [comment]
final suggested "Description"

> A short string which uniquely identifies the observation within the dataset.

**Comment by brianraymor** [comment]
Wouldn't this just be replacing `uint64` with `str` in the value row? 

Perhaps I don't understand the significance of a ***short*** string.

**Comment by bkmartinjr** [comment]
We could say "string" rather than "short string". I'm not sure "short' adds any real value (even though I think the word originated with me!)
