### ISSUE TITLE
Deletion request: duplicate submission

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#524]
In [483b3084-21b8-43cf-a2ff-d1c24f544dd1](https://cellxgene.cziscience.com/collections/483b3084-21b8-43cf-a2ff-d1c24f544dd1), it appears that the `Dissection: Body of hippocampus (HiB) - Rostral DG-CA4` was accidentally submitted twice & published. I have confirmed that prior to patching the is_primary_data field, the md5sums of the downloaded .h5ad file matched between the two datasets.
Therefore, we should delete one of them. Specifically, `2ef8f3ce-bbff-447b-9e51-567e5d6c47bd`  so that the other, which is primary:True, may remain.
No extra urgency given that is_primary_data is now patched to avoid duplicate data and there are no privacy concerns, etc.

**Comment by jahilton** [comment]
I approve this deletion request

**Comment by brianraymor** [comment]
Do we need to reopen [Publish must be blocked when duplicate datasets are detected](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1069)?

Based on the fact that this is neither time nor privacy sensitive, I've added the request to [Deletion of published data must be restricted](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/320) as a test case for when a deletion script is available. 

CC: @danieljhegeman @metakuni @pablo-gar

**Comment by jahilton** [comment]
I am in full support of enforcing Dataset title uniqueness. And yes, blocking Publish seems to be the way to do that.
(I am also in full support of enforcing Collection title uniqueness)

**Comment by brianraymor** [comment]
Well - it's not just title uniqueness. It's data uniqueness. You could still have duplicate datasets named "foo" and "bar".

**Comment by jahilton** [comment]
I'm up for that, as well - just more complicated and I'm not immediately sure how (compare the raw layers?)

**Comment by danieljhegeman** [comment]
Acknowledging this will be our test case for deletion in the dawn of the "restricted Deletion" era.

Regarding Dataset title uniqueness: if we were to do it, I presume this would be enforced only _within_ a Collection?

**Comment by brianraymor** [comment]
> Regarding Dataset title uniqueness: if we were to do it, I presume this would be enforced only within a Collection?

_uniqueness_ is not in scope for this issue. It was a conversation about re-opening an older issue (which would be separately prioritized). Sorry if this was confusing.

**Comment by danieljhegeman** [comment]
@jahilton I want to clarify what the request is:

You'd like the following Dataset:
`dataset_id`: `715327a6-7978-4896-ba91-69d6b04dbbfb`
`title`: `Dissection: Body of hippocampus (HiB) - Rostral DG-CA4`
`revised_at`: `2023-04-20T16:43:41.279680+00:00`

to be removed/withdrawn from Collection `283d65eb-dd53-496d-adb7-7570c7caa443`, which itself currently has no outstanding revisions open?

Is that correct?

**Comment by jychien** [comment]
We do need a dataset deleted, but the information of the dataset that should be removed/withdrawn is:

- Collection uuid: 483b3084-21b8-43cf-a2ff-d1c24f544dd1
- Dataset title: Dissection: Body of hippocampus (HiB) - Rostral DG-CA4
- Dataset uuid: 2ef8f3ce-bbff-447b-9e51-567e5d6c47bd

We would like the dataset with is_primary_data=True to be kept.

**Comment by brianraymor** [comment]
@danieljhegeman - after I re-read the top-level summary comment, I do not understand the source of your confusion.

Jason wrote:

 Therefore, we should delete one of them. Specifically, **2ef8f3ce-bbff-447b-9e51-567e5d6c47bd**

which matches @jychiens response.

**Comment by danieljhegeman** [comment]
@brianraymor thanks for pointing that out. I actually got sidetracked earlier on trying to figure out which collection was `[483b3084-21b8-43cf-a2ff-d1c24f544dd1`, because it turned out it was a Collection _version_ and not a Collection. I then failed to read the rest of the paragraph.

**Comment by danieljhegeman** [comment]
Done. Deleted dataset `2ef8f3ce-bbff-447b-9e51-567e5d6c47bd` and re-published the Collection.
