### ISSUE TITLE
Why does CXG conversion fail when int64 values cannot be converted to int32?

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#526]
## Read This First

@brianraymor writes:

We understand the source of the failure but not the _rationale_ for the failure - annotating as "schema" for further discussion. There will be a new `uint64` type introduced in `obs` for schema 4 - [Add observation_joinid](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/522). Currently, this will fail CXG conversion so it not the simple case of adding a new schema requirement prohibiting int64 values. 

## Context

See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1687483718696969)

cxg conversion fails in these cases

The error below was caused when I had created a column in the obs that was a `hash()` of the raw count values for that cell
`adata.obs['hashes'] = [hash(r.tobytes()) for r in adata.raw.X.toarray()]`

    "levelname": "ERROR",
    "asctime": "2023-06-23T01:11:55.023Z",
    "name": "processing",
    "message": "CXG conversion failed.",
    "lineno": 80,
    "pathname": "/backend/layers/processing/process_cxg.py",
    "exc_info": "Traceback (most recent call last):\n  File \"/backend/layers/processing/process_cxg.py\", line 76, in make_cxg\n    h5ad_data_file.to_cxg(cxg_output_container, sparse_threshold=25.0)\n  File \"/backend/layers/processing/h5ad_data_file.py\", line 77, in to_cxg\n    convert_dataframe_to_cxg_array(output_cxg_directory, \"obs\", self.obs, self.obs_index_column_name, ctx)\n  File \"/backend/common/utils/cxg_generation_utils.py\", line 55, in convert_dataframe_to_cxg_array\n    dtype, hints = get_dtype_and_schema_of_array(column_values)\n  File \"/backend/common/utils/type_conversion_utils.py\", line 64, in get_dtype_and_schema_of_array\n    return _get_type_info(array)\n  File \"/backend/common/utils/type_conversion_utils.py\", line 147, in _get_type_info\n    raise TypeError(f\"Annotations of type {dtype} are unsupported.\")\nTypeError: Annotations of type int64 are unsupported."

---

**Comment by signechambers1** [comment]
Summarizing my conversation with @atarashansky. Basically, Explorer is incompatible with int64 values so if int64 categories cannot be converted to int32 or string, we should exclude them from the cxg.

However, if the int64 fields are important to curators and they want them to be available in the download functionality, there is no reason to prevent that.

@brianraymor does that make sense? I'm not sure how that quite translates into schema-ese or if there is a need or precendent for non-Explorer fields to be included in the download H5AD?

**Comment by atarashansky** [comment]
Copying over my thoughts from private discussion with @signechambers1 

If categories cannot be cast to int32, we need to determine if it's because there are (A) too many categories, or if there are (B) not too many categories, but int values that are just too large.

If (A), solution is to cast to string.
If (B), solution is to hide from explorer.

I don't think either scenario should warrant a validation fail, because I would prefer not to exclude them from the source H5AD if the authors think they're valuable metadata.

**Comment by atarashansky** [comment]
I think hiding from explorer is straightforward as we can just remove it from the `cxg_group_metadata` meta property of the CXG.

**Comment by jahilton** [comment]
>I don't know whether there needs to be an explanation in the schema for submitters/curators if they're expecting int64 to be surfaced in Explorer.

We have yet to hit any int64 fields from contributors that couldn't be converted (only case was my accidental submission) & we haven't heard anyone ask/complain about their int64 field that is displayed as int32. So I'm not _super_ worried from a contributor standpoint.
But also, doesn't hurt to have it for reference maybe on the viz guidelines - "int64 are converted to int32 if possible, otherwise, they are dropped"

**Comment by signechambers1** [comment]
Thanks all, I have created a ticket for the explorer work to ignore int64 fields [here](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/644) and added this note to the Explorer presentation guidelines under Continuous Dimensions. Closing this ticket.
