### ISSUE TITLE
Out-of-memory issues when standardizing gene symbols with cellxgene-schema apply

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#54]
`cellxgene-schema apply` updates gene symbols in an AnnData object to a [static snapshot](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/hgnc_complete_set.txt.gz) of the HGCN database. 

While updating gene symbols, `cellxgene-schema apply` combines  genes (columns) when necessary, and to do so it [loads the entire count matrix into a pandas data frame](https://github.com/chanzuckerberg/single-cell-curation/blob/f54de6f710fbe7d66de76bec0249931b87e4930f/cellxgene_schema_cli/cellxgene_schema/remix.py#L165-L186). For datasets with large number of cells, this raises a python memory allocation error or the process gets killed. Depending on the number of cells this error occurs with machines that have up to 3TB of memory.

A proven but not implemented solution is to only load those genes (columns) that need to be updated into a pandas data frame, combine them as necessary, and then merge back to the expression matrix.

**Comment by brianraymor** [comment]
@pablo-gar - suggest that this be closed as _Won't fix_ since we're deprecating `apply`.
