### ISSUE TITLE
Validator should check for validity of ontology term id fields

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#55]
Schema v 1.1.1 and 1.2.0 do not allow empty strings in ontology term id fields. The validator should raise an error if an empty string or an incorrect term is found.

The current allowed prefixes for ontology term ids are :
- CL:  (cell type)
- UBERON: (tissue)
- MONDO: or PATO:0000461 (disease)
- EFO: (assay)
- HANCESTRO (ethnicity)
- HsapDv or EFO:0000399 (development stage)

**Comment by brianraymor** [comment]
This will be addressed in the validation update for schema 1.2.0. Closing.
