### ISSUE TITLE
Raw Data in Phenotypic variation of transcriptomic cell types in mouse motor cortex returns Not Found

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#57]
The [`Raw Data` link](http://data.nemoarchive.org/biccn/grant/zeng/tolias/) in [Phenotypic variation of transcriptomic cell types in mouse motor cortex](https://cellxgene.cziscience.com/collections/20a1dadf-a3a7-4783-b311-fcff3c457763/private) returns **Not Found**.

**Comment by pablo-gar** [comment]
I noticed this as well, however that is the link they use in the paper. I assumed that BICCN/NEMO will be fixing that, but I will contact them and make sure that's the case

**Comment by pablo-gar** [comment]
This has been corrected by NEMO and the link is working now.
