### ISSUE TITLE
Determine GENCODE migration mappings

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#572]
We need to investigate what Ensembl IDs should be updated from the current schema version (GENCODE v38) to a new Ensembl ID reflected in the next pinned annotation version in the schema (most recent is [currently v44](https://www.gencodegenes.org/human/)). And we need to establish a reproducible way to identify these version-to-version updates to 1) use again during future migrations and 2) establish some mappings in curation (as contributors will bring us data from older versions).

Plan: use v38 & v44 as our test case. Take a close look at what v38 gene IDs are not in v44, but we believe are represented by updated gene IDs. Design logic around determining those updates. Share the v38/v44 mapping for migration. Apply that logic to previous versions-to-v44 and include those mappings to our curation notebook so we are saving as much as possible during curation.

**Comment by brianraymor** [comment]
@jahilton notes _ENSG migration - hoping to have a proposal ready for review **Sept 8th**_

**Comment by jahilton** [comment]
The curation team is proposing a migration solution that does not require manual decisions to be made so that we ensure an unbiased solution that is simple enough to be followed & reproduced by users. We feel this simplicity is vital to ensuring provenance, and prevents the curation team from the burden of a tedious evaluation that will be difficult to estimate time needed.
For example, there are cases where 2 gene IDs have been collapsed to 1, thus 1 of the 2 gene IDs is deprecated while the other remains, and the curation team may "wish" the deprecated gene ID would have been the one to retain, but we will defer to the annotation resources.

We recommend 2-3 weeks allowance for curation team and comp bios to review the proposed migration implications before the migration plan is finalized. This will allow us to survey CELLxGENE data for the deprecated genes and identify any 'surprises' in the updated annotation version.

**Current draft proposal**
Definitions
_current_ = the pinned annotation that the schema currently references
_future_ = the pinned annotation that the new schema version will reference

- Any gene ID that is present in the _current_ version and the _future_ version will be retained
- Any gene ID that is present in the _current_ version but not in the _future_ version will be evaluated and retained with a revised gene ID if:
  - the transcript IDs (ENST without version number appended) attributed to that gene match exactly to a _future_ gene ID
AND/OR
  - the seqname (chromosome), start, stop, and strand all match exactly to a _future_ gene ID
  - AND the matching _future_ gene ID must not be present in the _current_ version

Gap - If a _current_ gene matches the transcript IDs with one _future_ gene ID and coordinates with a different _future_ gene ID. We’ll just have to evaluate at that time.

**Applying this logic to current schema versions & most updated GENCODE versions**
A hypothetical of migration from M27 to M33 for the mouse reference results in no potential revisions & 135 gene IDs being dropped.

For a hypothetical migration from v38 to v44 for human, this results in 11 revision cases (below) & 136 gene IDs being dropped including 2 that match to a gene ID that exists in v38 (1 from coordinates, 1 from both)
| v38 ID | v44 ID | reason |
| ---- | --- | --- |
| ENSG00000112096 | ENSG00000291237 | transcripts & coordinates |
| ENSG00000277077 | ENSG00000289133 | transcripts & coordinates |
| ENSG00000215271 | ENSG00000290292 | transcripts |
| ENSG00000225932 | ENSG00000288784 | transcripts |
| ENSG00000244693 | ENSG00000289604 | transcripts |
| ENSG00000203812 | ENSG00000288825 | transcripts |
| ENSG00000272196 | ENSG00000288859 | transcripts |
| ENSG00000263464 | ENSG00000288867 | transcripts |
| ENSG00000256374 |ENSG00000289549 | transcripts |
| ENSG00000288546 | ENSG00000289084 | coordinates |
| ENSG00000205485 | ENSG00000290873 | coordinates |

**Comment by brianraymor** [comment]
@jahilton - may this issue now be closed?
