### ISSUE TITLE
Amend PCA coordinate label for "Molecular characterization of foveal versus peripheral human retina by single-cell RNA sequencing."

### ISSUE THREAD

**Issue by rachadele** [chanzuckerberg/single-cell-curation#58]
PCA coordinates are labeled as UMAP when they should be tSNE.

https://cellxgene.cziscience.com/collections/7edef704-f63a-462c-8636-4bc86a9472bd

I have already fixed the h5ad and can re-submit when revisions are possible.

**Comment by brianraymor** [comment]
@rachadele - since you'll be revising the collection, would you also edit the collection title and remove the '.'. It's a minor editorial issue, but doesn't match the style of existing collections ...

**Comment by jahilton** [comment]
@brianraymor what is the ETA on enabling such a revision?
I am trying to determine if Rachel will have time to re-submit and then we migrate the re-submission, or if we should just lump the update in with the migration.

**Comment by brianraymor** [comment]
Based on outstanding issues in the epic and the need for additional testing, I expect that revisions is still +3 weeks out.

**Comment by jahilton** [comment]
I will plan on this being included in the migration. If the opportunity presents itself, then Rachel can update via re-submission between now and then.
@rachadele is that the only change you were planning to make to this dataset?
I have moved the Collection title update to #102

**Comment by rachadele** [comment]
@jahilton yes, I think so. I could also get rid of the cell_type field and final_cluster_labels since they seem redundant?

**Comment by jahilton** [comment]
It seems like celltype & final_cluster_labels do group cells equally in this dataset. However, each might have their own value as either/both may be used in the paper when referencing the data. So we tend to view the free text cell type annotations & cluster labels as non-redundant, even in these cases.

**Comment by jahilton** [comment]
New issue we uncovered today with this Dataset. The max value in .X is 8.821655. There is no raw.X layer, so the .X should be the raw values. Non-integer values less than 10 indicate the values are not raw.
@rachadele are raw (non-scaled, non-normalized) values available for this dataset?

**Comment by jahilton** [comment]
Given the lack of raw counts, and no response from the researcher, we are deleting this dataset. Being done in https://github.com/chanzuckerberg/single-cell-data-portal/issues/1467
