### ISSUE TITLE
Amend cell type colors for "Cells of the adult human heart"

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#59]
The following dataset has 13 colors assigned to the cell types under `AnnData.uns["cell_type_colors"]`. These colors correspond to the `cell_type_original` column in `AnnData.obs` and not to `cell_type`.

Dataset (All — Cells of the adult human heart):
[ https://cellxgene.cziscience.com/e/d4e69e01-3ba2-4d6b-a15d-e7048f78f22e.cxg/]( https://cellxgene.cziscience.com/e/d4e69e01-3ba2-4d6b-a15d-e7048f78f22e.cxg/)
Collection: 
[https://cellxgene.cziscience.com/collections/b52eb423-5d0d-4645-b217-e1c6d38b2e72
](https://cellxgene.cziscience.com/collections/b52eb423-5d0d-4645-b217-e1c6d38b2e72
)
Solution:
- Rename `AnnData.uns["cell_type_colors"]` to `AnnData.uns["cell_type_original_colors"]`
- Re-upload dataset when revisions of public datasets is available.

**Comment by jahilton** [comment]
According to [schema 2.0.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#appendix-a-changelog):

> Removed obs_column_colors

Is this task still worth doing?

**Comment by pablo-gar** [comment]
Yes, even though it is not part of the schema cellxgene will still recognize this column and change its behavior

**Comment by jahilton** [comment]
updated via the migration to 2.0.0
