### ISSUE TITLE
Download all the data

### ISSUE THREAD

**Issue by toycatI** [chanzuckerberg/single-cell-curation#593]
Really appreciate your work! I want to use Cellxgene for training on large models, so I'd like to download all the data from the website. Is there a more convenient way to do it rather than clicking on the download button for over eight hundred datasets one by one?

**Comment by pablo-gar** [comment]
Hi @toycatI! 

Yes we have a better ways to fetch data programmatically from CZ CELLxGENE Discover. In most cases for modeling, using the [Census API](https://chanzuckerberg.github.io/cellxgene-census/index.html) provides a great solution to this.

We can provide more guidance if you share a bit more more about what modeling framework you are planning to use, as well as any requirements you may have for the data itself.

For starters, the Python Census API [provides PyTorch loaders](https://chanzuckerberg.github.io/cellxgene-census/notebooks/experimental/pytorch.html) that work natively with our data.

**Comment by brianraymor** [comment]
@toycatI - have you had an opportunity to review?

**Comment by toycatI** [comment]
Thanks! I will learn to use this tool.
