### ISSUE TITLE
cellxgene schema apply does not permit empty strings as mapping keys

### ISSUE THREAD

**Issue by rachadele** [chanzuckerberg/single-cell-curation#60]
If a column being used to populate required schema fields has empty strings values, the empty string cannot be used as a mapping key. I believe this is because `cellxgene schema apply` automatically converts the values to `nan`. The workaround for this is to use `nan` as a mapping key. It would be great if curation software could handle empty values in the future.

**Comment by brianraymor** [comment]
`cellxgene-schema apply` is deprecated with 2.0.0. Closing.
