### ISSUE TITLE
cellxgene-schema CLI must validate schema_version

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#607]
# Context

See [**single-cell-four**](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1692813292823499?thread_ts=1692809869.002419&cid=C03PXFMM7ST).

As part of automated migration, the schema transitioned from curators annotating `schema_version` to CELLxGENE Discover annotating `schema_version`.  For 3.1, schema_version is temporarily overwritten as part of the transition:

_When a dataset is uploaded, CELLxGENE Discover MUST automatically add the schema_version key and its value to uns. If schema_version is already defined, then its value MUST be overwritten._

In 4.0, curators must not annotate this field. An error should be thrown blocking validation if it is provided, rather than the overwriting behavior it currently uses.

**Comment by nayib-jose-gloria** [comment]
@jahilton Ready for testing! For all testing, you can pull the latest release candidate version of 4.0.0 by running:
`pip install git+https://github.com/chanzuckerberg/single-cell-curation/@main#subdirectory=cellxgene_schema_cli`

**Comment by jahilton** [comment]
Unexpected behavior: the file will pass validation if uns['schema_version'] = `None`
Expected to fail because 'schema_version' is present in uns.

Sample adata was set by `adata.uns['schema_version'] = None` & writing to .h5ad

**Comment by jahilton** [comment]
You are correct. It drops when saving so the tested .h5ad didn't actually have uns.schema_version.
In that case, all clear!
