### ISSUE TITLE
Amend assay type for methylation data in "An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types""

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#61]
The assay type for the methylation datasets (see below) was set as "methylation profiling (EFO:0000751)". However, according to the paper the specific assay is snmC-seq for which there is an appropriate ontology term "snmC-seq (EFO:0008939)"

**Solution**

When revisions of published collections are available, change assay type to "snmC-seq" with term id "EFO:0008939" for the following datasets:

- An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types: DNA methylation (CGN)
- An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types: DNA methylation (CHN)

Which are from this collection:

[https://cellxgene.cziscience.com/collections/ae1420fe-6630-46ed-8b3d-cc6056a66467](https://cellxgene.cziscience.com/collections/ae1420fe-6630-46ed-8b3d-cc6056a66467)

**Comment by jahilton** [comment]
Updated to `snmC-seq` during migration (snmC-seq2 is not in the current pinned EFO version)
