### ISSUE TITLE
cellxgene-schema CLI must validate ndarray size in obsm, obsp, varm, and varp

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#610]
## `obsm` (Embeddings)

The size of the ndarray stored for a key in `obsm` MUST NOT be zero.

## `obsp`

The size of the ndarray stored for a key in `obsp` MUST NOT be zero.
<br>

## `varm`

The size of the ndarray stored for a key in `varm` MUST NOT be zero.
<br>

## `varp`
The size of the ndarray stored for a key in `varp` MUST NOT be zero.
<br>

**Comment by Bento007** [comment]
I assume "a key" means any key?

**Comment by brianraymor** [comment]
> I assume "a key" means any key?

Yes since this causes RDS conversion failures - https://github.com/chanzuckerberg/single-cell-curation/issues/597#issue-1842192464

**Comment by Bento007** [comment]
Do we have an existing test case dataset for any of these?

**Comment by brianraymor** [comment]
Not to my knowledge. When I was playing around with it, I realized that it also needed to meet other anndata requirements like obsm embeddings must be the same length as obs like:

```
adata.obsm['test'] = numpy.zeros((adata.n_obs, 0))
adata.obsm['test'].size 
```

**Comment by Bento007** [comment]
@jahilton thank you for these [notebooks](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/610_array_size.ipynb). They have been invaluable in reproducing the errors.

**Comment by Bento007** [comment]
@jahilton @corismall read for QA

**Comment by jahilton** [comment]
LGTM - [QA notebook](https://github.com/Lattice-Data/lattice-tools/blob/CXG290-schema4validator-testing/cellxgene_resources/cxg_4.0.0_testing/610_array_size.ipynb)
