### ISSUE TITLE
Update now-obsolete 'native cell' in schema

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#622]
# Context 
CL has made 'native cell' obsolete: https://github.com/obophenotype/cell-ontology/issues/2124.
Anticipated to be in the Sept release.

We reference the term in our schema twice.

- Under [Integration Metadata](https://github.com/chanzuckerberg/single-cell-curation/blob/main//schema/4.0.0/schema.md#integration-metadata)..."If no appropriate high-level term can be found or the cell type is unknown, then the most accurate term is [CL:0000003](https://www.ebi.ac.uk/ols4/ontologies/cl/classes?obo_id=CL%3A0000003) for native cell."
- In the [cell_type_ontology_term_id schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main//schema/4.0.0/schema.md#cell_type_ontology_term_id)..."If no appropriate high-level term can be found or the cell type is unknown, then it is STRONGLY RECOMMENDED to use ["CL:0000003"](https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000003) for native cell"

I can think of 2 options:

1. Replace ‘native cell’ with ‘cell’ [CL:0000000](https://www.ebi.ac.uk/ols4/ontologies/cl/classes?obo_id=CL%3A0000000)
2. Replace ‘native cell’ with a string (similar to how we allow `unknown` for dev_stage/ethnicity/sex)

---

# Design (@brianraymor)

## Integration Metadata

CELLxGENE requires ontology terms to enable search, comparison, and integration of data.
Ontology terms for cell metadata MUST use [OBO-format identifiers](http://www.obofoundry.org/id-policy.html), meaning a CURIE (prefixed identifier) of the form **Ontology:Identifier**.
For example, [EFO:0000001](https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0000001) is a term in the Experimental Factor Ontology (EFO).

The most accurate ontology term MUST always be used. If an exact or approximate ontology term is not available, a new term may be requested:

- For the [Cell Ontology], data submitters may [suggest a new term](https://github.com/obophenotype/cell-ontology/issues/new?assignees=bvarner-ebi&labels=new+term+request%2C+cellxgene&template=a_adding_term_cellxgene.md&title=%5BNTR-cxg%5D) and [notify the curation team](mailto:cellxgene@chanzuckerberg.com) of the pending term request, so that the datasets can be updated once the term is available.

  To meet CELLxGENE schema requirements, the most accurate available CL term MUST be used until the new term is available. For example if `cell_type_ontology_term_id` describes a relay interneuron, but the most accurate available term in the CL ontology is [CL:0000099](https://www.ebi.ac.uk/ols4/ontologies/cl/classes?obo_id=CL%3A0000099) for *interneuron*, then the interneuron term can be used to fulfill this requirement and ensures that users searching for "neuron" are able to find these data. If no appropriate term can be found (e.g. the cell type is unknown), then `"unknown"` MUST be used. Users will still be able to access more specific cell type annotations that have been submitted with the dataset (but aren't required by the schema).

---

### cell_type_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>cell_type_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be a CL term or <code>"unknown"</code> If no appropriate term can be found (e.g. the cell type is unknown). The following terms MUST NOT be used:
        <ul><li>
          <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000255"><code>"CL:0000255"</code></a> for <i>eukaryotic cell</i>
        </li>
        <li>
          <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000257"><code>"CL:0000257"</code></a> for <i>Eumycetozoan cell</i>
        </li>
        <li>
            <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000548"><code>"CL:0000548"</code></a> for <i>animal cell</i>
         </li></ul>
    </tr>
</tbody></table>
<br>

---

### cell_type

<table><tbody>
    <tr>
      <th>Key</th>
      <td>cell_type</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"unknown"</code> if the value of <code>cell_type_ontology_term_id</code> is <code>"unknown"</code>; otherwise, this MUST be the human-readable name assigned to the value of <code>cell_type_ontology_term_id</code>.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by BAevermann** [comment]
I am in favor of option #1: "Replace ‘native cell’ with ‘cell’ CL:0000000
<https://www.ebi.ac.uk/ols4/ontologies/cl/classes?obo_id=CL%3A0000000>"
This is because organoids will often have an unknown phenotype
(unclassifiable) and I think "cell" is the most accurate description.
Adding a non-CL string would just complicate things.

b.

**Comment by metakuni** [comment]
Bumped to `4.1` as discussed at weekly meeting

**Comment by brianraymor** [comment]
November 27 Triage - consensus for:

Replace ‘native cell’ with a string (similar to how we allow unknown for dev_stage/ethnicity/sex)

**Comment by danieljhegeman** [comment]
@brianraymor I just want to confirm the decision to go with Option 2 (replace with string) given that the CL page for the deprecated term [explicitly says 'Replaced by cell'](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000003), which would seem to indicate Option 1 (replace with 'cell'). I do not see this fact referenced in the discussion on this issue above and I want to be sure everyone was aware of it. cc @jahilton for comment

**Comment by jahilton** [comment]
Thanks for raising that @danieljhegeman. Doesn't change anything from my point-of-view

**Comment by danieljhegeman** [comment]
@brianraymor 

>Replace ‘native cell’ with a string (similar to how we allow unknown for dev_stage/ethnicity/sex)

Wrt considering engineering implications: does
> with a string

mean with a single, standard, string such as `"native cell"`? At the moment the validator seems configured to allow us to add exceptions; obviously it would have to be a limited number (preferably one) of excepted string(s).

Or does it mean that we should start accepting _any_ descriptive string? This would make validation of curie terms more challenging, e.g. perhaps we would only validate terms that start with known prefixes and otherwise would assume it is a descriptive string.

I'm assuming you want the former.

**Comment by brianraymor** [comment]
This is not actionable for Dev until I finalize and write the schema requirements. CC: @metakuni

**Comment by danieljhegeman** [comment]
>This MUST be "unknown" if set in...

I notice you use this phraseology in a couple of other spots in the schema. Does it mean "This MUST be `"unknown"` if set as `"unknown"` in [other attribute]"?

**Comment by danieljhegeman** [comment]
@brianraymor what _label_ do we want to replace `"native cell"` with?

`CL:0000003` -> `unknown`
`native cell` -> ???

From the [work ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/611):
> the code base must be reviewed for dependencies or references to the obsolete label or term

**Comment by brianraymor** [comment]
https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.0.0/schema.md#cell_type

**Comment by danieljhegeman** [comment]
Ah, yes, the label is the same as `cell_type`. Connecting dots...
