### ISSUE TITLE
duplicate column names causing error in validator

### ISSUE THREAD

**Issue by Jchaffer787** [chanzuckerberg/single-cell-curation#627]
Currently the CellxGene validator errors when there are duplicate schema column names in var (e.x. 'feature_is_filtered' and 'feature_is_filtered'), or duplicate schema or non-schema column names in obs (e.x. 'donor_id' and 'donor_id', or 'test' and 'test'). When there are duplicate non-schema column names in var or raw.var there is no error and the dataset passes validation.

The error appears to stem from this line in the validator:
`if col.dtype != "category":`

The error output is the following:
`AttributeError: 'DataFrame' object has no attribute 'dtype'. Did you mean: 'dtypes'?`

It appears that when the validator goes to check for the correct dtype in each of the columns, instead of a column being passed for col it is a dataframe of 2 columns, and therefore is expecting .dtypes instead of .dtype.

A solution to this would to be specify uniqueness in all obs, var, and perhaps raw.var within the schema req.
The validator can then be updated accordingly.

**Comment by Jchaffer787** [comment]
I've made an edit to include the specific column names that will reproduce this error.

**Comment by brianraymor** [comment]
The schema now prohibits - https://github.com/chanzuckerberg/single-cell-curation/issues/641 - please verify that this is addressed by https://github.com/chanzuckerberg/single-cell-curation/issues/729 when implemented. CC: @danieljhegeman @joyceyan .
