### ISSUE TITLE
Reserved Names and Uniqueness requirements must be clarified

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#641]
# Design

**Note: I'm preferring a _hand-wavy_ "metadata fields" rather than getting into details of keys or column names depending on the Anndata section in question. And obviously, some Anndata sections do not allow duplicates. I could create a table per Anndata section if that would be preferred.**

## General Requirements
...

**Reserved Names**. The names of metadata fields MUST NOT start with `"__"`. The names of the metadata fields specified by the schema are **reserved** for the purposes and specifications described in the schema.

**Unique Names**. The names of schema and data submitter metadata fields in `obs` and `var` MUST be unique. For example, duplicate <code>"feature_biotype"</code> keys in AnnData <code>var</code> are not allowed.

**Note: I will also be remodeling the Annotator in all metadata fields from:**

<table><tbody>
    <tr>
      <th>Key</th>
      <td>myKey</td>
    </tr>
    <tr>
      <th>Annotator</th>
         <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>numpy.ndarray</code>
        </td>
    </tr>
</tbody></table>
<br>

**to something like:**

<table><tbody>
    <tr>
      <th>Key</th>
      <td>myKey</td>
    </tr>
    <tr>
      <th>Annotator</th>
         <td>Curator MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>numpy.ndarray</code>
        </td>
    </tr>
</tbody></table>
<br>

# Context

See [#single-cell-four](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1694818587348629).

**Reserved Names** in [General Requirements](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#general-requirements) has been previously reviewed, but needs further clarification for new readers.

* "Metadata keys" is imprecise when referring to schema fields that could be `dict` keys in .`uns` or 
`pandas.core.frame.DataFrame` columns in `.obs`.

**Note**: when I revisited the rationale for using "Key" as the standard name in the schema field tables, I was reminded that `keys` is a common operation for both `obs` (DataFrame) and `uns` (dictionary). 

```

adata.obs.keys()
adata.uns.keys()

```

* In some cases, the underlying data type in AnnData already enforces uniqueness. But that is not always true. See [A Few Times, I’ve Broken Pandas](https://towardsdatascience.com/a-few-times-i-managed-to-broke-pandas-d3604d43708c#:~:text=Pandas%2C%20however%2C%20can%20be%20tricked,to%20debug%20problems%20in%20Python). 
* Uniqueness must be enforced for both author-provided and schema-defined fields. As @jahilton suggested _Apply the uniqueness requirement to both schema and author metadata (we can’t think of any valid use of non-unique column names & Jim has noted the issues they introduce)_
* All reserved names are unavailable to submitters, but there are fields that are reserved for curators to annotate and fields that are reserved for CELLxGENE Discover to annotate. 
* The rationale for requirements such as [Names starting with '__' must be reserved](https://github.com/chanzuckerberg/single-cell-curation/issues/269) should be retroactively captured in the Change Log for the day when @brianraymor is no longer available to remember "Why?".

**Comment by danieljhegeman** [comment]
Changed
>Uniqueness must be enforced for both author and schema fields
to
>Uniqueness must be enforced for both author-provided and schema-defined fields
for clarity
