### ISSUE TITLE
Seurat convertibility check is suboptimal

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-curation#656]
[This operation](https://github.com/chanzuckerberg/single-cell-curation/blob/77a2d25335b21a54ca139ba4d20d057dd948e25f/cellxgene_schema_cli/cellxgene_schema/validate.py#L934) in the seurat convertibility check is performing an iterative count of nonzero matrix values when it could instead reference a [dict that is already being populated](https://github.com/chanzuckerberg/single-cell-curation/blob/77a2d25335b21a54ca139ba4d20d057dd948e25f/cellxgene_schema_cli/cellxgene_schema/validate.py#L298) (for [non-csr matrix types](https://github.com/chanzuckerberg/single-cell-curation/blob/77a2d25335b21a54ca139ba4d20d057dd948e25f/cellxgene_schema_cli/cellxgene_schema/validate.py#L897-L910), at least).

**Comment by nayib-jose-gloria** [comment]
The function __count_matrix_nonzero_ [already checks](https://github.com/chanzuckerberg/single-cell-curation/blob/77a2d25335b21a54ca139ba4d20d057dd948e25f/cellxgene_schema_cli/cellxgene_schema/validate.py#L288) for the cached nonzero number count if its available, so we re already performing this optimization

**Comment by brianraymor** [comment]
@nayib-jose-gloria - per your comment, can this be closed?

**Comment by nayib-jose-gloria** [comment]
@brianraymor I believe this can be closed, but I'd like @danieljhegeman to confirm that this is the behavior he was describing before closing. just in case there is a misunderstanding and there is a further optimization here

**Comment by danieljhegeman** [comment]
I agree with @nayib-jose-gloria -- my original reading missed the reference to the cache at the beginning of the function.
