### ISSUE TITLE
Add requirements for Visium Spatial Gene Expression assay

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#674]
# Context

This addresses the [census requirements](https://docs.google.com/document/d/1x5jqTvI7xb-r2cqSS91FrriE0oVZvGf5FzCFDGx7Fc4/edit#heading=h.sb44irnz9vkx) authored by @pablo-gar. 

See [Improve CELLxGENE’s value proposition for data submitters and consumers by supporting visium and slide-seq experiments](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/473) and [Data Platform changes required to support visium experiments](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/512)

# Design

## Pending

[[NTR] Version specific Visium assays](https://github.com/EBISPOT/efo/issues/2178)

For easier review, these requirements are **additive** to the corresponding sections in the [schema 4 draft](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md). 

## General Requirements

...

<b>Visium Spatial Gene Expression.</b> It is STRONGLY RECOMMENDED that <i>Visium Spatial Gene Expression</i> datasets represent one Space Ranger output for a single tissue section. This representation is referenced throughout the schema as <b>Visium Single</b>.

Visium datasets that represent multiple Space Ranger outputs MAY be submitted. This representation is referenced throughout the schema as <b>Visium Multiple</b> which will have limited support in CELLxGENE experiences:
* There are no image underlays in CELLxGENE Explorer.
* Such datasets are not included in CELLxGENE Discover Census.
* Such datasets are not converted to Seurat for CELLxGENE Discover downloads.

---

## `X` (Matrix Layers)

...

The following table describes the matrix data and layers requirements that are **assay-specific**. If an entry in the table is empty, the schema does not have any other requirements on data in those layers beyond the ones listed above.

| Assay | "raw" required? | "raw" location | "normalized" required? | "normalized" location |
|-|-|-|-|-|
| Visium Spatial Gene Expression | REQUIRED. It is STRONGLY RECOMMENDED to use the unfiltered feature-barcode matrix (<code>raw_feature_bc_matrix</code>). See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/space-ranger-feature-barcode-matrices">Space Ranger Feature-Barcode Matrices</a>. Values MUST be de-duplicated molecule counts. ~~Each cell MUST contain at least one non-zero value.~~ All non-zero values MUST be positive integers stored as `numpy.float32`.| `AnnData.raw.X` unless no "normalized" is provided, then `AnnData.X` | STRONGLY RECOMMENDED | `AnnData.X` |
|||||

## `obs` (Cell Metadata)

`obs` is a [`pandas.DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

...

---
---
**Editor Note: See my [comment](https://github.com/chanzuckerberg/single-cell-explorer/issues/646#issuecomment-1679695035) related to filtering out some visium observations from Explorer.**

**Editor Note:  For Visium Single datasets based on one tissue sample, all the following fields MUST have *singleton* values:**

---
---

### assay_ontology_term_id

If **Visium Single**, all observations MUST be the same value. 

### development_stage_ontology_term_id

If **Visium Single**, all observations MUST be the same value. 

### donor_id

If **Visium Single**, all observations MUST be the same value. 

### organism_ontology_term_id

If **Visium Single**, all observations MUST be the same value. 

### self_reported_ethnicity_ontology_term_id

If **Visium Single**, all observations MUST be the same value. 

### sex_ontology_term_id

If **Visium Single**, all observations MUST be the same value. 

---

### array_col

<table><tbody>
    <tr>
      <th>Key</th>
      <td>array_col</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>int</code>. This MUST be the value of the column coordinate for the corresponding spot from the <code>array_col</code> field in <code>tissue_positions_list.csv</code> or <code>tissue_positions.csv</code>. The value MUST be in the range between <code>0</code> and <code>127</code>. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.
        </td>
    </tr>
</tbody></table>
<br>

### array_row

<table><tbody>
    <tr>
      <th>Key</th>
      <td>array_row</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>int</code>. This MUST be value of the row coordinate for the corresponding spot from the <code>array_row</code> field in in <code>tissue_positions_list.csv</code> or <code>tissue_positions.csv</code>. The value MUST be in the range between <code>0</code> and <code>77</code>. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.
        </td>
    </tr>
</tbody></table>
<br>

### cell_type_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>cell_type_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be a CL term or <code>"unknown"</code> if:
        <ul>
        <li> no appropriate term can be found (e.g. the cell type is unknown)</li>
        <li><b>Visium Single</b> and the corresponding value of <code>in_tissue</code> is <code>0</code></li><br>
        The following terms MUST NOT be used:
        <ul><li>
          <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000255"><code>"CL:0000255"</code></a> for <i>eukaryotic cell</i>
        </li>
        <li>
          <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000257"><code>"CL:0000257"</code></a> for <i>Eumycetozoan cell</i>
        </li>
        <li>
            <a href="https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000548"><code>"CL:0000548"</code></a> for <i>animal cell</i>
         </li></ul>
    </tr>
</tbody></table>
<br>

### in_tissue

---
---
**Editor Note**: This could be modeled as a boolean. Seurat models as an `integer`. Squidpy models as a `int64`. There was agreement to use an `int` for consistency.

---
---

<table><tbody>
    <tr>
      <th>Key</th>
      <td>in_tissue</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>int</code>. This MUST be the value for the corresponding spot from the <code>in_tissue</code> field in <code>tissue_positions_list.csv</code> or <code>tissue_positions.csv</code> which is either <code>0</code> if the spot falls outside tissue or <code>1</code> if the spot falls inside tissue. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.
        </td>
    </tr>
</tbody></table>
<br>

## `obsm` (Embeddings)

The size of the ndarray stored for a key in `obsm` MUST NOT be zero.

To display a dataset in CELLxGENE Explorer, Curators MUST annotate **one or more** embeddings of at least two-dimensions (e.g. tSNE, UMAP, PCA, spatial coordinates) as `numpy.ndarrays` in `obsm`.<br><br>

---
---

**Editor Note**: Jason recommends that the `spatial` implementation requirements for Explorer (selector names, scaling) be documented elsewhere. Brian says "in for a penny in for a pound". 

---
---

### spatial

<table><tbody>
    <tr>
      <th>Key</th>
      <td>spatial. For each available underlay image in <code>uns['spatial'][<i>library_id</i>]['images']</code>, CELLxGENE Explorer MUST add a corresponding item to its Embedding Choice selector and appropriately scale the embedding:<br><br>
        <ul>
        <li>CELLxGENE Explore MUST add a selector item named <code>"spatial_HighRes_Map"</code> and MUST scale the full resolution embedding by the value of <code>uns['spatial'][<i>library_id</i>]['scalefactors']['tissue_hires_scalef']</code>.</li><br>
        <li>If <code>uns['spatial'][<i>library_id</i>]['images']['fullres']</code> is present, then CELLxGENE Explorer MUST add a selector item named <code>"spatial_FullRes_Map"</code> and MUST NOT scale the full resolution embedding.</li><br>
        </ul>
        If <code>"spatial"</code> is set as the <code>default_embedding</code>, then Explorer MUST present <code>"spatial_HighRes_Map"</code> as the default.
        </td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate if <b>Visium Single</b>.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>numpy.ndarray</code>. The array MUST be constructed from the corresponding <code>pxl_row_in_fullres</code> and <code>pxl_col_in_fullres</code> fields from in <code>tissue_positions_list.csv</code> or <code>tissue_positions.csv</code>. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.<br><br>
        </td>
    </tr>
</tbody></table>
<br>

 ---

### X_{suffix}

<table><tbody>
    <tr>
      <th>Key</th>
      <td>X_{suffix} with the following requirements:<br><br>
      <ul>
        <li>{suffix} MUST be at least one character in length.</li>
        <li>The first character of {suffix} MUST be a letter of the alphabet and the remaining characters MUST be alphanumeric characters. (This is equivalent to the regular expression pattern <code>"^[a-zA-Z][a-zA-Z0-9]*$"</code>.)</li>
         <li>{suffix} MUST NOT be <code>"spatial"</code>.
      </ul><br>
      {suffix} is presented as text to users in the <b>Embedding Choice</b> selector in CELLxGENE Explorer so it is STRONGLY RECOMMENDED that it be descriptive.<br><br>See also <code>default_embedding</code> in <code>uns</code>.</td>
    </tr>
    <tr>
      <th>Annotator</th>
         <td>Curator MUST annotate if NOT <b>Visium Single</b>.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>numpy.ndarray</code> with the following requirements<br><br>
          <ul>
          <li>MUST have the same number of rows as <code>X</code> and MUST include at least two columns</li>
          <li>MUST be a <a href="https://numpy.org/doc/stable/reference/generated/numpy.dtype.kind.html"><code>numpy.dtype.kind</code></a> of <code>"f"</code>, <code>"i"</code>, or "<code>u"</code></li>
          <li>MUST NOT contain any <a href="https://numpy.org/devdocs/reference/constants.html#numpy.inf">positive infinity (<code>numpy.inf</code>)</a> or <a href="https://numpy.org/devdocs/reference/constants.html#numpy.NINF">negative infinity (<code>numpy.NINF</code>)</a> values </li>
          <li>MUST NOT contain all <a href="https://numpy.org/devdocs/reference/constants.html#numpy.nan">Not a Number (<code>numpy.nan</code>) </a>
values</li></ul>
        </td>
    </tr>
</tbody></table>
<br>

## `uns` (Dataset Metadata)

...

### default_embedding

<table><tbody>
    <tr>
      <th>Key</th>
      <td>default_embedding</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MAY annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>str</code>. The value MUST match a key to an embedding in <code>obsm</code> for the embedding to display by default in CELLxGENE Explorer.
        </td>
    </tr>
</tbody></table>
<br>

### spatial

---
---

**Editor Note: Add a requirement that only the fields documented in the schema must be present under <code>spatial</code>.**

---
---

<table><tbody>
    <tr>
      <th>Key</th>
      <td>spatial</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>dict</code>. The key-value pairs are documented in the following sections:
          <ul>
          <li>spatial[<i>library_id</i>]</li>
          <li>spatial[<i>library_id</i>]['images']</li>
          <li>spatial[<i>library_id</i>]['images']['fullres']</li>
          <li>spatial[<i>library_id</i>]['images']['hires']</li>
          <li>spatial[<i>library_id</i>]['metadata']</li>
          <li>spatial[<i>library_id</i>]['scalefactors']</li>
          <li>spatial[<i>library_id</i>]['scalefactors']['spot_diameter_fullres']</li>
          <li>spatial[<i>library_id</i>]['scalefactors']['tissue_hires_scalef']</li>
         </ul>
        </td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]
<table><tbody>
    <tr>
      <th>Key</th>
      <td>Identifier for the Visium library</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>dict</code>. There MUST be only one <code><i>library_id</i></code>.</td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]['images']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>images</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>dict</code>
        </td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]['images']['fullres']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>fullres</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MAY annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>ndarray</code><br><br>It is STRONGLY RECOMMENDED that the submitter include the full resolution image which MUST be converted to an array of shape (, , 3).
        </td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]['images']['hires']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>hires</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>ndarray</code><br><br><code>tissue_hires_image.png</code> MUST be converted to an array of shape (, , 3). Its largest dimension MUST be 2000 pixels. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.
        </td>
    </tr>
</tbody></table>
<br>

---
---

**Editor Note: Document that <code>metadata</code> is supported for scverse cases.**

---
---

#### spatial[_library_id_]['metadata']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>metadata</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MAY annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>dict</code>
        </td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]['scalefactors']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>scalefactors</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>dict</code>
        </td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]['scalefactors']['spot_diameter_fullres']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>spot_diameter_fullres</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>float</code>. This must be the value of the <code>spot_diameter_fullres</code> field from <code>scalefactors_json.json</code>. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.</td>
    </tr>
</tbody></table>
<br>

#### spatial[_library_id_]['scalefactors']['tissue_hires_scalef']
<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue_hires_scalef</td>
    </tr>
    <tr>
      <th>Annotation</th>
      <td>Curator MUST annotate if <b>Visium Single</b>; otherwise, this key MUST NOT be present.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>float</code>. This must be the value of the <code>tissue_hires_scalef</code> field from <code>scalefactors_json.json</code>. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.
        </td>
    </tr>
</tbody></table>
<br>

---
---

**Editor Note: Removed `slide_version` in favor of @jychien's [proposal for adding EFO terms](https://czi-sci.slack.com/archives/C02TSE92DBM/p1707330756115809?thread_ts=1707159001.961109&cid=C02TSE92DBM):**

* Visium Spatial Gene Expression (existing)
  * Visium Spatial Gene Expression V1 (max X/Y is 128/78; total spots: 4992)
* Visium CytAssist Spatial Gene Expression
  * Visium CytAssist Spatial Gene Expression V4 (6.5 mm, max X/Y is 128/78; total spots: 4992)
  * Visium CytAssist Spatial Gene Expression V5 (11 mm, max X/Y is 224/128; total spots: 14336)
.

---
---

## Appendix A. Changelog

schema v4.1.0

* Introduced formal validation for *Visium Spatial Gene Expression* based on modeling in scanpy and squidpy.

**Comment by jahilton** [comment]
for in_tissue:0 observations, I would expect a dependency with cell_type. The cell_type_ontology_term_id MUST be ____ (I suggest to add a new value like `empty`).

---
Could enforce tissue_type is tissue or organoid if it's Visium.

---
There is nothing that addresses single section/library Datasets vs integrated Datasets. So currently, images & spatial embeddings are required for datasets where multiple slides have been integrated and those aren't as useful.
Aggregated Datasets will be required to submit one (and only one) hires image?
And are downstream features OK with consuming Datasets that will differ in this key aspect? (I would assume that they'd like to ignore the integrated cases and only consume the individual sections)

---
>Or should the library_id be eliminated - it's used for aggregation in frameworks.

☝️ For a Dataset with a single section/library, this is unnecessary. Something that the downstream features can consider adding (in a standardized & globally unique manner) as they are aggregating Datasets for users.

---
What is the value prop for the lowres when the hires is required?

---
Is there value in storing the Capture Area size? Could it be calculated from the array_*?

---
I don't understand how X_suffix is deprecated?
Seems like obsm requirements don't change?

---
I don't understand how default_embedding is deprecated?
There will be no way for any Dataset (Visium or not) to specify the obsm of choice?

---
uns.embeddings - 3 different identifiers seems excessive
What is the value prop to offer a "title" that differs from the current display of the obsm key?
Can't we enforce a single obsm key that these refer to (see my comment below about scaling)?
Or require a consistency between image key & obsm key?

---
uns.embeddings only stores info for spatial-related embeddings? Or are there implications for non-Visium datasets too?

---
> CELLxGENE Explorer MUST automatically apply the corresponding scalefactor from uns['spatial'][library_id]['scalefactors'] to the embedding.

So the embedding are not scaled to each image at submission? Wouldn't this mean that each of the uns.embeddings point to the same obsm key, and that will just get scaled differently?

---
What is the benefit to scaling on CxG-side instead of putting that on the user?

---
Have we contacted 10x to ensure there are no plans to rename `hires`? This proposal is putting a lot of stock on their naming convention (esp when it can be misleading to some people - "the _hi_ res isn't the highest?")

**Comment by jychien** [comment]
Thanks for the thorough schema proposal, Brian! Some general thoughts:
- Overall, the overfitting (such as array_row and array_col) lends itself to be in lock step with Space Ranger. Seurat and Scanpy/Squidpy have also gone this path, and there is overall [confusion](https://github.com/satijalab/seurat/issues/6338) whenever old/new files are not in sync with the software version that users are running. If we are all aware and are fine with this type of data modeling, then that's fine, and we will migrate whenever Space Ranger has updates. Then it makes sense to match our CxG schema to Scanpy/Squidpy, so to ease wrangling efforts by curators or contributors.
- Majority of the schema coincides with Scanpy/Squidpy. I would say that there could be some more clarity and efficiency made with storing of X/Y coordinates. If the scalefactors are required to be named with the resolution of the image, does the image need to be matched up to the corresponding pre-scaled X/Y coordinates? I had initially mentioned that we wanted the post-scaling X/Y coordinates to help with QA, but if we are already requiring scaling factors, we can just use those and scale the embedding ourselves. I anticipate confusion as to which set of X/Y coordinates to put where, so something straight forward is best.

**Comment by brianraymor** [comment]
# Rewrite for Embeddings

**Editor's Note: The Explorer selector names are simply placeholders. I defer the actual names to @niknak33.**

Per @jahilton's proposal:

1. `default_embedding` is resurrected.
2. `embeddings are replaced by spatial and X_{suffix}
3. {suffix} MUST NOT be "spatial"

## `obsm` (Embeddings)

The size of the ndarray stored for a key in `obsm` MUST NOT be zero.

To display a dataset in CELLxGENE Explorer, Curators MUST annotate **one or more** embeddings of at least two-dimensions (e.g. tSNE, UMAP, PCA, spatial coordinates) as `numpy.ndarrays` in `obsm`.<br><br>

## spatial

<table><tbody>
    <tr>
      <th>Key</th>
      <td>spatial. For each available underlay image in <code>uns['spatial'][<i>library_id</i>]['images']</code>, CELLxGENE Explorer MUST add a corresponding item to its Embedding Choice selector and appropriately scale the embedding:<br><br>
        <ul>
        <li>CELLxGENE Explore MUST add a selector item named <code>"spatial (with high resolution)"</code> and MUST scale the full resolution embedding by the value of <code>uns['spatial'][<i>library_id</i>]['scalefactors']['tissue_hires_scalef']</code>.</li><br>
        <li>If <code>uns['spatial'][<i>library_id</i>]['images']['tissue_fullres_image']</code> is present, then CELLxGENE Explorer MUST add a selector item named <code>"spatial (with full resolution)"</code> and MUST NOT scale the full resolution embedding.</li><br>
        <li>If <code>uns['spatial'][<i>library_id</i>]['images']['tissue_lowres_image']</code> is present, then CELLxGENE Explore MUST add a selector item named <code>"spatial (with low resolution)"</code> and MUST scale the full resolution embedding by the value of <code>uns['spatial'][<i>library_id</i>]['scalefactors']['tissue_lowres_scalef']</code>.</li>
        </ul>
        </td>
    </tr>
    <tr>
      <th>Annotator</th>
         <td>Curator MUST annotate if the <code>assay_ontology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0010961">EFO:0010961</a> for <i>Visium Spatial Gene Expression</i>.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>numpy.ndarray</code>. The array MUST be constructed from the corresponding <code>pxl_row_in_fullres</code> and <code>pxl_col_in_fullres</code> fields from <code>tissue_positions.csv</code>. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/spatial-outputs">Space Ranger Spatial Outputs</a>.<br><br>
        </td>
    </tr>
</tbody></table>
<br>

 ---

## X_{suffix}

<table><tbody>
    <tr>
      <th>Key</th>
      <td>X_{suffix} with the following requirements:<br><br>
      <ul>
        <li>{suffix} MUST be at least one character in length.</li>
        <li>The first character of {suffix} MUST be a letter of the alphabet and the remaining characters MUST be alphanumeric characters. (This is equivalent to the regular expression pattern <code>"^[a-zA-Z][a-zA-Z0-9]*$"</code>.)</li>
         <li>{suffix} MUST NOT be <code>"spatial"</code>.
      </ul><br>
      {suffix} is presented as text to users in the <b>Embedding Choice</b> selector in CELLxGENE Explorer so it is STRONGLY RECOMMENDED that it be descriptive.<br><br>See also <code>default_embedding</code> in <code>uns</code>.</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>numpy.ndarray</code> with the following requirements<br><br>
          <ul>
          <li>MUST have the same number of rows as <code>X</code> and MUST include at least two columns</li>
          <li>MUST be a <a href="https://numpy.org/doc/stable/reference/generated/numpy.dtype.kind.html"><code>numpy.dtype.kind</code></a> of <code>"f"</code>, <code>"i"</code>, or "<code>u"</code></li>
          <li>MUST NOT contain any <a href="https://numpy.org/devdocs/reference/constants.html#numpy.inf">positive infinity (<code>numpy.inf</code>)</a> or <a href="https://numpy.org/devdocs/reference/constants.html#numpy.NINF">negative infinity (<code>numpy.NINF</code>)</a> values </li>
          <li>MUST NOT contain all <a href="https://numpy.org/devdocs/reference/constants.html#numpy.nan">Not a Number (<code>numpy.nan</code>) </a>
values</li></ul>
        </td>
    </tr>
</tbody></table>
<br>

**Comment by niknak33** [comment]
Thanks Brian

I was thinking something along these lines:

HighRes_Map, FullRes_Map, and LowRes_Map for the names, I believe those
follow the guidelines.

Thank you,

Nik.

**Comment by brianraymor** [comment]
I performed the renames for HighRes_Map and FullRes_Map. We agreed to not support low resolution images.

**Comment by niknak33** [comment]
I totally understand that; I just assumed you might want it in case you
wanted to reference it at some point.

Thanks,

Nik

**Comment by brianraymor** [comment]
| Assay | "raw" required? | "raw" location | "normalized" required? | "normalized" location |
|-|-|-|-|-|
| Visium Spatial Gene Expression | REQUIRED. The unfiltered feature-barcode matrix (<code>raw_feature_bc_matrix</code>) MUST be used. See <a href="https://www.10xgenomics.com/support/software/space-ranger/analysis/outputs/space-ranger-feature-barcode-matrices">Space Ranger Feature-Barcode Matrices</a>. Values MUST be de-duplicated molecule counts. All non-zero values MUST be positive integers stored as `numpy.float32`.| `AnnData.raw.X` unless no "normalized" is provided, then `AnnData.X` | STRONGLY RECOMMENDED.<br>This MUST be a <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html"><code>scipy.sparse.csr_matrix</code></a>. If the <code>obs['in_tissue']</code> is <code>0</code> for an observation, then the values of its corresponding variable references MUST be <a href="https://docs.scipy.org/doc/scipy/tutorial/sparse.html#sparse-arrays-implicit-zeros-and-duplicates">implicit zero</a>. | `AnnData.X` |
|||||

**Comment by pablo-gar** [comment]
Looks good to me!

**Comment by jahilton** [comment]
I am expecting further requirements to enforce `The unfiltered feature-barcode matrix (raw_feature_bc_matrix) MUST be used.`

**Comment by brianraymor** [comment]
> I am expecting further requirements to enforce

Do you have specific suggestions for the schema, @jahilton ? CC: @pablo-gar

**Comment by jahilton** [comment]
First thought is require obs count to be in a specific range.

**Comment by jychien** [comment]
My question would be that if I were a Census user and did not want to reprocess each Visium dataset from scratch and wanted to integrate the data, is there a straight forward way to subset to only the spots analyzed by the authors? Would it be implied that I would need to use spots with cell_type not `unknown` and in_tissue:1.

**Comment by pablo-gar** [comment]
From my conversations with SpatialData developers:

> They are moving to a place where the provide defaults for most use case but still enable flexibility, in this case default is to load “in-tissue” data but the flexibility exists

Census is likely to adopt such paradigm as well

**Comment by pablo-gar** [comment]
LGTM! One typo I found

> CELLxGENE Explore MUST add a selector item named "spatial_HighRes_Map" and MUST scale the full resolution embedding by the value of uns['spatial'][library_id]['scalefactors']['tissue_hires_scalef'].

Explore is missing the **r**
