### ISSUE TITLE
Add images and associated metadata to h5ad

### ISSUE THREAD

**Issue by jychien** [chanzuckerberg/single-cell-curation#676]
**Collection**: https://cellxgene.cziscience.com/collections/8191c283-0816-424b-9b61-c3e1d6258a77
I am able to add images and metadata to adata.uns['spatial'] and the x/y coordinates to adata.obsm['spatial']. However, the coordinates in adata.obsm['X_spatial'] do not currently match the lowres nor the hires image. So, if I add an image to adata.uns['image'], it will not match the coordinates in adata.obsm['X_spatial']. So, I can do either or both:

- Add images (both hires and lowres) and metadata only to adata.uns['spatial']. This would include the original X/Y coordinates to adata.obsm['spatial'], parsed from tissue_positions_list.csv, where the coordinates have not been scaled and are whole numbers.
- Add ‘hires’ image to adata.uns['image'] and replace adata.uns['X_spatial'] with adata.uns['spatial'] * adata.uns['spatial']['Visium_8_CK286']['scalefactors']['tissue_hires_scalef']

**Collection**: https://cellxgene.cziscience.com/collections/60358420-6055-411d-ba4f-e8ac80682a2e
I’ve looked at the first dataset listed, and picked Adult A1 as an example. Couple of things to note:

- The orientation of the original raw image embedding (which I’m going to call “orig_spatial”) is different than the spatial embedding being displayed at cxg. Can switch X & Y coordinate for it to match the lowres image. 
- The spatial embedding being displayed at cxg has max values of 484.46 & 541.12, whereas the orig_spatial has max values of 6351 & 5686. So, the image can be displayed correcly with the orig_spatial embedding using the tissue_hires_scalef or tissue_lowres_scalef to calculate scaling. 
- After multiplying the orig_spatial by the tissue_lowres_scalef , it looks like the current spatial embedding is based off of the lowres image.

**Comment by brianraymor** [comment]
Temporarily tracking this curation issue in the related **Discovery** epic for visibility.

**Comment by brianraymor** [comment]
@jychien @jahilton - does this issue need to remain open until the changes are published or has it be addressed in revisions?

**Comment by jychien** [comment]
This has been addressed in revisions. I will close this ticket.
