### ISSUE TITLE
Greatly relax dependencies for CLI

### ISSUE THREAD

**Issue by Zethson** [chanzuckerberg/single-cell-curation#677]
## Motivation

The package is currently really hard to install in environments with other packages. The pins are too strict and use old versions that are no longer supported.

See:
https://github.com/chanzuckerberg/single-cell-curation/blob/b680cc775c5bae53c73a1a64ee21a659dea102ec/cellxgene_schema_cli/requirements.txt

## Definition of Done

Please unpin as many packages as possible and reasonable. Please also ensure that the package still works with the newer version. There may be issues with Pandas.

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ] Unpin dependencies one by one in https://github.com/chanzuckerberg/single-cell-curation/blob/b680cc775c5bae53c73a1a64ee21a659dea102ec/cellxgene_schema_cli/requirements.txt#L1
- [ ] Test the package.

**Comment by brianraymor** [comment]
We generally recommend the use of `venv` or `pipx`. The CLI is primarily for use by our curators and our ingestion pipeline which accounts for the strictness.  For example we currently only accept anndata 0.8.0 datasets per the schema. 

Can you tell me more about your use of the CLI?

**Comment by Zethson** [comment]
We subclassed your Validator and implemented some of our own checks.

**Comment by brianraymor** [comment]
> implemented some of our own checks.

Can you share more details?

**Comment by Zethson** [comment]
It's a private repository. Nevertheless, we just wanted a quick and dirty Validator that checks whether specific columns are present and for those columns we only wanted to allow specific terms.

It's nothing complex.

**Comment by brianraymor** [comment]
I'm glad that you were able to reuse the code.

**Comment by Zethson** [comment]
So you're not planning to relax the dependencies?

**Comment by brianraymor** [comment]
That is correct per me comments above.
