### ISSUE TITLE
survey use of "tissue_type" in existing 

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#678]
schema 4.0.0 will introduce obs.tissue_type as a schema field.
In order to be more informed about how to migrate Datasets, it will be very helpful to survey the existing cases - what Collections & Datasets currently have obs.tissue_type present and how do they use it (what are the values)?
From this report, we can determine if we want to migrate (rename) this field on a per-dataset basis, or if they can all be batch renamed.

Implementation Note From Nayib: leverage TileDB to iterate over cxgs. Can potentially leverage existing analytics [scripts](https://github.com/chanzuckerberg/single-cell-analytics/blob/main/inputs/extract_discover_data.py) with small tweaks

**Comment by nayib-jose-gloria** [comment]
2 currently published datasets have obs.tissue_type:

- "Human Multiple Cortical Areas SMART-seq" in [Transcriptomic cytoarchitecture reveals principles of human neocortex organization](https://cellxgene.cziscience.com/collections/d17249d2-0e6e-4500-abb8-e6c93fa1ac6f)
        - There is a single value for all rows--"postmortem"
- "Integrated Single-nucleus and Single-cell RNA-seq of the Adult Human Kidney" in [An atlas of healthy and injured cell states and niches in the human kidney](https://cellxgene.cziscience.com/collections/bcb61471-2a44-4d00-a0af-ff085512674c)
        - The values are 'Biopsy', 'Deceased Donor', and 'Nephrectomy'

**Comment by nayib-jose-gloria** [comment]
@jahilton and 2 currently private uploaded datasets as well:

- "Oligodendrocytes in MS" in [Single nuclei RNA- sequencing from the white matter of individuals with progressive MS and non-neurological controls](https://cellxgene.cziscience.com/collections/16c1e722-96ae-4bf6-b408-cd7f8918484f)
        - There is a single value for all rows--"tissue"
- "snRNA-seq data for human cerebella from 9-12 developmental stages" in [Cellular development and evolution of the mammalian cerebellum
](https://cellxgene.cziscience.com/collections/72d37bc9-76cc-442d-9131-da0e273862db)
        - There is a single value for all rows--"tissue"

**Comment by jahilton** [comment]
Fantastic. I just pushed a commit to migrate the Published cases.
The 2 Private are being actively worked on so we will remove tissue_type ahead of the migration.
