### ISSUE TITLE
Amend collection information of "A human cell atlas of fetal gene expression"

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#68]
Requests from Jay Shendure about this collection:

[](https://cellxgene.cziscience.com/collections/c114c20f-1ef4-49a5-9c2e-d965787fb90c
)

> 1) is it possible to add Cole Trapnell <coletrap@uw.edu> and Junyue
> Cao <jcao@rockefeller.edu> to the list of contacts as well?
> 2) can website be changed to https://descartes.brotmanbaty.org/

**Comment by brianraymor** [comment]
The portal does not support multiple contacts.

**Comment by pablo-gar** [comment]
Added  https://descartes.brotmanbaty.org/ as data source
