### ISSUE TITLE
Question about cell type annotation

### ISSUE THREAD

**Issue by JY-97** [chanzuckerberg/single-cell-curation#681]
I observe that there is cell type annotation at different resolutions. For example, most B cells are annotated as B cells in PBMC, while some are annotated at fine granularity, such as mature B cells. Is there a criterion for these annotations? And is there a recommended way to get the full cell type ontology for each cell record?

Many thanks!

**Comment by BAevermann** [comment]
Hello Jinyuan!

You are indeed correct. The cell type annotations are applied at varying
resolution across datasets. This is the result of our curation/ingestion
process where the data contributor (usually the lab that generated the
data) is responsible for assigning cell types at the level they feel
comfortable which leads to the heterogeneity in resolution. Could you
explain "full cell type ontology for each cell record" a bit more for me?
Do you want to see a given cell type within its ontological context? If so,
the Cell Guide tool might be of help as it has an easily navigable tree
view of the ontology that focuses on a given cell type. See here for the B
cell example <https://cellxgene.cziscience.com/cellguide/CL_0000236> used
earlier.

Thanks!

Brian Aevermann

**Comment by JY-97** [comment]
Hi Brian, Thank you for your time and explanation! Now I understand that. My expression of "full cell type ontology" might not be the standard terminology and sorry for the misunderstanding. My initial point was trying to retrieve the finest possible cell type annotation and also the higher level of annotation along the Cell ontology hierarchy. I have looked in the resource you provide and will try to achieve that using some computational ways. Thanks again for the information!

Best,
Jinyuan
