### ISSUE TITLE
Remove or update empty dictionary

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#683]
In [collection,](https://cellxgene.cziscience.com/collections/3116d060-0a8e-4767-99bb-e866badea1ed) I noticed that the _Visium spatial - SAN dataset_ has an empty dictionary in `.uns`:

`'log1p': {},`

This same pattern appears to be repeated in other datasets in the same collection.

**Comment by jahilton** [comment]
empty uns values were removed corpus-wide during the 5.0.0 migration. confirmed in the Dataset mentioned in the description.
