### ISSUE TITLE
tighten development_stage_ontology_term_id allowances for ontology terms

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/single-cell-curation#685]
development_stage_ontology_term_id

- human: MUST be the most accurate child of `HsapDv:0000001` for _life cycle_
- mouse: MUST be the most accurate child of `MmusDv:0000001` for _life cycle_

**Comment by brianraymor** [comment]
I'd prefer that all updates to HsapDv and MmusDV be addressed together. I'm blocking this on [Assess impact of updating HsapDv and MmusDv](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/401).

**Comment by brianraymor** [comment]
Addressing in #884
