### ISSUE TITLE
Misformatted datasets/explorer instances in the MSK 

### ISSUE THREAD

**Issue by MaximilianLombardo** [chanzuckerberg/single-cell-curation#693]
## Bug report

Hi all - [a user identified](https://github.com/chanzuckerberg/cellxgene-census/issues/862) that plotting gene expression is not functional in all of the explorer instances for this collection: [MSK SPECTRUM – Ovarian cancer mutational processes drive site-specific immune evasion](https://cellxgene.cziscience.com/collections/5b83b2ec-668f-438c-b578-c6b85a84f971).

When searching a gene in the quick gene search, the gene appears and can be added to the UI. The expected histogram of gene expression values (distribution of expression values across all cells in the dataset) does not appear. This behavior is only observed for some genes (see screenshot below). Since other collections don't seem to be affected, it may be a curation/dataset formatting issue .

<img width="365" alt="image" src="https://github.com/chanzuckerberg/single-cell-curation/assets/25663501/4639db8c-698b-46bc-ac51-6117e0368d6e">

cc: @dominikglodzikhms

**Comment by jahilton** [comment]
Correct CELLxGENE URL: https://cellxgene.cziscience.com/collections/4796c91c-9d8f-4692-be43-347b1727f9d8
Quick look at the Dendritic Cells Dataset and there does seem to be a general disagreement between the raw count layer & normalized layer for a handful of genes. So we'll keep this issue to investigate and possibly revise.

However, MALAT1 & ATM currently have all 0 values for that Dataset, which can explain what you're seeing in Explorer. So if there is a separate issue that you expect a different Explorer experience, then that should be a separate ticket.

**Comment by MaximilianLombardo** [comment]
Ps just sharing some additional context w.r.t. what I got for the expression values in the dendritic cells object for MALAT1 - So I am seeing non-zero values in the normalized layer

<img width="1214" alt="image" src="https://github.com/chanzuckerberg/single-cell-curation/assets/25663501/ed752ce5-ff31-425e-b91f-7ad5f1a2b4e2">

**Comment by jahilton** [comment]
@jychien & I have tracked down the curation side of the issue. The X layer in these Datasets have had significant gene filtering relative to the raw layer. Looks like not all filtered genes were marked as feature_is_filtered=True. But that is why some genes have raw data but all 0s in X.

(@MaximilianLombardo not sure about the array values you're seeing, but the UMAP plot is showing the expression from the raw layer - the plot may default `use_raw=True`)

**Comment by jahilton** [comment]
✅ feature_is_filtered has been correct & the revision Published
