### ISSUE TITLE
Datasets with multiple species break current schema

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#7]
Current [schema](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/schema/corpora_schema.md) v1.1.0 requires that species is indicated in the `uns` object of the anndata. 

Datasets that have integrated single-cell data from multiple organisms contain cells for each of those. As `uns` is dataset-level metadata it will be impossible to properly annotate this type of datasets.

Moving the `organism_ontology_term_id` and `organism` slots from `uns` to `obs` in the schema will solve this problem.

**Comment by brianraymor** [comment]
> Moving the `organism_ontology_term_id` and `organism` slots from `uns` to `obs` in the schema will solve this problem.

Addressed in schema 2.0.0.
