### ISSUE TITLE
Add description to schema

### ISSUE THREAD

**Issue by rcannood** [chanzuckerberg/single-cell-curation#700]
## Motivation

I'm working on aligning the data formats used in OpenProblems to that of the CELLxGENE census corpus, because it will allow us to pull a lot of datasets directly from cellxgene census. I'm working on adding some documentation for my code and the schema of the datasets we use in this project, but it seems like the CELLxGENE schema specified in this repo doesn't contain a very descriptive description for each of the keys in the schema.

For instance, for [`cell_type_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/schema.md#cell_type_ontology_term_id), the schema contains:

> ### cell_type_ontology_term_id
> 
> <table><tbody>
>     <tr>
>       <th>Key</th>
>       <td>cell_type_ontology_term_id</td>
>     </tr>
>     <tr>
>       <th>Annotator</th>
>       <td>Curator</td>
>     </tr>
>     <tr>
>       <th>Value</th>
>         <td>categorical with <code>str</code> categories. This MUST be a CL term.
>         </td>
>     </tr>
> </tbody></table>

And for [`cell_type`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/schema.md#cell_type):

> ### cell_type
> 
> <table><tbody>
>     <tr>
>       <th>Key</th>
>       <td>cell_type</td>
>     </tr>
>     <tr>
>       <th>Annotator</th>
>       <td>CELLxGENE Discover</td>
>     </tr>
>     <tr>
>       <th>Value</th>
>         <td>categorical with <code>str</code> categories. This MUST be the human-readable name assigned to the value of <code>cell_type_ontology_term_id</code>.
>         </td>
>     </tr>
> </tbody></table>

## Definition of Done

Add a description to each of the elements in the schema.md file.

For example:
  * `cell_type_ontology_term_id`: "categorical with `str` categories. Classification of the cell type based on its characteristics and function within the tissue or organism. This MUST be a Cell Ontology (`CL:`) term."
  * `cell_type`: "categorical with `str` categories. Classification of the cell type based on its characteristics and function within the tissue or organism. This MUST be the human-readable name assigned to the value of `cell_type_ontology_term_id`. "

Is the [`schema.md`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/schema.md) file somehow automatically generated from the [`schema_definition.yaml`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml) file? I looked through the code but couldn't immediately find a script to do this. 

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ] Add descriptions to each of the elements in the schema.md file.
- [ ] Optional: Also store these descriptions in the `schema_definition.yaml` file. This would allow generating the `schema.md` file from the `schema_definition.yaml` if this is not already the case.

If it helps, I'm more than happy to create a PR with proposed changes to the `schema.md`/`schema_definition.yaml` files.

**Comment by brianraymor** [comment]
> Is the [schema.md](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.1.0/schema.md) file somehow automatically generated from the [schema_definition.yaml](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml) file?

Hi @rcannood,

I'm the editor for the schema. It's not _automagically_ generated.

**Comment by brianraymor** [comment]
Reviewed in small group. Closing. 

The schema is focused on minimal normative requirements for a primary audience of the curation and engineering teams. 

For these audiences, more non-normative descriptive text is not helpful. It increases review time and introduces the potential for extended _bikeshedding_ descriptions based on varying opinions.
