### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by agurdita** [chanzuckerberg/single-cell-curation#707]
Hi, 

Can the dataset from this publication be added: https://academic.oup.com/hmg/article/32/10/1698/6988025

Thanks,

**Comment by BAevermann** [comment]
Hello agurdita!

**Comment by agurdita** [comment]
I dont know anyone personally at this lab but I can reach out to the corresponding author to recommend publishing in CellxGene.

**Comment by BAevermann** [comment]
That would be great! 
We find that data generators both appreciate and respect fellow researchers reusing their data and are more motivated to submit. 
In the email, you can direct them to cellxgene@chanzuckerberg.com and our curators will pick it up from there. Thanks!
