### ISSUE TITLE
cellxgene-schema must update validation for disease_ontology_term_id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#719]
# Context

See [disease_ontology_term_id](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.1.0/schema.md#disease_ontology_term_id).

## 4.0.0 was:

This MUST be a MONDO term or `"PATO:0000461"` for _normal or healthy_

## 4.1.0 adds further requirements:

This MUST be one of:
- `"PATO:0000461"` for _normal or healthy_
- the most accurate child of `"MONDO:0000001"`for _disease_
- `"MONDO:0021178"` for _injury_ or **preferably** its most accurate child

**Comment by joyceyan** [comment]
@brianraymor @danieljhegeman Is there any way for us to know if the MONDO term provided is the most accurate term for the disease / injury? Or would the work on the validation side just be to verify that a MONDO term provided is a child of either MONDO:0000001 or MONDO:0021178?

**Comment by brianraymor** [comment]
>  Is there any way for us to know if the MONDO term provided is the most accurate term for the disease / injury?

No. This _language_ is a common pattern for schema fields for curators _to encourage_ the submitter to not use a general term (which often happens in the first iteration). Curators will often review the research and request the submitter to update the precision.

**Comment by danieljhegeman** [comment]
>most accurate child

@brianraymor please confirm: a _child_ is a _direct descendant_, and not a _multi-level descendant_, i.e. B is a child of A but C is not a child of A in: A > B > C where A is the foremost ancestor. cc @joyceyan

**Comment by danieljhegeman** [comment]
![image](https://github.com/chanzuckerberg/single-cell-curation/assets/23110111/9c34ac1a-d055-4992-ad99-43b31d9f2d2b)

**Comment by brianraymor** [comment]
Let's use a concrete, simple case - [MONDO](https://www.ebi.ac.uk/ols4/ontologies/mondo).

It's any descendant of the `disease` root:

<img width="440" alt="Screenshot 2024-01-25 at 10 22 17 AM" src="https://github.com/chanzuckerberg/single-cell-curation/assets/3644743/b1248e41-f610-45c7-a274-44d6fa777b71">


which unfortunately allows [non-human animal disease](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0005583?lang=en) to be specified for human observations at the moment per my comments in [**#cell-science-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1706143382081429).

**Comment by danieljhegeman** [comment]
@brianraymor Ok, thanks for clarifying. I'll make a ticket to change the language in the schema and code base.

**Comment by danieljhegeman** [comment]
[Approved by Lattice](https://czi-sci.slack.com/archives/C06AVGFV222/p1706304831084439?thread_ts=1706221540.055719&cid=C06AVGFV222)
