### ISSUE TITLE
Cell Ontology (CL) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#72]
The following ontology dependency is *pinned* for this version of the schema. 

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Cell Ontology] | CL | [cl.owl] : [2021-06-21]|

[Cell Ontology]: http://obofoundry.org/ontology/cl.html
[2021-06-21]: https://github.com/obophenotype/cell-ontology/releases/tag/v2021-06-21
[cl.owl]: https://github.com/obophenotype/cell-ontology/blob/v2021-06-21/cl.owl

**Parsing requirement:**
- Extract the term identifier and its human-readable label

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
