### ISSUE TITLE
uns must not contain values of zero length

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-curation#728]
See [schema ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/684)

**Comment by brianraymor** [comment]
Doh. Auto-closed the wrong issue.

**Comment by joyceyan** [comment]
I re-opened the issue since we discovered a bug with this while running the dev migration. But it should be resolved by this, so re-closing this issue. https://github.com/chanzuckerberg/single-cell-curation/pull/803
