### ISSUE TITLE
Experimental Factor Ontology (EFO) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#73]
The following ontology dependency is *pinned* for this version of the schema. 

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Experimental Factor Ontology] | EFO | [efo.owl] : [2021-06-15 EFO 3.31.0]

[Experimental Factor Ontology]: http://www.ebi.ac.uk/efo
[2021-06-15 EFO 3.31.0]: https://github.com/EBISPOT/efo/releases/tag/v3.31.0
[efo.owl]: https://github.com/EBISPOT/efo/releases/download/v3.31.0/efo.owl

**Parsing requirements:**
- Extract the term identifier and its human-readable label
- Extract the following children per [`assay_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#assay_ontology_term_id) for warnings during validation:

    An assay based on 10X Genomics products SHOULD either be <a href="http://www.ebi.ac.uk/efo/EFO_0008995"><code>"EFO:0008995"</code></a> for <i>10x technology</i> or <b>preferably</b> its most accurate child. Other assays SHOULD be the most accurate child of either <a href="http://www.ebi.ac.uk/efo/EFO_0002772">EFO:0002772</a> for <i>assay by molecule</i> or <a href="http://www.ebi.ac.uk/efo/EFO_0010183">EFO:0010183</a>  for <i>single cell library construction</i>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
