### ISSUE TITLE
cellxgene-schema CLI must update validation for cell_type_ontology_term_id and annotation for cell_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#735]
# Context

See [Update now-obsolete 'native cell' in schema](https://github.com/chanzuckerberg/single-cell-curation/issues/622).

---

# Changelog

  * Updated the requirements for `cell_type` to annotate`"unknown"` as the label when the `cell_type_ontology_term_id`value  is  `"unknown"`. 
  * Updated the requirements for `cell_type_ontology_term_id` to replace `"CL:0000003"` for *native cell* with `"unknown"` to indicate that the cell type is unknown. 

---

# Schema

See [cell_type_ontology_term_id](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.1.0/schema.md#cell_type_ontology_term_id)
See [cell_type](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.1.0/schema.md#cell_type)

**Comment by danieljhegeman** [comment]
This validation change should also be applied to `tissue_ontology_term_id` per conversation with @brianraymor 

Brian, do you plan on making analogous updates to the schema text for `tissue_ontology_term_id`?

**Comment by brianraymor** [comment]
Per my response on the call this morning, I felt this was already addressed by the requirement in `tissue_ontology_term_id`:

> If tissue_type is "cell culture" this MUST follow the requirements for cell_type_ontology_term_id.

**Comment by danieljhegeman** [comment]
Acknowledged. I had missed the connecting `tissue_type` designator.
