### ISSUE TITLE
Mondo Disease Ontology (MONDO) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#76]
The following ontology dependency is pinned for this version of the schema.

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Mondo Disease Ontology] | MONDO |[mondo.owl] : [2021-06-01] |

[Mondo Disease Ontology]: http://obofoundry.org/ontology/mondo.html
[2021-06-01]: https://github.com/monarch-initiative/mondo/releases/tag/v2021-06-01
[mondo.owl]: https://github.com/monarch-initiative/mondo/releases/download/v2021-06-01/mondo.owl

**Parsing requirement:**
- Extract the term identifier and its human-readable label

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
