### ISSUE TITLE
Mouse Development Stages (MmusDv) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#77]
The following ontology dependency is pinned for this version of the schema.

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Mouse Developmental Stages]| MmusDv |  [mmusdv.owl] : [2016-07-06 (0.1)] |

[Mouse Developmental Stages]: http://obofoundry.org/ontology/mmusdv.html
[mmusdv.owl]: https://github.com/obophenotype/developmental-stage-ontologies/blob/0.1/src/mmusdv/mmusdv.owl

**Parsing requirements:**
- Extract the term identifier and its human-readable label

There are recommended terms for different stages in [`development_stage_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#development_stage_ontology_term_id), but enforcement should rely more on curation review by Stanford than validation warnings.

Note: The `ontology.json` could annotate STRONGLY RECOMMENDED MmusDv terms with a `recommended` flag. This could be used to warn curators when development stage values did not fall into the recommended ranges.

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
