### ISSUE TITLE
Update requirements for feature_length

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#778]
# Context

Should  the[`feature_length`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#feature_length) requirements be updated per the conversation in [**#single-cell-platform**](https://czi-sci.slack.com/archives/C06AVGFV222/p1707852003073529?thread_ts=1707412552.115149&cid=C06AVGFV222).

@pablo-gar's [**Feb 20 2024 summary**](https://czi-sci.slack.com/archives/C06AVGFV222/p1708475995183779?thread_ts=1707412552.115149&cid=C06AVGFV222):

The Comp Bios had a conversation about this (Genevieve, Katrina, Dan, and Sidney).

1. This is the summary:
2. The method "merged length of all isoforms" is a commonly used method to the best of our knowledge.
3. The method "median" may be sensitive to groups of outliers, but in theory it can be a good alternative to 1).
4. The motivation to change the method is to provide more stability of gene lengths over  migrations -- there is a hypothesis that   "merged length of all isoforms" is less stable than "median". However we have no data to indicate that "median" will be more stable.
5. Users who find our all calculations of gene length to be not ideal can calculate genes lengths themselves if needed. We anticipate this number of users is pretty low since  "merged length of all isoforms" is a relatively common practice.
6. Gene lengths are only useful in the context of Smart-seq data, which is <5% of our data. This is a low priority item.

We suggest to not change the method until:

1. We test "median" is more stable over migrations. Test: compare delta of gene lengths for each method, comparing schema 4.0 vs 5.0 artifacts.
2. We test "median" is a good alternative method by checking it is not too sensitive to groups of outliers -- this is our main concern with this method.
3. We (comp bio team) can test this sometime later in Q2 (we are currently maxed out for this quarter, and this is low pri), so it would be done for the next migration(s).

**Comment by pablo-gar** [comment]
@brianraymor and @jahilton 

We are likely to get a contractor to work on this task late Q2 or early Q3. We'll share more as we now more. cc @sidneymbell

**Comment by brianraymor** [comment]
@pablo-gar added a new issue - #960. Closing as duplicate.
