### ISSUE TITLE
NCBI organismal classification (NCBITaxon) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#78]
The following ontology dependency is pinned for this version of the schema.

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [NCBI organismal classification] |  NCBITaxon | [ncbitaxon.owl] : [2021-06-10] |

[NCBI organismal classification]: http://obofoundry.org/ontology/ncbitaxon.html
[2021-06-10]: https://github.com/obophenotype/ncbitaxon/releases/tag/v2021-06-10
[ncbitaxon.owl]: https://github.com/obophenotype/ncbitaxon/releases/download/v2021-06-10/ncbitaxon.owl.gz

**Parsing requirements:**
- A short cut may be to simply add the following into `ontology.json` with the expectation that the identifiers are unchanging:

    This MUST be either "NCBITaxon:9606" for Homo sapiens or "NCBITaxon:10090" for Mus musculus.

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
