### ISSUE TITLE
cellxgene-schema CLI must update annotation of uns['schema_reference'] and uns['schema_version']

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#787]
# Context

See [**schema_reference**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#schema_reference) and [**schema_version**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#schema_version).

**Comment by nayib-jose-gloria** [comment]
Note to engineers: these changes will be automatically picked up by bumping current version to 5.1.0 https://github.com/chanzuckerberg/single-cell-curation/blob/main/.bumpversion.cfg#L2
