### ISSUE TITLE
Phenotype And Trait Ontology (PATO) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#79]
The following ontology dependency is pinned for this version of the schema.

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Phenotype And Trait Ontology] | PATO | [pato.owl] : [2021-06-15] |  |

[Phenotype And Trait Ontology]: http://www.obofoundry.org/ontology/pato.html
[2021-06-15]: https://github.com/pato-ontology/pato/releases/tag/v2020-06-15
[pato.owl]: https://github.com/pato-ontology/pato/blob/v2020-06-15/pato.owl

**Parsing requirements:**

- For [`disease_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#disease_ontology_term_id), extract `PATO:0000461` for _normal_.

- For [`sex_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/corpora_schema.md#sex_ontology_term_id), extract the children of `PATO:0001894` for _phenotypic sex_

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
