### ISSUE TITLE
Uberon multi-species anatomy ontology (UBERON) must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#80]
The following ontology dependency is pinned for this version of the schema.

| Ontology | OBO Prefix | Required version |
|:--|:--|:--|
| [Uberon multi-species anatomy ontology] |  UBERON | [uberon.owl] : [2021-02-12] |

[Uberon multi-species anatomy ontology]: http://www.obofoundry.org/ontology/uberon.html
[2021-02-12]: https://github.com/obophenotype/uberon/releases/tag/v2021-02-12
[uberon.owl]: https://github.com/obophenotype/uberon/blob/v2021-02-12/uberon.owl

**Parsing requirement:**
- Extract the term identifier and its human-readable label

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
