### ISSUE TITLE
ENSEMBL (Human) gene reference must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#81]
The following gene annotation dependency is *pinned* for this version of the schema.

| Organism | Required version | Download |
|:--|:--|:--|
| [ENSEMBL (Human)] | Human reference GRCh38 (GENCODE v32/Ensembl 98)] matching [cellranger 2020-A (July 7, 2020) release] | [gencode.v32.primary_assembly.annotation.gtf] |

[ENSEMBL (Human)]: http://www.ensembl.org/Homo_sapiens/Info/Index
[gencode.v32.primary_assembly.annotation.gtf]: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.primary_assembly.annotation.gtf.gz

**Parsing requirement:**
- Extract the ENSEMBL gene identifier and its human-readable label

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
