### ISSUE TITLE
cellxgene-schema CLI must update validation for obs['self_reported_ethnicity_ontology_term_id']

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#811]
# Context

`self_reported_ethnicity_ontology_term_id` must not allow duplicate HANCESTRO terms when multiple terms are present:

... the value MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO terms in ascending lexical order **with no duplication of terms** or "unknown" if unavailable.

See [**self_reported_ethnicity_ontology_term_id**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#self_reported_ethnicity_ontology_term_id) for the full requirements.

**Comment by nayib-jose-gloria** [comment]
this behavior is already captured by validator CLI as of schema 4.0.0 release.
