### ISSUE TITLE
ENSEMBL (Mouse) gene reference must be downloaded and prepared

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#82]
The following gene annotation dependency is *pinned* for this version of the schema.

| Organism | Required version | Download |
|:--|:--|:--|
| [ENSEMBL (Mouse)] | Mouse reference mm10 (GENCODE vM23/Ensembl 98) matching [cellranger 2020-A (July 7, 2020) release]| [gencode.vM23.primary_assembly.annotation.gtf] |

[ENSEMBL (Mouse)]: http://www.ensembl.org/Mus_musculus/Info/Index
[gencode.vM23.primary_assembly.annotation.gtf]: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M23/gencode.vM23.primary_assembly.annotation.gtf.gz

[cellranger 2020-A (July 7, 2020) release]: https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build

**Parsing requirement:**
- Extract the ENSEMBL gene identifier and its human-readable label

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
