### ISSUE TITLE
Add feature type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#831]
## Context

See the conversation in [**cell-science-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1711540426286249).

From Sara Simmonds:

**Direct integration of gene type metadata in CELLxGENE**
_Value_
1. Data richness and biological context - including gene type metadata (e.g., protein coding, long non-coding RNAs) gives more biological context for genes (e.g., mitochondria, gene regulation) and can aid in quality control, data processing and analysis.
2. Support reproducibility and provide consistency - including gene type metadata supports consistent and reproducible data workflows for users and across users. Some users might not know where to get gene type metadata from on their own or users might use different sources creating potential inconsistency.

### feature_type

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_type</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. If the <code>feature_biotype</code> is <code>"gene"</code> then this MUST be the human-readable gene type assigned to the feature identifier in <code>var.index</code>. If the <code>feature_biotype</code> is <code>"spike-in"</code> then this MUST be <code>"synthetic"</code>.<br><br>See  <a href="https://www.gencodegenes.org/pages/biotypes.html "](https://www.gencodegenes.org/pages/biotypes.html)>GENCODE</a> and <a href="https://useast.ensembl.org/info/genome/genebuild/biotypes.html "](https://www.gencodegenes.org/pages/biotypes.html)>Ensembl</a> references.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by pablo-gar** [comment]
From Sara Simmonds

> Direct integration of gene type metadata in CELLxGENE
> Value
> Data richness and biological context - including gene type metadata (e.g., protein coding, long non-coding RNAs) gives more biological context for genes (e.g., mitochondria, gene regulation) and can aid in quality control, data processing and analysis.
> Support reproducibility and provide consistency - including gene type metadata supports consistent and reproducible data workflows for users and across users. Some users might not know where to get gene type metadata from on their own or users might use different sources creating potential inconsistency.

**Comment by nayib-jose-gloria** [comment]
See https://github.com/chanzuckerberg/single-cell-curation/issues/960#issuecomment-2297274065

Same run should pick up these changes after an implementation is written in gene_processing.py
