### ISSUE TITLE
cellxgene-schema CLI must update validation for obs['is_primary_data']

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#834]
# Design

See [is_primary_data](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.1.0/schema.md#is_primary_data).

The new requirement is:

 This MUST be <code>False</code> if <code>uns['spatial']['is_single']</code> is <code>False</code>. 

### is_primary_data

<table><tbody>
    <tr>
      <th>Key</th>
      <td>is_primary_data</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>bool</code>. This MUST be <code>False</code> if <code>uns['spatial']['is_single']</code> is <code>False</code>. This MUST be <code>True</code> if this is the canonical instance of this cellular observation and <code>False</code> if not. This is commonly <code>False</code> for meta-analyses reusing data or for secondary views of data.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by nayib-jose-gloria** [comment]
@brianraymor @brian-mott for validation of obs columns that depend on spatial metadata like this--do we need to account for datasets having both spatial and non-spatial assay rows? Would that scenario ever happen?

If so, should `This MUST be False if uns['spatial']['is_single'] is False.` only apply to rows with Visium Spatial Gene Expression or Slideseqv2 assays? Or all rows as long as uns['spatial']['is_single'] exists and is False?

**Comment by brianraymor** [comment]
> do we need to account for datasets having both spatial and non-spatial assay rows? Would that scenario ever happen?

No. The use of `uns` for spatial implicitly indicates that we're "allowing" only Visium Spatial Gene Expression or Slideseqv2 in the dataset (not a mixture of assays per observations). I think we may have had a hard requirement in `assay_ontology_term_id` in an earlier draft that required all observations to have the same term id when Visium Spatial Gene Expression or Slideseqv2. We could clarify. CC: @jahilton for thoughts

CC: @jahilton

**Comment by jahilton** [comment]
Yes, I can see the gap in the current documentation & think we can close that by enforcement in assay_ontology_term_id. If _any_ observation is assay:Visium then _all_ must be assay:Visium. If _any_ observation is assay:Slide-seqV2 then _all_ must be assay:Slide-seqV2.
This blocks the possibility of a Visium-Slide-seq integration, but I think that would complicate the X table. Better to deal with that when we expand to more spatial assays (when that type of integration is more likely)

**Comment by brianraymor** [comment]
@nayib-jose-gloria - tracking in https://github.com/chanzuckerberg/single-cell-curation/issues/871 - will create a matching CLI issue when the schema is updated.
