### ISSUE TITLE
update schema definition to reference to ontology guide

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#836]
# Motivation
The schema.md should be the source of truth for what is in the schema. Now that cellxgene-ontology-guide is used to track the ontology version used, it should be mentioned where it can be found and that it is used.

## Definition of Done

Within the [Required Ontologies ](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.0.0/schema.md#required-ontologies)section mention the locked version are in cellxgene-ontology-guide

**Comment by brianraymor** [comment]
I'm not sure that I fully understand the motivation.

There's never been a schema reference to the CLI which processed the "pinned" versions of ontology releases.

From my perspective, the schema defines requirements for COG similar to the requirements on the CLI. For example - chanzuckerberg/cellxgene-ontology-guide#80

Perhaps there should be a COG reference in the README.md in the single-cell-curation repo?

**Comment by Bento007** [comment]
> I'm not sure that I fully understand the motivation.
> 
> There's never been a schema reference to the CLI which processed the "pinned" versions of ontology releases.
> 
> From my perspective, the schema defines requirements for COG similar to the requirements on the CLI. For example - [chanzuckerberg/cellxgene-ontology-guide#80](https://github.com/chanzuckerberg/cellxgene-ontology-guide/issues/80)
> 
> Perhaps there should be a COG reference in the README.md in the single-cell-curation repo?

I see, you want the schema to be updated first and everything else follow. We can close this.

**Comment by Bento007** [comment]
As part of the migration process it should be documented that COG needs to be updated.

**Comment by brianraymor** [comment]
> As part of the migration process it should be documented that COG needs to be updated.

Nit - but migration occurs after the CLI is updated. COG will be updated when the schema/CLI are updated - prior to migration.
