### ISSUE TITLE
cellxgene-schema must validate cell_type_ontology_term_id and add human-readable label to cell_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#84]
The curator MUST annotate `cell_type_ontology_term_id`. There MUST NOT be duplicates in `obs`.

## cell_type_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>cell_type_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be a CL term. 
        </td>
    </tr>
</tbody></table>

---

The curator MUST NOT annotate `cell_type`.

### cell_type

<table><tbody>
    <tr>
      <th>Key</th>
      <td>cell_type</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be the human-readable name assigned to the value of <code>cell_type_ontology_term_id</code>.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
