### ISSUE TITLE
Remove convert.py, deprecated as of 3.0

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-curation#840]
Clean up in aisle 5... `convert.py` was deprecated in 3.0 and was supposed to be removed in 4.0:
- https://github.com/chanzuckerberg/single-cell-curation/pull/559/files#diff-46de65287208112ebb24f7bf8b950b67e9ab960682df1b69a4fab019580ce41dR11

**Comment by nayib-jose-gloria** [comment]
captured in https://github.com/chanzuckerberg/single-cell-curation/commit/bc86a512c07d53b021e5311ebf9e57f5b5295900#diff-747694e77b7c0844973c169f76fad346521ddf895c7bdcfca8b96d01fbb484d5
