### ISSUE TITLE
Update suspension_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#851]
# Design

## Additions

<table>
<thead>
  <tr>
    <th>For Assay</th>
    <th>MUST Use</th>
      </tr>
</thead>
  <tbody>
    <tr>
      <td><i>mCT-seq</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0030060"><code>EFO:0030060</code></a>]</td>
      <td><code>"cell"</code> or <code>"nucleus"</code></td>
    </tr>
    <tr>
      <td><i>MERFISH</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0008992"><code>EFO:0008992</code></a>]</td>
      <td><code>"na"</code></code></td>
    </tr>
    <tr>
      <td><i>methylation profiling by high throughput sequencing</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0002761"><code>EFO:0002761</code></a>] and its descendants</td>
      <td><code>"nucleus"</code></td>
    </tr>
    <tr>
      <td><i>ScaleBio single cell RNA sequencing</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0022490"><code>EFO:0022490</code></a>]</td>
      <td><code>"cell"</code> or <code>"nucleus"</code></td>
    </tr>
    </tbody></table>

## Deletions

<table>
<thead>
  <tr>
    <th>For Assay</th>
    <th>MUST Use</th>
      </tr>
</thead>
  <tbody>
    <tr>
      <td><i>CITE-seq</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0009294"><code>EFO:0009294</code></a>] and its descendants</td>
      <td><code>"cell"</code></td>
    </tr>
    <tr>
      <td><i>smFISH</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0009918"><code>EFO:0009918</code></a>] and its descendants</td>
     <td><code>"na"</code></td>
    </tr>   
    <tr>
      <td><i>snmC-seq</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0008939"><code>EFO:0008939</code></a>]</td>
      <td><code>"nucleus"</code></td>
    </tr>
          <tr>
              <td><i>snmC-seq2</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0030027"><code>EFO:0030027</code></a>]</td>
              <td><code>"nucleus"</code></td>
    </tr>
    <tr>
      <td><i>spatial proteomics</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0700000"><code>EFO:0700000</code></a>] and its descendants</td>
      <td><code>"na"</code></td>
    </tr>
    </tbody></table>

# Notes

Additional assays can be added to `suspension_type`.

Types from @jychien:
1. ~mCT-seq: “cell” or “nucleus”~
2. ~[ScaleBio](https://scale.bio/our-technology/): “cell” or “nucleus”~
3.  ~methylation profiling by high throughput sequencing: The current children are both “nucleus”. Methylation is typically done on nucleus, but I am guessing we’ll need to revisit if there are new decedents in the future.~

Note from @jahilton:
With the updated submission policy, our only `smFISH` Datasets (which are private) will be removed, and no more will be accepted. So the `smFISH and its descendants` row can be simplified to `MERFISH EFO:0008992`

That assay list review...
- ~remove "CITE-seq and its descendants"~
- ~replace "smFISH and its descendants" with "MERFISH EFO:0008992"~
- ~remove "snmC-seq"~
- ~replace snmC-seq2 with "methylation profiling by high throughput sequencing [EFO:0002761] and its descendants"~
  - ~we need to cover snm3C-seq as all our existing "methylation profiling..." datasets will be revised to that~
- ~remove spatial proteomics and its descendants~

The list of assays must also be reviewed to eliminate cases that are not supported such as cite-seq.

**Comment by jahilton** [comment]
That assay list review...
- remove "CITE-seq and its descendants"
- replace "smFISH and its descendants" with "MERFISH EFO:0008992"
- remove "snmC-seq"
- replace snmC-seq2 with "methylation profiling by high throughput sequencing [EFO:0002761] and its descendants"
  - we need to cover snm3C-seq as all our existing "methylation profiling..." datasets will be revised to that
- remove spatial proteomics and its descendants

**Comment by brianraymor** [comment]
**Show the math. Current set of assays:**

| assay | included? |
|---|---|
| "10x 3' transcription profiling", |  |
| "10x 3' v1", |  |
| "10x 3' v2", |  |
| "10x 3' v3", |  |
| "10x 5' transcription profiling", |  |
| "10x 5' v1", |  |
| "10x 5' v2", |  |
| '10x multiome', |  |
| '10x scATAC-seq', |  |
| 'BD Rhapsody Targeted mRNA', |  |
| 'BD Rhapsody Whole Transcriptome Analysis', |  |
| 'CEL-seq2', |  |
| 'DroNc-seq', |  |
| 'Drop-seq', |  |
| 'GEXSCOPE technology', |  |
| 'inDrop', |  |
| 'MARS-seq', |  |
| 'mCT-seq', |  |
| 'MERFISH', |  |
| 'microwell-seq', |  |
| 'Patch-seq', |  |
| 'ScaleBio single cell RNA sequencing', |  |
| 'scATAC-seq', |  |
| 'sci-Plex', |  |
| 'sci-RNA-seq', |  |
| 'sci-RNA-seq3', |  |
| 'Seq-Well', |  |
| 'Seq-Well S3', |  |
| 'Slide-seqV2', |  |
| 'Smart-seq', |  |
| 'Smart-seq v4', |  |
| 'Smart-seq2', |  |
| 'snm3C-seq', |  |
| 'snmC-Seq2', |  |
| 'SPLiT-seq', |  |
| 'STRT-seq', |  |
| 'TruDrop', |  |
| 'Visium Spatial Gene Expression' |  |
