### ISSUE TITLE
cellxgene-schema CLI must update validation for obsm embeddings

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#853]
# Context

See [#cell-science-data-wrangling](https://czi-sci.slack.com/archives/C024HCSH9PT/p1713559401168969?thread_ts=1713557432.295309&cid=C024HCSH9PT)

# Requirements

See #855

**Comment by brianraymor** [comment]
Per my comments in slack, I was planning to open the schema/CLI issues today. I believe that this CLI issue should be moved to single-cell-curation?
