### ISSUE TITLE
Update uns[{column}_colors] to match ordering in implementation

### ISSUE THREAD

**Issue by brian-mott** [chanzuckerberg/single-cell-curation#854]
## Context

While curating a recent Collection, I ran into some ambiguity to wrangle column color information from the obs dataframe into uns[{column}_colors]. The readme notes that:

> The color code at the Nth position in the ndarray corresponds to the Nth category of anndata.obs.{column}.unique()

`anndata.obs.{column}.unique()` will return an unsorted list of category names for {column} as they are encountered in the obs dataframe. 

It looks like [this line](https://github.com/chanzuckerberg/single-cell-data-portal/blob/edb7dc3c8d046e4afaefd4554925e554a0a83b2e/backend/common/utils/color_conversion_utils.py#L241) in the `single_cell_data_portal` repo assigns colors based on the `adata.obs[column].cat.categories` attribute, which returns a sorted list of the category names. 

Once I realized this, it was easy to map colors in the proper order after sorting or using `adata.obs[column].cat.categories` but I think it would be helpful to have some further clarity explaining that the `uns[{column}_colors]` array depends on the sorted order of category names.

### {column}_colors

<table><tbody>
  <tr>
    <th>Key</th>
      <td>
        {column}_colors where {column} MUST be the name of a <code>category</code> data type column in <code>obs</code> that<br> is annotated by the data submitter or curator. The following columns that are annotated by CELLxGENE<br> Discover MUST NOT be specified as {column}:<br><br>
      <ul>
        <li>assay</li>
        <li>cell_type</li>
        <li>development_stage</li>
        <li>disease</li>
        <li>organism</li>
        <li>self_reported_ethnicity</li>
        <li>sex</li>
        <li>tissue</li>       
      </ul><br>
      Instead annotate {column}_ontology_term_id_colors for these columns such as <code>assay_ontology_term_id</code>.<br><br>
    </td>
  </tr>
  <tr>
    <th>Annotator</th>
    <td>Curator MAY annotate.</td>
  </tr>
  <tr>
    <th>Value</th>
      <td>
        <code>numpy.ndarray</code>. This MUST be a 1-D array of shape <code>(, c)</code>, where <code>c</code> is greater than or equal to the<br> number of categories in the {column} as calculated by:<br><br>
           <samp>anndata.obs.{column}.cat.categories.size</samp><br><br>
        The color code at the Nth position in the <code>ndarray</code> corresponds to the Nth category of <samp>anndata.obs.{column}.cat.categories</samp>.<br><br>For example, if <code>cell_type_ontology_term_id</code> includes two categories:<br><br>
        <samp>anndata.obs.cell_type_ontology_term_id.cat.categories.values</samp><br><br>
        <samp>array(['CL:0000057', 'CL:0000115'],
      dtype='object')</samp><br><br>then <code>cell-type_ontology_term_id_colors</code> MUST contain two or more colors such as:<br><br>
        <samp>['aqua' 'blueviolet']</samp><br><br>where <code>'aqua'</code> is the color assigned to <code>'CL:0000057'</code> and <code>'blueviolet'</code> is the color assigned to<br> <code>'CL:0000115'</code>.<br><br>All elements in the <code>ndarray</code> MUST use the same color model, limited to:<br><br>
          <table>
          <thead>
            <tr>
              <th>Color Model</th>
              <th>Element Format</th>
            </tr>
          </thead><tbody>
            <tr>
              <td>
              <a
              href="https://www.w3.org/TR/css-color-4/#named-colors"
              ><i>Named Colors </i>
              </a>
            </td>
              <td><code>str</code>. MUST be a case-insensitive CSS4 color name with no spaces such as<br> <code>"aliceblue"</code>
            </td>
            </tr>
            <tr>
             <td>
              <a
              href="https://www.w3.org/TR/css-color-4/#hex-notation"
              ><i>Hex Triplet</i>
              </a>
            </td>
              <td><code>str</code>. MUST start with <code>"#"</code> immediately followed by six case-insensitive hexadecimal<br> characters as in <code>"#08c0ff"</code></td>
            </tr>
          </tbody></table>
        </td>
    </tr>
</tbody></table>
<br>

**Comment by brianraymor** [comment]
Hmm. The objective is that the implementation match the schema requirements; otherwise, it should not pass QA. 

See an [earlier comment thread](https://github.com/chanzuckerberg/single-cell-curation/issues/216#issuecomment-1639288957) where the difference between unique and cat.catgories was under discussion. And the same line of code was referenced.

CC: @niknak33 @atarashansky

**Comment by brianraymor** [comment]
April 25 - per review with @dsadgat and recommendation by @jahilton, the schema to be updated to match the current CXG implementation. It will specify `cat.categories` instead of `unique()`.
