### ISSUE TITLE
cellxgene-schema must validate ethnicity_ontology_term_id and add human-readable label to ethnicity

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#87]
The curator MUST annotate `ethnicity_ontology_term_id`. There MUST NOT be duplicates in `obs`.

### ethnicity_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>ethnicity_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If <code>organism_ontolology_term_id</code> is <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>, this MUST be either a HANCESTRO term or <code>"unknown"</code> if unavailable. <br><br>Otherwise this MUST be <code>"na"</code>.
        </td>
    </tr>
</tbody></table>
<br>

---

The curator MUST NOT annotate `ethnicity`.

### ethnicity

<table><tbody>
    <tr>
      <th>Key</th>
      <td>ethnicity</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"na"</code> or <code>"unknown"</code> if set in <code>ethnicity_ontology_term_id</code>; otherwise, this MUST be the human-readable name assigned to the value of <code>ethnicity_ontology_term_id</code>. 
        </td>
    </tr>
</tbody></table>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
