### ISSUE TITLE
Do not check if X has zero values and release a 5.0 patch.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#877]
# Problem

See [Problem slide](https://docs.google.com/presentation/d/1uQ4iCRyR416y7oi3iukaNCZOqDX64sA0x67XzEdWQIY/edit#slide=id.g2c9903b59f1_0_8) and [Ideas slide](https://docs.google.com/presentation/d/1uQ4iCRyR416y7oi3iukaNCZOqDX64sA0x67XzEdWQIY/edit#slide=id.g2c9903b59f1_0_0).

Per 5.1.0 X (Matrix Layers), a Visium dataset may contain zero values:
REQUIRED … If any obs['in_tissue'] values are 0, then at least one cell corresponding to a obs['in_tissue'] with a value of 0 MUST contain a non-zero value.
But the existing 5.0.0 X (Matrix Layers) requirements blocks curators from submitting such a revision of a Visium dataset prior to migration:
REQUIRED. Values MUST be de-duplicated molecule counts. Each cell MUST contain at least one non-zero value. All non-zero values MUST be positive integers stored as numpy.float32.

# Solution

We will create a patch release of the CLI for lattice that does not check for zero values in the X matrix. This will unblock lattice, and allow those datasets to be fully validated during the 5.1 migration.

**Comment by nayib-jose-gloria** [comment]
Note: If Explorer doesn't support just "spatial" embedding yet, need to allow "X_spatial" obsm embeddings in the patch (this will be forbidden in 5.1.0 proper)
