### ISSUE TITLE
cellxgene-schema must validate organism_ontology_term_id and add human-readable label to organism

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#89]
The curator MUST annotate `organism_ontology_term_id`. There MUST NOT be duplicates in `obs`.

### organism_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>organism_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be a NCBITaxon term.
        </td>
    </tr>
</tbody></table>
<br>

---

The curator MUST NOT annotate `organism`.

### organism

<table><tbody>
    <tr>
      <th>Key</th>
      <td>organism</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be the human-readable name assigned to the value of <code>organism_ontology_term_id</code>. 
        </td>
    </tr>
</tbody></table>

**Comment by brianraymor** [comment]
Updated the requirements for multi-organism support.

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
