### ISSUE TITLE
upgrade anndata to latest version

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#894]
# Need

We are currently using anndata==0.8.0. At the time of writing this ticket anndata is on 0.10.7. The longer we wait to upgrade the more difficult it will be.  

Updating the version in the CLI will also require the version used in single-cell-portal to update as well. 

# DOD
- update anndata to latest version in CLI
- update anndata to the same version use as the CLI.

**Comment by brianraymor** [comment]
We need to ensure that the schema is updated before anndata is updated. There is a general requirement:

> The canonical data format for CELLxGENE Discover is HDF5-backed [AnnData](https://anndata.readthedocs.io/en/latest) as written by version 0.8 of the anndata library.

In addition, it also impacts submitters/curators and seurat conversions.

**Comment by brianraymor** [comment]
@Bento007 and @nayib-jose-gloria - how are you feeling about [0.10.8](https://anndata.readthedocs.io/en/latest/release-notes/index.html#id6) for schema 5.2.0?

**Comment by nayib-jose-gloria** [comment]
Updated in patch 5.1.1 https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v5.1.1
