### ISSUE TITLE
cellxgene-schema must validate sex_ontology_term_id and add human-readable label to sex

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#90]
The curator MUST annotate `sex_ontology_term_id`. There MUST NOT be duplicates in `obs`.

### sex_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>sex_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be a child of <a href="http://purl.obolibrary.org/obo/PATO_0001894">PATO:0001894</a> for  <i>phenotypic sex</i> or <code>"unknown"</code> if unavailable.
        </td>
    </tr>
</tbody></table>

---

The curator MUST NOT annotate `sex`.

### sex

<table><tbody>
    <tr>
      <th>Key</th>
      <td>sex</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"unknown"</code> if set in <code>sex_ontology_term_id</code>; otherwise, this MUST be the human-readable name assigned to the value of <code>sex_ontology_term_id</code>.
        </td>
    </tr>
</tbody></table>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
