### ISSUE TITLE
Update CellGuide and WMG to use the new schema version

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#909]

**Comment by brianraymor** [comment]
@Bento007 - Isn't WMG based on the census schema version? 

Also, these should be single-cell-data-portal issues -  perhaps children of [Downstream consumers can perform 5.1.0 post-migration operations](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/692)

**Comment by Bento007** [comment]
No, both CG and WMG has the schema version hardcoded. This was so they could transition at their own pace since it also requires update the COG version. We can update the COG version now for both CG and WMG, since COG support both 5.0.0 and 5.1.0, but we will still need to change the hardcoded cellxgene-schema version after migration.

**Comment by Bento007** [comment]
We can create another ticket for the CG and WMG team to actually make the change in the other epic. But this ticket it for the DP team to make sure we push for it to get done.

**Comment by Bento007** [comment]
This work will be finished when https://github.com/chanzuckerberg/single-cell-data-portal/pull/7078 merges

**Comment by Bento007** [comment]
complete
