### ISSUE TITLE
cellxgene-schema must validate tissue_ontology_term_id and add human-readable label to tissue

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#91]
The curator MUST annotate `tissue_ontology_term_id`. There MUST NOT be duplicates in `obs`.

### tissue_ontology_term_id

<table>
  <tbody>
    <tr>
      <th>Key</th>
      <td>tissue_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>
        categorical with <code>str</code> categories. This MUST be the term that best describes the tissue that this cell was derived from, depending on the type of biological sample: <br />
        <br />
        <table>
          <thead>
            <tr>
              <th>For</th>
              <th>Use</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Tissue</td>
              <td>
                MUST be an UBERON term<br />
                (e.g. <code>"UBERON:0008930"</code> for a <i>sematosensory cortex</i> tissue sample)
              </td>
            </tr>
            <tr>
              <td>Cell Culture</td>
              <td>
                MUST be a CL term appended with <code>" (cell culture)"</code><br />
                (e.g. <code>"CL:0000057 (cell culture)"</code> for the <i>WTC-11 cell line</i>)
              </td>
            </tr>
            <tr>
              <td>Organoid</td>
              <td>
                MUST be an UBERON term appended with <code>" (organoid)"</code><br />
                (e.g. <code>"UBERON:0000955 (organoid)"</code> for a <i>brain organoid</i>)
              </td>
            </tr>
            <tr>
              <td>
                Enriched,<br />
                Sorted,or<br />
                Isolated<br />
                Cells from<br />
                a Tissue
              </td>
              <td>
                MUST be an UBERON or CL term and SHOULD NOT use terms that do not capture<br />
                the tissue of origin<br />
                (e.g. In the case of <i>CD3+ kidney cells</i>, use <code>"UBERON:0002113"</code> for <i>kidney</i>
                <br />
                instead of <code>"CL:000084"</code> for <i>T cell</i>. However, in the case of <i>EPCAM+ cervical cells</i>,
                <br />
                use <code>"CL:000066"</code> for <i>epithelial cell</i> of the cervix.)
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

---

The curator MUST NOT annotate `tissue`.

### tissue

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be the human-readable name assigned to the value of <code>tissue_ontology_term_id</code>. <code>" (cell culture)"</code> or <code>" (organoid)"</code> MUST be appended if present in <code>tissue_ontology_term_id</code>.<br><br>
       For example, if the <code>tissue_ontology_term_id</code> was curated as <code>"CL:0000057 (cell culture)"</code>, then the value would be <code>"fibroblast (cell culture)"</code>.
        </td>
    </tr>
</tbody></table>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
