### ISSUE TITLE
Access to Dataset descriptions

### ISSUE THREAD

**Issue by mengerj** [chanzuckerberg/single-cell-curation#945]
## Motivation

I wish to download datasets with a corresponding description through the API 

## Definition of Done

Let me know if this is still possible or wether the description information is no longer accessible 

## Tasks

I am downloading data through the requests library as explained in the curation-api notebooks. It seems there used to be an entry including a description for datasets for each dataset and this has been depricated. Is there an option to still access this information? Even if only for a subset of the currently available data. 
Thank you very much!

**Comment by brianraymor** [comment]
> Let me know if this is still possible or wether the description information is no longer accessible

Hi @mengerj - the schema has never supported a `description` for datasets; only their collection. For example, the deprecated `project_description` was the equivalent of the current collection description (all datasets in a collection had the same `project_description`) which was used before there was a UI for curators to create collections.
