### ISSUE TITLE
cellxgene-schema must validate feature_id and add human-readable label to feature_name

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#95]
The curator MUST annotate `feature_id`. There MUST NOT be duplicates in `var`.

### feature_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_id <code>(var.index)</code></td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. If the <code>feature_biotype</code> is <code>"gene"</code> then this MUST be an ENSEMBL term. If the <code>feature_biotype</code> is <code>"spike-in"</code> then this MUST be an ERCC Spike-In identifier. </td>
    </tr>
</tbody></table>
<br>

---

The curator MUST NOT annotate `feature_name`.

### feature_ name

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_name</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Data Portal</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. If the <code>feature_biotype</code> is <code>"gene"</code> then this this MUST be the human-readable ENSEMBL gene name assigned to the <code>feature_id</code>. If the <code>feature_biotype</code> is <code>"spike-in"</code> then this MUST the ERCC Spike-In identifier appended with <code>" spike-in control"</code>.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by brianraymor** [comment]
Updated requirements for spike-in support.

**Comment by tihuan** [comment]
@atolopko-czi PTAL thank you!

**Comment by tihuan** [comment]
Wait for PR to be reviewed and merged!
