### ISSUE TITLE
Update pinned ontology references

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#951]
### Design

The following pinned ontologies MUST be refreshed:

| Ontology | OBO Prefix | Release | Download |
|:--|:--|:--|:--|
| [Cell Ontology] | CL |  [2024-08-16] | [cl.owl]|
| [Experimental Factor Ontology] | EFO | [2024-08-15 EFO 3.69.0] | [efo.owl]
| [Human Developmental Stages] |  HsapDv | [2024-05-28] | [hsapdv.owl] |
| [Mouse Developmental Stages]| MmusDv | [2024-05-28] | [mmusdv.owl] |
| [Mondo Disease Ontology] | MONDO | [2024-08-06] | [mondo.owl] |
| [Uberon multi-species anatomy ontology] |  UBERON | [2024-08-07] | [uberon.owl] |
| | | | |

[Cell Ontology]: http://obofoundry.org/ontology/cl.html
[2024-08-16]: https://github.com/obophenotype/cell-ontology/releases/tag/v2024-08-16
[cl.owl]: https://github.com/obophenotype/cell-ontology/releases/download/v2024-08-16/cl.owl

[Experimental Factor Ontology]: http://www.ebi.ac.uk/efo
[2024-08-15 EFO 3.69.0]: https://github.com/EBISPOT/efo/releases/tag/v3.69.0
[efo.owl]: https://github.com/EBISPOT/efo/releases/download/v3.69.0/efo.owl

[Human Ancestry Ontology]: http://www.obofoundry.org/ontology/hancestro.html
[3.0]: https://github.com/EBISPOT/hancestro/releases/tag/3.0
[hancestro-base.owl]: https://github.com/EBISPOT/hancestro/blob/3.0/hancestro-base.owl

[Human Developmental Stages]: http://obofoundry.org/ontology/hsapdv.html
[2024-05-28]: https://github.com/obophenotype/developmental-stage-ontologies/releases/tag/v2024-05-28
[hsapdv.owl]: https://github.com/obophenotype/developmental-stage-ontologies/releases/download/v2024-05-28/hsapdv.owl

[Mondo Disease Ontology]: http://obofoundry.org/ontology/mondo.html
[2024-08-06]: https://github.com/monarch-initiative/mondo/releases/tag/v2024-08-06
[mondo.owl]: https://github.com/monarch-initiative/mondo/releases/download/v2024-08-06/mondo.owl

[Mouse Developmental Stages]: http://obofoundry.org/ontology/mmusdv.html
[mmusdv.owl]: https://github.com/obophenotype/developmental-stage-ontologies/releases/download/v2024-05-28/mmusdv.owl

[NCBI organismal classification]: http://obofoundry.org/ontology/ncbitaxon.html
[2023-06-20]: https://github.com/obophenotype/ncbitaxon/releases/tag/v2023-06-20
[ncbitaxon.owl]: https://github.com/obophenotype/ncbitaxon/releases/download/v2023-06-20/ncbitaxon.owl.gz

[Phenotype And Trait Ontology]: http://www.obofoundry.org/ontology/pato.html
[2023-05-18]: https://github.com/pato-ontology/pato/releases/tag/v2023-05-18
[pato.owl]: https://github.com/pato-ontology/pato/blob/v2023-05-18/pato.owl

[Uberon multi-species anatomy ontology]: http://www.obofoundry.org/ontology/uberon.html
[2024-08-07]: https://github.com/obophenotype/uberon/releases/tag/v2024-08-07
[uberon.owl]: https://github.com/obophenotype/uberon/releases/download/v2024-08-07/uberon.owl

The following ontologies **will not be updated**

| Ontology | OBO Prefix | Release | Download |
|:--|:--|:--|:--|
| [Human Ancestry Ontology] | HANCESTRO | [3.0] | [hancestro-base.owl] |
| [NCBI organismal classification] |  NCBITaxon | [2023-06-20] | [ncbitaxon.owl] |
| [Phenotype And Trait Ontology] | PATO | [2023-05-18] | [pato.owl]  |
| | | | |

**Comment by Bento007** [comment]
There is a procedure on how to do this. I estimate 1 day for an engineer.
