### ISSUE TITLE
cellxgene-schema CLI must update validation of obs['suspension_type']

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#953]
# Design

See [**suspension_type**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md#suspension_type) for complete reference.

## Additions

<table>
<thead>
  <tr>
    <th>For Assay</th>
    <th>MUST Use</th>
      </tr>
</thead>
  <tbody>
    <tr>
      <td><i>mCT-seq</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0030060"><code>EFO:0030060</code></a>]</td>
      <td><code>"cell"</code> or <code>"nucleus"</code></td>
    </tr>
    <tr>
      <td><i>MERFISH</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0008992"><code>EFO:0008992</code></a>]</td>
      <td><code>"na"</code></code></td>
    </tr>
    <tr>
      <td><i>methylation profiling by high throughput sequencing</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0002761"><code>EFO:0002761</code></a>] and its descendants</td>
      <td><code>"nucleus"</code></td>
    </tr>
    <tr>
      <td><i>ScaleBio single cell RNA sequencing</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0022490"><code>EFO:0022490</code></a>]</td>
      <td><code>"cell"</code> or <code>"nucleus"</code></td>
    </tr>
     <tr>
              <td><i>sci-RNA-seq3</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0030028"><code>EFO:0030028</code></a>]</td>
              <td><code>"cell"</code> or <code>"nucleus"</code></td>
           </tr>
    </tbody></table>

## Deletions

<table>
<thead>
  <tr>
    <th>For Assay</th>
    <th>MUST Use</th>
      </tr>
</thead>
  <tbody>
    <tr>
      <td><i>CITE-seq</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0009294"><code>EFO:0009294</code></a>] and its descendants</td>
      <td><code>"cell"</code></td>
    </tr>
    <tr>
      <td><i>smFISH</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0009918"><code>EFO:0009918</code></a>] and its descendants</td>
     <td><code>"na"</code></td>
    </tr>   
    <tr>
      <td><i>snmC-seq</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0008939"><code>EFO:0008939</code></a>]</td>
      <td><code>"nucleus"</code></td>
    </tr>
          <tr>
              <td><i>snmC-seq2</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0030027"><code>EFO:0030027</code></a>]</td>
              <td><code>"nucleus"</code></td>
    </tr>
    <tr>
      <td><i>spatial proteomics</i> [<a href="https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0700000"><code>EFO:0700000</code></a>] and its descendants</td>
      <td><code>"na"</code></td>
    </tr>
    </tbody></table>

## Implementation Note (@nayib-jose-gloria)

See https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L332

**Comment by nayib-jose-gloria** [comment]
Impl Note: See https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L332
