### ISSUE TITLE
feature length must be annotated for spike-in

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#957]
# Context

See the conversation in [**cell-science-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1711540426286249).

@pablo-gar requests that the length for "spike-in" which is [already calculated](https://github.com/chanzuckerberg/single-cell-curation/blob/f034f552e2dad7f09a87d7353bc280b17c0157c1/cellxgene_schema_cli/scripts/gene_processing.py#L197) be surfaced in the `feature_length` annotation.

> We already calculate length in bps for spike ins https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/ontology_files/genes_ercc.csv.gz

# Design

**PENDING**

### feature_length

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_length</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
        <code>uint</code> number of base-pairs (bps). If the <code>feature_biotype</code> is <code>"gene"</code>, then the value is calculated by creating non-overlapping concatenated exons across all isoforms of the gene, and then adding up their length in base-pairs. This approach is modeled on the "length of merged exons of isoforms of a gene" from <a href="https://doi.org/10.1093/bioinformatics/btac561">GTFtools: a software package for analyzing various features of gene models.</a><br><br> If <code>feature_biotype</code> is NOT <code>"gene"</code> then the value MUST be set to 0.
      </td>
    </tr>
</tbody></table>
<br>

**Comment by Bento007** [comment]
Given this is already calculated, it's a matter of surfacing it in the h5ad. I estimate 1-3 days

**Comment by brianraymor** [comment]
This is addressed in #960. Closing.
