### ISSUE TITLE
cellxgene-schema must validate X and uns.X_normalization

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#96]
`cellxgene-schema` MUST display a warning when this case is detected:

In any layer, if a matrix has 50% or more values that are zeros, it is STRONGLY RECOMMENDED that the matrix be encoded as a [`scipy.sparse.csr_matrix`]
(https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html).

---

*   All matrix layers MUST have the same shape, and have the same cell labels and gene labels.

---

The following table describes the matrix data and layers requirements that are **assay-specific**. If an entry in the table is empty, the cellxgene schema does not have any other requirements on data in those layers beyond the ones listed above.

| Assay | "raw" required? | "raw" location | "final" required? | "final" location |
|-|-|-|-|-|
| scRNA-seq (UMI, e.g. 10x v3) | REQUIRED. Values MUST be de-duplicated molecule counts. | `AnnData.raw.X` unless no "final" is provided, then `AnnData.X` | STRONGLY RECOMMENDED | `AnnData.X` |
| scRNA-seq (non-UMI, e.g. SS2) | REQUIRED. Values MUST be one of read counts (e.g. FeatureCounts) or  estimated fragments (e.g. output of RSEM). | `AnnData.raw.X` unless no "final" is provided, then `AnnData.X` | STRONGLY RECOMMENDED | `AnnData.X` |
| Accessibility (e.g. ATAC-seq, mC-seq) | NOT REQUIRED | | REQUIRED | `AnnData.X` | STRONGLY RECOMMENDED |
|||||

---

Review [Lattice cxg_audit](https://github.com/Lattice-Data/lattice-tools/blob/cxg-audit-script/scripts/cxg_audit.py) per [single-cell-data-wrangling](https://czi-sci.slack.com/archives/C024HCSH9PT/p1627402038086500) for:

> heuristics to check for "probably wrong" data (e.g. missing raw data) that we could take inspiration from for the validator.

---
## `uns` (Dataset Metadata)

Curators MUST annotate:

### X_normalization

<table><tbody>
    <tr>
      <th>Key</th>
      <td>X_normalization</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>str</code>. This SHOULD describe the method used to normalize the data stored in AnnData <code>X</code>. If data in <code>X</code> are raw, this SHOULD be <code>"none"</code>.
        </td>
    </tr>
</tbody></table>
<br>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
