### ISSUE TITLE
Feature length should be calculated as the median of isoforms instead of the merged length of isoforms

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell-curation#960]
### feature_length

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_length</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
        <code>uint</code> number of base-pairs (bps). The value is the median of the lengths of isoforms, reusing the median calculation from <a href="https://doi.org/10.1093/bioinformatics/btac561">GTFtools: a software package for analyzing various features of gene models.</a>
      </td>
    </tr>
</tbody></table>
<br>

---

### schema v5.2.0

* var and raw.var (Gene metadata)

  * Updated the requirements for `feature_length`. All `feature_biotypes` are now included. The calculation of the value changed from the merged length of isoforms to the median of the lengths of isoforms.
  
---

@pablo-gar wrote:

## Motivation

Currently gene lengths are calculated using GTFtools algorithm of "merged" length of isoforms. It was brought to our attention by @jychien that these may be unstable across Genecode versions and therefore CELLxxGENE schema versions.

For general information on gene length calculations available in GTFtools  please see this [slide deck](https://docs.google.com/presentation/d/15LOITu909LHkbcge0FIqfsL8YAVJs7BaSr7Oym-UcBY/edit#slide=id.g2baee9ce288_1_2).

We then have performed a systematic analysis that indeed demonstrates "merged" length of isoforms is less stable than other calculations. Please the full report [here](https://docs.google.com/document/d/1pgoK4vkjwQoIJ2p5-NXCCiT3OZpB3t8n/edit).

<img width="874" alt="image" src="https://github.com/chanzuckerberg/single-cell-curation/assets/29237819/cc8f7aca-0480-4d01-8b4e-20512d9ae702">

## Definition of Done

To change the calculation of gene length from "merged" to "median" using GTFtools implementation.

Current implementation in our code base is here: 

https://github.com/chanzuckerberg/single-cell-curation/blob/0c77179d2e794846861f8109c037b723507959cb/cellxgene_schema_cli/scripts/gene_processing.py#L129

The new implementation should be taken from here:

https://github.com/RacconC/gtftools/blob/140fc21003a565a0f69b5176db734b9a04a004a4/gtftools/gtftools.py#L670-L688

**Comment by Bento007** [comment]
The code changes will be easy. There are no unit tests at the moment which should be written, and this will make this work take longer. I estimate 2-3 days.

**Comment by nayib-jose-gloria** [comment]
Note: after re-writing `_get_gene_lengths_from_gtf` to use the new approach, we will also need to re-run the Gene Processing [script](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/Makefile#L5) and push the [resulting updated CSVs to */genecode_files/*](https://github.com/chanzuckerberg/single-cell-curation/tree/main/cellxgene_schema_cli/cellxgene_schema/gencode_files)
