### ISSUE TITLE
cellxgene-schema must validate embeddings in obsm and uns.default_embedding

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#97]
## `obsm` (Embeddings)

For each `str` key, `obsm` stores a `numpy.ndarray` of shape `(n_obs, m)`, where `n_obs` is the number of rows in `X` and `m >= 1`.

Curators MUST annotate **one or more** two-dimensional (`m >= 2`) embeddings (e.g. tSNE, UMAP, PCA, spatial coordinates) as **`numpy.ndarrays`** in `obsm`. The key for the embedding MUST be prefixed with `"X_"`. 

---

### default_embedding

​Curators MAY annotate the associated optional `default_embedding` key in `uns`. If the key is present, then its value MUST NOT be empty.

<table><tbody>
    <tr>
      <th>Key</th>
      <td>default_embedding</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>
          <code>str</code>. The value MUST match a key to an embedding in <code>obsm</code> for the embedding to display by default in cellxgene Explorer.
        </td>
    </tr>
</tbody></table>

**Comment by pablo-gar** [comment]
Implemented in[ cellxgene-schema v2.0.0](https://github.com/chanzuckerberg/single-cell-curation/releases/tag/v2.0.0)
