### ISSUE TITLE
cellxgene-schema CLI must update validation of obs['development_stage_ontology_term_id']

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#988]
## Design

Per the 5.2 changelog, the new requirements are:

  * Updated requirements for `development_stage_ontology_term_id` to require the most accurate descendant of _life cycle_. 
    * If <code>organism_ontolology_term_id</code> is <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>, this MUST be the most accurate descendant of `HsapDv:0000001` for _life cycle_
    * If <code>organism_ontolology_term_id</code> is <code>"NCBITaxon:10090"</code> for <i>Mus musculus</i>, this MUST be the most accurate descendant of `MmusDv:0000001` for _life cycle_

See [**development_stage_ontology_term_id**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md#development_stage_ontology_term_id).

## Implementation Notes (@nayib-jose-gloria)

Requires updating curie_constraints + error messages under [development_stage_ontology_term_id in the schema definition yaml](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L282). Consider adapting curie_constraint rules modeled after [assay_ontology_term_id](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L122), which also enforces requirements about specific descendant terms.

**Comment by nayib-jose-gloria** [comment]
Impl Note: Requires updating curie_constraints + error messages under [development_stage_ontology_term_id in the schema definition yaml](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L282). Consider adapting curie_constraint rules modeled after [assay_ontology_term_id](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L122), which also enforces requirements about specific descendant terms.
