### ISSUE TITLE
Draft Danio rerio (zebrafish)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-curation#995]
## Design

**October 21 2024** Superseded by draft [Multiple Species Experimental Schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/drafts/experimental_species_schema.md). 

---

This draft design reflects additions to corresponding sections in [schema 5.2.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md). Reviewers are expected to be familiar with the CELLxGENE schema.

**Editorial Notes** that are inlined in the design below will not be surfaced in the schema. 

---

### Required Ontologies

| Ontology | OBO Prefix | Release | Download |
|:--|:--|:--|:--|
| [Zebrafish Anatomy Ontology] | ZFA | [2022-12-09] | [zfa.owl] |
|||||

[Zebrafish Anatomy Ontology]: https://obofoundry.org/ontology/zfa.html
[2022-12-09]: https://github.com/ZFIN/zebrafish-anatomical-ontology/releases/tag/v2022-12-09
[zfa.owl]: https://github.com/ZFIN/zebrafish-anatomical-ontology/blob/v2022-12-09/zfa.owl

#### Editorial Notes

* [OLS ZFA](https://www.ebi.ac.uk/ols4/ontologies/zfa)
* [OLS ZFS](https://www.ebi.ac.uk/ols4/ontologies/zfs) - Zebrafish developmental stages ontology (ZFS) is available with other [development stage ontologies](https://github.com/obophenotype/developmental-stage-ontologies/releases/); however, it is also incorporated in ZFA. See [Clarify difference between two versions of ZFS](https://github.com/obophenotype/developmental-stage-ontologies/issues/81). 
* Also note [UBERON ZFA mapping issues](https://github.com/obophenotype/uberon/issues?q=is%3Aopen+is%3Aissue+label%3Amapping+ZFA)

Reviewing:
* [Zebrafish Phenotype Ontology (ZP)](https://github.com/obophenotype/zebrafish-phenotype-ontology/releases/) imports PATO. See [OLS ZP](https://www.ebi.ac.uk/ols4/ontologies/zp)
* [Zebrafish Experimental Conditions Ontology (ZECO)](https://github.com/ZFIN/zebrafish-experimental-conditions-ontology/releases). See [OLS ZECO](https://www.ebi.ac.uk/ols4/ontologies/zeco)

---

### Required Gene Annotations

| Source | Required version | Download |
|:--|:--|:--|
| [ENSEMBL (Zebrafish)] | GRCz11.112 (Ensembl 112) | [Danio_rerio.GRCz11.112.gtf] |

[ENSEMBL (Zebrafish)]: https://useast.ensembl.org/Danio_rerio/Info/Index
[Danio_rerio.GRCz11.112.gtf]: https://ftp.ensembl.org/pub/release-112/gtf/danio_rerio/Danio_rerio.GRCz11.112.gtf.gz

#### Editorial Notes

Also see [Lawson Lab zebrafish transcriptome annotation](https://www.umassmed.edu/lawson-lab/reagents/zebrafish-transcriptome/)

---

### cell_type_ontology_term_id

No schema changes are required.

#### Editorial Notes

Also see [Add CL bridge between species-specific and taxon-neutral ontology terms](https://github.com/chanzuckerberg/single-cell-curation/issues/1002)

---

### development_stage_ontology_term_id

If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A7955"><code>"NCBITaxon:7955"</code></a> for <i>Danio rerio</i> this MUST be the most accurate ZFS term and MUST NOT be <a href="https://www.ebi.ac.uk/ols4/ontologies/zfs/classes?obo_id=ZFS%3A0000000"><code>ZFS:0000000</code></a> for <i>Unknown</i>. 

#### Editorial Notes

Also see [Development Stages](https://zfin.org/zf_info/zfbook/stages/)

There is already a requirement in the current schema for:

If unavailable, this MUST be <code>"unknown"</code>.

---

### disease_ontology_term_id

No schema changes are required.

#### Editorial Notes

Propose to replace [Disease Ontology](https://github.com/DiseaseOntology/HumanDiseaseOntology/releases/tag/v2024-07-31) with MONDO

---

### organism_ontolology_term_id

<code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A7955"><code>"NCBITaxon:7955"</code></a> for <i>Danio rerio</i>

---

### sex_ontology_term_id

No schema changes are required.

#### Editorial Notes

There is [ZFA:male organism](https://www.ebi.ac.uk/ols4/ontologies/zfa/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FZFA_0000242?lang=en) and [ZFA:female organism](https://www.ebi.ac.uk/ols4/ontologies/zfa/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FZFA_0000303?lang=en).

---

### organism_cell_type_ontology_term_id

If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A7955"><code>"NCBITaxon:7955"</code></a> for <i>Danio rerio</i> this MUST be the most accurate descendant of <a href="https://www.ebi.ac.uk/ols4/ontologies/zfa/classes?obo_id=ZFA%3A0009000"><code>ZFA:0009000</code></a> for <i>cell</i> or <code>"unknown"</code> ...

#### Editorial Notes

Also see [Add CL bridge between species-specific and taxon-neutral ontology terms](https://github.com/chanzuckerberg/single-cell-curation/issues/1002)

---

### organism_tissue_ontology_term_id

If <code>organism_ontolology_term_id</code> is <a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A7955"><code>"NCBITaxon:7955"</code></a> for <i>Danio rerio</i> this MUST be the most accurate descendant of <a href="https://www.ebi.ac.uk/ols4/ontologies/zfa/classes?obo_id=ZFA%3A0100000"><code>ZFA:0100000</code></a> for <i>zebrafish anatomical entity</i> and MUST NOT be <a href="https://www.ebi.ac.uk/ols4/ontologies/zfa/classes?obo_id=ZFA%3A0009000"><code>ZFA:0009000</code></a> for <i>cell</i> or any of its descendants.

#### Editorial Notes

There is the potential to block other terms after review.

This allows the use of <a href="https://www.ebi.ac.uk/ols4/ontologies/zfa/classes?obo_id=ZFA%3A0001093"><code>ZFA:0001093</code></a> for <i>unspecified</i>

Also see [Add UBERON bridge between species-specific and taxon-neutral ontology terms](https://github.com/chanzuckerberg/single-cell-curation/issues/1003)

---

### tissue_ontology_term_id

No schema changes are required.

#### Editorial Notes

Also see [Add UBERON bridge between species-specific and taxon-neutral ontology terms](https://github.com/chanzuckerberg/single-cell-curation/issues/1003)

---

#### Editorial Notes

Pending discussion about the requirements for organoids and cell cultures. 

---

### feature_reference

<table><tbody>
    <tr>
      <th>Key</th>
      <td>feature_reference</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover MUST annotate.</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. This MUST be the reference organism for a feature:
          <br><br>
          <table>
          <thead>
          <tr>
          <th>Reference Organism</th>
          <th>MUST Use</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><i>Danio rerio</i></td>
              <td><a href="https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon/classes?obo_id=NCBITaxon%3A7955"><code>"NCBITaxon:7955"</code></a></td>
            </tr>
          </tbody></table>
        </td>
    </tr>
</tbody></table>
<br>

## References

[Zebrafish Information Network](https://zfin.org/)
[Zebrafish information network, the knowledgebase for Danio rerio research](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8982015/)
[ZFIN Data Load Sheets Template](https://docs.google.com/spreadsheets/d/1p7e6LyxU1wSObD4q8Fon0f6Kf5w-O_xPF-QTmDZSwJc/edit?gid=2099777656#gid=2099777656)

[From multiallele fish to nonstandard environments, how ZFIN assigns phenotypes, human disease models, and gene expression annotations to genes](https://academic.oup.com/genetics/article/224/1/iyad032/7067396)

[Alliance of Genome Resources](https://www.alliancegenome.org/members/zfin)

[Zebrafish Book](https://zfin.org/zf_info/zfbook/zfbk.html)

[Zebrahub](https://zebrahub.ds.czbiohub.org/) and [Zebrahub – Multimodal Zebrafish Developmental Atlas Reveals the State-Transition Dynamics of Late-Vertebrate Pluripotent Axial Progenitors](https://www.biorxiv.org/content/10.1101/2023.03.06.531398v2.full)

[A single-cell transcriptome atlas for zebrafish development](https://www.sciencedirect.com/science/article/pii/S0012160619304919)

[ZSCAPE - Zebrafish Atlas of Perturbed Embryos](https://cole-trapnell-lab.github.io/zscape/downloads/)

[The zebrafish anatomy and stage ontologies: representing the anatomy and development of Danio rerio](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3944782/pdf/2041-1480-5-12.pdf)

[Line Designations](https://zfin.org/action/feature/line-designations) and [Wild-type Lines](https://zfin.org/action/feature/wildtype-list). Also [Variants/Alleles](https://www.alliancegenome.org/downloads).

[A single cell transcriptome atlas of the developing zebrafish hindbrain](https://www.sciencedirect.com/science/article/pii/S0012160619304919)

[Demystifying Zebrafish](https://ashpublications.org/ashclinicalnews/news/3725/Demystifying-Zebrafish)

From Keir Balla:
[Tracing cell-type evolution by cross-species comparison of cell atlases](https://pubmed.ncbi.nlm.nih.gov/33657376/) 
[An improved zebrafish transcriptome annotation for sensitive and comprehensive detection of cell type-specific genes](https://pubmed.ncbi.nlm.nih.gov/32831172/)

[BGEE Reference](https://www.bgee.org/species/7227)

**Comment by nayib-jose-gloria** [comment]
> sex_ontology_term_id
No schema changes are required.
Editorial Notes
There is [ZFA:male organism](https://www.ebi.ac.uk/ols4/ontologies/zfa/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FZFA_0000242?lang=en) and [ZFA:female organism](https://www.ebi.ac.uk/ols4/ontologies/zfa/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FZFA_0000303?lang=en).

@brianraymor to clarify, we are currently choosing not to accept these ZFA terms for this first run at an experimental validator, correct? We could do so, but it would violate schema 5.2.0 as written, as I believe they are not descendants of PATO:0001894

**Comment by brianraymor** [comment]
@nayib-jose-gloria - you can safely ignore Editorial Notes which are just my musings/research.  That's why I wrote "No schema changes are required.". Per the DP call, I am drafting an experimental schema which (fingers crossed) will be ready by EOD.
